### ISSUE TITLE
Align upper level classes with identifiers.org types

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#10]
See for example http://identifiers.org/registry?query=pharmgkb

 - pathways
 - gene
 - drug
 - disease

http://identifiers.org/registry?query=hgnc

 - family
 - genefamily (what is the difference between this an the above?)
 - symbol

**Comment by nlharris** [comment]
Can this be closed?

**Comment by deepakunni3** [comment]
Need a bit more context here. Not sure what we have to align here. Do we align the prefixes from idot for the top-level classes?

**Comment by nlharris** [comment]
@cmungall is this still relevant or can it be closed?

**Comment by sierra-moxon** [comment]
closing as done (links are not working and we have lots of mappings to identifiers.org, etc); please reopen if I was incorrect in my assessment. :)
