### ISSUE TITLE
Missing definitions in meta.yaml

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolink-model#101]
The following elements do not have descriptions in the meta.yaml:

* alt_descriptions - a multi-valued string attribute used in the definition of [sequence variant](https://hsolbrig.github.io/biolink-model/docs/SequenceVariant.html)
* see_also - a url attribute used in the definition of [gene to expression site association](https://hsolbrig.github.io/biolink-model/docs/GeneToExpressionSiteAssociation.html)
* id_prefixes - a multi-valued string attribute used in the definition of [biological process or activity](https://hsolbrig.github.io/biolink-model/docs/BiologicalProcessOrActivity.html), [molecular activity](https://hsolbrig.github.io/biolink-model/docs/MolecularActivity.html), [biological process](https://hsolbrig.github.io/biolink-model/docs/BiologicalProcess.html), [pathway](https://hsolbrig.github.io/biolink-model/docs/Pathway.html), and several other definitions.
* entity - a boolean attribute used in [gene product isoform](https://hsolbrig.github.io/biolink-model/docs/GeneProductIsoform.html)
* role - a string attribute used in the subject and object of [gene regulatory relationship](https://hsolbrig.github.io/biolink-model/docs/GeneRegulatoryRelationship.html)

They need to be defined and their semantics needs to be implemented in the various generators

**Comment by nlharris** [comment]
@hsolbrig is this still needed?

**Comment by hsolbrig** [comment]
I need to write clearer issue reports.  That said, whatever this was getting at, if it is still a problem, has changed enough that it needs to be re-reported.

**Comment by nlharris** [comment]
ok, closing.
