### ISSUE TITLE
Pydantic model slots incorrectly generated for biolink:primary_knowledge_source and biolink:original_knowledge_source?

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#1039]
**Describe the bug**

[Current Pydantic models](https://github.com/biolink/biolink-model/blob/master/pydantic/biolink-model.py#L3303)  for some provenance slots are **Optional[List[str]]** but are `multivalued: false` in the model, thus they should be **Optional[str]** only?

**Comment by cmungall** [comment]
What's an example?

This is MV

  knowledge source:
    is_a: association slot
    description: >-
      An Information Resource from which the knowledge expressed in an
Association was
      retrieved, directly or indirectly. This can be any resource through
which the
      knowledge passed on its way to its currently serialized form. In
practice,
      implementers should use one of the more specific subtypes of this
generic property.
    range: information resource
    multivalued: true
    close_mappings:
      - pav:providedBy


however subproperties not NOT mv, which seems problematic

**Comment by RichardBruskiewich** [comment]
Hi @cmungall, I'm purely fixated on the impedance mismatch between the Pydantic code and the Biolink Model for these slots. @sierra-moxon suggests that the issue is  `biolink:primary_knowledge_source` and `biolink:original_knowledge_source `inheritance from `knowledge_source`. Unfortunately, `knowledge_source` is like an abstract parent but isn't strictly forbidden to be used, and perhaps, the code generation doesn't know how to handle the transition from parent `multivalue: true` to `multivalued: false` in  child slot classes.  This seems less a semantic issue than a code generation one?
