### ISSUE TITLE
`relation` property of `pairwise interaction association` has a slot for a range

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolink-model#104]
The `relation` property of `pairwise interaction association` redefines the `relation` slot, declaring its range as `molecularly interacts with`.  This is not correct, as `molecularly interacts with` is a slot...

**Comment by hsolbrig** [comment]
Range has been commented out (line 1922) for the moment

**Comment by nlharris** [comment]
For some reason this issue shows up on the list when filtering for is:open. Reopening and closing again resolved the same problem for another issue; seeing if it works on this one.
