### ISSUE TITLE
Post-translational modifications

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#1043]
**Is your feature request related to a problem? Please describe.**
We are interested in adding information on histone post-translational modifications to our graphs.  There are various things that we'd like to be able to say like
H3S10 phosphorylation controls gene expression
and
H3S10 phosphorylation is a phosphorylation
and maybe...
phosphorylations are capable of controlling gene expression

**Describe the solution you'd like**
I'm not entirely sure, but this is a guess: some structure for talking about types of PTMs (phosphorylations, acetylations, etc), and an ability to say that specific PTMs at particular places on some proteins (like H3S10 meaning the Serine 10 on the histone H3) is associated with some process or effect or phenotype.

**What working group (or team) did this request originate from?**
Coming from some spinoff work from Translator at RENCI, but we would be wanting to expose this information in a KP as well.

Note: This is relevant for members of NCATS Translator.

**Additional context**
There's a nice description of all this here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4099259/pdf/nihms576064.pdf

**Tag relevant members for discussion**
@DnlRKorn @beasleyjonm

**Comment by cbizon** [comment]
Additionally, I think we will want to be able to make statements about DNA modifications in addition to PTMs.

**Comment by cbizon** [comment]
Note that RHEA has some terms for particular residues / modifications to those residues as in : 
https://www.rhea-db.org/rhea/60224

**Comment by beasleyjonm** [comment]
I made a PR to the biolink model [https://github.com/biolink/biolink-model/pull/1102](url) recently that makes new classes for "epigenomic entity (mixin)", "posttranslational modifications", and "nucleosome modifications".

I think any PTMs or histone variants could fall under one of these classes.

**Comment by sierra-moxon** [comment]
closing as PR has been merged.
