### ISSUE TITLE
Add BioPlanet IDs as a valid prefix for Pathway

### ISSUE THREAD

**Issue by andrewsu** [biolink/biolink-model#1047]
In https://github.com/biothings/pending.api/issues/60, we are loading data from [BioPlanet](https://tripod.nih.gov/bioplanet/), a database of pathway-gene and pathway-disease mappings.  The database uses a custom BioPlanet ID (e.g., `bioplanet_283`).

**Describe the solution you'd like**
Please add BioPlanet as an ID prefix that is valid for Pathway entities (and/or whatever other suitable class in that general neighborhood)

**What working group (or team) did this request originate from?**
Exploring Agent

**Comment by sierra-moxon** [comment]
https://github.com/biopragmatics/bioregistry/issues/445
