### ISSUE TITLE
Inconsistent hierarchy placements of "treats" and "treated by" predicates

### ISSUE THREAD

**Issue by vdancik** [biolink/biolink-model#1048]
**Describe the bug**
`treats` and `treated by` predicates do not have consistent place in the Biolink hierarchy.  The parent of `treats` is `ameliorates` and it's parent is `affects` while the parent of `treated by` is `related_to_at_instance_level`

**Expected behavior**
We would expect that a parent of the inverted predicate is the same as inverted parent of the predicate.

**What working group (or team) did this request originate from?**
MolePro

Note: This is relevant for members of NCATS Translator.

**Additional context**
Causes with queries NCATSTranslator/testing#209 and NCATSTranslator/testing#208

**Tag relevant members for discussion**

**Comment by sierra-moxon** [comment]
Talking with @vdancik -

- add "ameliorated by" as the inverse of "ameliorates"
- treated_by should be a child of ameliorated_by
- ameliorated_by should be a child of 'affected by'

If we change the treats hierarchy (collapse treats and ameliorates) - need to be aware/fix this hierarchy as well.
