### ISSUE TITLE
Request biolink support for Aug QotM

### ISSUE THREAD

**Issue by jh111** [biolink/biolink-model#1049]
In August, the QotM will looking at risk factors for progression to Psoriatic Arthritis. We have information about how are edges were derived that we would like users to be able to see.

We would like a recommendation on which predicate to use and have biolink changes integrated by July. Either associated_with_likelihood_of or associated_with (with likelihood in a qualifier) would work, and a direction qualifier is needed (increased, decreased). See [Clinical KP Use Cases](https://docs.google.com/document/d/1zJdVFrbM5sQnDrxcsAXmhVMcFDTmjznPQIy_sPRyN5E/edit). For additional history, see #335.

@mbrush @sierra-moxon @karafecho @CaseyTa @mikebada

**Comment by karafecho** [comment]
I would like to discuss this during our CDC meeting on Wednesday, 7/5.
