### ISSUE TITLE
Request for clinical data study qualifiers needed for Aug QotM

### ISSUE THREAD

**Issue by jh111** [biolink/biolink-model#1050]
Clinical KPs would like recommendation on which attributes to use for communicating Clinical KP metadata.

For EHR Risk KP, current attributes are shown at: [](https://arax.ncats.io/?r=46840)
We can proceed with the Aug QotM with information as currently displayed. However, it is very data-science centric it would be better to display this information within standard biolink model attributes, using commonly understand biomedical terms. We've put some suggestions below, but will happy with other recommendation.

Notes based on:
[KP Associations and Evidence/Provenance Requirements](https://docs.google.com/spreadsheets/d/1WDkqNMhy7aer_3-JB4SCVhp1MZeFYZjCnYuRCnoZguo/edit#gid=1484827769)
[Clinical KP use cases](https://docs.google.com/document/d/1zJdVFrbM5sQnDrxcsAXmhVMcFDTmjznPQIy_sPRyN5E/edit)

-  supporting_study_metadata: link to [](https://github.com/NCATSTranslator/Translator-All/wiki/EHR-Risk-KP), in future this will refer to a pubmed paper.
-  supporting_study_method_type: multivariable logistic regression
-  supporting_study_performance metrics: AUROC
-  supporting_study_size: different per entity: currently expressed as order_of_magnitude to avoid differential privacy attacks
-  supporting_study_cohort_inclusion_exclusion_criteria: age < 18
-  supporting_study_date_range: 2022-2022 (contemporaneous) 2020-2022 (future prediction)
-  supporting_study_context: Providence St Joseph Health System, seven states in the western United States
- object_variable_state: present (contemporaneous), new onset (future prediction)
- temporal_interval_qualifier: 2 years

@mbrush @sierra-moxon

**Comment by sierra-moxon** [comment]
@jh111 - I am adding these for biolink 3.0.  
I see one small changes based on the spreadsheet and what is in the model - are these ok?
- `supporting_study_cohort_inclusion_exclusion_criteria` in the spreadsheet, inclusion/exclusion seem to be referenced in the definition for  `supporting_study_cohort` ?
