### ISSUE TITLE
Formatting issue in markdown representation of fields

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolink-model#106]
The entire line in the `fields` entry of the markdown is italicized:
 example: 
```* _[iri](iri.md) *subsets*: (translator_minimal)_```
giving:
* _[iri](iri.md) *subsets*: (translator_minimal)_

Only the `subsets` element should be that way:
```* [iri](iri.md) _subsets_: (translator_minimal)```
* [iri](iri.md) _subsets_: (translator_minimal)

**Comment by nlharris** [comment]
Sounds like this can be closed.
