### ISSUE TITLE
Tab character in biolink-model.yaml

### ISSUE THREAD

**Issue by nishad-instacart** [biolink/biolink-model#1066]
The current biolink-model.yaml contains a tab character, which prevents it from being valid yaml.

May be valuable to add an automated check via a tool like [yq](https://github.com/mikefarah/yq) to ensure the file validates.

```
$ yq -r '.' biolink-model.yaml
Error: bad file 'biolink-model.yaml': yaml: line 1119: found a tab character where an indentation space is expected
```

**Comment by sierra-moxon** [comment]
thanks @nishad-instacart!  We do validate by loading the yaml file with pyyaml, but I will look into adding another layer of validation here.

**Comment by sierra-moxon** [comment]
https://github.com/biolink/biolink-model/pull/1067
