### ISSUE TITLE
biolink-model.yaml - `filler` property domain is not specified

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolink-model#107]
The domain of the `filler` property is not specified

**Comment by nlharris** [comment]
Fixed?

**Comment by hsolbrig** [comment]
No.

**Comment by deepakunni3** [comment]
@hsolbrig What is the purpose of `filler` property? What is the expected domain for this slot?

**Comment by nlharris** [comment]
@hsolbrig if this still needs to be fixed, can you respond to deepak's questions? this should be easy to fix if you respond.

**Comment by hsolbrig** [comment]
`filler` is defined at https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L527  .  It does not appear to be used.  I have no idea what its purpose is -- I am just observing that it appears to be orphaned.

**Comment by sierra-moxon** [comment]
fixed in branch `bugs`
