### ISSUE TITLE
add exact, narrow, broad, related synonym slots to the model

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#1073]
per request from Monarch ontology team.

**Comment by sierra-moxon** [comment]
@matentzn - happy to have more details here when you get a chance. :)

**Comment by matentzn** [comment]
For some use cases, distinguishing the synonym type are essential. For example, if we populate a solr index from a KGX file, we would score exact synonyms higher than narrow ones or worse, related ones. Right now, the biolink model mushes them all together, so when I transform an ontology to a KG, I loose these distinctions which are nicely curated in many of our ontologies.
