### ISSUE TITLE
biolink-model.yaml - undefined classes / types

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolink-model#108]
The following elements:
* `phenotype`
* `evidence instance`
* `chemical formula value`

Appear as the range of:
* `has phenotype`
* `has evidence` 
* `has chemical formula`
 
They have no type or definition.  For the moment we've just listed them as types

**Comment by hsolbrig** [comment]
phenotype should be "phenotypic feature"

**Comment by nlharris** [comment]
Did this get fixed?

**Comment by hsolbrig** [comment]
The range of `has phenotype` is now `phenotypic feature`, `has evidence` is `evidence type` and `has chemical formula` is `chemical formula value`, all of which exist, so yes.
