### ISSUE TITLE
Add ComplexPortal as an identifier prefix to MacromolecularComplexMixin

### ISSUE THREAD

**Issue by gaurav** [biolink/biolink-model#1088]
**Is your feature request related to a problem? Please describe.**
We're currently working on incorporating macromolecular complexes from the [EBI Complex Portal](https://www.ebi.ac.uk/complexportal/) into Babel (https://github.com/TranslatorSRI/Babel/issues/54; https://github.com/TranslatorSRI/Babel/pull/55). We intend to include these as [MacromolecularComplexMixin](https://biolink.github.io/biolink-model/docs/MacromolecularComplexMixin.html). To do this, we need an identifier prefix for ComplexPortal identifiers such as [CPX-1424](https://www.ebi.ac.uk/complexportal/complex/CPX-1424) ("Tubulin alpha-beta heterodimeric complex, TUB1 variant").

**What working group (or team) did this request originate from?**
 The need for representing this type of data originated from the Babel/Node Normalizer project of the Translator SRI team.

**Note:** This is relevant for members of NCATS Translator.

**Describe the solution you'd like**
1. Add `ComplexPortal` as an identifier prefix to MacromolecularComplexMixin
   - Note that there is some disagreement about the capitalization of the CURIE prefix: [bioregistry.io](https://bioregistry.io/registry/complexportal) and [identifiers.org](https://registry.identifiers.org/registry/complexportal) uses `complexportal`, while [UniProt](https://www.uniprot.org/database/DB-0228) uses `ComplexPortal` and [biocontext](https://github.com/prefixcommons/biocontext/search?q=complexportal) uses both `ComplexPortal` and `COMPLEXPORTAL`. Given this lack of standardization, I think we can pick whichever capitalization makes the most sense for the Biolink model.
2. Add `ComplexPortal` to the list of prefixes with an IRI prefix of `https://www.ebi.ac.uk/complexportal/complex/`, so that e.g. `ComplexPortal:CPX-1424` is resolved to https://www.ebi.ac.uk/complexportal/complex/CPX-1424.

**Additional information to support this request** (optional)
- https://bioregistry.io/registry/complexportal
- https://registry.identifiers.org/registry/complexportal
- https://www.uniprot.org/database/DB-0228
- https://github.com/prefixcommons/biocontext/blob/aa5b9d8c9de406566211183df0c41e6e1c47eda7/registry/go_context.jsonld#L172
- https://github.com/prefixcommons/biocontext/blob/aa5b9d8c9de406566211183df0c41e6e1c47eda7/registry/idot_context.jsonld#L440

**Tag relevant members for discussion**
N/A

**Comment by sierra-moxon** [comment]
Changes to support:
- [x] make macromolecular complex a class vs. a mixin
- [x] add ComplexPortal (used this casing because it looks like its `ComplexPortal` at EBI, GO uses this capitalization and it is listed as an alternative prefix/synonym of `complexportal` at Bioregistry).

**Comment by sierra-moxon** [comment]
Thank you everyone for voting on the issue; it really helps me see what is a priority! :)
