### ISSUE TITLE
biolink-model.yaml: undefined `single locus feature complement` domain

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolink-model#109]
The domain of `has zygosity` is `single locus feature complement`, which is undefined.

For the moment we've commented the domain out (line 1055)

**Comment by nlharris** [comment]
Fixed? Or is the commenting out workaround sufficient?

**Comment by hsolbrig** [comment]
The comment line should be removed at someone's convenience.  It is now explicitly declared as a slot of `genotype`

**Comment by deepakunni3** [comment]
@hsolbrig Thanks for commenting out; For now, I'll edit the domain from `genotype` to `genomic entity` to better reflect the hierarchy in GENO and SO.

**Comment by nlharris** [comment]
Can this be closed, or was the commenting-out just a temporary workaround?

**Comment by sierra-moxon** [comment]
closed as fixed
