### ISSUE TITLE
child association slots not appearing on association slot webpage

### ISSUE THREAD

**Issue by mbrush** [biolink/biolink-model#1093]
**Describe the bug**
The list of association slots reported at https://biolink.github.io/biolink-model/docs/association_slot.html does not seem to include slots that are children of another association slot.  

**To Reproduce**
For example, 'knowledge source' has two child slots (primary knowledge source, and aggregator knowledge source) that are missing form the list of association slots (but show up as children if we look at the [knowledge source](https://biolink.github.io/biolink-model/docs/knowledge_source.html) page)

**Expected behavior**
I would expect child slots to show up on the list (ideally nested under parent slots)

**Comment by vincentvialard** [comment]
I agree, as stated in the description:

> **Slot: association_slot**
> any slot that relates an association to another entity

**Comment by sierra-moxon** [comment]
https://biolink.github.io/biolink-model/knowledge_source/ in the new doc has two child slots listed

**Comment by vincentvialard** [comment]
looks good to me!
