### ISSUE TITLE
request for new types in BL

### ISSUE THREAD

**Issue by YaphetKG** [biolink/biolink-model#1096]
**Is your feature request related to a problem? Please describe.**

- We want to add new types under `biolink:InformationContentEntity`
  - `biolink:Studies`
  - `biolink:Variables`
  - `biolink:CDE` (`biolink:CommonDataElements`)

These types would be very useful for us in making specific graphs relating to clinical studies and common data elements.

**Comment by nlharris** [comment]
Hi @YaphetKG, can you remind me which KP / ARA / Working Group you're associated with? Thanks!

**Comment by cbizon** [comment]
@YaphetKG works with ranking agent (though to be entirely clear these elements are to enable the use of the ROBOKOP KG in a non-translator environment where we use it as the basis of a semantic search for studies/variables/cdes)

**Comment by sierra-moxon** [comment]
Hi @YaphetKG  - (sorry to be pedantic :) ) - the new classes you propose here are pluralized -- does this have meaning to you or if I add "biolink:Study" and "biolink:Variable" and "biolink:CommonDataElement" classes, will that be sufficient?   If not too much trouble, could you provide me with descriptions for each of these new classes?

**Comment by YaphetKG** [comment]
Hi @sierra-moxon, sorry for the delayed response 
Thanks for your comment about the pluralization, i think you are right that singular form would be sufficient. 
For the descriptions:

biolink:CommonDataElement
> A Common Data Element (CDE) is a standardized, precisely defined question, paired with a set of allowable responses, used systematically across different sites, studies, or clinical trials to ensure consistent data collection. Multiple CDEs (from one or more Collections) can be curated into Forms. ([ref ](https://cde.nlm.nih.gov/home))


biolink:Study
> a detailed investigation and/or analysis.

 biolink:StudyVariable (maybe StudyVariable might be more fitting here than Variable)
> a variable that is used as a measure in the investigation of a study.

**Comment by sierra-moxon** [comment]
thanks for all the votes on the issue, it really helps me prioritize! :)
