### ISSUE TITLE
align with Broad reasoner types and paths

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#11]
https://github.com/broadinstitute/reasoner/blob/master/reasoner/KnowledgeMap.py

**Comment by cmungall** [comment]
this may now be covered by @mbrush's spreadsheet?

**Comment by mbrush** [comment]
if someone would extract a list of types and predicates from the knowledge map, i could see how they align/fit into the predicates in the spreadsheet.

**Comment by sierra-moxon** [comment]
@vdancik - do we still need to address this, or has Broad moved forward to use biolink-model associations?

**Comment by vdancik** [comment]
The ticket can be closed - this is not needed anymore.

**Comment by sierra-moxon** [comment]
thanks @vdancik! :)
