### ISSUE TITLE
permanent release links

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#1104]
### Discussed in https://github.com/biolink/biolink-model/discussions/675

<div type='discussions-op-text'>

<sup>Originally posted by **balhoff** March 17, 2021</sup>
Is there a permanent link for the latest release of biolink-model artifacts? I couldn't find one in the readme or docs.</div>

**Comment by nlharris** [comment]
@balhoff sorry for inadvertently neglecting this question!

**Comment by sierra-moxon** [comment]
keeping a ticket here for prosperity.
