### ISSUE TITLE
Align and connect 'supporting document' and 'publications' edge properties

### ISSUE THREAD

**Issue by mbrush** [biolink/biolink-model#1107]
At present, the most common Biolink edge property used in Attributes to hold supporting publications is [`publications`](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L6855).

But Biolink also provides a [`supporting document`](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L6743) edge property that would cover non-publication source documents (a request from TMKP where not all mined text is from publications).

At present these edge properties are not hierarchically related in the Biolink Model.

#### Questions:
1. Do we want to keep both? 
2. If so, we should make `publications` a child of `supporting document`.  And name these properties consistently (e.g. change 'publications' -> 'supporting publications')
3. If not, which one to keep? 
4. If we decide to only keep 'supporting document' do we need a way to indicate that the document is a publication? 
       a. e.g. Attribute.value_type field = biolink:Publication
      b. e.g. a nested Attribute object keyed on the biolink:type property, with value = biolink:Publication

**Comment by mbrush** [comment]
**Proposal:**
- Keep both, but rename `publications` -> `supporting publications`
- Move `supporting publications` under `supporting documents`
- Update definitions to make them more consistent with each other and their new hierarchical relationship.
       - Proposed `supporting documents` definition: _A referencable document that reports the statement expressed in an Association, or provides information used as evidence supporting this statement._
       - Proposed `supporting publications` definition: _A publication that reports the statement expressed in an Association, or provides information used as evidence supporting this statement._


Another issue here is to decide if the names of these properties should be plural or singular . . .

**Comment by sierra-moxon** [comment]
@mbrush  - is it necessary to change 'publications' to 'supporting publications' (totally doable, I just know this is a very widely used parameter and would require a lot of downstream changes.  Alternatively, I could add `supporting publications` as an alias of `publications`).

**Comment by sierra-moxon** [comment]
also should (somewhat pedantically) note that `supporting document` is currently in the model, and is not multivalued.  Would the second part of this proposal make `supporting document` multivalued?

**Comment by sierra-moxon** [comment]
should 'supporting data set' also be a child of 'supporting documents' ?

**Comment by mbrush** [comment]
My thoughts on your questions @sierra-moxon:
- not totally necessary to change `publications` to `supporting publications`, but IMO it is preferred (it is a more descriptive/informative name, and provides consistency with `supporting documents`)
- `supporting documents` was created at the request of TMKP, and they did not need it to be multivalued.  But I think it should be, so support other use cases for this property.
- `supporting text` should not be renamed, and is not a subproperty of `supporting document` (it refers to a single span of text, not an entire document)
- - `supporting data set` should not be moved under `supporting document` either, as IMO we should not consider a dataset to be a type of document. (This is consistent with how they are modeled in OBO ontologies like IAO)

**Comment by mbrush** [comment]
Re-opening this issue as additional questions regarding the representation of supporting documents have surfaced, and may warrant reconsideration of decisions made above.

1. Confirm we want two slots.

2. Revisit idea or renaming to be more consistent.

3. Broaden `supporting documents` definition to include the idea of documents supporting things besides Statements (e.g. StudyResults), and indicating that provenance information qualifies as supporting info:

> Documents that provide information supporting the creation of a Statement or other Information Entity.  Most often this slot is used to reference documents that report the Statement expressed in an Association, or provide evidence or provenance information supporting this Statement.  Another common use is to reference documents that supported the creation of a Study Result object.

4. Broaden `publications` definition to:
> Publications that provide information supporting the creation of a Statement or other Information Entity. Most often this slot is used to reference publications that report the Statement expressed in an Association, or provide evidence or provenance information supporting this Statement.


5. Establish conventions of use for these properties in TRAPI messages (see ticket [here](https://github.com/NCATSTranslator/ReasonerAPI/issues/398))

**Comment by mbrush** [comment]
Voting on decisions that address 1-4 above is happening in Discussion #1234.

**Comment by mbrush** [comment]
Closing, based on outcomes of voting in #1234 and final decisions documented in the [supporting publications specification here](https://github.com/NCATSTranslator/ReasonerAPI/blob/master/ImplementationGuidance/Specifications/supporting_publications_specification.md).
