### ISSUE TITLE
Move mappings for deprecated interaction predicates

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#1109]
**Is your feature request related to a problem? Please describe.**
I want to update our predicate mapping code in bl_lookup to handle biolink 3.     For qualifiers, some of this mapping lives outside the model currently, but there are also cases where qualifiers are not involved.  For instance, there are a bunch of "interaction" predicates that are being deprecated in favor of some new predicates.  But these are not 1:1. 

**Describe the solution you'd like**
 I think what should happen is that the mappings under e.g. directly_interacts_with should be distributed across a few different new predicates like binds,  and directly physically interacts with.   Some of these are GAMMA predicates - these are a grouping family of predicates that we should remove and replace with whatever is being aggregated there.  @EvanDietzMorris can help with that.

**What working group (or team) did this request originate from?**
SRI is trying to update bl_lookup; ranking agent relies on bl_lookup to transform its data for biolink 3.

**Tag relevant members for discussion**
@sierra-moxon @EvanDietzMorris

**Comment by EvanDietzMorris** [comment]
#1117 removes all of the GAMMA predicates. Most were obsolete and for the ones that are still used we are switching to alternative mappings.

**Comment by sierra-moxon** [comment]
Next release of biolink will see these changes; already in master. Closing as done.
