### ISSUE TITLE
Generated UML diagrams are too busy

### ISSUE THREAD

**Issue by deepakunni3** [biolink/biolink-model#111]
Ex: https://biolink.github.io/biolink-model/docs/GeneToExpressionSiteAssociation.html

Certain elements in the diagram are not properly legible.

**Comment by hsolbrig** [comment]
Need some advice on how to clarify.  Bigger diagram?  Omit inherited properties and/or associations?  One frustrating thing is that YUML isn't really great on multiple arcs , so the three GeneToExpressionSiteAssociation to OntologyClass links are difficult to read.

**Comment by TomConlin** [comment]
If the three arcs have identical labels,  (I cant tell) 
just keep one and make it heavier if possible

**Comment by hsolbrig** [comment]
All three arcs have different labels:

1. gene to expression site association.quantifier qualifier
2. association type
3. qualifiers

All of the information in the graph is also available in the text -- perhaps we could organize the text to help.  Another example of an unreadable diagram (at leas un-magnified) is https://biolink.github.io/biolink-model/docs/Association.html.  The alternative here would appear to be a single box "Association" with all children omitted...

Suggestions?

**Comment by nlharris** [comment]
> Ex: https://biolink.github.io/biolink-model/docs/GeneToExpressionSiteAssociation.html
> 
> Certain elements in the diagram are not properly legible.

The font is small, but (just barely) readable. Is this still something that's viewed as needing improvement? (Not sure it's very high priority, regardless.)

**Comment by sierra-moxon** [comment]
while we haven't completely fixed this issue, maybe new diagrams in the doc balance detail with readability?  
https://biolink.github.io/biolink-model/GeneToExpressionSiteAssociation/. they can still get unmanageable but hopefully, the page text makes up for the lack of readability.  the new  hierarchy visualizations might also help https://biolink.github.io/biolink-model/categories.html. (these still need mixin support)

**Comment by sierra-moxon** [comment]
https://github.com/biolink/biolink-model/pull/1418
