### ISSUE TITLE
Find a place for qualified mappings

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#1110]
**Is your feature request related to a problem? Please describe.**
In biolink 2.x, there are mappings for RO:0002213 to etc. positively regulates.   But that is now a deprecated predcate, replaces with a predicate (regulates) + qualifier(object: increase).  So where does that mapping go.

**Describe the solution you'd like**
Some formal place to keep this mapping.  It could be a new kind of mapping (qualified mapping) that has as subelements the different qualifier key-value pairs that are mapped.  Or it could be in some other structured place other than the yaml.  But it should be part of 'the model' somewhere.

**What working group (or team) did this request originate from?**
SRI attempting to implement bl_lookup and ranking agent attempting to use it to parse input data.

**Tag relevant members for discussion**
@sierra-moxon

**Comment by sierra-moxon** [comment]
@cbizon - I updated "deprecated predicate" in the mapping file to "mapped predicate" (some other options I wrote down were "source" or "original predicate"...I might have missed some).

**Comment by sierra-moxon** [comment]
closing for now as completed.  The next release of biolink will have these changes, the master branch has them now.
