### ISSUE TITLE
Two pairs of 'inverse' predicates have no canonical_predicate specified?

### ISSUE THREAD

**Issue by amykglen** [biolink/biolink-model#1112]
**Question:**

This question relates to these two pairs of inverse predicates in Biolink 3.0.3:
1. `increases activity of` / `activity increased by`
2. `positively regulates` / `positively regulated by`

For each pair, neither predicate appears to be labeled as the `canonical_predicate`. Not sure if that was a mistake, or if we shouldn't count on every pair of inverse predicates having a `canonical_predicate` specified?

**Comment by amykglen** [comment]
Thanks @nlharris! I think this may be a bit different from #657 - that issue appears to be about predicate _opposites_ (e.g., treats/causes) whereas this one is about predicate _inverses_ (e.g., treats/treated_by).

**Comment by sierra-moxon** [comment]
Hi @amykglen - you're right that these don't have canonical annotations.  Noting also that both of these predicates are deprecated in Biolink 3.*?  

increases activity of predicate would be converted to an "affects" predicate, with a subject|object_aspect_qualifier = "activity" and a subject|object direction_qualifier of "increased" (there could be a qualified_predicate here too, depending on what other qualifiers you need to use here).  

positively regulates predicate -> regulates predicate with a object_direction_qualifer = 'upregulated'

**Comment by amykglen** [comment]
Ah, I forgot that they're deprecated. Part of our ARAX code loads the entire Biolink YAML file, and that's where this was causing an issue for us. (Meaning, we weren't actually _assigning_ these predicates to edges, just parsing them from the Biolink YAML file.)

Since they're deprecated I suppose there's no need to fix this. Is there a plan for how long such deprecated predicates will be kept around in the Biolink YAML file?

**Comment by sierra-moxon** [comment]
Good point; I am removing all deprecated predicates from the next release of Biolink.

**Comment by amykglen** [comment]
ok! I'll go ahead and close this issue then since I don't think there's anything further to do
