### ISSUE TITLE
CLINVAR vs ClinVarVariant

### ISSUE THREAD

**Issue by karafecho** [biolink/biolink-model#1119]
**Describe the bug**
The October 2022 Question of the Month exposed confusion related to [CLINVAR:1333833](https://www.ncbi.nlm.nih.gov/clinvar/variation/1333833/?oq=1333833&m=NM_152296.5(ATP1A3):c.2552A%3EG%20(p.Gln851Arg)) versus ClinVarVariant:1333833.
Both are valid Biolink prefixes, but only CLINVAR is in the context.jsonld, so we probably need to remove ClinVarVariant.

Also see https://github.com/biolink/biolink-model/issues/842#issue-973061840 (closed issue).

**Tag relevant members for discussion**
@mbrush @sierra-moxon : Does this seem right to you?

**Comment by sierra-moxon** [comment]
@karafecho - Biolink echo's Bioregistry (albeit capitalized in Biolink vs. lowercase in bioregistry) on this prefix and declares it to be "CLINVAR". 

`clinvar.variant` is a synonym for `clinvar` at bioregistry.
