### ISSUE TITLE
ORPHANET vs ORPHA

### ISSUE THREAD

**Issue by karafecho** [biolink/biolink-model#1122]
**Describe the bug**
The October 2022 QotM surfaced confusion related to the Biolink prefix ORPHANET vs ORPHA, specifically, in the context of [ORPHA:2131](https://hpo.jax.org/app/browse/disease/ORPHA:2131). The general consensus was that the correct prefix should be ORPHANET, but it is unclear.

**Tag relevant members for discussion**
@mbrush @sierra-moxon - please triage.

**Comment by sierra-moxon** [comment]
see also: https://github.com/biopragmatics/bioregistry/issues/646#issuecomment-1297801067
