### ISSUE TITLE
canonical predicate annotation is inconsistent

### ISSUE THREAD

**Issue by colleenXu** [biolink/biolink-model#1124]
Both [affects_response_to](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L2375) and its inverse [response_affected_by](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L2390) are annotated as the canonical-predicate. 

Not clear if all predicate-pairs (non-symmetrical ones) are labeled with a canonical-predicate. For example the [likelihood](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L1827) predicates or [mixin](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L2329) predicates

**Comment by sierra-moxon** [comment]
Thanks @colleenXu - good catch.  There was some ambiguity about which direction should be canonical with these new predicates.  I've selected the "affects" descendants as canonical (e.g.: "affects response to" vs. "response affected by") for consistency, but please let me know if you have objections.  I've also deprecated the mixin predicates.
