### ISSUE TITLE
CHEBI_ROLE properties

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#1132]
**Is your feature request related to a problem? Please describe.**
CHEBI has terms for roles like "antidepressant" or "pesticide".   We want to include those roles in the ROBOKOP graphs.   I think that the best would be to make them node properties on chemicals

**Describe the solution you'd like**
Some properties in the model, or at least some common agreement on how these should be structured (Do we define the property with the chebi id or name or what?  Do properties need source namespaces etc).  What we've done in the past is something like `"CHEBI_ROLE:pesticide": true`.  But CHEBI_ROLE isn't a thing, and using the name is good (readable) and bad(not a strong id).  

**What working group (or team) did this request originate from?**
Ranking-agent

Note: This is relevant for members of NCATS Translator.

**Additional context**

**Tag relevant members for discussion**
@wumirose @EvanDietzMorris

**Comment by cbizon** [comment]
One other idea that may be worth a separate issue: we have previously used high level mondo terms (like respiratory disease) as properties on subclasses of that term.   So instead of asthma-[subclass_of]->respiratory_disease, we'd have
```
{ 
  "id": "MONDO:(asthma)",
  "MONDO:respiratory_disease": true
}
```
This is kind of not good from the point of view of now having somewhat inconsistent ways to model the same relationship (subclass) but it removes a whole bunch of high level highly connected nodes from the graph which makes certain tasks easier/better.  So it's possible that there's a more general discussion here than just the CHEBI thing (though I think that's separable because that case doesn't have anything to do with subclasses.)

**Comment by mikebada** [comment]
With regard to your second comment, this to me points to a filtering of low-information-content assertions (disease-type subclass assertions here), analogous to the filtering of all specific genes/proteins being subclasses of generic gene/protein classes, which I recall discussing a while ago...

**Comment by cmungall** [comment]
https://w3id.org/biolink/vocab/ChemicalRole

could definitely do with more docs!

btw you may want to consider using CHIRO to hop out the role middleman... But I appreciate that may not be possible in the short term so fine to keep using ChemicalRole as a kind of reified relationship

**Comment by sierra-moxon** [comment]
@cbizon - I added definitions and mappings to the "chemical role" class in Biolink (there is also a node property, "has chemical role" to hold the CHEBI identifier on a node that represents the role.
