### ISSUE TITLE
Syntax of an instance: Association 

### ISSUE THREAD

**Issue by raven44099** [biolink/biolink-model#1133]
**Question:**
I looked quite hard, but I cannot find the syntax of a concrete instances.
How would I write down a complicated example of an Association? By the way I think this is pretty important and missing in the documentation, or at another obvious point. I really dont want to download the 15 GiB KG-covid-19. 

**My example of an association w/ Statement, Qualifier, Subject- , Predicate- and Object Qualifier:**

```py
{n0: {name='tea-cup', is_a='tool'},
n1:{name='hot-water', is_a='liquid'},
association:{statement={
modifier triple={
core triple={
predicate='place_in'
},
subject_qualifier='white', predicate qualifier= 'in one move', object qualifier='77 degree C'
},
statement_qualifier='each monday'
},
metadata={generic='what is generic?', provenance='whats provenance?', evidence= 'd.o.i.xyz'}
}
```

I guess my syntax is quite awesome, but wrong. Could you please tell me, where could I look it up?

**Comment by sierra-moxon** [comment]
Hi @raven44099  - thank you for the ticket, you raise a great point about documentation; it is definitely on our radar that examples go a long way to help with understanding the model.  We also hope that our model components have good descriptions, but we can always improve.    
I've started the improvement (hopefully! :) ) with this PR: https://github.com/biolink/biolink-model/pull/1134
and more specifically, with association examples here: https://github.com/biolink/biolink-model/blob/1133/guidelines/association-examples-with-qualifiers.md

**Comment by raven44099** [comment]
Wow, you perfectly understood my issue! The linked examples are exactly what I was looking for! 💯  😄
