### ISSUE TITLE
How to attend Help Desk meeting?

### ISSUE THREAD

**Issue by raven44099** [biolink/biolink-model#1138]
When I open a new issue by selecting the template for _Biolink Help Desk questions_ , it emphasises the Office hours. It is very userfriendly, but since I want to attend, I face one problem:
- [x] it doesnt show how to attend the meeting.

Is it possible to add a link to the room or further details?

**template currently:**

> **Question:**
> Please replace this text with a clear and concise description of what your question or issue is. Please include any relevant links.
> 
> (After you create this ticket, you are welcome to come to our Help Desk office hours (currently Mondays at 10am PT / 1pm ET) to discuss your question.)

**Comment by nlharris** [comment]
Hi Raven, the Biolink Help Desk is for Translator team members. Are you on Translator?

**Comment by sierra-moxon** [comment]
@raven44099 - good question!  If you're not a member of the Translator project, as a first step, maybe we should set up a time to meet as a one-off, and then we can figure out how to host a more general HelpDesk that isn't Translator-focused.  :)

**Comment by raven44099** [comment]
Yes, this sounds really great. I'll contact you in an instant by mail.
