### ISSUE TITLE
Recommended way of pinning Biolink version?

### ISSUE THREAD

**Issue by slobentanzer** [biolink/biolink-model#1140]
**Question:**
For KGs built for specific use cases, one would usually want to pin the Biolink version. What is the recommended way of doing that? The BMT advises to build from a YAML file using local path or URL. Is there a way to get a permanent URL of the current Biolink model, preferably through the BMT directly? Or is the BMT not the current best practise?

I know I can get the Biolink version BMT uses through `bmt.Toolkit().get_model_version()` (which seems to be behind the current Biolink release, for me it is at `2.2.13`). Is there an easy way to specify the Biolink version and get a YAML for that from a URL?

**Comment by sierra-moxon** [comment]
Hi @slobentanzer - is it possible that your local virtual environment could be updated to use the most recent version of BMT?  (BMT is set to use the latest Biolink by default, but as you point out, you can pass it to other versions of Biolink Model on instantiation).  

```
import bmt
import requests
import json
from pprint import pprint

tk = bmt.Toolkit("https://github.com/biolink/biolink-model/blob/latest/biolink-model.yaml")
#  tk = bmt.Toolkit("https://github.com/biolink/biolink-model/blob/v3.0.3/biolink-model.yaml")
``` 

We do update the 'latest' branch of Biolink on release - https://github.com/biolink/biolink-model/blob/latest/biolink-model.yaml (which should be stable). 

We could add this to our dev call agenda for next time, if it's not working for you?

**Comment by slobentanzer** [comment]
Hi @sierra-moxon,
Thanks for the reply! I made the mistake of assuming that looking at the minor version (0.8) would be enough when checking whether my BMT was current. That's on me; pinning BMT at 0.8.12 got me the current Biolink.

However, I do think that version pinning using the second suggestion would be better; that way one can update the BMT while still keeping the Biolink version stable. I assume that `../blob/<vX.X.X>/biolink-model.yaml` works for every release?

Or would I have to expect other problems when the BMT is more current than the Biolink model?

**Comment by sierra-moxon** [comment]
Hi @slobentanzer - the plan is to release a version of BMT in concert with Biolink releases (I am working on a BMT release at the moment, to coincide with Biolink Model release 3.1.0).  We changed our release naming for Biolink model, BMT, and KGX over the course of the last year to be consistent going forward, as you suggest above `<vX.X.X>`. It is also possible that BMT moves ahead in release versions without a Biolink Model release (for example, we are adding functionality to navigate enumeration hierarchies more effectively in BMT, which does not require a Biolink Model change to proceed).  

Some non-technical things I can do to help:
1) add the Biolink model version number to the Changelog/release notes of BMT
2) display the Biolink model version on the documentation websites for Biolink and BMT (good suggestion)
3) add examples of returning the Biolink model version with BMT prominent on the documentation site (in progress).

**Comment by slobentanzer** [comment]
Great, sounds reasonable! Thanks for the hard work!
