### ISSUE TITLE
Current Biolink model website and BMT give conflicting information?

### ISSUE THREAD

**Issue by slobentanzer** [biolink/biolink-model#1145]
**Question:**
Sorry if this issue results from my ignorance of the BMT functions or the Biolink model website, but for me the class `macromolecular complex` of Biolink `v3` does not exist in BMT `0.8.12`. `bmt.Toolkit().get_model_version()` is `3.0.3`. `get_element("macromolecular complex")` returns `None`, while the older `get_element("macromolecular complex mixin")` returns a mixin class definition. At the same time, the website has a page on `MacromolecularComplex` (https://biolink.github.io/biolink-model/docs/MacromolecularComplex.html#class-macromolecularcomplex), but the `MacromolecularComplexMixin` does not seem to be there any more. 

I also tried finding the `macromolecular complex` in the children of `biological entity`, but no luck there either.

Can someone clear this up for me? Thanks a lot!

**Comment by slobentanzer** [comment]
Never mind, I figured it out; it's a synchronisation issue. The website is built from `3.1.0` already, which the BMT does not provide yet. Maybe it would be possible to display the Biolink model version somewhere on the website?

**Comment by nlharris** [comment]
Remaining task:
- [ ] display the Biolink model version somewhere on the website

**Comment by sierra-moxon** [comment]
The doc now has the latest version released in the "github" header section: https://biolink.github.io/biolink-model/
