### ISSUE TITLE
duplicate URI prefixes in Biolink Model context jsonld file.

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#1150]
a RENCI group who are working with some extracts out of Ubergraph. They tried loading the Biolink model context into curies but go errors related to duplicate namespaces.
RENCI tried `converter = Converter.from_jsonld_url(url)`
it throws a ton of DuplicateURIPrefixes errors

```
"catalyzes": {
         "@type": "@id"
      },
      "category": {
         "@type": "@id"
      },
      "caused_by": {
         "@type": "@id"
      },
      "causes": {
         "@type": "@id"
      },
```

these stanzas represent biolink components themselves.

**Comment by sierra-moxon** [comment]
We think this is an issue for the `curies` package: we might need it to recognize that there can be various other things besides prefix mappings in a JSON-LD context, and some prefix mappings may be buried in objects (will investigate)

**Comment by balhoff** [comment]
He is going to use this file instead: https://github.com/biolink/biolink-model/blob/master/prefix-map/biolink-model-prefix-map.json

That file was created specifically for prefix maps anyway. Maybe it is a `curies` bug that it doesn't fully support general JSON-LD context files.
