### ISSUE TITLE
References to deprecated 'relation' in documentation

### ISSUE THREAD

**Issue by vincentvialard** [biolink/biolink-model#1155]
Multiple references to deprecated [relation](https://biolink.github.io/biolink-model/docs/relation) in the [Edge properties](https://biolink.github.io/biolink-model/about/mapping-neo4j.html#edge-properties) section of the [Mapping to Neo4j page](https://biolink.github.io/biolink-model/about/mapping-neo4j.html). 

I originaly thought all instances should be replaced by [predicate](https://biolink.github.io/biolink-model/docs/predicate), but after reading the [Edge semantics](https://biolink.github.io/biolink-model/guidelines/working-with-the-model.html#edge-semantics) section of the [Working with Biolink Model](https://biolink.github.io/biolink-model/guidelines/working-with-the-model.html) page, I think things have to be clarified here.

**Comment by sierra-moxon** [comment]
we have added a large red banner for deprecated classes and slots: https://biolink.github.io/biolink-model/relation/
