### ISSUE TITLE
Breadcrumb navigation broken in some parts of the documentation

### ISSUE THREAD

**Issue by vincentvialard** [biolink/biolink-model#1157]
Breadcrumb elements of the [Predicates](https://biolink.github.io/biolink-model/docs/predicates.html) page are correctly linked to parent and grand-parent page:

> [Browse Biolink Model](https://biolink.github.io/biolink-model/docs/) / [Slots](https://biolink.github.io/biolink-model/docs/slots.html) / Predicates 

whereas on any of the subpages all are linked to the page itself.

Example: Breadcrumb of the [biolink:active_in](https://biolink.github.io/biolink-model/docs/active_in.html) page:

> [Slots](https://biolink.github.io/biolink-model/docs/active_in.html) / [Predicates](https://biolink.github.io/biolink-model/docs/active_in.html) / biolink:active_in

**Comment by sierra-moxon** [comment]
I am not sure we have an equivalent section to point to in the new doc, but the doc is organized in a new way that hopefully helps folks navigate from high level groupings like "predicate" to specific predicate children, etc. https://biolink.github.io/biolink-model/active_in/
https://biolink.github.io/biolink-model/#predicates-visualization

**Comment by vincentvialard** [comment]
the inheritance tree is a way better solution than the breadcrumb.

**Comment by sierra-moxon** [comment]
https://github.com/biolink/biolink-model/pull/1418
