### ISSUE TITLE
Problems with the documentation of the category attribute

### ISSUE THREAD

**Issue by vincentvialard** [biolink/biolink-model#1158]
* (at least in the [NamedThing](https://biolink.github.io/biolink-model/docs/NamedThing.html) page) the `category` attribute is listed as **Own** as well as **Inherited from entity**. This seems to propagate to the children of `NamedThing`, [Article](https://biolink.github.io/biolink-model/docs/Article.html#inherited-from-named-thing) for instance.
* indentation of the neo4j and RDF bullet points is wrong
* the neo4j usage description is unclear 
    * *Current:* In a neo4j database this MAY correspond to the neo4j label tag.
    * *Proposed:* In a neo4j database some of the values MAY correspond to some of the neo4j label tags.
* *Question:* Why is it expected to have the category hierarchy materialized in a RDF database but not in neo4j?
> In an RDF database it should be a biolink model class URI. This field is multi-valued. **It should include values for ancestors of the biolink class;** for example, a protein such as Shh would have category values biolink:Protein, biolink:GeneProduct, biolink:MolecularEntity, …

**Comment by sierra-moxon** [comment]
https://github.com/biolink/biolink-model/pull/1418
