### ISSUE TITLE
Documentation top level navigation is disorienting

### ISSUE THREAD

**Issue by vincentvialard** [biolink/biolink-model#1160]
Speaks for itself:

[Browse Biolink Model](https://biolink.github.io/biolink-model/docs/)
    [Biolink Model 3.0 Migration Guide](https://biolink.github.io/biolink-model/Migration_3.0_Guide.html)
    [Biolink Model Guidelines](https://biolink.github.io/biolink-model/guidelines/README.html)
    [Installation and Usage Notes](https://biolink.github.io/biolink-model/notes.html)
    [Mapping to a graph store](https://biolink.github.io/biolink-model/about/)
    [Release Instructions](https://biolink.github.io/biolink-model/release-instructions.html)
    [Slot: anatomical context qualifier](https://biolink.github.io/biolink-model/docs/chemical_affects_gene_association_anatomical_context_qualifier.html)
    [Slot: anatomical context qualifier](https://biolink.github.io/biolink-model/docs/chemical_gene_interaction_association_anatomical_context_qualifier.html)
    [Slot: associated environmental context](https://biolink.github.io/biolink-model/docs/organism_taxon_to_organism_taxon_interaction_associated_environmental_context.html)
    [Slot: catalyst qualifier](https://biolink.github.io/biolink-model/docs/chemical_to_chemical_derivation_association_catalyst_qualifier.html)
    [Slot: category](https://biolink.github.io/biolink-model/docs/association_category.html)
    [Slot: category](https://biolink.github.io/biolink-model/docs/named_thing_category.html)
    [Slot: causal mechanism qualifier](https://biolink.github.io/biolink-model/docs/chemical_affects_gene_association_causal_mechanism_qualifier.html)
    [Slot: enabled by](https://biolink.github.io/biolink-model/docs/molecular_activity_enabled_by.html)
    [Slot: has attribute](https://biolink.github.io/biolink-model/docs/clinical_finding_has_attribute.html)
    [Slot: has attribute](https://biolink.github.io/biolink-model/docs/organismal_entity_has_attribute.html)
    [Slot: has attribute](https://biolink.github.io/biolink-model/docs/socioeconomic_exposure_has_attribute.html)
    [Slot: has attribute type](https://biolink.github.io/biolink-model/docs/clinical_measurement_has_attribute_type.html)
    [Slot: has biological sequence](https://biolink.github.io/biolink-model/docs/sequence_variant_has_biological_sequence.html)
    [Slot: has count](https://biolink.github.io/biolink-model/docs/variant_to_population_association_has_count.html)
    [Slot: has evidence](https://biolink.github.io/biolink-model/docs/druggable_gene_to_disease_association_has_evidence.html)
    [Slot: has gene](https://biolink.github.io/biolink-model/docs/sequence_variant_has_gene.html)
    [Slot: has input](https://biolink.github.io/biolink-model/docs/molecular_activity_has_input.html)
    [Slot: has output](https://biolink.github.io/biolink-model/docs/molecular_activity_has_output.html)
    [Slot: has quotient](https://biolink.github.io/biolink-model/docs/variant_to_population_association_has_quotient.html)
    [Slot: has taxonomic rank](https://biolink.github.io/biolink-model/docs/organism_taxon_has_taxonomic_rank.html)
    [Slot: has total](https://biolink.github.io/biolink-model/docs/variant_to_population_association_has_total.html)
    [Slot: id](https://biolink.github.io/biolink-model/docs/agent_id.html)
    [Slot: id](https://biolink.github.io/biolink-model/docs/book_id.html)
    [Slot: id](https://biolink.github.io/biolink-model/docs/pairwise_molecular_interaction_id.html)
    [Slot: id](https://biolink.github.io/biolink-model/docs/publication_id.html)
    [Slot: id](https://biolink.github.io/biolink-model/docs/sequence_variant_id.html)
    [Slot: id](https://biolink.github.io/biolink-model/docs/serial_id.html)
    [Slot: id](https://biolink.github.io/biolink-model/docs/small_molecule_id.html)
    [Slot: iso abbreviation](https://biolink.github.io/biolink-model/docs/article_iso_abbreviation.html)
    [Slot: name](https://biolink.github.io/biolink-model/docs/agent_name.html)
    [Slot: name](https://biolink.github.io/biolink-model/docs/attribute_name.html)
    [Slot: name](https://biolink.github.io/biolink-model/docs/macromolecular_machine_mixin_name.html)
    [Slot: name](https://biolink.github.io/biolink-model/docs/publication_name.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/anatomical_entity_to_anatomical_entity_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/anatomical_entity_to_anatomical_entity_ontogenic_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/anatomical_entity_to_anatomical_entity_part_of_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/behavior_to_behavioral_feature_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/chemical_affects_gene_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/chemical_entity_assesses_named_thing_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/chemical_entity_or_gene_or_gene_product_regulates_gene_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/chemical_gene_interaction_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/chemical_to_chemical_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/chemical_to_chemical_derivation_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/chemical_to_disease_or_phenotypic_feature_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/chemical_to_pathway_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/contributor_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/disease_or_phenotypic_feature_to_genetic_inheritance_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/disease_or_phenotypic_feature_to_location_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/disease_to_phenotypic_feature_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/drug_to_gene_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/entity_to_disease_association_mixin_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/entity_to_disease_or_phenotypic_feature_association_mixin_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/entity_to_exposure_event_association_mixin_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/entity_to_outcome_association_mixin_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/entity_to_phenotypic_feature_association_mixin_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/exon_to_transcript_relationship_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/functional_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/gene_to_disease_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/gene_to_expression_site_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/gene_to_gene_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/gene_to_gene_family_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/gene_to_gene_homology_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/gene_to_gene_product_relationship_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/gene_to_go_term_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/gene_to_pathway_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/gene_to_phenotypic_feature_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/genomic_sequence_localization_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/genotype_to_disease_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/genotype_to_gene_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/genotype_to_genotype_part_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/genotype_to_variant_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/information_content_entity_to_named_thing_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/macromolecular_machine_to_biological_process_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/macromolecular_machine_to_cellular_component_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/macromolecular_machine_to_molecular_activity_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/material_sample_derivation_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/molecular_activity_to_chemical_entity_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/molecular_activity_to_molecular_activity_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/molecular_activity_to_pathway_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/organism_taxon_to_environment_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/organism_taxon_to_organism_taxon_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/organism_taxon_to_organism_taxon_interaction_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/organism_taxon_to_organism_taxon_specialization_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/organism_to_organism_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/pairwise_molecular_interaction_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/population_to_population_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/reaction_to_catalyst_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/sequence_feature_relationship_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/sequence_variant_modulates_treatment_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/taxon_to_taxon_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/transcript_to_gene_relationship_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/variant_to_disease_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/variant_to_gene_association_object.html)
    [Slot: object](https://biolink.github.io/biolink-model/docs/variant_to_population_association_object.html)
    [Slot: object aspect qualifier](https://biolink.github.io/biolink-model/docs/chemical_affects_gene_association_object_aspect_qualifier.html)
    [Slot: object aspect qualifier](https://biolink.github.io/biolink-model/docs/named_thing_associated_with_likelihood_of_named_thing_association_object_aspect_qualifier.html)
    [Slot: object context qualifier](https://biolink.github.io/biolink-model/docs/chemical_affects_gene_association_object_context_qualifier.html)
    [Slot: object context qualifier](https://biolink.github.io/biolink-model/docs/chemical_gene_interaction_association_object_context_qualifier.html)
    [Slot: object context qualifier](https://biolink.github.io/biolink-model/docs/named_thing_associated_with_likelihood_of_named_thing_association_object_context_qualifier.html)
    [Slot: object direction qualifier](https://biolink.github.io/biolink-model/docs/chemical_affects_gene_association_object_direction_qualifier.html)
    [Slot: object direction qualifier](https://biolink.github.io/biolink-model/docs/chemical_entity_or_gene_or_gene_product_regulates_gene_association_object_direction_qualifier.html)
    [Slot: object form or variant qualifier](https://biolink.github.io/biolink-model/docs/chemical_affects_gene_association_object_form_or_variant_qualifier.html)
    [Slot: object form or variant qualifier](https://biolink.github.io/biolink-model/docs/chemical_gene_interaction_association_object_form_or_variant_qualifier.html)
    [Slot: object part qualifier](https://biolink.github.io/biolink-model/docs/chemical_affects_gene_association_object_part_qualifier.html)
    [Slot: object part qualifier](https://biolink.github.io/biolink-model/docs/chemical_gene_interaction_association_object_part_qualifier.html)
    [Slot: pages](https://biolink.github.io/biolink-model/docs/publication_pages.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/anatomical_entity_to_anatomical_entity_ontogenic_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/anatomical_entity_to_anatomical_entity_part_of_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/chemical_affects_gene_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/chemical_entity_assesses_named_thing_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/chemical_entity_or_gene_or_gene_product_regulates_gene_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/chemical_gene_interaction_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/chemical_or_drug_or_treatment_side_effect_disease_or_phenotypic_feature_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/chemical_or_drug_or_treatment_to_disease_or_phenotypic_feature_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/chemical_to_chemical_derivation_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/contributor_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/disease_or_phenotypic_feature_to_genetic_inheritance_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/druggable_gene_to_disease_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/gene_to_expression_site_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/gene_to_gene_coexpression_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/gene_to_gene_family_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/gene_to_gene_homology_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/gene_to_gene_product_relationship_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/genomic_sequence_localization_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/genotype_to_disease_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/genotype_to_gene_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/genotype_to_genotype_part_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/genotype_to_phenotypic_feature_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/genotype_to_variant_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/information_content_entity_to_named_thing_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/material_sample_derivation_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/model_to_disease_association_mixin_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/molecular_activity_to_pathway_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/named_thing_associated_with_likelihood_of_named_thing_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/organism_taxon_to_environment_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/organism_taxon_to_organism_taxon_interaction_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/organism_taxon_to_organism_taxon_specialization_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/pairwise_gene_to_gene_interaction_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/pairwise_molecular_interaction_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/population_to_population_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/variant_to_disease_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/variant_to_gene_association_predicate.html)
    [Slot: predicate](https://biolink.github.io/biolink-model/docs/variant_to_gene_expression_association_predicate.html)
    [Slot: published in](https://biolink.github.io/biolink-model/docs/article_published_in.html)
    [Slot: published in](https://biolink.github.io/biolink-model/docs/book_chapter_published_in.html)
    [Slot: qualified predicate](https://biolink.github.io/biolink-model/docs/chemical_affects_gene_association_qualified_predicate.html)
    [Slot: qualifiers](https://biolink.github.io/biolink-model/docs/contributor_association_qualifiers.html)
    [Slot: quantifier qualifier](https://biolink.github.io/biolink-model/docs/gene_expression_mixin_quantifier_qualifier.html)
    [Slot: quantifier qualifier](https://biolink.github.io/biolink-model/docs/gene_to_expression_site_association_quantifier_qualifier.html)
    [Slot: species context qualifier](https://biolink.github.io/biolink-model/docs/chemical_affects_gene_association_species_context_qualifier.html)
    [Slot: stage qualifier](https://biolink.github.io/biolink-model/docs/gene_to_expression_site_association_stage_qualifier.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/anatomical_entity_to_anatomical_entity_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/anatomical_entity_to_anatomical_entity_ontogenic_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/anatomical_entity_to_anatomical_entity_part_of_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/behavior_to_behavioral_feature_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/case_to_entity_association_mixin_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/cell_line_as_a_model_of_disease_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/cell_line_to_disease_or_phenotypic_feature_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/cell_line_to_entity_association_mixin_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/chemical_affects_gene_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/chemical_entity_assesses_named_thing_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/chemical_entity_or_gene_or_gene_product_regulates_gene_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/chemical_entity_to_entity_association_mixin_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/chemical_gene_interaction_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/chemical_to_chemical_derivation_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/chemical_to_entity_association_mixin_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/chemical_to_pathway_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/contributor_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/disease_or_phenotypic_feature_to_entity_association_mixin_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/disease_to_entity_association_mixin_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/disease_to_phenotypic_feature_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/drug_to_entity_association_mixin_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/druggable_gene_to_disease_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/exon_to_transcript_relationship_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/exposure_event_to_phenotypic_feature_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/functional_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/gene_as_a_model_of_disease_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/gene_has_variant_that_contributes_to_disease_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/gene_to_disease_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/gene_to_entity_association_mixin_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/gene_to_expression_site_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/gene_to_gene_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/gene_to_gene_family_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/gene_to_gene_homology_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/gene_to_gene_product_relationship_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/gene_to_go_term_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/gene_to_pathway_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/gene_to_phenotypic_feature_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/genomic_sequence_localization_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/genotype_as_a_model_of_disease_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/genotype_to_disease_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/genotype_to_entity_association_mixin_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/genotype_to_gene_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/genotype_to_genotype_part_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/genotype_to_phenotypic_feature_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/genotype_to_variant_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/information_content_entity_to_named_thing_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/macromolecular_machine_to_entity_association_mixin_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/material_sample_derivation_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/material_sample_to_entity_association_mixin_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/model_to_disease_association_mixin_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/molecular_activity_to_chemical_entity_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/molecular_activity_to_molecular_activity_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/molecular_activity_to_pathway_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/organism_taxon_to_entity_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/organism_taxon_to_environment_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/organism_taxon_to_organism_taxon_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/organism_taxon_to_organism_taxon_interaction_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/organism_taxon_to_organism_taxon_specialization_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/organism_to_organism_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/organismal_entity_as_a_model_of_disease_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/pairwise_molecular_interaction_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/population_to_population_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/reaction_to_participant_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/sequence_feature_relationship_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/sequence_variant_modulates_treatment_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/taxon_to_taxon_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/transcript_to_gene_relationship_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/variant_as_a_model_of_disease_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/variant_to_disease_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/variant_to_entity_association_mixin_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/variant_to_phenotypic_feature_association_subject.html)
    [Slot: subject](https://biolink.github.io/biolink-model/docs/variant_to_population_association_subject.html)
    [Slot: subject aspect qualifier](https://biolink.github.io/biolink-model/docs/chemical_affects_gene_association_subject_aspect_qualifier.html)
    [Slot: subject aspect qualifier](https://biolink.github.io/biolink-model/docs/named_thing_associated_with_likelihood_of_named_thing_association_subject_aspect_qualifier.html)
    [Slot: subject context qualifier](https://biolink.github.io/biolink-model/docs/chemical_affects_gene_association_subject_context_qualifier.html)
    [Slot: subject context qualifier](https://biolink.github.io/biolink-model/docs/chemical_gene_interaction_association_subject_context_qualifier.html)
    [Slot: subject context qualifier](https://biolink.github.io/biolink-model/docs/named_thing_associated_with_likelihood_of_named_thing_association_subject_context_qualifier.html)
    [Slot: subject derivative qualifier](https://biolink.github.io/biolink-model/docs/chemical_affects_gene_association_subject_derivative_qualifier.html)
    [Slot: subject derivative qualifier](https://biolink.github.io/biolink-model/docs/chemical_gene_interaction_association_subject_derivative_qualifier.html)
    [Slot: subject direction qualifier](https://biolink.github.io/biolink-model/docs/chemical_affects_gene_association_subject_direction_qualifier.html)
    [Slot: subject form or variant qualifier](https://biolink.github.io/biolink-model/docs/chemical_affects_gene_association_subject_form_or_variant_qualifier.html)
    [Slot: subject form or variant qualifier](https://biolink.github.io/biolink-model/docs/chemical_gene_interaction_association_subject_form_or_variant_qualifier.html)
    [Slot: subject part qualifier](https://biolink.github.io/biolink-model/docs/chemical_affects_gene_association_subject_part_qualifier.html)
    [Slot: subject part qualifier](https://biolink.github.io/biolink-model/docs/chemical_gene_interaction_association_subject_part_qualifier.html)
    [Slot: type](https://biolink.github.io/biolink-model/docs/association_type.html)
    [Slot: type](https://biolink.github.io/biolink-model/docs/book_type.html)
    [Slot: type](https://biolink.github.io/biolink-model/docs/publication_type.html)
    [Slot: type](https://biolink.github.io/biolink-model/docs/serial_type.html)

**Comment by sierra-moxon** [comment]
Top level documenation has been refactored: https://biolink.github.io/biolink-model/

**Comment by vincentvialard** [comment]
perfect!
