### ISSUE TITLE
Domain 'None' in the documentation does not feel right

### ISSUE THREAD

**Issue by vincentvialard** [biolink/biolink-model#1161]
For instance on the [iri](https://biolink.github.io/biolink-model/docs/iri.html#domain-and-range) page:

> **Domain and Range**
> None -> 0..1 [IriType](https://biolink.github.io/biolink-model/docs/types/IriType.html)

If it should be kept informal, 'Anything' would be better suited.

**Comment by sierra-moxon** [comment]
Domain has been removed from the iri page: https://biolink.github.io/biolink-model/iri/

**Comment by vincentvialard** [comment]
Simple an elegant!
