### ISSUE TITLE
Title of the 'referenced by class' section of the documentation is misleading

### ISSUE THREAD

**Issue by vincentvialard** [biolink/biolink-model#1162]
At least on the [Gene](https://biolink.github.io/biolink-model/docs/Gene#referenced-by-class) page not classes but [association types](https://biolink.github.io/biolink-model/about/mapping-neo4j.html#association-types) are listed:

> **Referenced by class**
>   - **[DiseaseOrPhenotypicFeature](https://biolink.github.io/biolink-model/docs/DiseaseOrPhenotypicFeature.html)** [condition associated with gene](https://biolink.github.io/biolink-model/docs/condition_associated_with_gene.html) 0..* **[Gene](https://biolink.github.io/biolink-model/docs/Gene.html)**
>    - **[GeneProductMixin](https://biolink.github.io/biolink-model/docs/GeneProductMixin.html)** [gene product of](https://biolink.github.io/biolink-model/docs/gene_product_of.html) 0..* **[Gene](https://biolink.github.io/biolink-model/docs/Gene.html)**
 >   - **[GeneToGeneFamilyAssociation](https://biolink.github.io/biolink-model/docs/GeneToGeneFamilyAssociation.html)** [subject](https://biolink.github.io/biolink-model/docs/subject.html) 1..1 **[Gene](https://biolink.github.io/biolink-model/docs/Gene.html)**
 > ...

**Comment by sierra-moxon** [comment]
Thanks @vincentvialard, I can see how splitting associations from classes is inconsistent in the documentation, I'm working on a major documentation upgrade (https://github.com/sierra-moxon/biolink-model-doc) and I'll make sure this is clarified.  In Biolink, Associations are classes.

**Comment by sierra-moxon** [comment]
https://github.com/biolink/biolink-model/pull/1418
