### ISSUE TITLE
Types of subject and object not accessible in documentation of associations

### ISSUE THREAD

**Issue by vincentvialard** [biolink/biolink-model#1163]
The types of the subject and object of associations are found only in the UML diagrams (when readable). This critical information should be made easily accessible and include inherited information.

* An example of hardly readable UML diagram can be found on the [PairwiseMolecularInteraction](https://biolink.github.io/biolink-model/docs/PairwiseMolecularInteraction.html) page
* An example of hidden inherited subject can be found on the [DrugToGeneAssociation](https://biolink.github.io/biolink-model/docs/DrugToGeneAssociation.html) page

**Comment by sierra-moxon** [comment]
I hope the less detailed UML diagrams are easier to read now: https://biolink.github.io/biolink-model/DrugToGeneAssociation/, https://biolink.github.io/biolink-model/PairwiseMolecularInteraction/ -- its a balance in the UML generator between enough information to correctly represent the relationships, and a giant, unreadable diagram for very connected or high-level classes.  Hopefully the more detailed texts and tables make up for the less detailed diagram.

**Comment by vincentvialard** [comment]
It looks like you found a good balance, I sure can live with that!
