### ISSUE TITLE
erroneous id_mapping for chemical substance?

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#117]
The yaml has "CHEMBL.TARGET" for the id_mapping for chemical substance.  I think that should be "CHEMBL.COMPOUND" (or even just "CHEMBL").

I think CHEMBL.TARGET is the prefix for chembl's gene identifiers?

**Comment by cbizon** [comment]
Sorry, meant id_prefixes, not id_mapping

**Comment by nlharris** [comment]
For some reason this issue shows up on the list when filtering for is:open. I'm going to try reopening it and closing it again; maybe that will resolve the problem.

**Comment by nlharris** [comment]
Re-closing
