### ISSUE TITLE
Can we know when/if children are disjoint?

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#118]
@cmungall @mbrush 

**Are Biolink Model siblings disjoint?**

Some classes in biolink model are disjoint.  For instance, the translator group has decided that disease and phenotype are disjoint.  If there is an ALS entity in disease it is a different thing from an ALS entry in phenotype.

In discussions with @mbrush though, it appears that this is not a general feature of the model.  For instance, drug and metabolite might both have an entry for the same chemical substance.

**Why is this important?**

In ROBOKOP, we use the biolink model to help decide if calling a function might return the type I want based on how the function is annotated.  So, if I want a chemical substance, then a function that returns metabolites is a good one to call, and I can upcast anything I get back.  If a function returns a biological_process_or_activity, and I just want biological_process, I know that I can call it and try to filter out the things I want.

In cases where siblings are not disjoint, it means that basically I can call any function and might get anything back.  So if I want a drug, maybe I should call something that returns metabolites and try to work out if what I got back is a drug.  And there are cases where that makes sense.  But I don't think that if I want e.g. a gene, that calling a service returning drug makes any sense.  

**Possible paths forward**

1. Don't add anything to the model.  I can make some assumptions in our use of the model that will get over this issue, but might on occasion be incorrect.
2. Add some kind of annotation to a class saying that its children are disjoint
3. Add some kind of pairwise statement to a node saying explicitly that if you are an A, then you cannot be a B.
4. ?

**Comment by kshefchek** [comment]
This came up recently in applying bl categories in Monarch, for now we are going to assume that all categories are disjoint unless they can be connected by 1 or more is_a / subClassOf edges.

But as you mention this does break down in some cases (drug and metabolite) - we could do something like TypeClasses (drug) and RoleClasses (metabolite), but this could get complicated.  Adding an annotation to classes where children are disjoint is probably the way to go.

**Comment by nlharris** [comment]
> Adding an annotation to classes where children are disjoint is probably the way to go.

Is there agreement that this is the right solution, or does it need to be discussed?

**Comment by nlharris** [comment]
@sierra-moxon do you know anything about this?

**Comment by sierra-moxon** [comment]
@kshefchek - do you think you could give me a few more examples of how you would like to see this handled?

**Comment by sierra-moxon** [comment]
closing for now, LinkML does now allow us to declare disjointness, we now have a chemical role class.  We can certainly reopen if disjointness comes up again.
