### ISSUE TITLE
GeneToDiseaseAssociation doesn't have original_predicate slot

### ISSUE THREAD

**Issue by kevinschaper** [biolink/biolink-model#1181]
I hit a validation error when trying to add an original_predicate to a gene to disease association, it looks like it's just missing from the list of slots on the top level association class. 

I'll make a quick PR for it.

**Comment by kevinschaper** [comment]
It looks like original_subject and original_object aren't there either, I'll throw them in.  (I've used those, but not with the generated python/pydantic code, which seems to be my best validation step!)

**Comment by sierra-moxon** [comment]
merged in. closing.
