### ISSUE TITLE
chemical roles proposal

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#1187]
We would like to represent chemical roles consistently in Biolink.  ChEBI establishes [chemical role classes](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:51086) and assigns roles to chemical entities.  [Chiro](https://doi.org/10.26434/chemrxiv.12591221.v1 ) is a project that connects chemical roles to their targets. Chiro curators also establish property chains such that relationships between ChemicalEntities and their target molecular functions (for example) can be inferred. 

Our proposal for representing these associations in biolink is as follows:

1. Capture the association between a biolink:ChemicalEntity and its biolink:ChemicalRole (possible source: ChEBI via MolePro)

subject: biolink:ChemicalEntity
predicate: biolink:has_chemical_role (child of "related to instance level")
object: biolink:ChemicalRole
association: biolink:ChemicalToChemicalRoleAssociation

example association:
subject: Cvarespladib
predicate: has_chemical_role
object: anti-inflammatory

2. Capture the association between a biolink:ChemicalRole and its biolink:MolecularActivity (possible source: Chiro via MolePro)

subject: biolink:ChemicalRole
predicate: biolink:affects 
qualified_predicate: biolink:causes
object: biolink:MolecularActivity
object_aspect_qualifier: **activity?**
object_direction_qualifier: decreased
causal_mechanism_qualifier: inhibits

association: biolink:ChemicalRoleToMolecularActivityAssociation

example association:
subject: anti-inflammatory (CHEBI:)
predicate: affects
qualified_predicate: biolink:causes
object: Inflammatory response
object_aspect_qualifier: **activity?**
object_direction_qualifier: decreased
causal_mechanism_qualifier: inhibits

3. Capture the "shortcut" association between a biolink:ChemicalEntity and its biolink:MolecularActivity (possible source: Chiro via MolePro)

subject: biolink:ChemicalEntity
predicate: biolink:affects
object: biolink:MolecularActivity

association: biolink:ChemicalEntityToMolecularActivityAssociation

example association:
subject: Cvarespladib
predicate: biolink:affects 
qualified_predicate: biolink:causes
object: Inflammatory response
object_aspect_qualifier: **activity?**
object_direction_qualifier: decreased
causal_mechanism_qualifier: inhibits

4. Capture chemical treats disease association (via chemical role)

subject: Cvarespladib
predicate: treats
object: arthritis
** causal_mechanism_qualifier: anti-inflammatory (CHEBI:) ? **

subject: Cvarespladib
predicate: has_role
object: anti-inflammatory (CHEBI:)

#1132

**Comment by sierra-moxon** [comment]
<img width="893" alt="Screen Shot 2022-12-08 at 10 18 03 AM" src="https://user-images.githubusercontent.com/4561292/206534201-58b1b227-bfb2-4621-a612-812ff232b28f.png">

**Comment by sierra-moxon** [comment]
From the DM call: we like the "top" approach; modeling chemical roles explicitly.  We'd like this for a few reasons:
1) We may not always have the role-affects-activity/process edges.
2) We can see some applications for search/grouping that would be helpful (though from a UI perspective via Andy C., having roles on the chemical node itself as a node property would be easiest for their use cases). 
3) We can continue to curate Chiro to add these relationships to Translator.

**Comment by sierra-moxon** [comment]
https://github.com/biolink/biolink-model/pull/1197 fixes this

**Comment by karafecho** [comment]
Also see: https://github.com/NCATSTranslator/Feedback/issues/76.
