### ISSUE TITLE
correct prefix for ORPHANET?

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#1198]
from @colleenXu  
I'd like to confirm some prefixes in Biolink 3.1.1:
Is the prefix "orphanet", not ORPHANET or ORPHA? I notice that [Node Normalizer prod](https://nodenorm.transltr.io/1.3/get_normalized_nodes?curie=orphanet%3A1777&conflate=true) seems to recognize ORPHANET/orphanet as a prefix, but will only report the all-caps version in their response.
Is the prefix "CLINVAR" for clinvar variant IDs, not "ClinvarVariant"?

**Comment by sierra-moxon** [comment]
@colleenXu  - we try to use bioregistry prefixes when we can in Biolink model.  https://bioregistry.io/registry/orphanet

Some exceptions to this rule occur when a source we need to reference has a 'preferred' prefix that has been established and well-used in our domain for many years.  For example, `NCBIGene` is used in Biolink instead of `ncbigene` because we have users that depend on the `NCBIGene` capitalization and it has been widely adopted by the community ahead of the inception of bioregistry.   If `ORPHA` is another such case that we should specifically support over `orphanet` in Biolink, please let me know?  @cbizon 

I'd prefer to outsource as much of the prefix maintenance and authority as possible to Bioregistry but we can certainly make exceptions in Biolink when we need to.

**Comment by cbizon** [comment]
I'm not aware of any particular needs wrt Orphanet prefixes...

**Comment by colleenXu** [comment]
so then....clinvar variant seems to be this bioregistry entry? https://bioregistry.io/registry/clinvar so the prefix is "clinvar"?

**Comment by sierra-moxon** [comment]
The second complication here is that LinkML is helpfully warning about prefix case mismatches based on prefixcommons and identifiers.org (two of the existing prefix registries around before biolink and bioregistry).  In this case, prefixcommons wants `CLINVAR` so if I change the prefix from `CLINVAR` to `clinvar` in Biolink, we get a warning/error that we have a prefix case mismatch.  

I am working to allow Biolink to draw directly from a merged set of prefixmaps, via LinkML and the prefixmaps repository (see: https://github.com/linkml/linkml-runtime/pull/231) so that the error checking is configurable based on the prefixmaps we choose.

**Comment by colleenXu** [comment]
FYI I don't think our team has any preference for what the prefix for orphanet or clinvar variation/variant is..

If it's easier to use the prefixes from identifiers.org or prefixcommons or bioregistry...that's probably fine with us...

**Comment by sierra-moxon** [comment]
for what its worth, Biolink is now consistent in its use of `orphanet` as the prefix.

**Comment by sierra-moxon** [comment]
Let me know if this needs more attention?   Else I will close as completed.

**Comment by colleenXu** [comment]
Yeah, I think you can close this. We've noticed this but currently don't have plans to upgrade from v3.1.1...
