### ISSUE TITLE
3.1.1 QC report

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#1199]
from @colleenXu 
predicates
lines 1865-1867 and 1878-1880: both associated with likelihood of and its inverse are canonical predicates??
lines 2949-2950 and 2969-2970: gene associated with condition and its inverse. The domain and range for both are swapped and now incorrect?
lines 3916-3917, 3924-3925, 3929-3930, 3937-3938: domain and range for these predicates seems off (nucleic acid entities are not the only things that catalyze, molecular activities don't have substrates).
qualifiers:
lines 1203-1215: case of example values, typo with "analong", mismatch between examples and notes
lines 1226-1241: case of example values, mismatch between examples and notes
lines 1268-1274: mismatch between examples and notes
line 10441: typo absorbtion

**Comment by sierra-moxon** [comment]
predicates:
- [x] `lines 1865-1867 and 1878-1880: both associated with likelihood of and its inverse are canonical predicates??` 
I'm not sure what you are seeing here @colleenXu - maybe you are seeing the canonical tags on both `associated with increased likelihood` and `associated with likelihood` (note the `increased` in there).  I see their respective inverses in the model, and none of them are canonical. https://github.com/biolink/biolink-model/blob/2808534b51708af7ee22e707e7478b92f665dff9/biolink-model.yaml#L1869

- [x] `lines 2949-2950 and 2969-2970: gene associated with condition and its inverse. The domain and range for both are swapped and now incorrect?`
fixed. I think we had a PR that confused the two: https://github.com/biolink/biolink-model/commit/7fccc0564206327b3b5b3a33af85dba353379079. I fixed this PR for the information content entity changes, but I missed this one.  thanks.

- [ ] `lines 3916-3917, 3924-3925, 3929-3930, 3937-3938: domain and range for these predicates seems off (nucleic acid entities are not the only things that catalyze, molecular activities don't have substrates).`
will need to investigate further, this change was a commenting in of existing domain/range constraints.

- [x] `lines 1203-1215: case of example values, typo with "analong", mismatch between examples and notes`
fixed typo in the "notes" field, and lower cased the examples.  please do note that different serialization of the model will have different casing, but good catch on the notes and examples being different cases.

- [x] `lines 1226-1241: case of example values, mismatch between examples and notes`
lowercased the examples and notes to be case equivalent.

- [x] `lines 1268-1274: mismatch between examples and notes` 
please be more specific on the misunderstanding here, I do not see the issue.

- [x] `line 10441: typo absorbtion`
fixed

**Comment by colleenXu** [comment]
> lines 1865-1867 and 1878-1880: both associated with likelihood of and its inverse are canonical predicates??

I looked at this again, and yeah I forgot to expand the diff in github website. So it's my bad

> lines 1268-1274: mismatch between examples and notes

Notes mentions `hippocampus` which isn't in the example values and the example values aren't mentioned in the notes. Dunno if that's confusing...

**Comment by sierra-moxon** [comment]
moving the unresolved domain/range oddities to their own ticket:https://github.com/biolink/biolink-model/issues/1204
