### ISSUE TITLE
`required: true` setting from `slot usage` not correctly documented

### ISSUE THREAD

**Issue by vincentvialard** [biolink/biolink-model#1207]
The `required: true` setting from `slot usage` seems to be ignored in some parts of the documentation.

Examples from the ["Article" page](https://biolink.github.io/biolink-model/docs/Article.html) 

* `published in` in the ["Own" section](https://biolink.github.io/biolink-model/docs/Article.html#own)
* `type` in the ["Inherited from publication" section](https://biolink.github.io/biolink-model/docs/Article.html#inherited-from-publication)

are both wrongly annotated with `0..1`. In both case it should be `1..1` as stated in the slot usages and **correctly represented in the ULM diagram** (no question mark).

The "required: true" setting in slot definition seems to be working fine: the multiple `id` instances are all annotated with `1..1`.

**Comment by vincentvialard** [comment]
This might be due to the inheritance problems with `slot_usage` in LinkML.
See https://github.com/linkml/linkml/issues/48

**Comment by sierra-moxon** [comment]
https://biolink.github.io/biolink-model/Article/ - I believe this is now reflective of the model.

**Comment by vincentvialard** [comment]
Seems to be fixed.
As well the locally required `published in` as the for `Named Thing` required `category` are correct.
