### ISSUE TITLE
New Predicates to support CTD Gene-Chemical data 

### ISSUE THREAD

**Issue by mbrush** [biolink/biolink-model#121]
Chemical-Gene associations are an important data type that is currently missing/underrepresented across the Translator  ecosystem of  knowledge sources and services. CTD provides a dataset with over 1 million chemical-gene associations curated from the literature. All CTD chemical-gene interaction types in this dataset are shown [here](http://ctdbase.org/help/glossary.jsp).  There are 159 'predicates' possible given the 53 base interaction types  x 3 directions (affects, increases, decreases).  
 
Gamma currently has a simple representation of the CTD Chemical-Gene dataset using smartBags. This  data does not use BLM-compliant predicates, omits aspects of qualifying context, and only includes the simple/atomic interactions (i.e. omits nested interactions such as "Cadmium inhibits the reaction [Magnesium results in increased activity of ABCB1 protein]").  We plan to enhance this representation by providing specific BLM-based predicates describing the chemical-gene  interaction type, and qualifiers to add additional specificity and context for these associations.  For this we will need to create new predicates in the Biolink model to accommodate these interaction types.  

We propose creating 20 predicates and mapping the 159 in CTD data to these, as proposed in the mapping spreadsheet [here](https://docs.google.com/spreadsheets/d/1dOHh0Jp9Hbca7-bqXTN2ep_bvPIZdV78HfEIIjN-2wo/edit#gid=0) (this could expand to 60 if we include predicates for dec/inc for each interaction type, in addition to affects). In addition to these predicates, we will capture additional context for these associations using qualifier-based modeling patterns also proposed in the spreadsheet, These will capture things like more specific molecular modification type, the 'form' of the gene affected, and the species in which interaction was observed). 

Once the proposals are vetted and final, @mbrush will add the new predicates to the Biolink model, and @cbizon will use these to create an improved version of the gamma CTD smartBag data.  The goal is to have an API serving this data ready for the Portland Hackathon.

**Comment by mbrush** [comment]
**Longer term plans/improvements:**
- We will map human gene identifiers used in all records to the orthologous model organism gene identifier, and use this as the S/O in associations so we can drop the species qualifier.
- We will leverage the work @balhoff is doing to model these more complex, nested Chemical-Gene interactions in OWL using the GO-CAM approach, to create a flatter, graph-based representation to be included with the initial round of simple interactions. 
- We will consider implementing a transform form smartBags to a proper TKG in neo4j (e.g. SciGraph so we can create a Biolink API call for this data)

**Comment by mbrush** [comment]
**Summarizing initial decisions form the 9-9-18 KGS call:**

1. We will implement the predicates as listed in the spreadsheet,  save a few exceptions where further  diligence is required to understand what is being asserted as true in the data:
    -  **'affects  binding of'** is not appropriate  if these  associations are  just asserting  that a chemical binds a gene/produce.  use molecularly interacts with
     - similarly, **'affects transport of'** may not be appropriate  if these  associations assert that a gene  product is directly transporting the chemical - in which case we can use 'transports' as the predicate.  I spot  checked – 5 ‘affects’ and ‘increases’ records, which were  all about transporters/channels. But several ‘decreases’ records were not.  I think we have to use affects transport as a more general/forgiving predicate, as we  cannot  be sure that the gene product is doing the transporting in all cases. 

2. We will implement increases and decreases sub-predicates for each affects predicate. 

3. For qualifiers - review whether _gene products_ are always (or  nearly  always) the subjects of the 'affects molecular modification of' predicate.  If these are commonly used to describe modification of small molecules/none gene  products, then we may reconsider the use of GO terms as qualifiers (as these will likely be specific for protein modification, e.g. for acetylation (GO:0006473 ! protein acetylation

**Comment by mbrush** [comment]
Added 48 new predicates in [pull#122](https://github.com/biolink/biolink-model/pull/122), as per the mappings in the spreadsheet linked above, to accommodate initial ingest of  CTD  chemical-gene data by gamma.  

@vdancik and @saramsey be notified and review if you wish!

**Comment by balhoff** [comment]
@mbrush should there be increases/decreases molecular interaction with?

**Comment by deepakunni3** [comment]
This should be part of the recent predicate harmonization discussion.

**Comment by sierra-moxon** [comment]
@mbrush @vdancik - I am closing this issue as it indicates that there was a big PR pulling in many.  I will move @balhoff and @vdancik's comments on the PR (that was merged) into separate tickets if necessary (these comments might be handled already in other tickets from the chemical working group)?
