### ISSUE TITLE
uniprot prefixes in prefixmap seem to be a bit random and not uniprot purls

### ISSUE THREAD

**Issue by JervenBolleman** [biolink/biolink-model#1220]
e.g.  
```
  "UNIPROT.ISOFORM": "http://identifiers.org/uniprot.isoform/" 
"UniProtKB": "http://identifiers.org/uniprot/",
```
in the context.jsonld

these should be

"UniProtKB": "http://purl.uniprot.org/uniprot/",
and
"UNIPROT.ISOFORM": "http://purl.uniprot.org/isoforms/",

This was fixed in part in https://github.com/biolink/biolink-model/commit/5ddb324af703662b51c9b6a9972bab17639d321f
but got overwritten by something.

**Comment by sierra-moxon** [comment]
Thanks @JervenBolleman - Biolink imports prefix maps from a variety of sources, one of which currently is prefixcommons,  which establishes the UniProt expansion `"UniProtKB": "http://identifiers.org/uniprot/",` 

I'm working towards incorporating [prefixmaps](https://github.com/linkml/prefixmaps/blob/main/src/prefixmaps/data/merged.csv) prefix maps (merged maps from prefixcommons, identifiers.org, bioregistry, etc)  as well (which also has the identifiers.org expansion) 

It would be ideal if we could change the expansion upstream in one of these sources, but if we can't we can certainly add an exception in Biolink as we've done with other cases. :)

**Comment by kltm** [comment]
Tagging @cmungall . I'm assuming we use this metadata; wouldn't a change in identifier have consequences for what is already in play?

**Comment by JervenBolleman** [comment]
@kltm I suspect not, considering it has in the past already had a uniprot purl and a uniprot www address expansion :) They still represents the same thing.

**Comment by sierra-moxon** [comment]
closing as completed - for now we will put in exceptions in biolink, fixing later upstream in prefixmaps.
