### ISSUE TITLE
Some biolink predicates no longer exist in latest Biolink Model

### ISSUE THREAD

**Issue by nlharris** [biolink/biolink-model#1226]
Please see this issue for details: https://github.com/NCATSTranslator/Clinical-Data-Committee-Tracking-Voting/issues/23
@bill-baumgartner

**Comment by sierra-moxon** [comment]
These eliminated predicates are prime use cases for the qualifier methodology.  
Many examples here: https://biolink.github.io/biolink-model/guidelines/association-examples-with-qualifiers.html
and here: https://biolink.github.io/biolink-model/guidelines/reading-a-qualifier-based-statement.html

**Comment by nlharris** [comment]
Thanks, Sierra. Can this issue be closed?

**Comment by leonqli** [comment]
The links don't work any more. Please help check the docs. 

> These eliminated predicates are prime use cases for the qualifier methodology. Many examples here: https://biolink.github.io/biolink-model/guidelines/association-examples-with-qualifiers.html and here: https://biolink.github.io/biolink-model/guidelines/reading-a-qualifier-based-statement.html

**Comment by sierra-moxon** [comment]
@leonqli : 
https://biolink.github.io/biolink-model/association-examples-with-qualifiers/
https://biolink.github.io/biolink-model/reading-a-qualifier-based-statement/
