### ISSUE TITLE
Biolink prefixes for PharmGKB knowledge source

### ISSUE THREAD

**Issue by codewarrior2000** [biolink/biolink-model#1228]
**Is your feature request related to a problem? Please describe.**
We are mapping PharmGKB entities to Biolink

**What working group (or team) did this request originate from?**
The need for representing this type of data originated from MolePro
**Note:** This is relevant for members of NCATS Translator.

**Describe the solution you'd like**
In the [Biolink YAML](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml) we suggest the following four new prefixes:

1. PHARMGKB.DISEASE 'https://www.pharmgkb.org/search?type=disease&query='
2. PHARMGKB.CHEMICAL  'https://www.pharmgkb.org/search?type=chemical&query='
3. PHARMGKB.GENE 'https://www.pharmgkb.org/search?type=gene&query='
4. PHARMGKB.VARIANT 'https://www.pharmgkb.org/search?type=variant&query='

**Tag relevant members for discussion**
@sierra-moxon @vdancik

**Comment by codewarrior2000** [comment]
Hi, I see the Biolink YAML has been augmented with what I requested. Is this issue #1228 waiting for me to close it?

**Comment by sierra-moxon** [comment]
thanks @codewarrior2000 - yep! :). I'll close it now.
