### ISSUE TITLE
Add a record_url association slot

### ISSUE THREAD

**Issue by mbrush** [biolink/biolink-model#1238]
Needed to support the ability to capture urls of web pages that contain records of the knowledge expressed in an Association.   See  https://github.com/NCATSTranslator/ReasonerAPI/issues/392#issuecomment-1460937695.
 

### Proposed Biolink Association Slot:
 
````
record urls:
  is_a: association slot
  description: >-
    holds one or more urls for web pages that contain a specific record of the knowledge expressed in 
    the Association.  Note that this is similar to a biolink:xref you might find on a node, which provides 
    alternate database identifiers for the named thing the node represents, as a means to find more 
    information about this thing.  A 'record url' serves a similar purpose, but does not represent an
    identifier for the Association it hangs from - it simply points to a web page that contains within it 
    a record of the knowledge expressed. 
  range: uriorcurie

````

### Usage in TRAPI:
- The TRAPI schema provides a dedicated place in the RetrievalSources object to capture record urls from InformationResources that actually served as the source of this knowledge (`source_record_url`). 
- The Biolink property proposed here would be used as the key of a TRAPI Attribute object used to hold _additional_ record URLs from resources that were not one of the actual retrieval sources for an Edge, but which a KP wants to reference as additional web records of the reported knowledge.  
- - For more info, see https://github.com/NCATSTranslator/ReasonerAPI/issues/392#issuecomment-1460937695.

**Comment by sierra-moxon** [comment]
Shall we revisit the "xref" node property and align these two?  
It would be great to have one property that is allowed on both edges and nodes.

**Comment by mbrush** [comment]
I am all for this.  Is there a precedent or mechanism in LinkML to define a single property that can hang form a node or an edge/association?  Or would we need to define separate 'xref' properties (one node property, one  association slot)  that have the same 'xref' semantics?
