### ISSUE TITLE
PharmGKB chemical-to-gene-variant associations

### ISSUE THREAD

**Issue by codewarrior2000** [biolink/biolink-model#1242]
**Question:**
The PharmGKB knowledge source (https://www.pharmgkb.org) is rich in curated as well as un-curated data on how chemicals affects or affected by variants in genes. It uses PubMed publications to indicate the level of association between the variants and the chemicals used as drugs. Those levels may be either "associated", "not associated", or ambiguous".

For example, see:
https://www.pharmgkb.org/chemical/PA450428/variantAnnotation
where the "Association" table column contains information on how genotypes are associated with the chemical Methotrexate. If there are PubMed publications with opposing opinions on that association then PharmGKB would annotate it as "ambiguous".

The question is, how can MolePro convey PharmGKB's association information while also providing the Biolink predicate "affects" (and inverse predicate "affected_by") in the Knowledge Graph? Would it be a contradiction with the Biolink predicate if the association is "not associated".

**Comment by codewarrior2000** [comment]
Thank you [mbrush](https://github.com/mbrush). Nice work on the journal article, which provides more insight than the prosaic descriptions on the PharmGKB website.

**Comment by sierra-moxon** [comment]
discussed at helpdesk: will use `negation` property as needed.
