### ISSUE TITLE
remove smartapi infores

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#1245]
There are a number of infores entries that use the smartapi registration for their URL.   This url is now being displayed in the translator UI as a place for users to find more information.  I think most of these sources should have a better URL.  For instance the SRI reference KG could maybe point at monarch or somewhere.  For tools/aggregators, I think that the github page would even be more useful than the smart api registration.   Note that the registration IDs are not stable!

**Comment by cbizon** [comment]
@EvanDietzMorris can you check the infores & see if there are some that should be removed? e.g. obsolete automats

**Comment by EvanDietzMorris** [comment]
I made a PR for removing the obsolete/inactive automats. I wasn't sure what to put for the URLs for the other automats so those are still blank though.
