### ISSUE TITLE
Add node for prefix with properties for metadata

### ISSUE THREAD

**Issue by kshefchek** [biolink/biolink-model#127]
We want a node for a prefix that describes metadata about the source (base url, description, etc.)

**Comment by cmungall** [comment]
@mbrush @mellybelly any standard model we should use here?

E.g. https://schema.org/PublicationEvent

**Comment by deepakunni3** [comment]
What do we mean by a node for a prefix? @kshefchek 
Is this still relevant?

**Comment by kshefchek** [comment]
not sure what I meant to say here - looks like I made this during the portland translator hackathon, i'm guessing it was a request someone made and I translated poorly

**Comment by TomConlin** [comment]
A prefix is a name space. 
The name space may have context or attributes beyond the short sequence of characters that forms the (curie) prefix.

Internal and external preferred URI, valid categories, pointers to authoritative institutions, previous versions and known synonyms the list goes one and on.

Do not recall if the ticket came from me,  But a place to curate the few hundred prefixes in use would provide an obviouse starting place for allot of QC/avoiding issues in the first place.

**Comment by deepakunni3** [comment]
Having prefix node describe itself would be useful.
Not critical to Translator, but useful to have it implemented in biolink model

**Comment by sierra-moxon** [comment]
I believe this is handled in the InfoRes meta data catalog [here](https://docs.google.com/spreadsheets/d/1Ak1hRqlTLr1qa-7O0s5bqeTHukj9gSLQML1-lg6xIHM/edit#gid=293462374).  closing for now :) please reopen if necessary.
