### ISSUE TITLE
Add hpoa to infores catalog

### ISSUE THREAD

**Issue by kevinschaper** [biolink/biolink-model#1280]
We noticed that we had a string instead of the resource in kgx produced rdf for hpoa, and that hpoa isn't yet defined in the infores catalog

**Comment by kevinschaper** [comment]
Oh, whoops!  I'll just use the existing one. I guess if I was really trying to help future me I might sneak "hpoa" into the line somewhere for control-f-sake.

**Comment by nlharris** [comment]
So can this be closed?

**Comment by kevinschaper** [comment]
Yup, closing!  thanks for the nudge!
