### ISSUE TITLE
Formatting issue in infores_catalog_nodes rendering

### ISSUE THREAD

**Issue by nlharris** [biolink/biolink-model#1302]
In Slack, @andrewsu wrote:
Github is not rendering https://github.com/biolink/biolink-model/blob/master/infores_catalog_nodes.tsv in a nice table because some recent commits have deleted trailing tabs (for empty columns).  Seems like a recurring issue.  Would be great if someone wrote a simple one-liner/utility to make that file rectangular!

**Comment by sierra-moxon** [comment]
All fixed, and a validator was added.   I removed several columns at the end of the sheet as they were often null and often missed during PRs to add infores parameters.   I'm moving this file from TSV to YAML for easier editing.
