### ISSUE TITLE
infores catalog - some rows missing columns, causing bmt to crash

### ISSUE THREAD

**Issue by CaseyTa** [biolink/biolink-model#1306]
**Describe the bug**
biolink model toolkit keeps crashing for me
```
  File "/app/cohd/translator/__init__.py", line 6, in <module>
    bm_toolkit = Toolkit(f'https://raw.githubusercontent.com/biolink/biolink-model/{bm_version}/biolink-model.yaml')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bmt/toolkit.py", line 70, in __init__
    "description": line[5],
                   ~~~~^^^
IndexError: list index out of range
```

I think this is caused by a couple of rows in the infores catalog where there are fewer tabs/columns than expected. I think it may be rows 52 and 206 for BioCatalogue and Translator Knowledge Collaboratory API, where changes were made earlier today. 

**To Reproduce**
Instantiate the bmtoolkit. Doesn't seem to matter what version of biolink since they point to the infores catalog on master branch. 

**What working group (or team) did this request originate from?**
Clinical Data Services team

Note: This is relevant for members of NCATS Translator.

**Tag relevant members for discussion**
@sierra-moxon

**Comment by sierra-moxon** [comment]
Hi @CaseyTa  - good catch!   We did release a version of BMT on Friday last week that handles the change in field length in the infores catalog, https://github.com/biolink/biolink-model-toolkit/releases/tag/v1.0.13.  Would it be possible for you to try and upgrade?  

https://github.com/biolink/biolink-model/ we added a validation script for the infores catalog in version https://github.com/biolink/biolink-model/releases/tag/v3.3.2.

**Comment by sierra-moxon** [comment]
Thanks @CaseyTa  - I did end up finding more errors, so you were right.  I am converting that TSV to YAML as I think it will be easier to edit and validate.
