### ISSUE TITLE
Slot inheritance problems in documentation (at least)

### ISSUE THREAD

**Issue by vincentvialard** [biolink/biolink-model#1315]
The slot `name` in `NamedThing` is documented as being inherited from `macromolecular machine mixin`. This makes no sense at all. 

https://biolink.github.io/biolink-model/docs/NamedThing.html#inherited-from-macromolecular-machine-mixin

While not really a blocker, it does contribute to building trust in the model and its tooling and may reveal a real problem if the issue is caused by a module used outside of the documentation.

Related issue: #1164 

Here are all wrongly "inherited" slots of `NamedThing`: 

<img width="553" alt="Bildschirmfoto 2023-05-17 um 14 47 48" src="https://github.com/biolink/biolink-model/assets/16098519/1ee9c312-6cbd-4a09-bc1c-71a9149c695a">

**Comment by sierra-moxon** [comment]
https://biolink.github.io/biolink-model/name/ - this is the new doc page for the slot, "name".  Feedback welcome.

**Comment by vincentvialard** [comment]
the issue is gone and the new layout is way better!
