### ISSUE TITLE
`symbol` slot of the `Gene` class missing on the generated documentation

### ISSUE THREAD

**Issue by satra** [biolink/biolink-model#1351]
the `symbol` slot of the `Gene` class does not show up on the documentation. It can be seen in the diagram, but not under the list of attributes.

**Comment by sierra-moxon** [comment]
https://biolink.github.io/biolink-model/Gene/ - fixed doc page, feedback most welcome!

**Comment by sierra-moxon** [comment]
https://github.com/biolink/biolink-model/pull/1418
