### ISSUE TITLE
review mapping for "Biomedical or Dental Material" (STY:T122 / bodm)

### ISSUE THREAD

**Issue by andrewsu** [biolink/biolink-model#1355]
In https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L6678C17-L6678C17, `STY:122` (the UMLS semantic type for "Biomedical or Dental Material", abbreviation "bodm") is mapped to `biolink:device`. I just want to ask that someone take a second look at this to make sure that's what's intended.  Examples of entities that fall under this semantic type can be found here: https://biothings.ncats.io/semmeddb/query?q=subject.semantic_type_abbreviation:bodm&fields=subject.name&limit=100.  

This issue arose in the context of https://github.com/NCATSTranslator/Feedback/issues/407, in which Durapatite was labeled as a device.

**Comment by sierra-moxon** [comment]
Note: STY:T122 is a narrow mapping in the model to "biolink:device". Some examples include: (e.g "eye drops", "suspensions", "fluoride", "microplastics", "Durapatite", "flakes", "Alloys", "Biocompatible Materials" ... quite a wide range, and quite a wide definition of "biolink:Device" as well).

Also, from MeSH:

"The mineral component of bones and teeth; it has been used therapeutically as a prosthetic aid and in the prevention and treatment of osteoporosis."

prosthetic aid as a device doesn't seem wrong as a narrow mapping.

I don't see a better place for this in the model, but I can remove the mapping. Thoughts?

**Comment by gaurav** [comment]
I wonder if biolink:Drug might be a better mapping for this semantic type? In any case, we have 6,917 UMLS IDs that we're currently leaving out of NodeNorm because we don't have a Biolink Model mapping for STY:T122: https://github.com/TranslatorSRI/Babel/issues/421
