### ISSUE TITLE
trapi validation issue with biolink:support_graphs 

### ISSUE THREAD

**Issue by colleenXu** [biolink/biolink-model#1363]
**Describe the bug**
There's an issue with TRAPI validation where KG edges with the attribute `biolink:support_graphs` are being flagged with a warning. I think this is happening because [support_graphs](https://github.com/biolink/biolink-model/blob/ea0ebc39362626c2dec85b597c4574f153adb0de/biolink-model.yaml#L666) isn't an association slot in the biolink-model or is somehow not being recognized as a valid edge-attribute attribute_type_id...

This is an example warning message from BTE's validation report at this [PK](https://arax.ncats.io/?r=4352f003-ee4c-420c-8e34-88af3d9dcb32). 

```
* Knowledge Graph Edge Attribute Type Id Not Association:
=> Edge has an attribute_type_id that is not an association slot
	$ infores:biothings-explorer
		# biolink:support_graphs:
		- edge_id: 
			MESH:C007789--biolink:treats->MONDO:0007035
	$ global
		# biolink:support_graphs:
		- edge_id: 
			CHEMBL.COMPOUND:CHEMBL4298120--biolink:treats->MONDO:0007035
```

**What working group (or team) did this request originate from?**
Exploring Agent / Service Provider

@sierra-moxon @RichardBruskiewich

**Comment by sierra-moxon** [comment]
thanks @colleenXu.

**Comment by sierra-moxon** [comment]
@colleenXu - https://github.com/biolink/biolink-model/pull/1364 for your review.

**Comment by colleenXu** [comment]
Looks like the PR will help. 

I'm unsure if there's a way to test whether PRs / latest versions of biolink-model help with reasoner-validator errors. Based on the docs for reasoner-validator, it looks like it depends on biolink-model toolkit. And it's unclear to me if biolink-model toolkit can handle PRs / latest versions of biolink-model (above 3.5.0?)....
