### ISSUE TITLE
add CellOntology in the Biolink model

### ISSUE THREAD

**Issue by gloriachin** [biolink/biolink-model#1368]
**Is your feature request related to a problem? Please describe.**
I want to add "CellOntology" id prefix in the Biolink model. 

**Describe the solution you'd like**
"CellOntology":"http://purl.obolibrary.org/obo/CL_"
or 
"CellOntology":"http://purl.obolibrary.org/obo/"

**What working group (or team) did this request originate from?**
The need for this change originated from the Multiomics Provider team.

**Tag relevant members for discussion**
@gloriachin   @sierra-moxon

**Comment by gloriachin** [comment]
The result triple may look like this:

{
  "_id": "Gene_biolink:expressed_in_Cell_cellmarker.csv_45921",
  "attributes": [
    {
      "attribute_type_id": "biolink:publications",
      "value": "PMID:34875227"
    },
    {
      "attribute_type_id": "biolink:primary_knowledge_source",
      "value": "infores:cellmarker2.0" #may also need to add infores
    },
 
    {
      "attribute_type_id": "biolink:anatomical_context_qualifier",
      "value": "UBERON_0000160"
    }
  ],
  "object": {
    "CellOntology": "CellOntology:CL_0000236",
    "id": "CellOntology:CL_0000236",
    "name": "B cell",
    "type": "Cell",
    "xref": "http://purl.obolibrary.org/obo/CL_0000236"
  },
  "predicate": "biolink:expressed_in",
  "sources": [
    {
      "resource_id": "infores:cellmarker2.0",
      "resource_role": "primary_knowledge_source"
    },
    {
      "resource_id": "infores:biothings-multiomics-biggim-drugresponse",
      "resource_role": "aggregator_knowledge_source",
      "upstream_resource_ids": [
        "infores:cellmarker2.0"
      ]
    }
  ],
  "subject": {
    "NCBIGene": "NCBIGene:930",
    "id": "NCBIGene:930",
    "name": "CD19",
    "type": "Gene",
    "xref": "https://www.ncbi.nlm.nih.gov/gene/930"
  }
}

**Comment by balhoff** [comment]
@gloriachin the standard prefix for Cell Ontology terms is `CL`, expanding to `http://purl.obolibrary.org/obo/CL_`. It is in Biolink (see https://github.com/biolink/biolink-model/blob/68d4e3d7612275d0d7e832a9919bf8666e1d5fde/prefix-map/biolink-model-prefix-map.json#L25).

The terms would be written as, e.g., `CL:0000236`. Does that work for you?

**Comment by gloriachin** [comment]
Thank you, @balhoff !
