### ISSUE TITLE
Add infores entry for KINOMEscan

### ISSUE THREAD

**Issue by vdancik** [biolink/biolink-model#1372]
With @michelle-mantilla we are adding a new knowledge source; KINOMEscan is a biochemical kinase profiling assay that measures drug binding using a panel of ~440 purified kinases:

https://lincs.hms.harvard.edu/kinomescan/

    knowledge level: raw data
    agent type: experimental

**Comment by sierra-moxon** [comment]
MolePro is not changing the data at all - its passing raw data to the consumer.
We need to verify that knowledge_level "raw_data" is ubiquitous for other edges. 
added in PR: https://github.com/biolink/biolink-model/pull/1377
