### ISSUE TITLE
Incorrect slot ranges for `trade name` and `is supplement` ?

### ISSUE THREAD

**Issue by tmprd** [biolink/biolink-model#1378]
Hello! 
`chemical entity` [has slot](https://github.com/biolink/biolink-model/blob/2efa8910f615342f2db52a17f6e573128e4209fe/biolink-model.yaml#L6862) `trade name`, but `trade name` [has range](https://github.com/biolink/biolink-model/blob/2efa8910f615342f2db52a17f6e573128e4209fe/biolink-model.yaml#L1187) `chemical entity`. 
Also, `chemical mixture` [has slot](https://github.com/biolink/biolink-model/blob/2efa8910f615342f2db52a17f6e573128e4209fe/biolink-model.yaml#L6952) `is supplement`, but `is supplement` [has range](https://github.com/biolink/biolink-model/blob/2efa8910f615342f2db52a17f6e573128e4209fe/biolink-model.yaml#L1182) `chemical mixture`.
Should these slot ranges be removed or corrected to domains?

I found these slots while loading the Biolink schema into [VALVE](https://github.com/ontodev/valve/tree/main), which is used for editing and validating very large amounts of data in [Nanobot](https://github.com/ontodev/nanobot.rs). I'm updating [this project](https://github.com/tmprd/valve-linkml) which converts LinkML schemas into VALVE by generating SQL tables for each class, columns for each slot, and foreign keys for each slot range, similar to other LinkML [generators](https://linkml.io/linkml/generators/index.html). Converting these slots results in cyclic dependencies.

Regardless of the conversion I'm working on, I thought these slots might be a problem for the Biolink model in particular. Or am I misunderstanding the meaning of a slot range in LinkML?

**Comment by sierra-moxon** [comment]
thank you for the ticket @tmprd - you're right, these are errors.
