### ISSUE TITLE
biolink-model.yaml snake case edge labels

### ISSUE THREAD

**Issue by lhannest** [biolink/biolink-model#139]
From the *Translation Knowledge Graph Standard Specification* document:

> edge_label [required]: MUST be from minimal list. - a high-level grouping for the relationship type. AKA minimal predicate, analogous to blm:category for nodes. BLM predicates have no identifiers, so use the snake_case label of the predicate (e.g. “expressed_in”)

But edge labels do not appear as snake case in [biolink-model.yaml](https://biolink.github.io/biolink-model/biolink-model.yaml). So checking that an edge label is compatible with the biolink model requires this ad hoc translation:

```python
is_compatible = edge_label.replace('_', ' ') in blm.schema().slots
```

@cmungall  Should we update all edge labels to be snake case in the biolink-model.yaml so that this sort of translation is not needed?

**Comment by cmungall** [comment]
@hsolbrig I don't think we should be encouraging any string manip - is there a better util method?

**Comment by hsolbrig** [comment]
@cmungall I think updating edge labels would be a really good idea. We're still going to have to mangle names for some targets (URL's being a prime example, IIRC), but the embedded spaces are a bit of a pain.  What would it take?

**Comment by hsolbrig** [comment]
@cmungall should we catch class names as well?  If so, do we go to camel case?

**Comment by cmungall** [comment]
It's designed so that the model is neutral but allows different serializations

**Comment by hsolbrig** [comment]
How much damage would we do if we replaced " " with "_" throughout?  I would be inclined to overload the slots, classes and types dictionaries so that all valid representations will work (vs. having to do the code snipped above).  I'd also be inclined to add a "canonical representation" where we are consistent (snake for slot, camel for class and type?)

**Comment by deepakunni3** [comment]
This can (and will) be handled in biolink-model-toolkit
