### ISSUE TITLE
Biolink Model "Cookbook" or ...

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#1412]
### Guidelines for Curating Biomedical Knowledge into Knowledge Graphs using the Biolink Model

Biolink Model usability:  some few years ago, the idea of documenting "best practices" of applying Biolink to encode specific knowledge. 

As the size and complexity of the Biolink Model continues to grow, this idea speaks of an increasing need for something beyond just "lookup" Biolink documentation, rather,  for some kind of more complete "cookbook" for the curation of external primary source knowledge into Biolink-compliant knowledge graphs. 

The **`treats`** predicate discussion is a good example of a part of the model which might really benefit from such a discourse (maybe Matt's October 26, 2023 Data Modelling call slides would form a good starting point for prototyping such a document)

Unless there are some obvious "cookbook" parameters - in addition to _examples forward design_  with Biolink YAML embedded examples run as tests - to encode directly into the Biolink Model elements themselves, we may wish to set up some novel kind of (LinkML?) 'generator' of 'cookbook' stub pages.

Such a compendium of 'cookbook' would be deployed separately from the regular Biolink Model 'contents-centric' documentation.

The stub 'cookbook' pages could be generated from a well thought out 'cookbook' page template, one page for each pertinent element in the Biolink Model? My guess is that the stub pages would mainly focus proper usage of the 'higher' level conceptual elements of Biolink, like categories, predicates and associations, and perhaps, key mixins (like 'treats' ;-))

Such pages would go beyond the model concept and relationship definitions (and slot contents) but rather, add searchable and fully indexed more verbose use case driven "best practices" discussions about how to represent specific knowledge using specific Biolink Model elements that accurately represent the underlying primary knowledge statements.

We may wish also to have some kind of 'tag' in the stub pages which determines status of the page as '**`stub`**', '**`under curation`**' and '**`published`**' to control public visibility and indexing, that is, to ensure that a 'cookbook' answer is only made public once the documentation has been properly curated by a human SME/SMURF/Biolink Model expert. 

We also somehow need to account for the fluidity of the Biolink Model - deprecations, renames, etc. - as it impacts the accuracy of the cookbook.

**Comment by sierra-moxon** [comment]
https://github.com/biolink/biolink-model/pull/1418
