### ISSUE TITLE
Should `OrganismTaxon` be a child of `OrganismalEntity` ?

### ISSUE THREAD

**Issue by hrshdhgd** [biolink/biolink-model#1419]
My question in the subject is based on the [tree here](https://tree-viz-biolink.herokuapp.com/categories) and a slack conversation with @cmungall . As per the tree:
-  `OrganismTaxon` `IS_A` `NamedThing` and has no relation to `OrganismalEntity`.
-  `OrganismalEntity` `IS_A` `BiologicalEntity` `IS_A` `NamedThing`.

Is this intentional by design or a bug?

**Comment by sierra-moxon** [comment]
It looks like a bug to me.  At the very least, OrganismTaxon should be a subclass_of OrganismalEntity.

**Comment by cmungall** [comment]
I think it's fine. OE is a grouping for individual organisms and parts of organisms. OT is a classification
