### ISSUE TITLE
schema fails linkml validation

### ISSUE THREAD

**Issue by glass-ships** [biolink/biolink-model#1420]
`biolink-model.yaml` fails LinkML validation

**Steps to Reproduce**
```python
>>> gene = {
    "id": "BOGUS:12345",
    "name": "Bogus Gene 12345",
    "category": ["biolink:NamedThing", "biolink:Gene"],
}
>>> from linkml.validator import validate
>>> model_url = "https://raw.githubusercontent.com/biolink/biolink-model/latest/biolink-model.yaml"
>>> v = validate(instance=gene, target_class="gene", schema=model_url)
```
Returns:
```
...
ValueError: WIKIDATA_PROPERTY:P854 is not a valid URI or CURIE
...
ValueError: Invalid schema: https://raw.githubusercontent.com/biolink/biolink-model/latest/biolink-model.yaml
```

**Expected behavior**
LinkML validator should successfully validate the biolink model schema

**What working group (or team) did this request originate from?**
This bug originated from the Monarch technical team (via Koza).

**Comment by sierra-moxon** [comment]
Thanks @glass-ships - please use linkml-runtime 1.6.0 in your project for the moment: we're dealing with a bug upstream: https://github.com/linkml/linkml-runtime/pull/283

**Comment by glass-ships** [comment]
gotcha, thanks for the update sierra!
