### ISSUE TITLE
NCIT prefix should be defined in the biolink-model.yaml `prefixes` section

### ISSUE THREAD

**Issue by gaurav** [biolink/biolink-model#1425]
**Is your feature request related to a problem? Please describe.**
Every prefix used in Biolink should be defined in the `prefixes` section so that it can be converted into an IRI. Example usage of the `NCIT:` prefix:

https://github.com/biolink/biolink-model/blob/7893e8763dcc508d5ba39104c2dea98b3d547ce3/biolink-model.yaml#L575

**What working group (or team) did this request originate from?**
Translator SRI (NodeNorm)

**Note:** This is relevant for members of NCATS Translator.

**Describe the solution you'd like**
NCIT should be defined in the `prefixes` section, either pointing to `http://purl.obolibrary.org/obo/NCIT_` or `http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#`. `http://purl.obolibrary.org/obo/NCIT_` would be better, since that is what UberGraph uses (see [example query](https://api.triplydb.com/s/DK0Mi95so)).

There _is_ a definition of NCIT-OBO in biolink-model.yaml, so maybe that could be renamed to `NCIT` or for references to `NCIT` could be renamed to `NCIT-OBO`:

https://github.com/biolink/biolink-model/blob/7893e8763dcc508d5ba39104c2dea98b3d547ce3/biolink-model.yaml#L106

**Tag relevant members for discussion**
@sierra-moxon

**Comment by sierra-moxon** [comment]
@gaurav - we do produce a prefix map (including imported prefixes from other registries).  the prefixes section is just for cases where Translator or other uses of Biolink can't comply with the registries upstream (or are waiting for reconciliation upstream):  https://github.com/biolink/biolink-model/blob/master/prefix-map/biolink-model-prefix-map.json (note: this will move in the PR for refactoring Biolink documentation to https://github.com/biolink/biolink-model/blob/master/project/prefixmap/biolink-model-prefix-map.json)

**Comment by gaurav** [comment]
Got it -- and the `NCIT` prefix is in the prefix map! I'll go ahead and close this ticket.

https://github.com/biolink/biolink-model/blob/7893e8763dcc508d5ba39104c2dea98b3d547ce3/prefix-map/biolink-model-prefix-map.json#L123

**Comment by gaurav** [comment]
The prefix-map directory appears to have been moved in Biolink v4.0 to [project/prefixmap/biolink_model_prefix_map.json](https://github.com/biolink/biolink-model/blob/v4.0.0/project/prefixmap/biolink_model_prefix_map.json).
