### ISSUE TITLE
Some confusion about the URL to be used for NCBIGene in the prefix map

### ISSUE THREAD

**Issue by gaurav** [biolink/biolink-model#1431]
The NCBIGene concept IRI prefix in the Biolink Model prefix map is `http://identifiers.org/ncbigene/`:

https://github.com/biolink/biolink-model/blob/ce4f70988e4141b50fe9e1161d696483094fe192/prefix-map/biolink-model-prefix-map.json#L121

However, Ubergraph thinks the concept IRI prefix should actually be `https://identifiers.org/ncbigene/` (i.e. `https` instead of `http`), which comes from the [Provisional Cell Ontology (PCL)](https://www.ebi.ac.uk/ols4/ontologies/pcl/classes/https%253A%252F%252Fidentifiers.org%252Fncbigene%252F4522), while identifiers.org thinks it should be `https://identifiers.org/ncbigene:` or `https://www.ncbi.nlm.nih.gov/gene/` (https://registry.identifiers.org/registry/ncbigene).

I would propose that Biolink Model goes with `https://identifiers.org/ncbigene/` to keep us in sync with Ubergraph, but I don't know if these identifier.org concept need to be rethought at some point.

@balhoff Any thoughts on this?

**Comment by cmungall** [comment]
Yes, in fact identifiers.org has over the years given 2x2 options (http vs https, slash vs hash). From a web browser POV it doesn't matter, they all resolve. But for semantic URIs this indecision destroys interoperability between triplestores.

as http-with-slash was the first that is what many groups adopted first, so we should stick to that. If we do make a change it should be something with absolute guaranteed cast iron permanence.

**Comment by sierra-moxon** [comment]
I followed up with the CL folks, and they had  just had a new release with this change merged in.  I am going to call this Biolink issue closed as I imagine @balhoff's ubergraph will be updated automatically, and that will trigger a fix for you, @gaurav -- please of course reopen if I missed a component.
