### ISSUE TITLE
chemical to pathway association domain

### ISSUE THREAD

**Issue by lhannest** [biolink/biolink-model#144]
Is `molecular entity` in the domain of `chemical to pathway association`? Right now no domain is specified. But I want to know if a protein can be the subject of this kind of association. I am not sure if "chemical" is intended to refer to `chemical substance` or `molecular entity`.

https://github.com/biolink/biolink-model/blob/72f9107a6138ee3723df1f1a312e85496145d82e/biolink-model.yaml#L2469-L2484

**Comment by deepakunni3** [comment]
@cmungall Do we know for sure what the domain for this association ought to be?

**Comment by deepakunni3** [comment]
Change to molecular entity to pathway association

**Comment by sierra-moxon** [comment]
Also, the chemical hierarchy refactor worked on this area and I believe disambiguated the model?  closing.  please reopen if the issue still needs work.  :)
