### ISSUE TITLE
Create a class representing Information Resources

### ISSUE THREAD

**Issue by mbrush** [biolink/biolink-model#1447]
Should we define a class in Biolink to represent the notion of an `InformationResource`, as implemented in the [infores catalog](https://github.com/biolink/biolink-model/blob/knowledge_level_agent_type/infores_catalog.yaml)?  Would be good to have a formal, authoritative place to reference and describe what these are, and what properties they have.

**Definition**: an information system that provides data or knowledge content.

**Description**: 
- The infrastructure of such ‘information systems’ necessarily includes a database or knowledgebase to store content, and interfaces/services that deliver content to consumers (e.g. web portals, APIs, query endpoints, streaming services, data download sites, etc.) 
- A single Information Resource may span/serve content from many different datasets or databases, across its access endpoints and interfaces. 
- However, if two separate API/web service infrastructures are  independently set up to distribute content from the same underlying databases - possible using different structures/models  - these represent different Information Resource instances.
Slots attached to this class can include those in the[ infores catalog](https://github.com/biolink/biolink-model/blob/knowledge_level_agent_type/infores_catalog.yaml) used to collect metadata about Information Resource instances.

**Comment by sierra-moxon** [comment]
We already do! :) -- this is the schema I used to validate the infores_catalog.yaml (in concert with a URL checking script I wrote to ensure that every URL in the catalog resolves).   https://github.com/biolink/biolink-model/blob/master/information-resource.yaml -- PR's welcome to help clarify.
