### ISSUE TITLE
Missing enum for approval status

### ISSUE THREAD

**Issue by vdancik** [biolink/biolink-model#1452]
**Describe the bug**
Missing enum for `highest FDA approval status` and `drug regulatory status world wide`

**Expected behavior**
Restore `FDAApprovalStatusEnum` from a previous Biolink version or or define a new enumeration.

**What working group (or team) did this request originate from?**
MolePro

**Comment by nlharris** [comment]
see also #869

**Comment by sierra-moxon** [comment]
@vdancik - `highest FDA approval status` and `drug regulatory status world wide` are still their own slot in Biolink (have not changed).  Do you want them to be part of a enum?  I think the original intent was to save `FDAApprovalStatusEnum` for those statuses that were not the highest -- these two slots were to help "denormalize" the edge metadata to a chemical node for easier retrieval.

**Comment by sierra-moxon** [comment]
clarified at the DM call 03/28/24 - we would like an enumeration to constraint `highest FDA approval status` with a set of permissible values.  `drug regulatory status world wide` should have a similar permissible value enumeration.

the change of the enumeration was to accommodate "edge level" annotation, so we might need a different set for this.
