### ISSUE TITLE
Is the associations in BioLink model going to distinguish experimentally-validated results vs ML prediction results

### ISSUE THREAD

**Issue by kevinxin90** [biolink/biolink-model#15]
Hi,

I'm wondering is the associations in BioLink model going to distinguish experimentally validated results against computational predicted results?

One example would be the 'ChemicalToGeneAssociation' (http://bioentity.io/vocab/ChemicalToGeneAssociation). 

There are two available API endpoints:

1. https://www.ebi.ac.uk/chembl/api/data/target_prediction
2. http://www.dgidb.org/api/v2/interactions.json?drugs={drugname}

They both contain information about chemical2gene associations, but the first one is from computational predicted results, while the second one is from experimentally validated results. 

Is the BioLink model going to regard these two cases as the same association or not?

Thanks!

**Comment by cmungall** [comment]
The core association model aims to represent the underlying statement about a biological relationship, regardless of evidence. Evidence would be added as additional properties on the association object.

The actual evidence model is orthogonal. We could opt for a simple model similar to what GO and Wikidata use, e.g. using [ECO](http://obofoundry.org/ontology/eco.html) to record evidence type. At the top level ECO distinguishes between experimental and computed; we could choose to adopt that as a minimal standard within translator. This would leave open the option of a richer evidence model, such as [SEPIO](http://obofoundry.org/ontology/sepio.html).

Should we include evidence as a future topic for discussion on a translator call? On the one hand I am keen to push forward discussing some minimal standard we can adopt. On the other, it might be easy for us to get distracted here, and we should perhaps wait first for use cases?

**Comment by mbrush** [comment]
+1 to Chris' response.  I think we can move on to evidence _after_ the core association model is set – including the task of standardizing semantic types and predicates.  Initially, we can limit any evidence metadata we need to collect to a simplistic model (ECO codes  + publications that hang from the association itself). 

As Chris indicated, SEPIO is designed to extend this simplistic model to provide richer evidence and provenance metadata. For example it would allow you to describe that actual data used as evidence (i.e. experimental measurements or computed scores), the details of the methods and tools used to generate these data, and even delineate when separate lines of evidence that are used in support of an assertion.

Once the core association model is set, hopefully soon, we can take a deeper dive into the orthogonal issue of a richer evidence and provenance model.

**Comment by kevinxin90** [comment]
Thanks! That makes perfect sense to me!!

**Comment by nlharris** [comment]
Is this question resolved or is there more to be done on this ticket?

**Comment by sierra-moxon** [comment]
@mbrush @kevinxin90 - I am closing this case with the notion that all of our EPC meta data group work has taken care of harmonizing evidence representation in the model (though we are still adding properties to capture supporting data types, etc.  - This more specific work is documented in other tickets).  Please reopen if your concerns aren't being addressed?
