### ISSUE TITLE
Evaluate gra.fo

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#151]
close if not relevant, of interest @hsolbrig?

EMAIL BELOW

A common frustration we’ve encountered is the lack of adequate tooling around ontology and knowledge graph schema design. Many tools exist-- some are overly complex, some are very expensive, and none allow one to work visually, collaboratively and in real time on a document with multiple concurrent users.

That is why two years ago we took half a dozen Capsenta engineers and set off to design and develop a solution. Our design principles were: 
- Real World: Focus on solving problems that we encounter in the real world with our customers and users.  
- Understand our audience: We work with data geeks but also business and domain experts-- our solution has to satisfy them both.
- Minimal: Let’s not boil the ocean; be focused and practical.
- Do not reinvent the wheel: A lot of great research and scientific results exist that should be leveraged.

With that in mind, we are very pleased to announce the official launch of Gra.fo (https://gra.fo/), a visual, collaborative, and real-time ontology and knowledge graph schema editor. It is the only editor where you can:

- Visually design your schema by dragging and dropping Concepts, Attributes, Relationships and Specializations-- what we lovingly refer to as C/A/R/S.
- Share your document with other users and grant view-only, commenting, or editing permissions.
- Collaborate in real-time with multiple users.
- Comment on individual C/A/R/S with other users.
- Search for C/A/R/S.
- Track document history, name a version and restore to any previous version.

Like other knowledge graph editing software, Gra.fo lets you Import and Export existing RDF/OWL ontologies. Property Graphs are also supported. For an overview of Gra.fo’s features, check out this short demo: http://bit.ly/grafokg

Gra.fo is currently the only visual, collaborative, and real-time ontology and knowledge graph schema editor in existence. But that’s not good enough for us. We want to be the best knowledge graph editor, period. Toward that end we are actively working on several new features with more to come:

- Git: Commit and push your document to Git.
- Import Mapping: View R2RML mappings within Gra.fo.
- API: Access and build knowledge graphs programmatically.

Please check it out at https://gra.fo/. We offer one month gratis at the Team level so feel free to try out all that Gra.fo offers. Serving the community is important to us so please let us know what you need!

--
Juan Sequeda, Ph.D
www.juansequeda.com

**Comment by deepakunni3** [comment]
@cmungall Still relevant?
