### ISSUE TITLE
Clarify evidence model and align with biothings

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#152]
https://github.com/MaastrichtU-IDS/biothingsprovenancemodel/blob/master/jsonldexample.json

cc @mbrush - how does this combine with SEPIO?

cc @micheldumontier @newgene @amalic

**Comment by amrapalijz** [comment]
please include me (amrapalijz) and Kody (kodymoodley) too as we have worked on developing the BioThings provenance model

**Comment by vemonet** [comment]
There have been some mention of the lack of provenance information in the Translator data providers
At the last Seattle hackathon there has been some discussions about improving the provenance/evidence definition in the BioLink model

We proposed a model mainly based on the [prov ontology](https://www.w3.org/TR/prov-o/) enabling to define multiple provenance/evidence for a same statement. You can find a human readable explanation of the model, as well as a snippet of RDF to showcase the definition of multiple evidence scores for an association in [this google docs](https://docs.google.com/document/d/1m7v46FdLmlzRT4YMyOuPyRBA6ObSfbFd5_yK6jUMTt0/edit?usp=sharing), feel free to add comments or suggestions


The [SEPIO ontology](https://github.com/monarch-initiative/SEPIO-ontology/), developed for the Monarch Initiative, has been mentioned as a good candidate for the Translator provenance. 

It would be interesting to have an example of using SEPIO with the BioLink model @mbrush @cmungall

**Comment by micheldumontier** [comment]
Here's the [RDF model](https://github.com/vemonet/translator-sparql-notebook/blob/master/resources/biolink-provenance-proposition.ttl) that uses biolink and PROV to model predicted protein-protein interactions.

**Comment by micheldumontier** [comment]
[Translator Relay Evidence and Provenance Discussion](https://docs.google.com/document/d/1BM0oSWHTqOnZebqZkchPPW6EjmSOCS333DaYWj1pdQg/edit#)

**Comment by deepakunni3** [comment]
Subsumed by existing work on Evidence and Provenance.

**Comment by sierra-moxon** [comment]
closing for now, please reopen as usual if I got it wrong :)
