### ISSUE TITLE
Visualize shex models

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#154]
Could we use this for visualizing our derived shex? h/t @balhoff cc @hsolbrig 

http://shaclex.validatingrdf.com/schemaInfo?schema=prefix%20%3A%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0Aprefix%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0Abase%20%3Chttp%3A%2F%2Fexample.org%2F%3E%0A%0A%3AUser%20CLOSED%20%7B%0A%20%20%20%20%3Aname%20xsd%3Astring%3B%0A%20%20%20%20%3Aage%20xsd%3Aint%3B%0A%20%20%20%20%3Aknows%20%40%3AUser%20%3B%0A%20%20%20%20%3AworksFor%20%40%3ACompany%20%3B%0A%20%20%20%20%3Abuys%20%40%3CProduct%3E%20%7B1%2C10%7D%0A%7D%0A%0A%3ACompany%20%7B%0A%20%20%20%20%3Aname%20xsd%3Astring%20%3B%0A%20%20%20%20%3AhasEmployee%20%40%3AUser%20*%0A%7D%0A%0A%3CProduct%3E%20%7B%0A%20%20%20%20%3Aname%20.%3B%0A%20%20%20%20%3Asku%20xsd%3Astring%20%3B%0A%20%20%20%20%3Amanufacturer%20%40%3COrganization%3E%0A%7D%0A%0A%3COrganization%3E%20%7B%0A%20%20%20%20%3Aname%20xsd%3Astring%20%3B%0A%20%20%20%20%3AisPartOf%20%40%3COrganization%3E%0A%7D&schemaFormat=ShExC&schemaEngine=ShEx

**Comment by hsolbrig** [comment]
Took a peek at it, unfortunately,
Wellformed: true
SVG conversion: Not implemented UML representation of ShapeOr. You can help us suggesting UML diagrams for OR
{
  "schemaName": "ShEx",
  "schemaEngine": "Iterative",
  "wellFormed": true,
  "errors": [],
  "parsed": "Parsed OK",
  "svg": "SVG conversion: Not implemented UML representation of ShapeOr. You can help us suggesting UML diagrams for OR"
}


I think I know the authors.  A UML “OR” is sometimes represented as a set of disjoint subtypes of an abstract base class.  I’ll pass it on…

**Comment by deepakunni3** [comment]
Is this something we want to support in biolinkml? @cmungall @hsolbrig
