### ISSUE TITLE
Three undefined properties in biolink-model.yaml

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolink-model#157]
* The `genotype to genotype part association` specializes `relation` as a subproperty of `has variant part`, which doesn't exist.
* `variant to disease association` specializes `relation` as a subproperty of `related condition`, which doesn't exist
* `anotomical entity to anatomical entity ontogenic association` specializes `relation` as a subproperty of `develops from`, which doesn't exist

**Comment by deepakunni3** [comment]
@cmungall Two questions:

1. Shouldn't we be defining `has variant part`,  `related condition`, `develops_from` as biolink relations?
2. Also, should we specialize on `relation` property or `edge_label` property?

Note: `relation` can be any CURIE whereas `predicate` is what specializes an association

**Comment by nlharris** [comment]
Are there still questions here that only @cmungall can answer?

**Comment by nlharris** [comment]
are there action items here? if not, perhaps this ticket can be closed?

**Comment by sierra-moxon** [comment]
closing - we are deprecating 'relation' and establishing a hierarchy of predicates.   And the suggestions by Deepak are already implemented :)
