### ISSUE TITLE
additional relations need to be declared multivalued

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#158]
E.g. expressed in

All object properties that are non-functional should have the multivalued qualifier

**Comment by deepakunni3** [comment]
@cmungall

**Comment by deepakunni3** [comment]
This can be handled by defining a default property `multivalued: true` for all slots

**Comment by nlharris** [comment]
has that been done?

**Comment by nlharris** [comment]
Maybe @sierra-moxon could take this on (assuming Deepak's suggestion on how to proceed is uncontroversial)?
