### ISSUE TITLE
Semantic Type for Reactome Complex

### ISSUE THREAD

**Issue by kevinxin90** [biolink/biolink-model#16]
Hi,

This question specifically regards the BioLink Semantic types. The example is a Reactome complex, e.g.R-HSA-5674003. A Reactome complex might be a combination of proteins, chemical compounds, etc. How would BioLink model assign semantic types for these biological entities, which could potentially be a mixture of multiple different biological entities?

Thanks!

**Comment by cmungall** [comment]
from https://github.com/NCATS-Tangerine/translator-knowledge-beacon/blob/develop/api/types.csv

```
macromolecular_complex	GO:0032991|SIO:010046
```

for the full model see: https://biolink.github.io/biolink-model/docs/MacromolecularComplex.html
