### ISSUE TITLE
Make URLs resolvable

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#165]
Easiest way would be to switch to w3ids, we already have an entry here:

https://github.com/perma-id/w3id.org/edit/master/biolink/.htaccess

**Comment by jmcmurry** [comment]
+1

**Comment by hsolbrig** [comment]
So: http://w3id.org/biolink/vocab/Gene redirects to https://biolink.github.io/vocab/Gene

I can change the URL's, but how do we populate the target?   I'm assuming start a vocab project under biolink, but what should we put there?

**Comment by hsolbrig** [comment]
What we've got at the moment is https://biolink.github.io/biolink-model/docs/Gene

**Comment by hsolbrig** [comment]
Does github.io support conneg?
