### ISSUE TITLE
Unrecognized prefixes

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolink-model#169]
The following prefixes do not have associated URI's:
```
Unrecognized prefix: UMLSSG
Unrecognized prefix: WD
Unrecognized prefix: Reactome
Unrecognized prefix: ECTO
Unrecognized prefix: VMC
Unrecognized prefix: IntAct
Unrecognized prefix: RNAcentral
Unrecognized prefix: ANCESTRO
Unrecognized prefix: GMODChado
Unrecognized prefix: CIViC
Unrecognized prefix: SEMMEDDB
Unrecognized prefix: oban
```

**Comment by cmungall** [comment]
ANCESTRO should be changed to HANCESTRO, standard OBO PURL http://obofoundry.org/ontology/hancestro.html

**Comment by hsolbrig** [comment]
ANCESTRO changed to HANCESTRO in commit https://github.com/biolink/biolink-model/commit/3d863790ce891fe3a5b00b31f5fbfefd32b41bcc
