### ISSUE TITLE
GraphViz dir only has bitmaps

### ISSUE THREAD

**Issue by TomConlin** [biolink/biolink-model#176]
GraphViz directory should contain `.gv` text files in the dot language
bitmaps could either stay or move to an image diretory

**Comment by hsolbrig** [comment]
Should we keep the bitmaps or just switch to ".gv"?  I favor the latter as it gives us a less bulky image...

**Comment by TomConlin** [comment]
I am not the audience the images are intended for so I'm reluctant to recommend ruining them for someone else.  I expect a significant number of people  have no idea what a .gv file was good for or how to view them  (or that they could have their browser map them to interactive graph renderer when clicked)  

On referring to '.gv's as  "less bulky" , you are far too kind.  
I have a 36k .gv file that bloats to a 25Meg bitmap, that is:
 700 times the space in exchange for eliminating usable information.

**Comment by jmcmurry** [comment]
is svg a non-starter?

**Comment by TomConlin** [comment]
```dot -Tsvg ```  certainly works   
on my example it yields a respectable intermediate size  362K  
the question of users being able to view them 
I must leave to folks more tuned into current front end browser abilities

**Comment by hsolbrig** [comment]
You can choose any dot output format:
```
gen-graphviz --help
Usage: gen-graphviz [OPTIONS] YAMLFILE

  Generate graphviz representations of the biolink model

Options:
  -d, --directory TEXT            Output directory - if supplied, a graph per
                                  class will be generated
  -o, --out TEXT                  Target file -- if supplied, one large graph
                                  will be generated
  -c, --classname TEXT            Class(es) to transform
  -f, --format [bmp|canon|cgimage|cmap|cmapx|cmapx_np|dot|dot_json|eps|exr|fig|gd|gd2|gif|gtk|gv|ico|imap|imap_np|ismap|jp2|jpe|jpeg|jpg|json|json0|pct|pdf|pic|pict|plain|plain-ext|png|pov|ps|ps2|psd|sgi|svg|svgz|tga|tif|tiff|tk|vml|vmlz|vrml|wbmp|webp|x11|xdot|xdot1.2|xdot1.4|xdot_json|xlib]
                                  Output format
  --help                          Show this message and exit.
```
The current make file uses the default (png):
```
gen-graphviz: dir-graphviz biolink-model.yaml
        gen-graphviz  -d graphviz biolink-model.yaml
```
