### ISSUE TITLE
What should be done with multiple mappings

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolink-model#185]
When there is more than one mapping for a biolink element:
```
  homologous to:
    is_a: related to
    ...
    mappings:
      - RO:HOM0000001
      - SIO:010302
```

Only the first mapping is used in the generated RDF output.  In particular, the context.jsonld contains:
```      "homologous_to": {
         "@type": "@id",
         "@id": "RO:HOM0000001"
      },
```

What should be done with the second and following mappings when it comes to emitting RDF and OWL?

**Comment by cmungall** [comment]
skos:exactMatch

(I thought we had a ticket with @mbrush talking about using more precise slots for mappings, but I can't see it...)

**Comment by mbrush** [comment]
@cmungall - the current thread for this issue is [here](https://github.com/biolink/biolink-model/pull/173) . . . the discussion somehow wandered into an already merged PR so this is likely why you couldn't find it.  Been waiting for final feedback from you and Harold on this before implementing - so take a look when you have a chance.

**Comment by cmungall** [comment]
It looks like @mbrush's changes here: https://github.com/biolink/biolink-model/pull/173/commits/11acddd979cb7434067cac177534428a49ba94a9

Never made it across to the new biolinkml repo?

**Comment by cmungall** [comment]
To answer the original Q, the metamodel now has `class_uri:` for indicating when to replace a biolink class IRI with another (and also slot_iri).

I redid Matt's changes in a new PR here https://github.com/biolink/biolinkml/pull/30

**Comment by nlharris** [comment]
So can this ticket be closed?

**Comment by hsolbrig** [comment]
Yes
