### ISSUE TITLE
inherited: true set in many cases where it should not be

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#193]
Following from #173

e.g. in meta.yaml, multivalued is set to true but in fact subproperties may restrict to single-valued

required should not be multivalued

**Comment by hsolbrig** [comment]
As best I can tell, it isn't.  Where are you getting this?

**Comment by mbrush** [comment]
#173 is about whether `inherited: true` is appropriate for the various 'mappings' slots now in biolink-model.yaml.  I propose it is not for most of these slots (see #173),

Your comments above seem to concern whether `multivalued` should be defined with 'inherited: true` in meta.yaml.    This is a separate but related issue, correct?

As for your comment on `required` - this is defined in meta.yaml as `inherited: true`, but there is nothing about whether it is multivalued.

**Comment by cmungall** [comment]
multivalued was just an example, there are others eg description

https://github.com/biolink/biolink-model/search?q=%22inherited%3A+true%22&unscoped_q=%22inherited%3A+true%22

**Comment by hsolbrig** [comment]
Skype

**Comment by cmungall** [comment]
oops mistyped
I meant to say "multivalued is not inherited"!

**Comment by hsolbrig** [comment]
I would think that it should be, since the default is false.

```
slots:
    parent:
        domain: human
        range: human
        multivalued: true

classes:
     human:

     large human:
           is_a: human
```

It would be very odd to find out that `large human` can only have one parent.

I need to test this, but I believe that you can say:

```
classes:
     orphan:
         slot_usage:
              parent:
                  multivalued: false
```

At the moment I don't believe there is any way to remove a slot (i.e. to declare that a slot cannot have any values).  Would be easily fixed if needed

**Comment by nlharris** [comment]
What's the status of this?

**Comment by hsolbrig** [comment]
While I don't know whether the issue has been completely resolved or not, I would propose that we close this issue and, if problems still exist, we start a new, more focused on in its stead

**Comment by nlharris** [comment]
sounds good to me!
