### ISSUE TITLE
Document differences with bioschemas

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#200]
We have a separate ticket for the basic mapping: #3 

However, the difference in overall modeling strategy should be documented. Briefly:

 * biolink is heavily "link" or *Association*-oriented. E.g bioschemas has a slot in [BioChemEntity](http://bio.sdo-bioschemas-227516.appspot.com/BioChemEntity) for [isInvolvedInBiologicalProcess](http://bio.sdo-bioschemas-227516.appspot.com/isInvolvedInBiologicalProcess). In BL, we would make an association object; this could be used to hang additional properties, provenance etc
 * Rather than specific properties like [hasECNumber](http://bio.sdo-bioschemas-227516.appspot.com/hasECNumber) we would have a generic mapping predicate
 * bs has a range for anatomicalLocation as DefinedTerm, whereas we follow OBO and make domain classes here
 * ...TODO...

**Comment by nlharris** [comment]
is this still needed? do you still want to be one of the assignees, @cmungall?

**Comment by sierra-moxon** [comment]
Closing for now; we have some mappings to bioschemas, we can open additional tickets as our collaboration with bioschemas grows?  We have not done the comprehensive alignment that is suggested in this ticket.
