### ISSUE TITLE
Association definition lacks edge label slot

### ISSUE THREAD

**Issue by lhannest** [biolink/biolink-model#205]
https://github.com/biolink/biolink-model/blob/52248983945ba786220c53a56e9655a99c418e6b/biolink-model.yaml#L2220-L2238

The slots array should contain `edge label`?

**Comment by nlharris** [comment]
Another possible one for @sierra-moxon to knock off?

**Comment by sierra-moxon** [comment]
I think edge label is no longer supported.   Now called 'predicate' also an association_slot. And predicate is listed in association object.
