### ISSUE TITLE
Add narrow ontology node property?

### ISSUE THREAD

**Issue by lhannest** [biolink/biolink-model#206]
Edges have both narrow (relation) and general (edge_label) ontological properties. But nodes only have a general (category) ontological property. Should nodes also have a narrow ontology property, maybe something that would be captured by rdf:type?

**Comment by cmungall** [comment]
This needs to be documented better, yes in Monarch we have a type edge to the ontology class

It's potentially confusing if the node is already an ontology class and we already have a subclass edge though, @hsolbrig @mbrush what do you think?
