### ISSUE TITLE
Adding seeAlso (x-ref) and alternative IDs

### ISSUE THREAD

**Issue by vemonet** [biolink/biolink-model#210]
Would it be interesting to include some of those common relations and properties to BioLink?
Especially to express alternative way to describe an entity (alternative URIs, IDs) or to express the fact that the entity is present in another resource (seeAlso)

Can [systematic_synonym](https://biolink.github.io/biolink-model/docs/systematic_synonym.html) be used as alternative IDs predicate?

**Comment by cmungall** [comment]
Systematic synonym is intended as a predicate that applies to genes. It should probably have a name that reflects the context.

**Comment by cmungall** [comment]
Agreed

**Comment by deepakunni3** [comment]
The recommendation is to use a combination of `xrefs` and `same_as`

**Comment by TomConlin** [comment]
`dbxref` please
