### ISSUE TITLE
Installing from pip fails due to hardcoded directory

### ISSUE THREAD

**Issue by kbruskiewicz** [biolink/biolink-model#214]
The exception:
`ValueError: path '/Users/solbrig/git/biolink-continuous/biolink-model/BiolinkMG.egg-info/PKG-INFO' cannot be absolute`

I got this after attempting to install Biolink-Toolkit with BiolinkMG as a requirement for pip. Looks like there's a hardcoded path.

I managed to install Biolink-Model from a local clone of the project, which suggests that PyPi needs to be updated?

Full error log:

> ERROR: Complete output from command 'c:\users\ken\venv\py37\scripts\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\Ken\\AppData\\Local\\Temp\\pip-install-l0_2kqvv\\BiolinkMG\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Ken\AppData\Local\Temp\pip-record-sgd5jwxs\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\ken\venv\py37\include\site\python3.7\BiolinkMG':
>     ERROR: running install
>     running build
>     running build_py
>     creating build
>     creating build\lib
>     creating build\lib\metamodel
>     copying metamodel\metamodel.py -> build\lib\metamodel
>     copying metamodel\__init__.py -> build\lib\metamodel
>     creating build\lib\metamodel\generators
>     copying metamodel\generators\contextgen.py -> build\lib\metamodel\generators
>     copying metamodel\generators\csvgen.py -> build\lib\metamodel\generators
>     copying metamodel\generators\dotgen.py -> build\lib\metamodel\generators
>     copying metamodel\generators\golrgen.py -> build\lib\metamodel\generators
>     copying metamodel\generators\graphqlgen.py -> build\lib\metamodel\generators
>     copying metamodel\generators\jsonldgen.py -> build\lib\metamodel\generators
>     copying metamodel\generators\jsonschemagen.py -> build\lib\metamodel\generators
>     copying metamodel\generators\markdowngen.py -> build\lib\metamodel\generators
>     copying metamodel\generators\owlgen.py -> build\lib\metamodel\generators
>     copying metamodel\generators\protogen.py -> build\lib\metamodel\generators
>     copying metamodel\generators\pythongen.py -> build\lib\metamodel\generators
>     copying metamodel\generators\rdfgen.py -> build\lib\metamodel\generators
>     copying metamodel\generators\shexgen.py -> build\lib\metamodel\generators
>     copying metamodel\generators\yumlgen.py -> build\lib\metamodel\generators
>     copying metamodel\generators\__init__.py -> build\lib\metamodel\generators
>     creating build\lib\metamodel\utils
>     copying metamodel\utils\builtins.py -> build\lib\metamodel\utils
>     copying metamodel\utils\comparefiles.py -> build\lib\metamodel\utils
>     copying metamodel\utils\formatutils.py -> build\lib\metamodel\utils
>     copying metamodel\utils\generator.py -> build\lib\metamodel\utils
>     copying metamodel\utils\loadschema.py -> build\lib\metamodel\utils
>     copying metamodel\utils\mergeutils.py -> build\lib\metamodel\utils
>     copying metamodel\utils\metamodelcore.py -> build\lib\metamodel\utils
>     copying metamodel\utils\namespaces.py -> build\lib\metamodel\utils
>     copying metamodel\utils\schemaloader.py -> build\lib\metamodel\utils
>     copying metamodel\utils\schemasynopsis.py -> build\lib\metamodel\utils
>     copying metamodel\utils\typereferences.py -> build\lib\metamodel\utils
>     copying metamodel\utils\yamlutils.py -> build\lib\metamodel\utils
>     copying metamodel\utils\__init__.py -> build\lib\metamodel\utils
>     running install_lib
>     running install_egg_info
>     running egg_info
>     writing BiolinkMG.egg-info\PKG-INFO
>     writing dependency_links to BiolinkMG.egg-info\dependency_links.txt
>     writing entry points to BiolinkMG.egg-info\entry_points.txt
>     writing requirements to BiolinkMG.egg-info\requires.txt
>     writing top-level names to BiolinkMG.egg-info\top_level.txt
>     reading manifest file 'BiolinkMG.egg-info\SOURCES.txt'
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\Ken\AppData\Local\Temp\pip-install-l0_2kqvv\BiolinkMG\setup.py", line 64, in <module>
>         "Programming Language :: Python :: 3.7",
>       File "c:\users\ken\venv\py37\lib\site-packages\setuptools\__init__.py", line 145, in setup
>         return distutils.core.setup(**attrs)
>       File "C:\Users\Ken\AppData\Local\Programs\Python\Python37\Lib\distutils\core.py", line 148, in setup
>         dist.run_commands()
>       File "C:\Users\Ken\AppData\Local\Programs\Python\Python37\Lib\distutils\dist.py", line 966, in run_commands
>         self.run_command(cmd)
>       File "C:\Users\Ken\AppData\Local\Programs\Python\Python37\Lib\distutils\dist.py", line 985, in run_command
>         cmd_obj.run()
>       File "c:\users\ken\venv\py37\lib\site-packages\setuptools\command\install.py", line 61, in run
>         return orig.install.run(self)
>       File "C:\Users\Ken\AppData\Local\Programs\Python\Python37\Lib\distutils\command\install.py", line 557, in run
>         self.run_command(cmd_name)
>       File "C:\Users\Ken\AppData\Local\Programs\Python\Python37\Lib\distutils\cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "C:\Users\Ken\AppData\Local\Programs\Python\Python37\Lib\distutils\dist.py", line 985, in run_command
>         cmd_obj.run()
>       File "c:\users\ken\venv\py37\lib\site-packages\setuptools\command\install_egg_info.py", line 34, in run
>         self.run_command('egg_info')
>       File "C:\Users\Ken\AppData\Local\Programs\Python\Python37\Lib\distutils\cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "C:\Users\Ken\AppData\Local\Programs\Python\Python37\Lib\distutils\dist.py", line 985, in run_command
>         cmd_obj.run()
>       File "c:\users\ken\venv\py37\lib\site-packages\setuptools\command\egg_info.py", line 296, in run
>         self.find_sources()
>       File "c:\users\ken\venv\py37\lib\site-packages\setuptools\command\egg_info.py", line 303, in find_sources
>         mm.run()
>       File "c:\users\ken\venv\py37\lib\site-packages\setuptools\command\egg_info.py", line 534, in run
>         self.add_defaults()
>       File "c:\users\ken\venv\py37\lib\site-packages\setuptools\command\egg_info.py", line 578, in add_defaults
>         self.read_manifest()
>       File "c:\users\ken\venv\py37\lib\site-packages\setuptools\command\sdist.py", line 199, in read_manifest
>         self.filelist.append(line)
>       File "c:\users\ken\venv\py37\lib\site-packages\setuptools\command\egg_info.py", line 476, in append
>         path = convert_path(item)
>       File "C:\Users\Ken\AppData\Local\Programs\Python\Python37\Lib\distutils\util.py", line 110, in convert_path
>         raise ValueError("path '%s' cannot be absolute" % pathname)
>     ValueError: path '/Users/solbrig/git/biolink-continuous/biolink-model/BiolinkMG.egg-info/PKG-INFO' cannot be absolute
>     ----------------------------------------
> ERROR: Command "'c:\users\ken\venv\py37\scripts\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\Ken\\AppData\\Local\\Temp\\pip-install-l0_2kqvv\\BiolinkMG\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Ken\AppData\Local\Temp\pip-record-sgd5jwxs\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\ken\venv\py37\include\site\python3.7\BiolinkMG'" failed with error code 1 in C:\Users\Ken\AppData\Local\Temp\pip-install-l0_2kqvv\BiolinkMG\

**Comment by hsolbrig** [comment]
Tried to reproduce via:
* `pip install BiolinkMG`  -- had an issue with `sparql_slurper`, which I'll take a look at, but installed fine.
* `pip install Biolink-Toolkit` -- not found
* ```
   git clone https://github.com/lhannest/biolink-model-toolkit.git
   cd biolink-model-toolkit
   pip install -e .``` 
worked with no issues.

The version that got installed was 0.3.0.  (It is a bit stale -- will submit a new one).  Can you try:
`pip install BiolinkMG --no-cache` ?

**Comment by bordercases** [comment]
I still get this error when applying `pip install BiolinkMG --no-cache` instead of installing from the local environment. (This is on Windows 10)

**Comment by PhillipsOwen** [comment]
I am encountering the same issue, also in a windows environment (within PyCharm). 

Seems to works ok in a linux environment.

**Comment by hsolbrig** [comment]
Is the reference to the solbrig directory still showing up???

**Comment by PhillipsOwen** [comment]
yes exactly:

ValueError: path '/Users/solbrig/git/biolink-continuous/biolink-model/BiolinkMG.egg-info/PKG-INFO' cannot be absolute

**Comment by hsolbrig** [comment]
Ah - BiolinkMG is not the current build.  You should be installing `biolink_model`

**Comment by PhillipsOwen** [comment]
thanks for the quick response BTW.

this is part of the install for KGX...

**Comment by hsolbrig** [comment]
I'll see whether I can deactivate BiolinkMG in pypi -- it is an artifact of the pre biolinkml/biolink-model split

**Comment by PhillipsOwen** [comment]
sounds good. BTW I am a RENCI guy.

**Comment by hsolbrig** [comment]
Slack?  (These messages get broadcast far and wide)
