### ISSUE TITLE
Add environments/exposures to BioLink model

### ISSUE THREAD

**Issue by diatomsRcool** [biolink/biolink-model#215]
to accommodate DataSTAGE work

related to #208 

and https://github.com/nhlbidatastage/helium-plus-milestones/issues/142

**Comment by cmungall** [comment]
Should we have both direct links, e.g. disease2chemical (which we have now) as well as disease2exposure2chemical?

**Comment by diatomsRcool** [comment]
I will make my notes here.

1. Can we change DrugExposure to ChemExposure? Not all chemicals will be drugs.
2. Is treatment meant to be a place for mixtures of exposures? Can we focus on the mixture and less on the treatment? We may need to link exposure to tropical climate and cigarette smoke and noise pollution. Maybe a co-occurrence association?
3. We need exposure to a behavior like smoking, exercising, stress, meditation or something of that nature. 
4. Exposure to a climactic regime. 
5. Let's have an association between an exposure and a phenotype, exposure and disease, and genotype+exposure as a unit is linked to a phenotype.
6. We need to think about exposure to a deficiency, like a vitamin deficiency.
7. We need exposure to environmental feature, like mountains or salt marsh.

**Comment by cmungall** [comment]
> Can we change DrugExposure to ChemExposure? Not all chemicals will be drugs.

Good point. I think this part could do with some work. Right now we have

 * environment
    * drug exposure
    * treatment

environment is a bit of a conflated concept here. I think we should deconflate. We need a good name for the general concept that encompasses any interaction between an organism and its environment, whether it is in the context of deliberate medical treatment, or through unintentional encounters to external environment. I might just go with "organism-environment interaction" but that sounds very ontological. "environmental encounter" sounds very FHIR-y. Maybe it's find to just go with "exposure" but it has connotations that exclude treatments?

But yes, the goal is to have a generic class that represents the root of ECTO

> Is treatment meant to be a place for mixtures of exposures? Can we focus on the mixture and less on the treatment? We may need to link exposure to tropical climate and cigarette smoke and noise pollution. Maybe a co-occurrence association?

The treatment class was meant to be expressive enough to capture drug regimens and the like. But we will likely want to represent sequences and mixture in non-drug contexts. E.g. exposure to intermittent or constant radiation, noise.

I think it's best to just have part-ofs and temporal between our exposure class and itself, to allow people to construct exposure sequence graphs

> We need exposure to a behavior like smoking, exercising, stress, meditation or something of that nature.

Yep, that's intended to be captured by what is currently called 'environment'

> Exposure to a climactic regime.

Ditto

> Let's have an association between an exposure and a phenotype, exposure and disease, and genotype+exposure as a unit is linked to a phenotype.

+1

> We need to think about exposure to a deficiency, like a vitamin deficiency.

Good point, currently we would precompose this in ECTO I think? 

> We need exposure to environmental feature, like mountains or salt marsh.

Yep, again should be covered by the general concept

**Comment by diatomsRcool** [comment]
> environment is a bit of a conflated concept here. I think we should deconflate
Agreed
OK, everything you said above makes sense to me. 
@deepakunni3 I think we talked about this earlier and this is something you can get started on?

**Comment by deepakunni3** [comment]
@diatomsRcool Yes, I can coordinate with Chris on this

**Comment by deepakunni3** [comment]
Action items from discussion with @cmungall ,
- Rename 'Environment' as 'Exposure' and have 'Environment' be an alias to 'Exposure'
- Do we call it 'Exposure' or 'Exposure Event'
- Add the following associations to the model, and enumerate where applicable:
    * DiseaseExposureAssociation
    * ExposureStressorAssociation
    * ExposureRouteAssociation
    * ExposureReceptorAssociation
    * ExposurePhenotypicFeatureAssociation

This requires more discussion and expertise from @diatomsRcool  @mbrush  @cmungall

**Comment by diatomsRcool** [comment]
> Rename 'Environment' as 'Exposure' and have 'Environment' be an alias to 'Exposure'

ok

> Do we call it 'Exposure' or 'Exposure Event'

I would call it Exposure Event, but I am ok with calling in Exposure and just thinking about it as an Exposure Event for my own mental processes.

> Add the following associations to the model, and enumerate where applicable:

I'm not sure about this, but maybe I'm thinking about BioLink wrong. Seems like an exposure event would have associations to outcomes (diseases and phenotypes) but wouldn't the stressor, route, and receptor be an attribute or a slit for the exposure event?

**Comment by diatomsRcool** [comment]
We need to finish this up within a month. Can everyone speak their mind?
