### ISSUE TITLE
can I load biolink model into ontobio?

### ISSUE THREAD

**Issue by saramsey** [biolink/biolink-model#216]
Hello Biolink Team,

Is there a version of the biolink model that I can directly load into ontobio?

Thanks,
Steve

**Comment by deepakunni3** [comment]
@saramsey We are in the process of having an OWL version of the model be autogenerated from the `biolink-model.yaml`

@hsolbrig is working actively on this.

**Comment by hsolbrig** [comment]
Correct.


Harold Solbrig

**Comment by cmungall** [comment]
Note that it should be possible to load https://github.com/biolink/biolink-model/blob/master/ontology/biolink.ttl into ontobio - but you said you tried that already @saramsey?

**Comment by saramsey** [comment]
Right, here is what happened. Maybe I need to upgrade `owltools` or `ontobio`?

<img width="656" alt="Screen Shot 2019-05-28 at 9 00 27 PM" src="https://user-images.githubusercontent.com/5562107/58528551-c6f6a180-818b-11e9-8766-64dc38b406fd.png">

**Comment by cmungall** [comment]
ah, in this case it's not using any external java library, it looks like it is trying to use it's built in rdf conversion which is incomplete, we should switch off that option.

As you already have robot I recommend doing this:

```
robot convert -i biolink-model.ttl -f json -o biolink-model.json
```

And then load the json file. obojson is the native representation for ontobio so it should have no issue with it (in theory)

(you can also convert with owltools but robot will give the same thing and is better supported)

We need to fix some of this magic ontology conversion in ontobio as it leads to unexpected behavior!

**Comment by saramsey** [comment]
It works!  Thank you, Chris and Team Orange!

**Comment by saramsey** [comment]
Thank you, we are using both `biolink-model.owl` and `context.jsonld` in our KG2 build process. Very helpful!
