### ISSUE TITLE
Fix inconsistent property names and values for "Publications/PMID" across NCATS knowledge graphs

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#218]
The various knowledge graphs using the Biolink Model do not have a consistent way of labeling citations in their edges.

Some graphs use the property 'pmid' (for Pub Med ID) while others use a propery "Publications" 

Aside from the naming of the attribute, the syntax - string list of PMID's versus a JSON-like encoding of the CURIES - diverges between knowledge graph implementations, hampering direct merger of graph data.

This issue documents the need to specify a unique property name and value syntax format and propagate the application of it to all Translator project graphs.

**Comment by RichardBruskiewich** [comment]
Some things to think about here: 

1. Are PubMed citations the only ones likely to be documented or is a more general range of CURIE targets likely?

2. If the above is assumed, should the values constrained to be CUIRIEs(?)

**Comment by TomConlin** [comment]
dipper provides monarch with a greater range of publications than PMID.
there are resources which are not publications provided as references.

**Comment by RichardBruskiewich** [comment]
Hi @TomConlin, yes.. exactly what I suspected to be the case. Therefore, we need to specify and enforce a more generic standard, supporting full CURIE but also URI's, for more _ad hoc_ web pages.

We can also have a fresh discussion about what the model field name ought to be called if not PMID or even "Publications".. that is, other candidate property names could be "References" or "Citations".

Then, we'd also need to agree on a common format for the value. One point mentioned in discussions is that the size of subgraphs (at least, in reasoner API outputs) may bloat to large multi-megabyte JSON. Keeping "syntactic sugar" down to a minimum in field values would help, e.g. use of brackets; single or double quotation marks; white space; use of URI encoding versus actual characters; enforcing CURIE versus URI usage (for many URIs in a subgraph using the same base URI's - i.e. use of local prefix namespaces?) and/or delimiters used.  

Since reference lists can potentially be long, this is a concern and also, an opportunity. If the reference value list is flat (one dimension) then JSON encoding of the list is not that necessary but a simpler specification provided.  We can outline the options and trade-offs then decide as a consortium what to specify and enforce, then apply those standards uniformly across all knowledge graphs published by anyone inside the consortium.

A similar perspective probably applies to issue 219 and issue 220 as well, plus any other additional standards issues that come up.

**Comment by RichardBruskiewich** [comment]
It is work mentioning here that the Biolink model itself associates a full *Publication* concept with a Biolink model entity: https://biolink.github.io/biolink-model/docs/Publication.html.

The *Association* model already has specified a slot name *Publication*.

Since such entities are expected to have a _mandatory_ (CURIE or URI) concept id: 

```id subsets: (translator_minimal)
Description: A unique identifier for a thing. Must be either a CURIE shorthand for a URI or a complete URI
range: IdentifierType
inherited from: NamedThing
```

which presumably globally identifies the supporting references, and we can probably assume that such CURIE's or URI's , if well formed, will not contain commas, then an absolute minimal standardised encoding of the supporting references to an edge for NCATS Translator could be a simple string which is a simple comma delimited list of said CURIES and URIs.

In such circumstances, URI's need not be URL encoded (thus meaning that the URI string length won't be bloated but rather minimal).

**Comment by RichardBruskiewich** [comment]
Hi @deepakunni3, even though this issue is closed, I merely point out the relationship of the issue with the [KGX issue #174](https://github.com/NCATS-Tangerine/kgx/issues/174).  Bill Baumgartner suggests that ```It seems to me that the provided_by and publications fields belong in the evidence node instead of the edge.``` in which case, we eliminate this node field (whatever its name) altogether?
