### ISSUE TITLE
Fix inconsistent concept node category value formats across NCATS knowledge graphs

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#219]
The various Translator knowledge graphs use the common property name *category* to semantically type concept nodes. That's good.

However,  the format and range of property value diverge significantly beyond (correctly) specified single *category* property values: 

1. some return all the parent concepts of a category; 
2. others, have mixed Boolean categories ("disease_or_gene") which are perhaps as fully Biolink compliant (or maybe they are valid Biolink Associations in some cases?).

This issue aims to specify and propagate the application of a consistent *category* property values across Translator knowledge graphs.

**Comment by TomConlin** [comment]
(* (^ 0 0) 1000000)

**Comment by RichardBruskiewich** [comment]
Some thoughts:

1. The *categories* field should generally only list the most specific category (or categories - see 2) ) applicable to a concept.   The (DAG) ancestral hierarchy of categories perhaps _does not need_ to be returned since perhaps it can be assumed that the client of the knowledge graph has access to a suitable index of the Biolink model at its disposal for (relatively) quickly retrieving all the ancestral categories of the most specific category given, for concept comparisons.

2) "categories' fields can have more than one category property in its list if such values are  recognized conjunction of semantic categories applicable to a specific concept.

**Comment by deepakunni3** [comment]
Just to highlight - the field is supposed to be 'category' and not 'categories'.
While the 'category' field itself can be multi-valued, the name of the field is singular: https://biolink.github.io/biolink-model/docs/category

**Comment by deepakunni3** [comment]
And this will be addressed as part of biolink validation suite and discussions currently underway in Translator Phase II
