### ISSUE TITLE
CURIE identifiers for biolink model entries

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#22]
Although the name: fields of the model are both unique and human friendly, there are still likely to be some programmatic instances in which a more concisely specified globally unique CURIE will be more convenient and efficient than multi-word, space delimited, variable length (and sometimes long) Biolink Model ontology term names.  For example, when encoding Biolink Model specific semantic data types and predicates as input parameters to API services or as the field values of JSON outputs, CURIEs are probably more concise but easily looked up by programs using an indexed Biolink model read into memory.

**Comment by cmungall** [comment]
Is this Q about entity categories, predicates, or both?

**Comment by RichardBruskiewich** [comment]
I'd have to say "both" since input parameters and output data for both concept types and predicates would benefit from concise CURIEs
