### ISSUE TITLE
Do we have a global metadata mechanism to document CURIE prefixes used in a given knowledge graph

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#221]
In whichever context that a given Biolink compliant knowledge subgraph is "published" and "shared" with other researchers, it may be very helpful to ensure accurate documentation and perhaps, local specification (for a given knowledge graph) of *xmlns* prefixes used in CURIES commonly used in the given graph.

This is analogous to "PREFIX" declarations in RDF documents or SPARQL queries.

Even if such prefixes are common to the global community (e.g. GO == Gene Ontology), it is likely very prudent to enforce the complete (100%) documentation of all prefixes used in a given knowledge graph.

Reasoner API calls can probably publish this *xmlns* list as an array of _prefix_ , _base uri_ mappings. The question is whether or not standalone knowledge graphs should also have them documented in an embedded manner somehow(?).

**Comment by deepakunni3** [comment]
Unclear how to implement something that would work for teams across translator.
One way to enable this is to have KGX do this. Unless I am misunderstanding the complexity of this request.

**Comment by RichardBruskiewich** [comment]
Alas, I don't recall what technical observation inspired this issue, but my rereading of it suggests that it is about having every (NCATS, Biolink-compliant) knowledge graph document the xmlns prefixes against their IRI's for all CURIES used in their graph(?). The proposal is analogous to SPARQL PREFIX declarations(?).

**Comment by sierra-moxon** [comment]
closing for now; please reopen if necessary
