### ISSUE TITLE
Clarify relationship with / map to DATS

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#23]
https://github.com/biocaddie/WG3-MetadataSpecifications

Broadly speaking, these two are orthogonal and complementary. There are some linkage points, e.g

 * https://github.com/biocaddie/WG3-MetadataSpecifications/blob/master/json-schemas/biological_entity_schema.json
 * https://github.com/biocaddie/WG3-MetadataSpecifications/blob/master/json-schemas/disease_schema.json

But the focus of DATS is on the intrinsic properties of the entities rather than linkages between the entities. We should write documentation that clarifies this, and map entity types where required.

Also: clarify relationship to bioschemas (#3)

**Comment by fractaler** [comment]
https://github.com/biocaddie/WG3-MetadataSpecifications/blob/master/json-schemas/biological_entity_schema.json: "A biological entity is a recognized entity covering biological process, molecular functions or cellular components". What about other biological components (cell, organism, population, etc.) besides the cellular component?

**Comment by proccaserra** [comment]
@cmungall agree on complementarity and meshing possibilities. the issue here is the clarify what you mean by 'linkage' between entities. We need to dig into this notion and review biolink. 

Also do you maintain a list of 'query cases /  use cases' ? that would focus the review process.

**Comment by cmungall** [comment]
hi @proccaserra 

I think this one is a good one to explore linkage:

https://github.com/biocaddie/WG3-MetadataSpecifications/blob/master/json-schemas/material_schema.json

Apologies, I wasn't aware that there were examples of these kinds of linkages in DATS. Others such as the [disease schema](https://github.com/biocaddie/WG3-MetadataSpecifications/blob/master/json-schemas/disease_schema.json) seem self-contained, and don't connect one biological entity to another.

Anyway, in the material schema schema, a material can be linked to another entity such as a disease:

https://github.com/biocaddie/WG3-MetadataSpecifications/blob/8246ab81116961746c3a1a385c7a6efc60fd09bc/json-schemas/material_schema.json#L57-L62

In the corresponding instance-level JSON or RDF, the disease would be nested/inlined directly under the material.

In the biolink model, associations are first-class entities, e.g. [sample to disease association](https://biolink.github.io/biolink-model/docs/BiosampleToDiseaseOrPhenotypicFeatureAssociation.html). This results in a much more verbose instance graph, but allows annotation of the association with provenance, additional qualifiers etc.

My rough first approximation characterization would be that the use case for DATS would be indexing and search, with the model optimized for questions like "find all materials of relevance to breast cancer (or datasets referencing such materials)". The use case for BioLink is reasoning over knowledge graphs.

It should in principle be possible to do a mapping, where a biolink X-to-Y association can be transformed to a DATS triple.

**Comment by proccaserra** [comment]
Hi @cmungall thx for this.

just to quote you "The blm is more association-centric, and is designed such that people can adorn associations with both biological metadata (what is the frequency of people with disease D that have symptom S? What is the severity? Who made the associations? What is the probability we associate with this?)"

The interesting bit is that we can certainly index a biolink dataset in datamed and , again, we need to have a better grasp of the use cases. 
Reasoning over findings in one thing , aggregating datasets for integration or reanalysis is another.
So we'll need to input of the group. 
On this issue of reasoning over knowledge graphs, if you have a specific example in mind, it would be great to document it in this thread.

But overall, I don't see any major roadblock in connecting both of our resources.

**Comment by fractaler** [comment]
" biolink X-to-Y association can be transformed to a DATS triple": seems X-to-Y = DATS triple = <a href=https://en.wikipedia.org/wiki/Talk:Semantic_triple>semantic triple</a>
