### ISSUE TITLE
No valid CURIE for related_to in context.jsonld

### ISSUE THREAD

**Issue by deepakunni3** [biolink/biolink-model#231]
```
      "related_to": {
         "@type": "@id",
         "@id": "owl:ObjectProperty"
      },
```

`owl:ObjectProperty` signifies the type of property that `related_to` is.
But looks like we do not have a CURIE mapping for this property? @cmungall

**Comment by deepakunni3** [comment]
Also, there is no `related_to` class in RO.

**Comment by hsolbrig** [comment]
how about skos:related?
