### ISSUE TITLE
Align with hetionet vocabulary

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#237]
See table 1 of
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5640425/

Metanode | Abbr | Nodes | Disconnected | Metaedges
-- | -- | -- | -- | --
Anatomy | A | 402 | 2 | 4
Biological process | BP | 11,381 | 0 | 1
Cellular component | CC | 1391 | 0 | 1
Compound | C | 1552 | 14 | 8
Disease | D | 137 | 1 | 8
Gene | G | 20,945 | 1800 | 16
Molecular function | MF | 2884 | 0 | 1
Pathway | PW | 1822 | 0 | 1
Pharmacologic class | PC | 345 | 0 | 1
Side effect | SE | 5734 | 33 | 1
Symptom | S | 438 | 23 | 1

Note: would also be useful to have an abbreviation field

**Comment by deepakunni3** [comment]
@cmungall Hetionet has been subsumed by many other projects. Is the target still Hetionet or something broader?

**Comment by deepakunni3** [comment]
Use `hetionet` as the prefix.

**Comment by sierra-moxon** [comment]
duplicate of #662
