### ISSUE TITLE
Document modeling pattern for relating drugs/chemicals to role descriptors

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#238]
See also https://github.com/obophenotype/chiro/issues/15

Current ncats-red is using blmod:category to link drugs to mesh IDs such as id:mesh/D000970 Antineoplastic Agents cc @vemonet 

The intent of blmod:category is to connect a node to a blmod class. @hsolbrig can we tighten the range from `iri type` to `class element`?

What relationship type should be used? We should add an association type.

Note in the ideal scenario we could link directly from the drug to another concept; e.g. `imatinib-[negatively regulates]->cancer`. (see chiro ticket for how we might expand this). However, in the absence of an expansion, we have to use a fairly generic 'descriptor' class as the mesh ID can come from different hierarchies, e.g.

![image](https://user-images.githubusercontent.com/50745/60407005-a5fbe480-9b6d-11e9-910e-d8cf5aca3de4.png)

**Comment by vemonet** [comment]
So the bl:category relation should be used only to link to the class of the instance? Same as rdf:type?

Should [ido:mesh/D000970](http://identifiers.org/mesh/D000970) be a [bl:OntologyClass](https://biolink.github.io/biolink-model/docs/OntologyClass.html) ? Like for GeneOntology with [bl:GeneOntologyClass](https://biolink.github.io/biolink-model/docs/GeneOntologyClass.html) ?

And have GeneOntology / MeSH associations to define entities features?

**Comment by vemonet** [comment]
I am meeting the same issue to categorize (PubMed) Publications using MeSH descriptors (provided by PubMed)

I am still using `bl:category` to do so, for a some reasons:

* I could not find any other way to express it using BioLink (we could have a way to define custom properties as I mentioned here: https://github.com/biolink/biolink-model/issues/239 )

* To define the BioLink class of an entity we already use `rdf:type`

* The semantic of category fits MeSH descriptors (as we use the MeSH ontology class to categorize the entity)

* The description is not clear about what `bl:category` should be:
> Name of the high level ontology class in which this entity is categorized. Corresponds to the label for the biolink entity type class. In a neo4j database this MAY correspond to the neo4j label tag

It says that it should be: "the label of the BioLink entity class" and "the name of the high level ontology class in which the entity is categorized". 

But the range require a `IriType` and [bl:OntologyClass](https://biolink.github.io/biolink-model/docs/OntologyClass.html) is  
> a concept or class in an ontology, vocabulary or thesaurus
> Children: GeneOntologyClass, OrganismTaxon, RelationshipType

However BioLink classes (Gene, ChemicalSubstance...) are not categorized as OntologyClass. Only `GeneOntologyClass`, `OrganismTaxon`, `RelationshipType` are defined as subClassOf OntologyClasses. 

So we should use only `GeneOntologyClass`, `OrganismTaxon`, `RelationshipType` to define biolink:category? Or can we use `ChemicalSubstance`, `Gene`, `Protein` ?

**Comment by vemonet** [comment]
Gene Family for Pfam: https://biolink.github.io/biolink-model/docs/GeneFamily.html

GO annotation?

Mesh descriptor

**Comment by deepakunni3** [comment]
@cmungall @vemonet Pinging on this thread to see if this still applies

**Comment by deepakunni3** [comment]
Its better go from the drug directly to the process and qualify the edge with roles. This avoids transient nodes.
