### ISSUE TITLE
drug approval status

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#239]
@vemonet currently models using 'filler'

```
id:drugbank:DB00619     blmod:filler    https://w3id.org/data2services/model/group/approved     https://w3id.org/data2services/graph/biolink/drugbank   Imatinib
```

we should have a better way of doing this

**Comment by vemonet** [comment]
Would it be possible to have a way to define a new property that is not in BioLink for an entity? 
For example:
```
?drug a bl:Drug ;
  bl:custom_property  [ 
    a bl:CustomProperty ; 
    bl:property d2svocab:drug_approval_status ; 
    bl:value  d2svocab:Approved 
  ] .
```

Or do we want every property used to be explicitly defined in BioLink? 
In this case we would need a property like `bl:approval_status` with a `bl:ApprovalStatus` class (e.g. `bl:Approved`, `bl:Pending`, `bl:Rejected`, `bl:Expired`)

Note that associations between `bl:Drug` and `bl:ApprovalStatus` could take extra properties like issued date, expire date, granted by organism, etc

**Comment by deepakunni3** [comment]
@cmungall We need to add properties that are pertinent to drugs in general.

**Comment by sierra-moxon** [comment]
@vemonet - the model now has several FDA approval status related attributes: https://github.com/biolink/biolink-model/pull/803

If these do not fulfill your use case, please do feel free to reopen :)
