### ISSUE TITLE
Make a biolink entity for chromosome

### ISSUE THREAD

**Issue by justaddcoffee** [biolink/biolink-model#244]
I could use an entity for chromosome. 

`molecular entity` seems close from the description
```
"A gene, gene product, small molecule or macromolecule (including protein complex)"), but possibly a bit too general for my purposes. 
```

Also `genomic entity` seems close:
```
"an entity that can either be directly located on a genome (gene, transcript, exon, regulatory region) or is encoded in a genome (protein)"
```
but again possibly too general for my purposes. 

The description for `genomic sequence localization` seems to imply that the chromosome entity exists 
```
("A relationship between a sequence feature and an entity it is localized to. The reference entity may be a chromosome, chromosome region or information entity such as a contig.")
```

**Comment by deepakunni3** [comment]
@justaddcoffee There is a discussion that needs to be had so as to how detailed should we be in the BioLink Model.

The model itself is supposed to be an upper level data model. 

For chromosome you could still tag it like so:
```
MONARCH:chr1 bl:category bl:GenomicSequenceLocalization
```
and still type the subject with another concept that is more detailed,
```
MONARCH:chr1 a SO:0000340
```

This allows you to freely type the subject to any concept of choice, in this case Sequence Ontology, while using `bl:category` to provide a high level overview on the nature of the subject.

Another recommendation is perhaps a term from [Monarch Chromosome Ontology] (https://github.com/monarch-initiative/monochrom).

**Disclaimer:** I did not know Monochrom existed until today. So it would be good to have @cmungall chime in on this issue

**Comment by cmungall** [comment]
I think it's fine to use GenomicEntity for now, but it would be good to introduce a subclass for the kinds of things that can serve as a reference

**Comment by justaddcoffee** [comment]
Okay, thanks, I'll just use GenomicEntity
