### ISSUE TITLE
need a standard way of encoding gaps in knowledge or questions

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#247]
For Sept hackathon as part of SME knowledge acquisition process we need to capture this

**Comment by RichardBruskiewich** [comment]
Just notice this issue assignment @cmungall ... I think  we may need to chat about this  early next week

**Comment by RichardBruskiewich** [comment]
Although I'm still not entirely wrapping my head around this, what comes to mind is to allow the SME knowledge capture process to simply insert some "blank" (_sensa_ RDF) nodes and edges into their knowledge graphs, preferably typed by Biolink categories, with relationship edges preferably  tagged by Biolink associations predicates, all that represent the unknowns.

If we are clever enough in the encoding, such "blank" nodes could be converted into queries on the NCATS knowledge system, to "fill in the blanks".
