### ISSUE TITLE
food type

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#248]
We're getting ready to integrate foodb.ca into robokop.    It would be nice to have a semantic type for "food".  It looks like in the current yaml, food is mapped directly to named_thing...

**Comment by deepakunni3** [comment]
This requires to make a `food` class and arrange it into the biolink model hierarchy, and map to FOODON.

**Comment by deepakunni3** [comment]
This also brings up the discussion on metabolites or drug which are roles of chemical substances.

**Comment by ehinderer** [comment]
Perhaps under PhysicalEntity? But the trick is that what we're really after (I think) is that the food is composed of ChemicalSubstances that may interact with other things. What are the predicates that would link between the two? has_part?

**Comment by sierra-moxon** [comment]
Food is in the model already, as are metabolites.  Closing for now, please reopen if necessary. :)
