### ISSUE TITLE
Slots list on website seems to be messed up

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#250]
https://biolink.github.io/biolink-model/docs/#slots

![image](https://user-images.githubusercontent.com/50745/62572779-6c438b00-b849-11e9-96a0-cbbd4e520c95.png)

object object object object....

**Comment by hsolbrig** [comment]
More cowbell!   (will see what has happened)

**Comment by nlharris** [comment]
Fixed?

**Comment by hsolbrig** [comment]
Yes
