### ISSUE TITLE
Chemical to chemical interactions

### ISSUE THREAD

**Issue by vemonet** [biolink/biolink-model#253]
A number of databases (DrugBank, STITCH) contain chemical to chemical interactions. How should we represent it with BioLink?

At the moment I am using a `bl:ChemicalToThingAssociation`:

```ttl
[] a bl:ChemicalToThingAssociation ;
  bl:relation bl:affects_activity_of ;
  bl:subject <http://identifiers.org/drugbank:DB00006> ;
  bl:object <http://identifiers.org/drugbank:DB11444> ;
  bl:description "Orgotein may increase the anticoagulant activities of Bivalirudin." .
```

Should we have a `bl:ChemicalToChemicalAssociation`?

**Comment by nlharris** [comment]
@vemonet can this be closed?

**Comment by deepakunni3** [comment]
@vemonet This has been addressed as part of another PR earlier in the year.

For more context, see: https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L4015
