### ISSUE TITLE
How to model "normal amount" and "crosses blood-brain barrier"?

### ISSUE THREAD

**Issue by webyrd** [biolink/biolink-model#254]
This issue came up at a recent PMI case review

We are trying to determine the normal amount of lipoic acid in a human.

Which BioLink predicates would be appropriate for that relationship?
Are there any examples of ‘baseline values’ of a substance in humans or animal models, for example?

Also, we want to find whether a substance crosses the blood-brain barrier.  How would this be modeled in Biolink?

Thanks!

--Will

**Comment by cmungall** [comment]
BBB crossing is an interesting one. Some things to be aware of:

 * the concept has to be species-specific. E.g. I believe some neonicotinoids cross the BBB in insects but not in humans
 * I believe the protonation state affects whether the structure crosses the BBB or not. This will get into interesting issues as to what the protonation state would be at normal physiological pH?

As to how to model this, I would define in terms of GO:0150104 _transport across blood-brain barrier_. Formally, there exists some GO:0150104 that occurs_in some taxon T that has_input some C.

This would be quite verbose, so I would just have a shortcut. We could simply have properties like 'crosses BBB in humans' and things could be tagged with this, analogous to what we do with CHEBI roles now.

But first you need to find a source of this data. I have no idea of the best source.

The bionumbers database (https://bionumbers.hms.harvard.edu) is a good source of normal quantitative information

It has some fun numbers that are unfortunately not so useful to you e.g. [Electrical resistance between tight junctions in the BBB (blood-brain barrier) endothelial cells and in other tissues](https://bionumbers.hms.harvard.edu/bionumber.aspx?id=117112&ver=4&trm=barrier&org=)
 
Nothing on lipoic acid

**Comment by cbizon** [comment]
Drugbank has BBB predictions based on admetSAR.  We have looked at admetSAR a little, but I don't think it has a service.

**Comment by cmungall** [comment]
From Tyler on slack:

HMDB has some numbers on this
http://www.hmdb.ca/metabolites/HMDB0000125

**Comment by sierra-moxon** [comment]
Adding this use case to our predicate/qualifier/modifier discussion.

**Comment by sierra-moxon** [comment]
closing for now; please reopen if this is still a concern.
