### ISSUE TITLE
GeneProduct is_a ChemicalSubstance?

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#258]
I think that every GeneProduct is also a chemical substance.  Is that correct?  Should it be inferable from the model?  Can/should it be an explicit is_a?

**Comment by cbizon** [comment]
This comes up specifically in how to handle things like peptides, which kind of get inbetween small molecules and proteins....

**Comment by cmungall** [comment]
It gets a bit tricky drawing the line here based on size, structural properties.

Either way, we should probably mostly use the parent `molecular entity` in domain/range constraints, and leave finer grained divisions to be more organizational

more later...

placeholder discussion on peptide in obo-core: https://github.com/OBOFoundry/Experimental-OBO-Core/issues/47

**Comment by lpalbou** [comment]
Anything is chemical but I think it's commonly accepted to distinguish the biological and chemical world and it makes sense to keep separated molecular entity (& gene products) from chemical substance.

In my former life, we used to distinguish [chemical space](https://en.wikipedia.org/wiki/Chemical_space) from [biological space](https://www.blopig.com/blog/2017/07/biological-space-a-starting-point-in-silico-drug-design-and-in-experimentally-exploring-biological-systems/).

Admittedly with both sRNA and small peptides being used as drugs too and having size / way to interact similar to small compounds, a clear definition is harder to establish.

**Comment by deepakunni3** [comment]
Closing since we have a plan of action:
> Either way, we should probably mostly use the parent molecular entity in domain/range constraints, and leave finer grained divisions to be more organizational
