### ISSUE TITLE
NCI Thesaurus Prefix

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolink-model#259]
The official prefix (per NCI) for the NCI Thesaurus is `http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#`.  Biolink-model currently uses `http://purl.obolibrary.org/obo/NCIT_`

**Comment by balhoff** [comment]
@hsolbrig `http://purl.obolibrary.org/obo/NCIT_` is correct for the NCIt OBO Edition: https://github.com/NCI-Thesaurus/thesaurus-obo-edition/wiki

**Comment by hsolbrig** [comment]
Thanks -- I did not know that.
