### ISSUE TITLE
Not all UMLS Semantic Groups are mapped

### ISSUE THREAD

**Issue by lhannest** [biolink/biolink-model#26]
DISO (Disorders), OCCU (Occupations), LIVB (Living Beings), and ORGA (Organizations)

Disorders is an especially common one, so it should be mapped.

**Comment by lhannest** [comment]
@RichardBruskiewich

**Comment by cmungall** [comment]
I took out occupations, it's not something we want to model here

**Comment by lhannest** [comment]
Okay, I'm putting in a pull request for DISO and ORGA now. I can't find where to put LIVB.
