### ISSUE TITLE
Add CONTRIBUTING or INSTALL file

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#267]
Add instructions for dummies like me on how to make changes to the yaml and compile everything

**Comment by nlharris** [comment]
@sierra-moxon maybe i could help with this

**Comment by nlharris** [comment]
seems like this is done -- can we close this ticket?

**Comment by sierra-moxon** [comment]
Documentation exists in the README for setting up developer environments, gh-actions take care of releases to pypi and running tests against the model.  closing as completed.
