### ISSUE TITLE
Wrong subject/object/relation property for some association (mixins)

### ISSUE THREAD

**Issue by vemonet** [biolink/biolink-model#273]
@deepakunni3 @cmungall 

It seems like some association or mixins are generating wrong subject properties. e.g.:

https://biolink.github.io/biolink-model/docs/cell_line_to_thing_association_subject.html 

When it should be simply `subject`

It also generates the following UI issues in the documentation:

![Screenshot from 2019-09-18 00-57-36](https://user-images.githubusercontent.com/3778439/65085725-78c21400-d9af-11e9-81fb-c9867a9e5e09.png)

**Comment by deepakunni3** [comment]
This can be fixed at the time of generating the markdown
