### ISSUE TITLE
Implement more advanced predicate mapping framework

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#285]
Currently our mappings are simple pairwise tuples.

We want to make this contextual. 

e.g. if the predicate is ‘increases’, and this connects a gene to a disease we would map to ‘increases risk of’)

We also want to be able to take account of inverse properties in mappings (we may not name all inverses)

We also want to be able to map to a tuple `(is_negated, target_relation)`, since we do not typically name complements

(note: complement is NOT an inverse)

We will use this to curate mappings for the 10,000+ source predicates gathered in the first phase of Translator

**Comment by sierra-moxon** [comment]
@mikebada proposed a hierarchy of predicates under "opposite of" to hand certain broad categories of oppositeness (including negation).
ie:
opposite of (possibly abstract):
  - positional/directional oppositeness (ie: start/end)
  - abstract directional oppositeness (ie: forward/backward)
  - negation (ie: related to, not related to - need a better example)
  
some opposites are in more than one higher level grouping.
- ie: cation is the opposite of anion, 'cation import' is the opposite directionally and charge wise of 'anion export'

"is opposite of" at a high level would/should contain “at least some degree of oppositeness”, but we'd be more specific in the subsequent child-predicates. 

We should also have some exploration of opposite classes as well as predicates, but that is explored in a different issue.  

Closing this issue as a grouping issue, and keeping remaining work in these granular issues:
#657 #664 #707
