### ISSUE TITLE
Complete mapping of all predicates

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#286]
As discussed on last KGS call

 * define spreadsheet structure/schema (see also #285)
 * aggregate all groups mappings into this
 * de-dupe and merge
 * curate and fix
 * migrate to maintaining this as yaml

**Comment by mbrush** [comment]
I set up a first pass at a [spreadsheets ](https://docs.google.com/spreadsheets/d/1n8EBWTbWIygoYSrUeI4hsJltoE5oL07HF7N4-Xp2OaU/edit#gid=1617925244) for collecting all KG predicates, and then curating them to harmonize mappings.  Comments welcome anytime, but we  can discuss as a group on the next call - to refine/finalize the templates, and define key participants and processes for doing this work.

**Comment by mbrush** [comment]
**Notes/Outcomes from the 11-19-19 KGS Call regarding the Predicate Harmonization Spreadsheets:**

-  Each KG team will populate the **"Sources"** sheet, using whatever name they want for their sources.  Include direct sources, and if possible upstream sources.  From here we will standardize how we refer to a given source.
-  Each KG team will add their predicate mappings to a separate **"All Preds"** sheet that includes their KG name (e.g. **"All Preds (RTX)"**).
- Regarding the use of the `Current Predicate Label` and `Current Predicate Identifer` columns:
     - **Scenario 1**: The KG uses a predicate that has not yet been mapped to Biolink. 
          - `Current Predicate Label` = the name of this predicate (e.g. _"is_substance_that_treats"_)
          - `Current Predicate Id` = an id for the predicate if one exists (e.g. _"RO:0002606"_)
     - **Scenario 2**:  The KG uses a proper Biolink predicate. 
          - `Current Predicate Label` = the name of this predicate, prefixed with "biolink") (e.g. _"biolink:physically interacts with"_)
          - `Current Predicate Id` = n/a (can leave blank)

- How to capture fact that a source relationship was inverted or transformed in some way in creating a KG edge (e.g. direction inverted from part_of to has_part).
     - The `Source Relationship` column should capture the relationship direction *as expressed in the source*. 
     - The `Current Predicate` and `Subject/Object Category` columns should reflect the relationship direction *as used in the KG*.  
     - Indicate in the comments column that the source predicate direction was inverted to create the KG edge (can simply write "inverted")
-  Rows 4 and 5 in the [**"All Preds (Examples)" sheet**](https://docs.google.com/spreadsheets/d/1n8EBWTbWIygoYSrUeI4hsJltoE5oL07HF7N4-Xp2OaU/edit#gid=83526723&range=4:4) show examples to try and follow.

------------------

Thanks all.  We will likely have to iterate a couple times to get things right over the next week. We appreciate your patience and feedback.  As questions or feedback arise, post them to the slack channel for discussion.

**Comment by saramsey** [comment]
OK Team RTX has added their predicate information to the Google Sheet. Please advise if anything looks amiss. Thanks.

**Comment by mbrush** [comment]
Summary of outcomes from the 12-16-19 call are in the minutes doc here: https://docs.google.com/document/d/1FeJRSUWSg5NzmBy4w3Fn8U7xaUwcqFtJSCEbdkG0hnY/edit#heading=h.b00qr612v9wu

**Comment by deepakunni3** [comment]
Needs further discussion as part of the Data Modeling calls

**Comment by sierra-moxon** [comment]
I think this is replaced by the project board for predicates working group. https://github.com/biolink/biolink-model/projects/3
