### ISSUE TITLE
causes / contributes to inverted?

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#294]
From the yaml:

```
contributes to:
    slot_uri: RO:0002326

causes:
    is_a: contributes to
    slot_uri: RO:0002410
```

But in RO, RO:0002410 (causally related to) is a superclass of RO:0002326.

Is this accidentally inverted in BL or is something else going on?

**Comment by deepakunni3** [comment]
Slot URI for `causes` is incorrect. Need to use proper slot URI from RO.

**Comment by sierra-moxon** [comment]
I believe these mappings have been fixed.
