### ISSUE TITLE
Incorrect URI prefix for biolink model classes in generated OWL

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#297]
Everything is prefixed with `https://w3id.org/biolink/biolinkml/meta/`

E.g. `https://w3id.org/biolink/biolinkml/meta/Gene`

Should be

https://w3id.org/biolink/vocab/Gene

**Comment by deepakunni3** [comment]
This is a bug in biolinkml OWL generator. Needs to be fixed upstream such that the proper prefix is used for biolink classes.

**Comment by nlharris** [comment]
@sierra-moxon this seems like something you could fix (if it still needs to be fixed)

**Comment by sierra-moxon** [comment]
Looks fixed to me, in the master branch (and latest release) of biolink-model.owl.ttl

<https://w3id.org/biolink/vocab/Gene> a owl:Class,
        linkml:ClassDefinition ;
    rdfs:label "gene" ;
