### ISSUE TITLE
annotate with bioschema URIs

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#3]

**Comment by stuppie** [comment]
I'll make a pull request. Just using this as scratch space

chemical substance
http://health-lifesci.schema.org/Substance

**Comment by fractaler** [comment]
IUPAC said "[chemical substance](https://goldbook.iupac.org/html/C/C01039.html): matter of constant composition best characterized by the entities (molecules, formula units, atoms) it is composed of. Physical properties such as density, refractive index, electric conductivity, melting point etc. characterize the chemical substance"

**Comment by proccaserra** [comment]
@cmungall @stuppie the health-lifesci extension of schema.org is not properly blessed by schema.org (AFAIU) and the coverage is heavily biased towards medical science rather than biology (.e.g there is now way to mark up taxonomic information with health-lifesci schema.org for anything other that pathogenic bacteria). and there is nothing about protein, genes, chemical entities and so on. hence bioschema.org.

**Comment by cmungall** [comment]
On 16 Mar 2018, at 3:24, Philippe Rocca-Serra wrote:

> [@cmungall](<https://github.com/cmungall>) [@stuppie](<https://github.com/stuppie>) the 
> health-lifesci extension of schema.org is not properly blessed by 
> schema.org (AFAIU) and the coverage is heavily biased towards medical 
> science rather than biology (.e.g there is now way to mark up 
> taxonomic information with health-lifesci schema.org for anything 
> other that pathogenic bacteria). and there is nothing about protein, 
> genes, chemical entities and so on. hence bioschema.org.

I also suspect that a lot of it is derived from dbpedia? The schema 
looks very similar.

**Comment by stuppie** [comment]
Also, there is http://bioschemas.org, which is trying to focus more on the research / non-clinical sciences ([specs](http://bioschemas.org/specifications/)). For example, [Protein](http://bioschemas.org/specifications/Protein/specification/). I do not know much about this project, and it seems very much a WIP.

**Comment by cmungall** [comment]
Assigned to you @stuppie as you'd made a start, but we can deprioritize this if current bioschema efforts are too preliminary

**Comment by cmungall** [comment]
Preview of new bioschemas here: bio.sdo-bioschemas-227516.appspot.com

**Comment by nlharris** [comment]
Is this done?

**Comment by nlharris** [comment]
can this issue be closed?
