### ISSUE TITLE
Derived file: matrix of entity types and how they connect

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#30]
From the subclasses of association, produce a matrix with cols/vals being subj/obj, and the values being predicates

**Comment by nlharris** [comment]
Still needed? (Also, I think this may overlap with at least one other issue.)

**Comment by nlharris** [comment]
@sierra-moxon does this relate at all to your work on predicates?

**Comment by sierra-moxon** [comment]
I think it could!  :) - I do have a reporting software that could report subject/object/predicate.  Is the matrix for documentation @cmungall?  Should we close this ticket in favor of incorporating a view like this into the dashboard?

**Comment by sierra-moxon** [comment]
I think this is done with the 'predicates' dashboard view here: https://translatorsri.github.io/translator-testing-dashboard-demo/. Please reopen if we need something further @cmungall ? :)
