### ISSUE TITLE
rebuild turtle file

### ISSUE THREAD

**Issue by balhoff** [biolink/biolink-model#302]
The  turtle output (biolink-model.ttl) seems to be lagging behind the yaml file. Could someone please rebuild? I am having trouble getting the python environment to work correctly. Also, there are some issues with incorrect namespaces in the existing ttl file (#301).

**Comment by deepakunni3** [comment]
@balhoff I have updated https://github.com/biolink/biolink-model/blob/master/biolink-model.ttl to the latest.

Let me know if you run into any issues with it.

**Comment by balhoff** [comment]
Thanks @deepakunni3!
