### ISSUE TITLE
json schema field is boolean instead of array

### ISSUE THREAD

**Issue by kshefchek** [biolink/biolink-model#308]
When using the json schema I get the following error:

Unexpected token encountered when reading value for 'required'. Expected StartArray, got Boolean. Path 'properties.AnatomicalEntityToAnatomicalEntityAssociation.properties.object.required', line 1107, position 31.

**Comment by deepakunni3** [comment]
Need to check this again with the latest biolinkml JSON Schema generator.

**Comment by kshefchek** [comment]
the latest json schema passes validation
