### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#313]
We use GH for both VCS and releases: https://github.com/biolink/biolink-model/releases

However, the release products don't self describe their version

 - include a specific version in the biolink-model yaml
 - have an SOP for GH releases such that the version and the GH tag match (just like a PyPi release)
 - consider sync release to PyPi
 - ensure the version number is included in products, e.g. versionIRI in OWL
 - ensure we keep ChangeLog up to date (changed to md file?)

**Comment by deepakunni3** [comment]
Related to #326

**Comment by RichardBruskiewich** [comment]
Related to https://github.com/biolink/biolink-model/pull/417

**Comment by sierra-moxon** [comment]
biolink-model version is stored at the top of the biolink-model.yaml and in github release.
