### ISSUE TITLE
Chemical Classes

### ISSUE THREAD

**Issue by mmayers12** [biolink/biolink-model#314]
I'm going through the process of converting some biomedical network data I have to the biolink model and I've run into a few mapping issues. 

As context, the network I'm working with is a compilation of a number of mechanisms of action that describe how a drug treats a disease. These MOAs are  expressed as a multi step path in a network. The results of this curation effort can be found at [DrugMechDB](https://github.com/SuLab/DrugMechDB). 

When converting these mechanistic paths to the biolink model, I've found that I have a node type and a few edge types that that don't appear to have direct mappings to Entity or relationship slots in the current biolink model. I'm hoping you can either help me find the most appropriate mappings, or potentially consider updates to the model to better capture these ideas.

The first concept is the node type Compound Class. I would consider this something similar to GeneFamily, a grouping of compounds that have some related feature.

Some examples in DrugMechDB include:

 - Prostaglandins (MESH:D011453)
 - hypophyseal hormones (MESH:D010907)
 - reative oxygen species (CHEBI:26523)

I will continue to create separate issues for each problem I encounter, refrencing this issue as context.

**Comment by vdancik** [comment]
Actually, this is a specific instance of a general notion of entity sets #385.

**Comment by cbizon** [comment]
FWIW, chemical classes are all lumped in with chemical_substance.  It's kind of wonky, and I think it makes theoretical sense to pull them into a separate biolink class.  

Practically, I'm worried about how to separate them out when as far as I know, many systems (CHEBI, MESH) don't differentiate between them.

**Comment by ehinderer** [comment]
Is this something we can handle with 'mixins'?

**Comment by nlharris** [comment]
Has this been addressed?

**Comment by vdancik** [comment]
> Has this been addressed?

no

**Comment by sierra-moxon** [comment]
We now have biolink:ChemicalRoles - we can use these here.  Closing as "done."
