### ISSUE TITLE
Inverse relationship slots

### ISSUE THREAD

**Issue by mmayers12** [biolink/biolink-model#315]
This issue is in reference to DrugMechDB conversion to biolink see issue #314   

I've found that some relationship slots have a semantic inverse while others do not. Are inverses planned to be added? 

For example `has biomarker` is complemented with `biomarker for`.  In DrugMechDB, some paths contain inverted relations like `regulated by` and `disrupted by` for which biolink only has the forward edge (`regulates` and `disrupts` respectively).

**Comment by nlharris** [comment]
related to #440?

**Comment by cmungall** [comment]
Yes, this is covered by #440
