### ISSUE TITLE
Genes of a gene family having specific effects on chemicals

### ISSUE THREAD

**Issue by mmayers12** [biolink/biolink-model#318]
This issue is in reference to DrugMechDB conversion to biolink, see issue #314

Most `affects` subtypes require a `MolecularEntity` for Subject and Object. The direct result of this is that a `GeneFamily` cannot `increase abundance of` a `ChemicalSubstance`. 

I only have one example in DrugMechDB but I am wondering how best to model it.

- glutimate-gated chloride channels 	INCREASES chloride ion

**Comment by vdancik** [comment]
Maybe we should just add relationships between the individual members of the protein family and the chemical.

**Comment by sierra-moxon** [comment]
Closing for now per Vlado's suggestion above.  Please feel free to reopen if that is unsatisfactory? :)
