### ISSUE TITLE
General assocaitons, non-gene to diseases

### ISSUE THREAD

**Issue by mmayers12** [biolink/biolink-model#319]
This issue is in reference to DrugMechDB conversion to biolink, see issue #314 

Is there some sort of general association edge? `Gene` `Disease` associations are present, but `Gene-Annotation` `Disease` associations are not:

`Cellular Component` (GO annotation) associated with `Disease` has no analog.

Some Examples:

- Luteinizing hormone secretion	ASSOCIATED_WITH Menorrhagia
- Histamine sections by Mast Cell	ASSOCIATED_WITH	Allergic conjuctivitis
- Clotting Factor Synthesis	ASSOCIATED_WITH	Pulmonary Embolism

**Comment by nlharris** [comment]
Can anyone answer this question? Maybe @mbrush?

**Comment by vdancik** [comment]
Is '_associated with_' different from '_related to_'?
