### ISSUE TITLE
Derived file: list of relations used in association hierarchy

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#32]
For alignment with https://docs.google.com/spreadsheets/d/1zXitcR1QjHyh6WocukgshSR7IoAVg7MJQG-HNh96Jec/edit#gid=3366698

**Comment by nlharris** [comment]
What's the request here? Is this still needed?

**Comment by nlharris** [comment]
is this obsolete?
@sierra-moxon

**Comment by sierra-moxon** [comment]
Yes, I think so - I am going to close for now in favor of the predicates WG task of getting all the missing predicates into the model. Please reopen if I got that wrong @cmungall!
