### ISSUE TITLE
Consider using owlstar to describe semantics of edges (logical, probabilistic, fuzzy)

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#320]
owlstar is a proposed vocabulary for standardizing semantics of ontological property graphs:

https://github.com/cmungall/owlstar

it allows

 - formal logical OWL semantics to be associated with ontological class-class links such as d2p links, or part-ofs in GO
 - probabilistic semantics associated with probable links (part of our NCE)

The proposal is to allow optional annotation of edges by including an equivalent property to `owlstar:interpretation` to blmod. This (edge) property could be filled with one of the types in owlstar (e.g. all-some). We would also include a `probability` (edge) property mapped to the owlstar property.

One objection to the general schema raised on a KG call was the need for clients to be defensive. Currently an edge is currently treated as 'more of less true'

But if we introduced an edge

```
<<<foo interacts-with bar>> os:probability 0.0
```

we are essentially negating it, a naive client that wants to say do a random walk over interactions may not know to check edge properties or may choose to ignore them getting wrong results.

I think the solution here is to simply make clients more defensive, but also provide ways in APIs to yield only 'known not-false/unlikely' edges, or ways to annotate graphs as to whether they are probabilistic or 'crisp'.

**Comment by graybeal** [comment]
I like the possibilities here.  Two quick questions/thoughts: 

(1) `os:probablility 0.0` could mean 'false', in which case 0.5='no information' or neutral; or 0.0 could mean 'no information' or 'neutral'. I think I prefer the latter, as presumably a negative relation expression can be used more appropriately (and with less reasoning confusion) to create negation. 

(2) Seems to me the critical application of edge probability is almost entirely in reasoners. The reasoner outcomes have to be capable of closing down an inferencing chain when it goes below a specified value; users who want highly speculative results could specify 0.0 (my scale) as the minimum, users who want old-school reasoning can specify 1.0.  Similarly, any API asking for existing non-inferred relations can just specify their minimum acceptable probability, 1.0 for old school and 0.0 for give me what you got. If no specification of minimum probably, a conservative/traditional server uses 1.0 by default, while a modern/radical/transparent server could pick some other minimum.

**Comment by cmungall** [comment]
On Tue, Mar 10, 2020 at 9:33 PM John Graybeal <notifications@github.com>
wrote:

> I like the possibilities here. Two quick questions/thoughts:
>
> (1) os:probablility 0.0 could mean 'false', in which case 0.5='no
> information' or neutral; or 0.0 could mean 'no information' or 'neutral'. I
> think I prefer the latter, as presumably a negative relation expression can
> be used more appropriately (and with less reasoning confusion) to create
> negation.
>

Pr=0 means false - there is no preference here.

I think if we want a different property to express fuzzier notions we can
have that, but we shouldn't use one that has a well defined meaning


> (2) Seems to me the critical application of edge probability is almost
> entirely in reasoners. The reasoner outcomes have to be capable of closing
> down an inferencing chain when it goes below a specified value; users who
> want highly speculative results could specify 0.0 (my scale) as the
> minimum, users who want old-school reasoning can specify 1.0. Similarly,
> any API asking for existing non-inferred relations can just specify their
> minimum acceptable probability, 1.0 for old school and 0.0 for give me what
> you got. If no specification of minimum probably, a
> conservative/traditional server uses 1.0 by default, while a
> modern/radical/transparent server could pick some other minimum.
>

I think this makes sense. We should also treat the default as being 'true'

**Comment by cmungall** [comment]
Another possibility: I think this was inspired by @cbizon and Patrick's comments on a KG call

We preserve the main relations R as being always true.

For each _r_ in R, We auto-project two relations

 * not _r_ : _r_ does **not** hold between subject and object
 * possible _r_ : there is a probability _p_ that _r_ holds between subject and object, where _p_ is specified by a probability edge property

Furthermore: it is invalid to use a probability edge property for any non `probable_r` relation

This is guaranteed safe for any subset of R specified in the query. Of course, clients could still write naive code where for example a random walk is made over a graph ignoring edge labels altogether. But such naive code is likely to be problematic anyway.

The details of the generation of derived properties could be worked out. This could be entirely implicit, but string/regex operations on labels is problematic. I think it's better to be completely explicit and have URIs for each derived property be made explicit, and have explicit linkages between properties. E.g.

 * not_foo is_negated_form_of foo

This could still be auto-generated from the yaml but to the consumer of the blmod products it would appear as if there were 3x as many relations

**Comment by sierra-moxon** [comment]
I'd like to close this ticket because we have representation in the model already for all:some, some:some via our `LogicalInterpretationEnum` - it may not be used in practice much yet?   In addition, we're just starting to talk about reasoning over Biolink instance data, it may be that we revisit this with more attention in 2023 (for Translator).  Please reopen if needed.  :)
