### ISSUE TITLE
MESH prefix expansion is incorrect

### ISSUE THREAD

**Issue by balhoff** [biolink/biolink-model#321]
Currently `MESH` points to an OBO PURL: https://github.com/biolink/biolink-model/blob/10ecb290d4932ab154b64573b9bbac4a61c445de/context.jsonld#L45

MESH is not registered with OBO. I've been using this expansion: `http://id.nlm.nih.gov/mesh/`

**Comment by nlharris** [comment]
this one seems like it should be straightforward to fix and doesn't require deepak's unique expertise?

**Comment by sierra-moxon** [comment]
@balhoff -- here is the current context for mesh:
      "MESH": "http://identifiers.org/mesh/"

**Comment by balhoff** [comment]
Is there a reason it should use identifiers.org? Since MeSH provides their own RDF rendering, it seems like that should be authoritative:

https://id.nlm.nih.gov/mesh/D000892.html (`http://id.nlm.nih.gov/mesh/D000892`)
