### ISSUE TITLE
Biolink Model version should be defined in the YAML

### ISSUE THREAD

**Issue by deepakunni3** [biolink/biolink-model#326]
Since Biolink Model is now being used extensively downstream by various projects, we need to define the version of the model in the YAML itself (and ensure that this version is included in all our autogenerated artifacts).

**Comment by RichardBruskiewich** [comment]
This issue relates to https://github.com/biolink/biolinkml/issues/217

**Comment by RichardBruskiewich** [comment]
Also related to https://github.com/biolink/biolink-model/issues/630

**Comment by sierra-moxon** [comment]
completed already. closing.
