### ISSUE TITLE
Incorrect and misleading URIs in generated JSON-LD context

### ISSUE THREAD

**Issue by deepakunni3** [biolink/biolink-model#328]
Currently there are a few URIs in the JSON-LD context that are either invalid or should be replaced for a better alternative.

**Comment by JervenBolleman** [comment]
A few examples are referring to example.org, which is probably the easiest to fix.
PubChem probably refers to compounds `http://rdf.ncbi.nlm.nih.gov/pubchem/compound/`

**Comment by sierra-moxon** [comment]
no more example.org examples exist and pubchem is replaced by correct identifiers.org for pubchem
