### ISSUE TITLE
improve docs on how variants and alleles are modeled

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#33]
will need help of @mbrush

we need to be capturing everything that is here https://github.com/monarch-initiative/ingest-artifacts/blob/master/sources/ClinVar/Update1-genomic_positions/ClinvarXML_20170308.cmap

**Comment by cmungall** [comment]
Some notes on possible illustrative examples. Would be good to see how to represent these in GENO

APOE haplotype (clinvar entry with 2 allele IDs):

 * https://www.ncbi.nlm.nih.gov/clinvar/variation/441269/

ClinVar entry for compound het, with multiple alleles: 

 * https://www.ncbi.nlm.nih.gov/clinvar/variation/424839/
 * https://www.ncbi.nlm.nih.gov/clinvar/variation/430723/

**Comment by nlharris** [comment]
is this still needed?

**Comment by sierra-moxon** [comment]
@mbrush @cmungall - I have some ideas here that I presented in the predicates working group this week (as it seems like some KPs are modeling variants in the predicate).

Ok if I assign myself?

**Comment by sierra-moxon** [comment]
@mbrush  - I believe the latest on this is that we might want to conflate sequence variant and gene (or said another way, sequence variant would be a qualifier of the gene subject).  Closing for now, but please reopen if you think we need to spend more time here.
