### ISSUE TITLE
Better document the role of mixins

### ISSUE THREAD

**Issue by andrewsu** [biolink/biolink-model#333]
I have a vague idea of what mixins are, but it's confusing.  I _think_ mixins are about defining groups of entities that share some common set of attributes.  For example, `frequency quantifier` has four slots for `has count`, `has total`, `has quotient`, and `has percentage`, so any entity that includes that mixin (like `variant to population association`) would automatically have those four slots.  Is this the basic use case?  And presumably this method is used instead of subclassing because BioLink Model only allows one subclass?

If yes, a few things that confuse me:

* `variant to population association` is the _only_ class that includes the `frequency quantifier` mixin. In this scenario, why abstract out those four slots?  Seems like it adds a level of complexity that isn't (currently) necessary?
* there are several mixins that only define one slot, e.g., `distribution level`, `data set summary`. If you're only including one slot, isn't that also another level of (currently) unnecessary abstraction? Is this planning for the future when more slots would be included? (If yes, consider the balance between that and the complexity it currently introduces.)
* there are also many mixins with _no_ slots, e.g., `positively regulates`, `relationship quantifier`.  What role do these play?
* there are things that are invoke as mixins that are not declared as mixins (e.g., `physical entity` on `anatomical entity`)  
* from the YAML I see that mixins can be defined for both slots (e.g., `regulates`) and classes (e.g., `relationship quantifier`), but on the ones on classes are listed at https://biolink.github.io/biolink-model/docs/Mixins.html

I hope me walking through my naive attempts at understanding mixins offers some ideas for additional documentation...

**Comment by deepakunni3** [comment]
CC'ing @cmungall  regarding `positively regulates` being a mixin and the design decisions for doing so

**Comment by RichardBruskiewich** [comment]
Our inconsistent use of the `mixin` and `mixins` tags in the model reflect a subtle bug in the Biolink Model, one which needs to be "fixed" by a combination of:

1. assessing Andrew's thoughtful comments, alongside other feedback we've received relating to the topic
2. discern and documenting "best practices" for `mixins ` in an appropriate location in the BiolinkML/Model  documentation stack
3. integrating code into the BiolinkML model parsing scripts to detect and warn about model violations in such "best practices"
4. repairing the Biolink Model to comply with the discerned "best practices"

**Comment by RichardBruskiewich** [comment]
Hi  @andrewsu, here's @cmungall's executive summary of mixins (also in the context of slots and classes):

-     **range:** range of the `mixins` property in a class SHOULD be a `mixin`
-     **homeomorphicity:** `is_a` SHOULD only connect either (1) two mixins (2) two classes (3) two slots
-     instances SHOULD NOT instantiate a  `mixin` directly: inject into a non-abstract class using the `mixins` property

More complete details may be  found in the BiolinkML [SPECIFICATION.md](https://github.com/biolink/biolinkml/blob/master/SPECIFICATION.md) document. This  document may be reviewed one more time soon for clarity.

We have also already noted that the  current Biolink Model likely does not yet fully comply with these `mixin` specifications. We will soon be  adding  some tests to the  BiolinkML to identify and log such design violations of the schema for remediation.

**Comment by andrewsu** [comment]
Thanks @RichardBruskiewich and @cmungall.  I think that executive summary is useful, but I admit it is still a bit abstract to me.  For me to really understand things, I think I would really find more description of the motivations behind mixins, and one or two examples worked out in some detail.  For example, I asked some specific questions about `frequency quantifier` in my initial issue description -- answers to those specific questions might help me generalize my understanding to mixins in general.  (On the other hand, if mixins are meant to be a behind-the-scenes thing that a typical user shouldn't need to care about, I'm happy for that to be the answer too...)

**Comment by RichardBruskiewich** [comment]
Good morning @andrewsu, 

@deepakunni3 ,  @cmungall and I are working  on the documentation  for mixins, both in [Biolink Model guidelines](https://github.com/biolink/biolink-model/blob/master/guidelines/using-the-modeling-language.md#mixin)  and in  BiolinkML (still a work-in-progress).   There is also now a [PR   #526 for  item 4 of the list I  gave above](https://github.com/biolink/biolink-model/pull/526)  I  gave above to repair the  Biolink Model, making it at least  _**apply**_ mixins with greater consistency. We  haven't yet  modified  BiolinkML to parse generate warnings about violations of mixin best practices.

All that said,  we've not yet considered your core concerns about undo complexity in the mixin models. I suppose we could consider such concerns on a case-by-case  basis as the model  evolves. Nobody would  insist that the  model doesn't  have room for improvement. We do need to continue thoughtful design iterations to ensure that it captures well the  core  needs of  the projects which use it.

**Comment by ramonawalls** [comment]
Maybe the developers are assuming that all biolink users are java or python developers, which we aren't. Reading up on abstract classes for coding did help me to understand mixins, I think, but maybe I am making invalid assumptions, because no where does it say explicitly mixins are supposed to be like coding abstract classes. The lack of solid documentation for mixins (what they are, why you chose them, when and how they should be used, with examples) is a major bottleneck right now.

**Comment by ramonawalls** [comment]
I want to say something positive too. [This page](https://biolink.github.io/biolink-model/guidelines/using-the-modeling-language.html) is really helpful. I now understand the different between `mixin` and `mixins`.

**Comment by sierra-moxon** [comment]
@ramonawalls - definitely I can see your point.  I think we use the term 'mixin' in a couple of ways.  First as a trait/interface (in support of polymorphism) mechanism, and second as a way to support multiple inheritance that doesn't interfere with the strict inheritance seen in the is_a path.  Your and Andrew's request for examples (with an emphasis on showing why we like/need/want mixins), is a good one.  I will try to assemble a list of examples with some good external links to documentation of mixins in a larger context.  Is there a particular example that is a bottleneck for you in the model w/re to how mixins are modeled?

**Comment by ramonawalls** [comment]
Thanks, @sierra-moxon. I only meant that it is a bottleneck to adoption, because I have shared  biolink with this some colleagues who were also confused by the mixins. We are just starting to build our data model, and I think I now understand well enough to use mixins appropriately.

**Comment by cmungall** [comment]
@sierra-moxon - thanks for the PR, looks great, this helps a lot!

Hi @ramonawalls!

I suspect your use case is more for the linkml framework itself rather than biolink model. Of course, we should document both, but I wonder if your use case is better handled over on the linkml repo. I'll also ping you separately about this as I have something to show you re: linkml MIxS encoding...
