### ISSUE TITLE
Represent clinical associations in terms of LOINC codes in Biolink Model

### ISSUE THREAD

**Issue by deepakunni3** [biolink/biolink-model#334]

**Comment by jh111** [comment]
LOINC Examples 

- Vital signs
- Lab results (need to address units, example HbA1C has % and absolute units, "reference range" which is sometimes lab calibrated and sometimes editorial)
- Observations from questions such as PHQ-9 for depression

Concepts of high, low, increasing, decreasing.

**Comment by jh111** [comment]
Ref from Larry Hunter: https://www.nature.com/articles/s41746-019-0110-4

**Comment by CaseyTa** [comment]
We are interested in using Loinc2Hpo to incorporate information derived from labs into COHD (thanks to Melissa Haendel for suggesting this to us)

**Comment by karafecho** [comment]
We also plan to incorporate LOINC2HPO into our FHIR PIT pipeline. See [Zhang et al. 2019 manuscript](https://www.nature.com/articles/s41746-019-0110-4) for additional information.

**Comment by sierra-moxon** [comment]
@jh111 - we have several LOINC narrow mappings on the 'has attribute' property.  Is this what you were looking for?  Could you help me understand the use case for these and what is needed?

**Comment by karafecho** [comment]
@sierra-moxon : The general use case is shared across clinical KPs. LOINCs are simply codes for laboratory measurements. They require a value and reference range or flag (e.g., high, normal, low) for interpretation. Translator speaks in ontologies. LOINC2HPO is a tool that Peter Robinson et al. developed to map LOINC codes+measurement results+reference ranges/flags to HPO terms. 

The clinical KPs would like to adopt a tool like LOINC2HPO as a standardized approach for leveraging clinical labs as part of Translator and more broadly.

**Comment by sierra-moxon** [comment]
@karafecho - I am tempted to close this Biolink issue.  Can you please advise?  Is there some sort of mapping or other work to do in Biolink to make the semantics here more attainable?  thanks! :)

**Comment by karafecho** [comment]
This issue was opened in the Biolink repo, but has been referenced several times, including within this open issue: https://github.com/NCATSTranslator/Clinical-Data-Committee-Tracking-Voting/issues/12. As such, we can probably close it.

**Comment by sierra-moxon** [comment]
Thank you @karafecho :)
