### ISSUE TITLE
Prediction and risk factors

### ISSUE THREAD

**Issue by jh111** [biolink/biolink-model#335]
We need  predicate to capture the idea of prediction. The edge normalizer suggests "causes" or "affects", but not all predictions are that strong.

We also need to allow users to ask about risk factors without specifying type. For example, what are a risk factor for myocardial infarction? Results could include genes, diseases, lab results, environmental exposures etc.

**Comment by nlharris** [comment]
Noting that Arpita joined the Biolink Help Desk call today to ask about this issue.

**Comment by deepakunni3** [comment]
@jh111 So there are two parts to this ticket:
- A need for a biolink predicate that is weaker than `affects` or `causes`
  - **Suggestion:** Would `contributes to` work?
- A need for a biolink predicate that enables representation of risk factors
  - **Suggestion:** A biolink predicate called `risk factor for` which can be used as `Entity A risk_factor_for Myocardial Infarction`

**Comment by deepakunni3** [comment]
Also, we have two predicates that deal with risk factors,
- related to
  - **affects risk for** 
  - **predisposes**

Would these be appropriate?

**Comment by jh111** [comment]
There's a subtle difference because we must explicitly avoid implying causality. Both _affects_ and _predisposes_ do.

Example: being male might be a risk factor (predictive) for femur fracture, but doesn't cause it.

Recommend: **potential risk factor for**

**Comment by jh111** [comment]
After considering many options, we recommend two directional predicates.

- factor potentially associated with increased risk for
- factor potentially associated with decrease risk for

**Comment by jh111** [comment]
The currently relevant points are being discussed well in #625, so I am closing this one.

**Comment by jh111** [comment]
The current Biolink hierarchy 

related_to
 - affects risk for
 
However, many real-world-evidence sources include risk that are not causal. 

We need an intermediate predicate to most accurately represent results to users and avoid being misleading.

Recommended predicate hierarchy: for risk:
       related_to
          - associated_with_risk_for  (could  be positive or negative)
               - affects

See related issue #625
