### ISSUE TITLE
provided_by as list

### ISSUE THREAD

**Issue by saramsey** [biolink/biolink-model#336]
This is Stephen Ramsey from NCATS Biomedical Data Translator Team "Expander Agent". 

I am writing to propose making the provided_by relationship a list. In many cases, there are multiple edges with identical subject, object, and predicate, differing only by source URI. It would greatly improve conciseness of the KG if we can represent this as a single edge with provided_by being a list. Is this something that has been discussed and/or considered?

**Comment by saramsey** [comment]
As an example
<img width="1037" alt="Screen Shot 2020-04-30 at 8 52 48 AM" src="https://user-images.githubusercontent.com/5562107/80731604-fd395100-8abf-11ea-91ec-ee1026bcba12.png">

**Comment by cmungall** [comment]
is the requirement explicitly for a list, or will a set suffice?

Specifically is there proposed semantics in the order? (i.e is this for supporting n-th order ingests, e.g. foo ingested from bar, did some magic, and we ingested from foo)?

For this kind of thing I would prefer an explicit prov-like graph of the form Michelle/Vincent are doing (can't seem to tag them...?)

**Comment by deepakunni3** [comment]
Yes, long term, a graph that preserves the order would be ideal. But in the absence of that, a list (set) should handle the immediate use-case.

CC'ing @vemonet and @micheldumontier

**Comment by cbizon** [comment]
The problem that we've run into in the past is that the edges don't differ only by edge source.  So for instance, there's whatever provenance, evidence, or scoring information is coming back from each source.  There's also whatever we generate on provenance like how we generated the call, when we acquired the info etc.

I think at the biolink level it might be possible to structure this set of stuff pretty rationally as a set of dictionaries (each element in the set is all the data from a source), but when it gets serialized (in our case to neo4j), the best you can do is a set of parallel lists (ugh).   I don't know if that impacts whether we need ordered lists in biolink, but under the covers at least some groups will implement it that way.

**Comment by saramsey** [comment]
Hi @cmungall for my purposes, the order of the items in the `provided_by` property is not important, so I guess a set would work fine (though of course, some serializations, like JSON and Cypher, don't have a notion of a set).
