### ISSUE TITLE
extend BioLink Model to handle COHD associations endpoints

### ISSUE THREAD

**Issue by andrewsu** [biolink/biolink-model#338]
At the Translator Relay meeting, we had a discussion about how to model the COHD ["Concept Associations" endpoints](https://smart-api.info/ui/8f2da4bf3a00d3ca317f6a5764022bf6#/Concept%20Associations) using BioLink Model.  For example, [this API call](http://tr-kp-clinical.ncats.io/api/association/chiSquare?dataset_id=1&concept_id_1=192855&domain=Drug
) returns drug-drug correlations in the COHD data set in a structure like this:

```
{
  "results": [
    {
      "chi_square": 370026.1780081638,
      "concept_2_domain": "Procedure",
      "concept_2_name": "Instillation of therapeutic substance into bladder",
      "concept_id_1": 192855,
      "concept_id_2": 4021588,
      "dataset_id": 3,
      "p-value": 0
    }
  ]
}
```

In the [discussion notes](https://docs.google.com/document/d/1ylE0nclJl7F8GtG9njFsELJObV2GPnVi7rA6ZfhKOIU/edit), we described two tangible changes to BioLink Model that needed to happen:

- [x] we need to expand the definition of the [existing](https://biolink.github.io/biolink-model/docs/correlated_with.html) `correlated_with` slot to include correlations between any two entity types
- [x] we need to create edge properties `pvalue` and `chisq_statistic`

cc @deepakunni3 @cmungall @kevinxin90 @newgene @CaseyTa

**Comment by andrewsu** [comment]
Also cc @dkoslicki

**Comment by karafecho** [comment]
ICEES+ provides [similar endpoints](https://icees.renci.org/apidocs/).

**Comment by deepakunni3** [comment]
We can rely on STATO and OBI for representing statistical test and their values, respectively.

**Comment by deepakunni3** [comment]
@andrewsu @dkoslicki @cmungall - I have translated what was discussed so far to the `biolink-model.yaml` (see #344).

We can iterate, refine, and merge in the coming days.

**Comment by nlharris** [comment]
Is there more to be done here? If so, can the todos be enumerated here?

**Comment by karafecho** [comment]
We are currently gathering requirements as a next step. Please see [this doc](https://docs.google.com/spreadsheets/d/1Asasex2ypEVZItDB9c1PlKmUtEbKeGtRG3QDfLLr1As/edit?usp=sharing).

**Comment by sierra-moxon** [comment]
per clinical WG meeting: closing for now.
