### ISSUE TITLE
Wikidata predicate relations

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#34]
The Semantic Medline Database and Wikidata use a set of predicates which should perhaps be added to the Biolink Model (perhaps, via the Translator predicate harmonization effort?). Here is the list of interest (Wikidata wd: curies given):

nse Body
[
  {
    "id": "wd:P3356",
    "name": "positive diagnostic predictor",
    "definition": ""
  },
  {
    "id": "wd:P129",
    "name": "physically interacts with (in molecular biology)",
    "definition": ""
  },
  {
    "id": "wd:P279",
    "name": "subclass of",
    "definition": ""
  },
  {
    "id": "wd:P276",
    "name": "location",
    "definition": ""
  },
  {
    "id": "wd:P1557",
    "name": "manifestation of",
    "definition": ""
  },
  {
    "id": "wd:P361",
    "name": "part of",
    "definition": ""
  },
  {
    "id": "wd:P156",
    "name": "followed by",
    "definition": ""
  },
  {
    "id": "wd:P1056",
    "name": "product",
    "definition": ""
  },
  {
    "id": "wd:P2888",
    "name": "exact match",
    "definition": ""
  },
  {
    "id": "wd:P2175",
    "name": "medical condition treated",
    "definition": ""
  },
  {
    "id": "wd:P2283",
    "name": "uses",
    "definition": ""
  },
  {
    "id": "wd:P1542",
    "name": "cause of",
    "definition": ""
  },
  {
    "id": "wd:property_id",
    "name": "",
    "definition": ""
  },
  {
    "id": "kb:P2176",
    "name": "drug used for treatment",
    "definition": ""
  },
  {
    "id": "wd:P703",
    "name": "found in taxon",
    "definition": ""
  },
  {
    "id": "wd:P688",
    "name": "encodes",
    "definition": ""
  },
  {
    "id": "wd:P684",
    "name": "ortholog",
    "definition": ""
  },
  {
    "id": "wd:P682",
    "name": "biological process",
    "definition": ""
  },
  {
    "id": "wd:P681",
    "name": "cell component",
    "definition": ""
  },
  {
    "id": "wd:P680",
    "name": "molecular function",
    "definition": ""
  },
  {
    "id": "wd:P3433",
    "name": "biological variant of",
    "definition": ""
  },
  {
    "id": "wd:P31",
    "name": "",
    "definition": ""
  },
  {
    "id": "wd:P2293",
    "name": "genetic association",
    "definition": ""
  },
  {
    "id": "wd:P1552",
    "name": "has quality",
    "definition": ""
  },
  {
    "id": "wd:P128",
    "name": "regulates (molecular biology)",
    "definition": ""
  }
]

**Comment by nlharris** [comment]
is this still desired?

**Comment by deepakunni3** [comment]
I think some of these are already in the model. @RichardBruskiewich Do you want to add the remaining relevant mappings?

**Comment by nlharris** [comment]
@RichardBruskiewich do you want to make this more specifically actionable?
