### ISSUE TITLE
Allow predicates from specific vocabularies

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#342]
This issue is sparked by this discussion from TranslatorArchitecture: https://github.com/NCATSTranslator/TranslatorArchitecture/pull/2

(especially @andrewsu's final comment)

Currently, I think there is a mismatch in how we handle nodes and edges in biolink-model.

When making a node conform to the biolink model, I have to choose a biolink semantic type and a biolink compliant identifier.  Because the choice of identifier is at the system level (I can pick e.g. any MONDO), it's not very hard to express in biolink almost exactly whatever entities I find in a database without changing the meaning of that node.

When I make an edge, I only have to make the predicate compliant.  But if I have to pick a predicate from the biolink model only, then there is usually a quite large transformation that I have to apply to roll that edge up into a pretty chunky level of granularity.  I am allowed to carry along the original predicate as a property, but it's the biolink predicate that is "the" predicate.  For instance, it's the one that gets serialized as the edge type in neo4j, and it's the most likely value to be used in graph integration.

(I suspect that the biolink-modelers think of the predicate as a closer analog to the semantic type of a node, but I think of it as more like the node identifier.)

I think we would be better off if biolink said that you can use predicates from any of the following vocabularies: (RO, SIO, ....). We can have an ordering of these like we do for other semantic types (prefer ontology X over Y) and handle equivalences.  If we want a chunkier value, we can add that one as an extra property, or we can have multiple chunk levels/algorithms as properties on the edge.

**Comment by sierra-moxon** [comment]
@cbizon - from the predicates WG - we decided to add any number of predicates (RO or SIO) needed to the model as per your suggestion here.  In particular, we're starting with the 'missing predicates' we've identified in the testing repo, and working from that list to add.  Alternatively, there are other cases to add specific predicates.  I think I might close this issue in favor of the specific requests for predicates?  Please reopen if I got this strategy wrong. :)
