### ISSUE TITLE
Test suite should check conversion to downstream formats

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#351]
This shouldn't have happened a6891b059fb6d767ba607294c3cdaf7170a3289e

travis should have flagged as an error

**Comment by nlharris** [comment]
just a note that we are probably switching from travis to github actions

**Comment by sierra-moxon** [comment]
I believe all downstream artifacts are now generated by actions.  Closing this case.  Please reopen as necessary? :)
