### ISSUE TITLE
General clinical, contextual, and spatiotemporal considerations

### ISSUE THREAD

**Issue by karafecho** [biolink/biolink-model#354]
How do we best adapt Biolink model and the Reasoner Std API to support contextual, and spatiotemporal considerations and reasoning across knowledge sources? Please see this [doc](https://docs.google.com/document/d/1VWIMmaLfw3YJeJDMElkUyh8095rYwDa7rb4nwwCbuPo/edit?usp=sharing). 

Related biolink-model issues #333, #334, #338, #341.
Related NCATS-ReasonerStdAPI issues [# 104](https://github.com/NCATS-Tangerine/NCATS-ReasonerStdAPI/issues).

**Comment by karafecho** [comment]
Also see #344

**Comment by karafecho** [comment]
Related to #461, #462

**Comment by mbrush** [comment]
@karafecho The link to the google doc in the initial ticket above is broken.  Can you provide a working one, if this document is still relevant?

**Comment by karafecho** [comment]
@mbrush : Sorry about that. Try [this link](https://docs.google.com/document/d/1ErXbtDvzc2I8XzyeCk5hZzq0EePPF8AsJRdfUBp098E/edit?usp=sharing).

**Comment by nlharris** [comment]
@karafecho is this still in progress or can it be closed?

**Comment by karafecho** [comment]
This is too general to be useful. I think we have more specific, actionable tickets. Closing this one.
