### ISSUE TITLE
biolink model YAML is inconsistent on the UniProtKB CURIE prefix

### ISSUE THREAD

**Issue by saramsey** [biolink/biolink-model#358]
Hello biolink friends, the biolink model YAML file seems to be inconsistent on which CURIE prefix should be used for UniProt accession numbers. See attached

<img width="1059" alt="Screen Shot 2020-06-18 at 4 56 50 PM" src="https://user-images.githubusercontent.com/5562107/85082808-db398200-b184-11ea-80b5-2ec7ed0810c3.png">

**Comment by saramsey** [comment]
Well, hmm, maybe in light of #327 it was *intended* to have two different CURIE prefixes for UniProt accession numbers?  But I confess I can't imagine why that would be desirable. Anyhow, I just want to know which we should use in RTX KG2, in order to comply with the Biolink model.

**Comment by deepakunni3** [comment]
@saramsey I am so sorry about this confusion. This was supposed to be fixed last week.
The prefix should always be `UniProtKB` and not `UNIPROT` or `UNIPROTKB`.

I'll make a PR removing the errant prefix definition.

**Comment by kshefchek** [comment]
I've addressed this in https://github.com/biolink/biolink-model/pull/353

**Comment by saramsey** [comment]
thanks, @deepakunni3 . I have updated RTX KG2 to use UniProtKB per your guidance above.
