### ISSUE TITLE
clarify difference between `association type` and `relation`

### ISSUE THREAD

**Issue by VladimirAlexiev** [biolink/biolink-model#362]
https://biolink.github.io/biolink-model/docs/Association#attributes:
`association type` (OntologyClass OPT) vs `relation` (Uriorcurie REQ).
- clarify the difference between these fields
- why are both needed (is it just a technical reason?)
- the difference in mandatoriness
- Is there 1-1 correspondence between them, i.e. do they break up into stable pairs and don't "mate" with other association types or relations?
  If not, what are the constraints? Eg can one `relation` relate to several `association type` but not vice versa?

These are one of the keys to the model, so a comprehensive explanation will be appreciated, maybe in https://github.com/biolink/biolink-model

**Comment by VladimirAlexiev** [comment]
From https://github.com/NCATS-Tangerine/kgx/blob/master/data-preparation.md#tsvcsv-format says that:
- `association type (edge_label)` is a Biolink Model type 
- `relation` is a more specific ontology term that well characterizes this relationship

It follows that each `association type` corresponds to several `relation`,
while each `relation` corresponds to one `association type` (if it's mapped to biolink) or to zero (if it's not yet mapped).

Is that true?

**Comment by nlharris** [comment]
Is Chris the only person who can answer this?

**Comment by sierra-moxon** [comment]
association type is deprecated in favor of category.  
category is defined as follows:
      Name of the high level ontology class in which this entity is categorized. Corresponds to the label for the
      biolink entity type class.
       * In a neo4j database this MAY correspond to the neo4j label tag.
       * In an RDF database it should be a biolink model class URI.
      This field is multi-valued. It should include values for ancestors of the biolink class; for example,
      a protein such as Shh would have category values `biolink:Protein`, `biolink:GeneProduct`, `biolink:MolecularEntity`, ...

      In an RDF database, nodes will typically have an rdf:type triples. This can be to the most specific biolink
      class, or potentially to a class more specific than something in biolink. For example, a sequence feature `f`
      may have a rdf:type assertion to a SO class such as TF_binding_site,
      which is more specific than anything in biolink. Here we would have categories {biolink:GenomicEntity,
      biolink:MolecularEntity, biolink:NamedThing}

relation is being deprecated.  'predicate' (any is_a child of 'related to' in biolink-model) should be as specific as necessary to describe the relationship between subject and object.   Further qualification of this relationship can be done via the 'qualifiers' collection on an association object, or via a new property 'predicate qualifier' that is coming soon.  

closing for now, please feel free to reopen if there needs to be more disambiguation here. :)
