### ISSUE TITLE
Types capitalization

### ISSUE THREAD

**Issue by VladimirAlexiev** [biolink/biolink-model#363]
https://biolink.github.io/biolink-model/docs/Types.html: Not all types use the UpperCamelCase convention.
- Datetime, Nodeidentifier and Objectidentifier are a little annoying
- Ncname and Uriorcurie are just atrocious

**Comment by sierra-moxon** [comment]
I am going to move this to LinkML as Biolink Model inherits types from there.

**Comment by sierra-moxon** [comment]
https://github.com/linkml/linkml/issues/798
