### ISSUE TITLE
use dct: instead of dcterms:

### ISSUE THREAD

**Issue by VladimirAlexiev** [biolink/biolink-model#365]
A minor nitpicking: use `dct:` instead of `dcterms:` for consistency's sake. Eg here:
```
  title:
    is_a: node property
    domain: data set version
    slot_uri: dct:title

  source data file:
    is_a: node property
    domain: data set version
    range: data file
    slot_uri: dcterms:source

  source web page:
    is_a: node property
    domain: data set summary
    slot_uri: dcterms:source
```

**Comment by TomConlin** [comment]
however please converge to `dcterms' not dct.

see: https://www.dublincore.org/specifications/dublin-core/dcmi-terms/

**Comment by kshefchek** [comment]
In https://github.com/biolink/biolink-model/pull/353 I all dct prefixes to dcterms
