### ISSUE TITLE
RDF* example is wrong

### ISSUE THREAD

**Issue by VladimirAlexiev** [biolink/biolink-model#367]
https://biolink.github.io/biolink-model/about/mapping-rdf.html#edge-and-edge-properties shows:
```
:x :p :y <<bl:publication http://identifiers.org/pmid/123>>
```

This should be
```
<<:x :p :y>> bl:publication <http://identifiers.org/pmid/123>.
```

Furthermore, it should mention 

"The jury is still out on the question whether referring to an RDF* triple also asserts the triple. Therefore in some RDF* implementations you need to assert it explicitly if you need to have it as a direct triple, similar to the RDF Reification example below:
```
:x :p :y.
<<:x :p :y>> bl:publication <http://identifiers.org/pmid/123>.
```

(For example, GraphDB's RDF* does not assert automatically.)

It is questionable whether such assertion that has association slot `negative=true` is meaningful.

**Comment by nlharris** [comment]
should Vladimir make a PR with this requested change?

**Comment by cmungall** [comment]
that'd be wonderful, though most in SRI-dm team should be able to handle

**Comment by nlharris** [comment]
@VladimirAlexiev would you be able to make a PR with your suggested changes?
