### ISSUE TITLE
incomplete sentence in RDF* to PG comparison

### ISSUE THREAD

**Issue by VladimirAlexiev** [biolink/biolink-model#368]
https://biolink.github.io/biolink-model/about/mapping-rdf.html#comparison-to-neo4j-mapping 
has an incomplete sentence "RDF* provides a PG later"

Also, it's more common to call these things LPG (labeled property graph), so it'd be good to revise this page and https://biolink.github.io/biolink-model/about/mapping-neo4j.html to use that name.

**Comment by sierra-moxon** [comment]
https://github.com/biolink/biolink-model/pull/768
