### ISSUE TITLE
ontology has wrong file extension and MIME

### ISSUE THREAD

**Issue by VladimirAlexiev** [biolink/biolink-model#370]
https://biolink.github.io/biolink-model/biolink-model.owl returns `biolink-model.rdf`.
Both of these extensions are wrong since it's a Turtle file.

The content type is also wrong:
```
>curl -IL https://biolink.github.io/biolink-model/biolink-model.owl
HTTP/2 200
server: GitHub.com
content-type: application/rdf+xml
```

**Comment by cmungall** [comment]
Can you provide link to the w3 spec that states it's wrong? Not saying it isn't, just the specs are unclear. It's common to have .owl render to any valid OWL serialization. I see content types recommended in functional and xml owl2 specs but not https://www.w3.org/TR/owl2-mapping-to-rdf/

@deepakunni3  I'm not sure how the content type gets added, is GH pages doing this automatically? 

I believe we should be able to override this by including 
https://github.com/perma-id/w3id.org/blob/master/biolink/.htaccess

**Comment by balhoff** [comment]
> Can you provide link to the w3 spec that states it's wrong?

The closest thing I can find is in the OWL 1 spec: https://www.w3.org/TR/owl-ref/#MIMEType

I don't know whether they were using other serializations besides RDF/XML at that time.

**Comment by VladimirAlexiev** [comment]
Google "turtle mime type" and you'll find it in the Turtle 1.1 spec.

It's `text/turtle` and `.ttl`

**Comment by balhoff** [comment]
Right—the question we had is whether it is valid to provide any OWL serialization (including Turtle) using the `.owl` extension, or if that necessarily indicates RDF/XML.

**Comment by VladimirAlexiev** [comment]
.owl is not officially registered 
- owl1 has not registered any mime and extensions
- owl2 has registered .owx see https://www.w3.org/TR/owl2-xml-serialization/#Appendix:_Internet_Media_Type.2C_File_Extension.2C_and_Macintosh_File_Type and .omn see https://www.w3.org/TR/2012/NOTE-owl2-manchester-syntax-20121211/#Appendix:_Internet_Media_Type.2C_File_Extension_and_Macintosh_File_Type

**Comment by cmungall** [comment]
I agree with @balhoff the specs don't indicate what we are doing in wrong

However, this barfs whenever I attempt to submit to it
https://lov.linkeddata.es/

As it has some hardcoded assumption about suffixes

also we want a better way to distinguish between the two *semantically* different serializations, currently differentiated by format suffixes .ttl and .owl. I suggest we rename biolink-model.owl to biolink-model.owl.ttl

**Comment by VladimirAlexiev** [comment]
Although `.owl` is not officially registered, this indicates to tools that support it `rdf/xml` (eg Jena RIOT).
https://wiki.edmcouncil.org/pages/viewpage.action?pageId=9011452 explains about different syntaxes, with links to the standard (summary: `.rdf .omx .omn` refer to RDF XML, OWL XML and Manchester notation, as I wrote above).

Turtle can carry A-Box (instance) data, and/or T-Box expressed in any number of formalisms (RDFS, OWL), but the file extension is always .ttl.

Renaming to `biolink-model.owl.ttl` is a good idea, as soon as the last part is `.ttl` and the MIME is `text/turtle`.

**Comment by nlharris** [comment]
@VladimirAlexiev If you do a PR with the suggested change, it probably can be reviewed and merged quickly...

**Comment by deepakunni3** [comment]
@nlharris This is more on the metamodel side of things. I can make a PR real quick and tag everyone on this thread for review..

**Comment by sierra-moxon** [comment]
closing as PR was merged.
