### ISSUE TITLE
Document approach for determining what URL to use for a source

### ISSUE THREAD

**Issue by kshefchek** [biolink/biolink-model#371]
Unofficially it looks like biolink-model prioritizes uses w3c, obo purls, and identifiers.org for URLs, this approach should be formalized and documented

**Comment by cmungall** [comment]
@kshefchek did you see this: https://biolink.github.io/biolink-model/#identifiers

**Comment by kshefchek** [comment]
I was thinking for developers adding new prefixes to the top-level overrides that a guide could be useful of how to pick URLs
