### ISSUE TITLE
NCBITaxon not in context.jsonld file?

### ISSUE THREAD

**Issue by saramsey** [biolink/biolink-model#375]
Hello Biolink Model team:

I'm confused about why `NCBITaxon` does not appear in the `context.jsonld` file?  I see that `NCBITaxon` is referenced on L1963 of https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml but for some reason it does not appear in the `context.jsonld` file like the other CURIE prefixes do.

I am working on a script that automatically validates KG2 CURIE prefixes against the `context.jsonld` file, and that is how I noticed this issue (not entirely sure this is an issue; maybe there is a reason why `NCBITaxon` is not supposed to be in the `context.jsonld` file; but in that case, is there a different file that I should be validating my CURIE prefixes against?)

Thanks,
Steve

**Comment by saramsey** [comment]
Oddly enough, `biolink` (which I understood from multiple sources to be the current, approved, canonical CURIE prefix for concepts in the Biolink metamodel) is also not in the `context.jsonld` file; only `biolinkml` .

**Comment by deepakunni3** [comment]
This is a bug in biolinkml. Will get this addressed soon.

**Comment by sierra-moxon** [comment]
NCBITaxon now appears in the jsonld context file as expected.
