### ISSUE TITLE
prefix choices

### ISSUE THREAD

**Issue by balhoff** [biolink/biolink-model#378]
I'm a little confused about how the prefix mappings file is built. There are the default curie maps: https://github.com/biolink/biolink-model/blob/ee4f4cb0930ff90ee9eb2ee0d8049b9f3c62f38f/biolink-model.yaml#L20-L24

But the biolink context does not have all OBO prefixes. How is it decided which are included?

**Comment by cmungall** [comment]
Only the subset referenced as valid id prefixes are exported. What prefix
do you expect to see?

**Comment by balhoff** [comment]
There are things in CAMs that aren't in there, like `EMAPA`, `DDANAT`, etc.

**Comment by cmungall** [comment]
Yep, the previous focus was on human

If you make a PR with the id_prefix entry for 'anatomical entity' extended
from Uberon to include these then they'll show up in the context

You could also normalize to uberon (at least for metazoa, ddanat would
still need to be there)

**Comment by nlharris** [comment]
Is there still an action item here or is this now resolved?

**Comment by balhoff** [comment]
I think this issue is resolved. I need to submit entries for prefixes I want.
