### ISSUE TITLE
Add CHEBI:59999 to mapping for Chemical Substance

### ISSUE THREAD

**Issue by kshefchek** [biolink/biolink-model#380]
Should CHEBI:59999 be a mapping for biolink:ChemicalSubstance?

**Comment by vdancik** [comment]
Looking at a ChEBI hierarchy, CHEBI:23367 (molecular entity) matches current use of Biolink's chemical-substance entity much better.

**Comment by nlharris** [comment]
Is this done?

**Comment by sierra-moxon** [comment]
done: closing
