### ISSUE TITLE
Support namespace prefix and identifier prefix (eg FlyBase:FBal*)

### ISSUE THREAD

**Issue by kshefchek** [biolink/biolink-model#382]
In some cases identifiers contain a prefix for specific types, for example:
FlyBase:FBal - alleles
FlyBase:FBgn - gene
WormBase:WBVar - variant
WormBase:WBRNAi - RNAi
ZFIN:ZDB-GENE - gene

Is this in scope for bl model?

**Comment by deepakunni3** [comment]
CC'ing @hsolbrig @cmungall

**Comment by cmungall** [comment]
Yes this would be useful

doing with comments for now, this would require blml extension

also we can make more use of the examples field

**Comment by sierra-moxon** [comment]
FB, WB, ZFIN are all identifier prefixes for sequence_variant, gene
