### ISSUE TITLE
Add properties to publication class

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#384]
We have a publication class: https://w3id.org/biolink/vocab/Publication

We should add properties to publication class, e.g. for author, year etc. Some of these would go on the parent

Note we shouldn't do any 'original' work here. We should simply adopt an existing schema or vocabulary and provide mappings for the different fields.

Ideally this would live in a separate reusable module that could be imported into bl. But I suggest an incremental approach - add properties first, map them, then separate out

As a strawman, I suggest taking the wikidata schema as a base here

I think this will be of broad interest across KPs and ARAs

**Comment by ehinderer** [comment]
I agree that it would be useful, especially in light of the requests for additional provenance features.

**Comment by cmungall** [comment]
From @mellybelly

COAR: http://vocabularies.coar-repositories.org/documentation/resource_types/
https://www.wikidata.org/wiki/Wikidata:Publication_types
https://www.nlm.nih.gov/mesh/pubtypes.html (see also https://id.nlm.nih.gov/mesh/lookup for RDF)
OCLC (https://www.oclc.org/bibformats/en.html but can never seem to find anything there)
http://bibliontology.com/ and https://www.dublincore.org/specifications/bibo/ (was adopted by Dublin Core)
https://sparontologies.github.io/fabio/current/fabio.html

**Comment by ehinderer** [comment]
Some of this is going beyond attributes for a publication though, right? This is listing out different types of sources. I think this ties into what Andrew Su was asking about in #356. I'll cross reference this discussion there.

**Comment by micheldumontier** [comment]
http://www.sparontologies.net/ontologies

**Comment by RichardBruskiewich** [comment]
I note that the https://w3id.org/biolink/vocab/Publication model has 

```
Identifier prefixes
    PMID
```
and

```
Referenced by class
    Association publications 0..* Publication
```

Both seem a bit too restrictive.  Will the integration of the spirit of the squid (SEPIO) also inspire a different perspective on documenting publications (i.e. in terms of "referenced by class")?

**Comment by nlharris** [comment]
> the spirit of the squid (SEPIO)
🦑😃

**Comment by RichardBruskiewich** [comment]
Resolved by PR  https://github.com/biolink/biolink-model/pull/481
