### ISSUE TITLE
Differentiate mappings according to granularity

### ISSUE THREAD

**Issue by deepakunni3** [biolink/biolink-model#387]
BiolinkML now supports representing mappings according to granularity: Narrow, Exact, Broad.

We should leverage this to better represent our mappings.

**Comment by kshefchek** [comment]
@deepakunni3 will we be replacing subclass_of with skos:narrowMatch?

**Comment by deepakunni3** [comment]
I believe that is the intent, as per previous discussions.
The use of `subclass_of` seems to be causing confusion. 

FYI @cmungall
