### ISSUE TITLE
Mappings and alias for exposure event, chemical exposure

### ISSUE THREAD

**Issue by kshefchek** [biolink/biolink-model#389]
Currently we have:
exposure event - SIO:000955, aliases: 'environment', 'exposure', 'experimental condition', is_a biological entity
chemical exposure - ECTO:9000000

Environment is not a good alias for exposure event, and SIO:000955 is not a great fit:
SIO:000955 is: An environment is a geographic region that hosts certain processes or objects.

Propose the changes to mappings:
- XCO:0000000 (experimental condition) should be a mapping for exposure event
- SIO:001399 (chemical exposure) should be a mapping for chemical exposure
- Remove SIO:000955 (environment) as a mapping to exposure event

**Comment by deepakunni3** [comment]
This is being addressed as part of PR #381
