### ISSUE TITLE
web page for "contraindicated_for" is missing

### ISSUE THREAD

**Issue by saramsey** [biolink/biolink-model#390]
**Describe the bug**
This URL gives a 404: https://biolink.github.io/biolink-model/docs/contraindicated_for.md
but from the `biolink-model.yaml` file, it looks like `contraindicated for` is a legit predicate.

**To Reproduce**
wget https://biolink.github.io/biolink-model/docs/contraindicated_for.md

**Expected behavior**
would expect to see a HTML page dedicated to the slot/relation `contraindicated for`

**What working group (or team) did this request originate from?**
This bug originated from the Expander Agent working group.

Note: This is relevant for members of NCATS Translator.

**Additional context**

**Tag relevant members for discussion**
Tag all relevant members to this ticket to start a discussion.

**Comment by sierra-moxon** [comment]
https://biolink.github.io/biolink-model/docs/contraindicated_for.html
