### ISSUE TITLE
Determining the level of granularity in Biolink Model for nodes and edges

### ISSUE THREAD

**Issue by deepakunni3** [biolink/biolink-model#392]
This ticket is to track an ongoing discussion on the following:
- The way we define granularity about nodes and edges are opposite in Biolink Model
- There has been a general level of confusion on what `relation` field means for edges and what the `edge_label` means in the context of the `relation` field
- A need from KPs for a change where the more granular predicates are primary and the more broader predicates be secondary
- A need for edge normalization where you give the tool a list of granular predicates, and a custom mapping that maps the granular predicates to broader predicates

CC'ing @cmungall @cbizon @RichardBruskiewich @mbrush @andrewsu @saramsey @TriageDr

**Comment by andrewsu** [comment]
Also relevant discussion in https://github.com/NCATSTranslator/TranslatorArchitecture/pull/2

And just to reiterate the clarification that @cbizon made [in slack](https://ncatstranslator.slack.com/archives/C014B3JAX36/p1595358785195500).  I don't think this issue is about BioLink model per se, which makes no effort (I don't think) to define one standard level of granularity.  Rather, it's IMO the combination of the SRI edge normalization + BioLink model which is making a de facto statement on a Translator-wide standard level of granularity.  And my fear with that (also [from slack](https://ncatstranslator.slack.com/archives/C014B3JAX36/p1595358295186700)) is that trying to define that Translator-wide standard 1) will take lots of time, and 2) be something that no one can really use "out of the box"...

**Comment by cbizon** [comment]
There is a biolink model component to this though - the normalizer tries as hard as it can to match the granularity of the input concept.   But the model has a granularity floor.  That's not a normalization issue, it's that the thing we're normalizing to doesn't represent the finest grain concepts.  (we can carry them along, but they're not part of the model) itself I think).

**Comment by saramsey** [comment]
I think it would help to have a realized, concrete example of a small JSON-serialized KG that completely conforms to the Biolink model. I feel that this would significantly help mitigate confusion.

Having said that, however we collectively choose to evolve the data model, I favor allowing a BigKG provider to express the following (for example):

1. from upstream provider `BSPO`, the original source predicate between node `X` and node `Y` is `BSPO:anterior_to`.

2. for that same relationship triple, the *harmonized* predicate between node `X` and node `Y` is `FMA:anterior_to`

I *strongly* favor having (or at least, allowing) relation CURIEs as the definitive way of stating the harmonized/simplified relationship type for a triple. I feel that if we encourage BigKG providers to use only a (non-CURIE) "edge label" for the "simplified" or "minimal" predicate, and do not allow the BigKG to *also* specify the relation CURIE for the simplified/minimal predicate, there will be confusion.

**Comment by cbizon** [comment]
I think that we can always harmonize a biolink predicate, but in a pretty degenerate way, since we can always default to "related to".  (that's admittedly unsatisfying)

**Comment by cbizon** [comment]
One thing we might want to clear up is the role of "mappings" for predicates.  Is it meant to be an equivalence relation, or is it a superclass/subclass relation?  I think for clarity we should make it into an equivalence relation, and handle 'rolling up' outside the model using tooling...

**Comment by sierra-moxon** [comment]
@cbizon @andrewsu @saramsey - from reading through the slack conversation last summer, it seemed like there was some agreement to add a node-normalizer to support "A need for edge normalization where you give the tool a list of granular predicates, and a custom mapping that maps the granular predicates to broader predicates."  It is not clear to me from reading through this ticket and the discussion on slack if there are missing predicates that need to be added to the model?  I can go ahead and close this ticket if not?

**Comment by nlharris** [comment]
related to (possibly even subsumed by) #632: Review predicates -- granular enough? Enough ways to group like things together?

**Comment by sierra-moxon** [comment]
I am going to close for now - we have a hierarchy of predicates that is continuing to evolve (we also have the edge normalizer already).
