### ISSUE TITLE
Purpose of class_uri and slot_uri in RDF version of biolink-model?

### ISSUE THREAD

**Issue by balhoff** [biolink/biolink-model#393]
We are using the [RDF rendering of biolink-model](https://github.com/biolink/biolink-model/blob/master/biolink-model.ttl) to enable bridging from Biolink into our RDF database for the Translator CAM KP. In previous builds of our database, we used `class_uri` and `slot_uri` to navigate from Biolink terms to OBO ontology terms. In recent versions of Biolink, these seem no longer to be useful for this purpose. What are these for? In all the examples I looked at, they just seem to be the URI for the the Biolink term itself. For example:

```turtle
<https://w3id.org/biolink/vocab/Cell> a meta:ClassDefinition ;
    skos:inScheme <https://w3id.org/biolink/biolink-model> ;
    meta:class_uri <https://w3id.org/biolink/vocab/Cell>
```

It seems odd for every Biolink term to link to itself.

cc @rajshruti18

**Comment by sierra-moxon** [comment]
Hi @balhoff  - we use very few slot and class uris in Biolink now, and the ones we have seem useful to me (mapping biolink:type -> rdf:type with no self-references to biolink.

I am going to close this as "done" but I can see potentially adding more class and slot uri annotations to biolink based on exact_mappings?  please reopen if I got this wrong.
