### ISSUE TITLE
mapping from biolink-model to ontology terms

### ISSUE THREAD

**Issue by balhoff** [biolink/biolink-model#394]
Another question about using the [RDF rendering of biolink-model](https://github.com/biolink/biolink-model/blob/master/biolink-model.ttl) to enable bridging from Biolink into our RDF database for the Translator CAM KP. 

There seems to be more than one way to map from a Biolink term to a term in an external ontology:

- `class_uri`/`slot_uri`—previously, maybe no longer used for this (see #393)
- `skos:mappingRelation`
- `rdfs:subClassOf`
- any others we should know about?

What is the difference between `skos:mappingRelation` and `rdfs:subClassOf`? Why aren't the values of `rdfs:subClassOf` also in `skos:mappingRelation`? Example:

```turtle
<https://w3id.org/biolink/vocab/MicroRNA> a meta:ClassDefinition ;
    rdfs:subClassOf <https://w3id.org/biolink/vocab/SO:0000276> ;
    skos:inScheme <https://w3id.org/biolink/biolink-model> ;
    skos:mappingRelation <https://w3id.org/biolink/vocab/SIO:001397>,
        <wikidata:Q310899> ;
    meta:class_uri <https://w3id.org/biolink/vocab/MicroRNA> ;
    meta:id_prefixes "MIR" ;
```

The SO term referenced is microRNA, so I'm not sure why there is a subClassOf relation at all.

Why does the list of ID prefixes include only MIR, and not any of the namespaces referenced in the mappings?

There is further a huge problem in that the URIs in both place are mangled; the SO term should be `http://purl.obolibrary.org/obo/SO_0000276`; the SIO term should be `http://semanticscience.org/resource/SIO_001397` (I think). See #301.

cc @rajshruti18

**Comment by kshefchek** [comment]
See the ticket here - https://github.com/biolink/biolinkml/issues/193 for the IRI issue, in the monarch fork I've fixed these manually for now

**Comment by balhoff** [comment]
I'm realizing that most of the issues I've opened here belong to biolinkml probably.

**Comment by kshefchek** [comment]
curious if there are any updates here?  I'm currently using a workaround that is stale.  @balhoff perhaps you have a more sane workaround?

**Comment by balhoff** [comment]
@kshefchek I'm using sed: https://github.com/NCATS-Tangerine/cam-pipeline/blob/d2475f5d8c694a967fba3b33dcbb47c31c0da1a0/Makefile#L112-L115

🤮

**Comment by nlharris** [comment]
@balhoff what is the "Translator CAM KP"? i can't match that to any of the KPs i'm aware of.

**Comment by balhoff** [comment]
It's a KP I'm developing under the Exposures Provider funding. We provide GO-CAMs.

**Comment by sierra-moxon** [comment]
work is happening on #667 - closing this one as duplicate for now, please reopen if I am incorrect in my assignment! :)
