### ISSUE TITLE
Produce simplified prefix.yaml and/or prefixes.json

### ISSUE THREAD

**Issue by balhoff** [biolink/biolink-model#397]
To come to a solution to the issues discussed in #301, I would like to propose that the Biolink build produces a simplified file for prefixes which is just a simple map from prefixes to expansions. This could be `prefixes.yaml`, `prefixes.json`, or both. This would give most users what they want—an easy to use map. Then the JSON-LD context would be freed up to become slightly more complex, adding `"@prefix": "true"` to every prefix object.

I'm hoping that then the RDFLIB JSON-LD library would be using the 1.1 spec, and using the more complicated context file we would get correct prefix expansions in the RDF serialization of Biolink model (@hsolbrig would this work in the current version?)

So what I am proposing are these two items:

- produce simplified `prefixes.yaml` or `prefixes.json`
- update JSON-LD context output to intersperse `"@prefix": "true"` as needed

**Comment by balhoff** [comment]
Does this need to be implemented at https://github.com/biolink/biolinkml instead of here?

**Comment by cmungall** [comment]
That would be preferable, since this would be generally useful, but if you
can't wait then we can implement here

alternatively, this could be a simple standalone script to go from the
different json-ld-context flavors to a simpler prefix yaml format

**Comment by balhoff** [comment]
@hsolbrig I am working with a developer at RENCI to make a pull request on biolinkml to modify `jsonldcontextgen` to output prefixes like this:

```json
{
  "@context": {
      "GO": {
          "@id": "http://purl.obolibrary.org/obo/GO_",
          "@prefix": true
      }
  }
}
```

We will also output a separate `prefix-map.json` with a simplified prefix-to-expansion map.

Question: does the JSON-LD processor currently used by biolinkml know how to use the `@prefix` directives?

**Comment by hsolbrig** [comment]
@balhoff - good question.   There is a 1.1 branch of the rdflib-jsonld processor but it isn't complete.  I've got a checkpoint of where I've referenced it in:

https://github.com/hsolbrig/stupid_jsonld_tricks

If rdflib-jsonld doesn't work, I would think that our next best option would be to try to switch to [pyld](https://github.com/digitalbazaar/pyld)

**Comment by hsolbrig** [comment]
I'm testing the question right now... will let you know in about 10 minutes

**Comment by hsolbrig** [comment]
Doesn't look promising - you may want to check my code but...

**Comment by hsolbrig** [comment]
Added pyld test - simple, works great, less filling....

**Comment by balhoff** [comment]
@hsolbrig I am helping @rajshruti18 to create a PR to change the jsonld-context output. Hopefully this will come through this week. Thanks for trying out pyld!

**Comment by cmungall** [comment]
very sorry about this.

can someone make a minimal example that replicates the problem and make a linkml ticket?

from #397  it seems you had someone working on this @balhoff ... but I don't see any open PRs?

**Comment by cmungall** [comment]
can we close this?

**Comment by balhoff** [comment]
This file isn't being provided by biolink-model yet, but #710 is a more specific request.
