### ISSUE TITLE
Separate drug from chemical substance

### ISSUE THREAD

**Issue by vdancik** [biolink/biolink-model#398]
Separate **drug** into it's own class that is not a subclass of **chemical substance** and add a new predicate _active_ingredient_of_ to connect drugs and chemical substances. In a chemistry-working-group discussion @cbizon suggested that **drug** should be a subclass of a **therapy** or **treatment** entity. This will allow modeling drugs that are not chemicals or drugs that are mixtures of chemicals.

**Comment by diatomsRcool** [comment]
I think this will work in the context of exposure events and ECTO.

**Comment by mellybelly** [comment]
+1 for separation. being a drug is a role for a chemical (it could be a toxin in other contexts, for example). I think this would work better for the different use cases.

**Comment by ehinderer** [comment]
I also agree with the separation. "Drug" is too ambiguous--it can imply trade name, approved treatments, etc.--whereas what might be sought after is the active compound (esomeprazole vs. "Nexium", for instance).

**Comment by southalln** [comment]
Weighing in to provide semantic perspective of FDA.
Drug product = formulated combination of ingredients administered as a therapy; contains active ingredients and excipients.
Drug substance = physical ingredient in drug product. Per ISO 11238, there are 6 substance types: chemical, protein, nucleic acid, polymer, mixture and structurally diverse ingredients (e.g. herbal extracts or cellular therapy). FDA's provides a UNII for every ingredient in medicinal products (chemicals and non-chemicals).
Active moiety = idealized ingredient (ignores salt forms and corresponds to biologically active part of the molecule in case of prodrugs). This is usually closer to the meaning of `drug` in the general literature.

First point, you might consider FDA's drug substance (per ISO 11238) to be a further enumeration of Biolink's MolecularEntity classes (in addition to chemical)?
Second point, I agree Biolink's Treatment class seems closest to FDA's drug product.
Third, drug substance might formally be the predicate linking a Treatment/drug product to a MolecularEntity/ingredient/substance.
Fourth, active moiety could be a predicate linking two `MolecularEntity`s.

It still isn't clear whether by `drug` you mean drug product or drug substance or some variation of active moiety/molecular entity. *FDA itself never defines `drug` (except by use), thus avoiding this conversation.

One solution is to consider `drug` to be the inferred link between a Treatment and a MolecularEntity via a drug substance and active moiety predicates.

**Comment by mikebada** [comment]
I'll sidestep the question of whether a drug is a physical molecular entity or a role, as I think it could plausibly be either.  However, classifying drugs as treatments really doesn't seem right to me, as treatments and therapies would seem to be processes.  Although this is ambiguous in its hierarchical modeling, Biolink:Treatment has "medical action" as an alias, which sure sounds like a process to me, and it's also mapped to OGMS:treatment, which is unambiguously modeled as a process.  I think that most would say that drugs aren't processes, but you could create a DrugTreatment subclass of Biolink:Treatment, which would utilize one or more drugs as causal agents.

As for the issue of mixtures, I agree that mixtures don't fit well into Biolink:ChemicalSubstance, which I think is confusingly defined.  To address this, I would recommend placing a ChemicalEntity class (either as a newly created class or as a reformulation of Biolink:ChemicalSubstance) as the top-level class for all chemical entities, analogous to CHEBI:'chemical entity', which does include chemical mixtures, among other types of chemical entities.

**Comment by cmungall** [comment]
@mikebada 
> classifying drugs as treatments really doesn't seem right to me

agreed

> but you could create a DrugTreatment subclass of Biolink:Treatment, which would utilize one or more drugs as causal agents

yes, this is how I interpreted the proposal.

>  I would recommend placing a ChemicalEntity class (either as a newly created class or as a reformulation of Biolink:ChemicalSubstance) as the top-level class for all chemical entities, analogous to CHEBI:'chemical entity', which does include chemical mixtures, among other types of chemical entities.

This is a good suggestion. I think the original intent was for the existing ChemicalSubstance to be this generic but I agree the nomenclature is confusing. Maybe make a separate ticket for this?

**Comment by vdancik** [comment]
Implemented in PR #750

**Comment by nlharris** [comment]
since that PR is merged, can we close this issue?
