### ISSUE TITLE
Make it easier to get to the related_to hierarchy in the docs

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#402]
From the front page of the docs, it's difficult to get to the related to hierarchy.  

For a lot of teams, getting the classes and the predicates are the parts that they want the most often, so those should be the easiest to get to.  

The simplest way I found to get to related to was to search for "related_to". searching for "related to" (no underscore) gave a bunch of less relevant results.

**Comment by sierra-moxon** [comment]
new doc shows children: https://biolink.github.io/biolink-model/related_to/ and a hierarchy viz: https://biolink.github.io/biolink-model/predicates.html

**Comment by nlharris** [comment]
This is really nice, @sierra-moxon!

**Comment by sierra-moxon** [comment]
https://github.com/biolink/biolink-model/pull/1418
