### ISSUE TITLE
Indicate when there are children

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#403]
If I'm poking around in a hierarchy like this:
![image](https://user-images.githubusercontent.com/10744350/89037688-fdd6c300-d30c-11ea-8c2c-9593813f509c.png)

It's nice to know which of the elements in the list might also have children so that I can browse down into them.  For instance, ontobee does this with "+" signs next to the elements that also have children.

**Comment by sierra-moxon** [comment]
new doc shows children: https://biolink.github.io/biolink-model/active_in/ and a hierarchy viz: https://biolink.github.io/biolink-model/predicates.html

**Comment by sierra-moxon** [comment]
https://github.com/biolink/biolink-model/pull/1418
