### ISSUE TITLE
develops from doesn't reference a slot

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolink-model#408]
Line 3952 asserts that the `anatomical entity to anatomical entity ontogenic association` `relation` slot is a `subproperty_of` "`develops from`".  "`develops from`" is not defined

**Comment by sierra-moxon** [comment]
@hsolbrig @deepakunni3 - I see "develops from" in the biolink-model.  Can I close @deepakunni3 ?  We can reopen if needed? :)

**Comment by deepakunni3** [comment]
Yup! Thanks @sierra-moxon
