### ISSUE TITLE
Mapping Knetminer ontology to Biolink Model

### ISSUE THREAD

**Issue by deepakunni3** [biolink/biolink-model#409]

**Comment by sierra-moxon** [comment]
https://github.com/Rothamsted/bioknet-onto seems to be the model we're trying to map to.

**Comment by sierra-moxon** [comment]
After reviewing the owl file for that repository, I am going to close for now.  I do not see specific classes/attributes to map, but happy to be pointed in the right direction.  I also note that the owl file was last generated in 2018.  Maybe there is an updated location somewhere.  Please re-open if need be. :)
