### ISSUE TITLE
Associations for events that occur one after another

### ISSUE THREAD

**Issue by diatomsRcool** [biolink/biolink-model#422]
**Is your feature request related to a problem? Please describe.**
The clinical data working group needs a Biolink association that can connect two things that occur one after another, but may or may not have a direct cause and effect relationship. For example, we need to be able to say that an exposure to X occurred before some observable outcome Y.
![image](https://user-images.githubusercontent.com/5140552/90551406-442a7f80-e15f-11ea-9634-5d6bc003a630.png)

**What working group (or team) did this request originate from?**
Clinical Data WG

**Note:** This is relevant for members of NCATS Translator.

**Describe the solution you'd like**
We think that a new association is needed. Possibly need to specify the time interval.

**Additional information to support this request** (optional)
https://github.com/NCATS-Tangerine/NCATS-ReasonerStdAPI/issues/104
https://docs.google.com/document/d/1ErXbtDvzc2I8XzyeCk5hZzq0EePPF8AsJRdfUBp098E/edit#heading=h.gjdgxs
https://docs.google.com/presentation/d/1Cg0Urz0tyJgLW967jFb-dS6c65C9eUp7th-yM33fI9o/edit#slide=id.g8d379c997a_0_0

**Tag relevant members for discussion**
@deepakunni3 @stevencox @karafecho

**Comment by diatomsRcool** [comment]
https://docs.google.com/presentation/d/1a1doGV-XZn2epMqP8tCQPdggwHSjZSOV_13EZBu28ns/edit#slide=id.g918882ba48_0_0

**Comment by diatomsRcool** [comment]
https://docs.google.com/presentation/d/1IkcYIwEkWsCqS9JqbIFHhNV9owNMINSpTh1UkBKVyn8/edit#slide=id.g8d379c997a_0_0

**Comment by RichardBruskiewich** [comment]
Is there also a need for more explicit biolink modelling of general temporal relationships, for example, BFO:0000068 "begins to exist in/starts at"

**Comment by cmungall** [comment]
biolink:precedes is the correct relation to use when temporal order is known but causality is unknown

This should be an equivalent property to RO:precedes

https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002411&viewMode=All&siblings=false

![image](https://user-images.githubusercontent.com/50745/93922954-89dee880-fcc7-11ea-9c7c-dd53f3ffc441.png)

**Comment by RichardBruskiewich** [comment]
Thanks @cmungall, for your feedback.

I edited my earlier comment to remove one 'precedes' containing RO term but left the other ones in with term names in inline comments, to emphasize the point that perhaps other predicates other than `biolink:precedes` may be necessary to adequately capture the temporal semantics involved.

I note that also, in the Biolink Model, `biolink:precedes` inherits directly from `biolink:related_to` with no intervening `biolink:temporarily_related_to` parent term.  (also, `biolink:regulates` _is_a_ `biolink:affects` _is_a_ `biolink:related_to`).

Does our hierarchy of temporal predicates in the Biolink Model require further refinement?

**Comment by stevencox** [comment]
Hi @RichardBruskiewich @cmungall @diatomsRcool thanks for the update.

I'm glad we've got precedes. And the preceding discussion makes a lot of sense.

Where we draw the boundary between things that should be modeled with predicates and things that should not?

Precedes implies two time periods. Each might be either a point in time or a period of time. An event, could in principle, consist of non-overlaping periods of time. (X was true Mon, Wed, Fri). We can imagine these relating in a variety of ways. Do (and should) we have predicates to model the possible varieties of overlap?

I'm guessing it's not healthy to attempt to explicitly model
* coextensive with
* overlaps beginning of
* overlaps end of
* after
* has some overlap
* has no overlap
* occurs during

And that we should, instead, support some sort of arithmetic operators on time to get around the need for such granularity. 

But is that right or is Biolink improved by populating the vocabulary of temporal predicates?

**Comment by diatomsRcool** [comment]
Should the temporal aspect be an annotation of the outcome, edge, or on some new time of node? See slide 8 [here](https://docs.google.com/presentation/d/1KVPjMfj3wSuXdbHEcQcGiRs4m5hbxT_vNQjqWiZeZn0/edit#slide=id.g9af8c3b7a0_27_6).

**Comment by RichardBruskiewich** [comment]
I've quietly added a new Biolink predicate: `biolink:temporarily_related_to` into the branch within which I'm working, and re-rooted `precedes` and `receded by` but we can add additional Biolink predicates that make sense here.

**Comment by sierra-moxon** [comment]
related: https://github.com/NCATSTranslator/Clinical-Data-Committee-Tracking-Voting/issues/14 
lower priority

**Comment by sierra-moxon** [comment]
per clinical WG - closing for now in favor of their ticket, we can reopen or add new cases that are actionable as needed.
