### ISSUE TITLE
Provide additional(?) formally documented guidelines for curating mappings, etc. of edges (and nodes?) in the Biolink Model

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#426]
Among other tasks (there may be other), the task of assigning third party `relation` ("predicate") mappings to a biolink model edge slot, in particular with respect to the partitioning of mappings into "exact", "close", "related", "broad" and "narrow", alongside asserted "domain" and "range" of the predicate, would benefit from a formally documented set of guidelines.

**Comment by sierra-moxon** [comment]
https://biolink.github.io/biolink-model/curating-the-model/#managing-mappings might help - feedback welcome.

**Comment by sierra-moxon** [comment]
https://github.com/biolink/biolink-model/pull/1418
