### ISSUE TITLE
Align with Apollo / Chado / JBrowse model of sequence locations

### ISSUE THREAD

**Issue by nathandunn** [biolink/biolink-model#427]
I would like to align as close as possible to the genomic model used in Apollo / JBrowse.  The reciprocal ticket is here: https://github.com/GMOD/Apollo3Server/issues/28

**What working group (or team) did this request originate from?**

The Apollo / JBrowse groups.

**Note:** This is relevant for members of NCATS Translator.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Do you have some recommendations on how this should be modeled?

I would like to adjust model and alias's to reflect the current model as much as possible, or make changes in the Apollo 3 codebase where needed.

**Additional information to support this request** (optional)
JSON Feature data is here: https://github.com/GMOD/Apollo3Server/issues/28#issuecomment-677958228

**Tag relevant members for discussion**
@deepakunni3  / @cmungall

**Comment by micheldumontier** [comment]
Please consider compliance FALDO, standardized for RDF data. https://github.com/OBF/FALDO

**Comment by deepakunni3** [comment]
While PR #445 did add ways to represent locations, the mappings are still missing.
