### ISSUE TITLE
Correct Biolink predicate mapping for SEMMEDDB:SAME_AS

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#431]
**Problem scope of feature request:**

The Semantic Medline UMLS predicate "SAME_AS" sounds equivalent to the `biolink:same_as` seems a bit fuzzier, with messier mappings within SemMedDb.  The definition in the pertinent paper (Kilicoglu _et al._ 2011) is "_comparative predicate_" where the equivalence could simply be functional, and example given is of one treatment being "_as effective as_" another treatment. The treatments themselves are not materially identical concepts.

**Describe the solution you'd like**

Assuming [pull request 429](https://github.com/biolink/biolink-model/pull/429), then:

```
close match:
    is_a: related to
    description: >-
      holds between two entities that are considered a skos:closeMatch to one another
...
    exact_mappings:
      - skos:closeMatch
      - SEMMEDDB:SAME_AS
```

**What working group (or team) inspiring this request**

The RTX predicate mappings prompted this discussion.

Note: This is relevant for members of NCATS Translator.

**Comment by cmungall** [comment]
So the question is, is sameAs sameAs sameAs? :-)

From what you are saying the answer seems no. And if semmeddb:SAME_AS is non-transitive it is not the same as biolink same_as, so go with closeMatch, or better, find a relation it does map to, e.g similar to?

**Comment by RichardBruskiewich** [comment]
Steve Ramsey of RTX mounted a good argument saying that Semmeddb data using the SAME_AS predicate does not show transitivity. Interestingly, though, the semantics is not really "similar to" but perhaps something else. See [Kilicoglu _et al._ 2011](https://www.ncbi.nlm.nih.gov/pmc/articles/pmid/22185221/). The words "comparative to" seems a closer fit.

**Comment by saramsey** [comment]
PR429 looks good to me. It would be super helpful to be able to express something like `biolink:close_match`, and not just for cases of `semmeddb:same_as`. Thank you, @RichardBruskiewich, @deepakunni3  and @cmungall

**Comment by nlharris** [comment]
Since #429 has been merged, can this issue be closed, or is there more to be done?

**Comment by sierra-moxon** [comment]
@saramsey - I am closing this issue because close_match can be used as a predicate as of #429.  please reopen if I have missed a critical unfinished piece! :)
