### ISSUE TITLE
A less specific 'treats'

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#433]
**Is your feature request related to a problem? Please describe.**
CTD chemical-disease relationships can be 'good' (chemical is potentially therapeutic) or 'bad'.  But these are very broad.  So the therapeutic class means that maybe there is some experiment in a cell assay showing some efficacious biomarker activity or something.  So that chemical is potentially positively influencing a given disease.  Currently, we turn that into 'treats' but that is far too strong.  This is not an approved treatment, or is there any real evidence (usually) that the chemical is in any way safe or effective in treating the disease.   Sometimes the chemical might be something that is even toxic, but provides a useful insight into the biology of the disease.  So we need  predicate for whatever this is.

**What working group (or team) did this request originate from?**
Old Gamma

**Note:** This is relevant for members of NCATS Translator.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Do you have some recommendations on how this should be modeled?

I think this is a new predicate of some sort, but I'm not sure what.

**Comment by ehinderer** [comment]
In a clinical setting, possibly something like "administered_for?" But I would imagine we would also need some kind of outcome as well (therapeutic, toxic), even if it's ambiguous (unclear, unreported). For screening, maybe "screened/tested_in" pointing to a CellLine class with a similar outcome?

**Comment by cbizon** [comment]
After discussing on the Biolink help desk call, this is the suggestion:

```
affects
  - ameliorates
      - treats
  - exacerbates
```

There are RO terms for ameliorates and exacerbates which are children of RO_0003305

**Comment by nlharris** [comment]
Hi, @sierra-moxon, Deepak and Chris thought this would be a good first Biolink Model issue for you to work on. Deepak can provide clarification if needed.

**Comment by sierra-moxon** [comment]
@deepakunni3 - I already see the hierarchy above in the biolink-model.yaml on master?  Maybe this can be closed?

**Comment by deepakunni3** [comment]
Perfect! Then let's close this ticket.
