### ISSUE TITLE
add RxNorm to biolink:Drug

### ISSUE THREAD

**Issue by CaseyTa** [biolink/biolink-model#436]
**Is your feature request related to a problem? Please describe.**
We would like to add RxNorm to the supported identifier prefixes for biolink:Drug

**What working group (or team) did this request originate from?**
This issue originated from the Clinical Data Working Group

**Note:** This is relevant for members of NCATS Translator.

**Describe the solution you'd like**
We would like to add RxNorm to the supported prefixes for biolink:Drug

**Additional information to support this request** (optional)
RxNorm is frequently used in clinical settings to represent drugs and is used by various Translator teams, including Clinical Data Provider, Multiomics Provider, Exposures Provider, and Unsecret Agent. Adding RxNorm to Biolink Model would allow more precise identification and differentiation of drugs and drug exposures since RxNorm drug concepts capture multiple levels of granularity, including drug ingredients, strength, dose form, and brand name. 

**Tag relevant members for discussion**
@rtroper, @mellybelly, @karafecho, @webyrd

**Comment by vdancik** [comment]
@CaseyTa Since RxNorm has multiple identifiers, I just want to clarify that by "RxNorm identifier" you mean RxCUI, right?

**Comment by CaseyTa** [comment]
@vdancik Yes, the RxCUI. Thanks!

**Comment by vdancik** [comment]
add label: chemical

**Comment by CaseyTa** [comment]
Could anyone please add the labels chemical and clinical for me? Looks like I don't have the write access needed to do that.

**Comment by sierra-moxon** [comment]
I see RxCUI as an id prefix on the Drug class in the model.  Closing for now as done, please reopen if there is more todo.

**Comment by karafecho** [comment]
Thanks!
