### ISSUE TITLE
Possible new Biolink Model predicate: biolink:realizes

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#438]
Do we need "biolink:realizes" reflecting the following term definition. RTX puts this term under inverse of "biolink:part_of" which is actually "biolink:has_part" but neither seems to capture the actual meaning of this term.

https://www.ebi.ac.uk/ols/ontologies/omiabis/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000055

**Comment by sierra-moxon** [comment]
@RichardBruskiewich - can you give me some more information about the use of this predicate?  Thanks!

**Comment by cmungall** [comment]
This is the correct URI

http://purl.obolibrary.org/obo/BFO_0000055

I don't think we need this. This is used for role modeling in OBO/BFO. 

E.g.

`P and has-participant some (M and has-role some realizes some R)`

In biolink we would just have a predicate corresponding to R and link P and M directly (or we can have a more generic predicate and include the role as en edge property)

**Comment by RichardBruskiewich** [comment]
> @RichardBruskiewich - can you give me some more information about the use of this predicate? Thanks!

Exactly as originally reported: t'was used in RTX. However, I see that Chris M. responded to this and closed the issue. I'm content with that.
