### ISSUE TITLE
Best Practices for Documenting Semantically Inverse Biolink Model edge predicates

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#440]
Insofar as edge relationships expressed using the Biolink Model are asymmetrical, one would expect predicate mappings which are the inverses of one other. This might best be expressed by triples with different subject and object categories, for example:

`(Process A)--[ biolink:occurs_in]->(Entity or Site B) `- e.g. where biolink:occurs_in has an _exact_mapping_ to **BFO:0000066**

However, the inverse term (e.g. **BFO:0000067** contains process) is not expressible in the Biolink Model except, perhaps, with relations to being a _close_mapping_ (or perhaps a _related_mapping_ ?) of  `biolink:occurs_in`.

In some parts of the Biolink Model, we introduce and document inverse edge predicates, but not consistently over the whole model. What is the accepted policy of the model with respect to such inverse mappings? What options do we have for semantic precision here?

**Option 1:** consistent introduce and fully document inverse predicates when needed (e.g. introduce "biolink:contains_process" for the above example).

**Option 2:** introduce a new edge mapping property, perhaps called `inverse_mapping` to serve as the target property for curating external ontology terms which have a clear inverse mapping to the term in question (would we then remove all instances of option 1 current in our model?)  

**Option 3:** is there another option here?

One concedes that a possible practical issue for **Option 2** `inverse_mapping` is to decide if such an inverse is an `(exact|close|broad|narrow)` inverse mapping to the 'forward' Biolink predicate. I'd be inclined to only document inverted `exact_mappings` terms, perhaps leaving other terms simply documented as `close_mappings`. Another, more radical idea might be to create the corresponding "compound" terms to deal with this, namely: `inverse_exact_mappings`, `inverse_close_mappings`, `inverse_broad_mappings` and `inverse_narrow_mappings`. Maybe that is a kind of **Option 3**?

**Comment by TomConlin** [comment]
Last week  I mentioned something about symmetric edges on a call but don't think my message got through, will retry in writing here.

```
The thought I did not get across very well last Thursday
is some edges (predicates) are symmetric
having a "preferred" representation 
	1) allows consistent serialization  as CM noted
	2) if consistently chosen would allow many? most? models to be expressed as a DAG.

An arbitrarily chosen edge can be consistent e.g. lexicographic order 
it may be less useful than a structurally consistent choice. 

Although every full ontology may be too complicated to be bound by a puny DAG many useful data modelling tasks are best served within such a constraint.
As such, a preferred edge is one which allows paths through models 
to flow from roots to leaves.

Aside:
In such a scheme 'broader' to 'narrower'  
or at least (not-narrower to not-broader)
could be implicit in the symmetry preference.
```

**Comment by RichardBruskiewich** [comment]
Thanks @TomConlin for the quick feedback on this issue.

Note that https://github.com/biolink/biolink-model/pull/432 is starting to deal with the semantics of "broad_mapping" and "narrow_mapping" (as well as "(exact|close|related)_mapping". Note that not all "symmetrical" predicates are broad/narrow relative to one another. They are simply semantic inverse relationships, sometimes naturally by distinct concept category, sometimes just in terms of some non-hierarchical directionality, e.g. A precedes B versus B preceded_by A

**Comment by saramsey** [comment]
It would be great if inverse predicate relationships between biolink relations was something that we could discover programmatically via the `biolink-model.yaml` file. We could then more clearly separate the "predicate mapping" part of `predicate-remap.yaml` from the "use the inverse of this relation" part. So where we currently have:
```
BFO:0000051:
  invert:
  - part_of
  - biolink:part_of
```
we could instead have something like:
```
BFO:0000051:
  rename:
  - has_part
  - biolink:has_part
  use_inverse: true
```
which would be a clearer separation of "relation mapping" and "predicate orienting".

**Comment by RichardBruskiewich** [comment]
Thanks @saramsey for your feedback.

I note that in fact, there is an `inverse:` model tag in BiolinkML which is already used in some predicate slots in the Biolink Model. This tag should provide programmatic support for "Option 1" I mentioned above.

That said, I must admit that I kind of like the idea of simplifying the Biolink Model slots to only include one 'preferred' edge direction but assuming that the inverse direction could somehow be flagged (as another `inverse: true` edge property) and to document 3rd party ontology mappings which are semantically inverted (but 'exact_match' to the reverse sense of the edge) with another mappings field, namely `inverse_mapping`.

The size of the predicate catalog could be minimized while capturing and preserving the bidirection semantics which may arise in raw knowledge sources.

**Comment by cmungall** [comment]
I agree with @RichardBruskiewich's analysis.

Option 3 is to essentially reify mappings, essentially the SSSOM datamodel embedded in biolink https://github.com/OBOFoundry/SSSOM

This is now allowed in biolinkml (I think this ticket should be closed: https://github.com/biolink/biolinkml/issues/167)

Each mapping would be an object, along with provenance etc as in SSSOM. An inverseOf could be added

Option 4a is to allow an expression in place of a CURIE with grammar

```
relationExpression ::=  '^'  atomicRelation | atomicRelation
atomicRelation ::= CURIE
```

Option 4b is to use on object for the relation expression rather than a parsed string

Independent of all this I like @TomConlin's suggestion to tag preferred directions, e.g. as subset. This is semantically silent but it's nice to have conventions. I don't think this should be enforced

Note there are subtle issues to do with quantification and abox vs tbox here

Before deciding, how many relations have a named inverse right now?

**Comment by RichardBruskiewich** [comment]
Good morning everyone. I'm going to try to digest all your comments, perhaps with some paraphrasing, so that we can converge on a decision here. Sorry if it gets a bit long. Semantics can be hard!

First of all, thank you @TomConlin, for your feedback.

I might need to clarify what I initially meant by "asymmetrical". 

In most cases, this simply means that the Biolink Model categories of the range and domain concept are **_not_** identical, e.g. some predicate might say "Gene - predicate -> Process", suggesting that perhaps an inverse predicate could be posited for "Process - inverse predicate -> Gene". I'm not sure that what you defined as "symmetric" means the same thing.  In my mind, a predicate like `biolink:related_to` is symmetric, which effectively means that it is its own inverse.  In the RTX curations, @saramsey might have tagged some 3rd party predicates as the "inverse" of `biolink:related_to`, for example:

```
BTO:develops_from:
  invert:
  - related_to
```
but I'm not sure what that means... A `biolink:related_to `B is purely reflexive, I think (i.e. B `biolink:related_to `A is always true).

Once again, 'broad' and 'narrow' only enters into the equation at the level of 1) the biolink term hierarchy itself and 2) the mappings of 3rd party terms against those biolink terms.  

If all 3rd party terms have "exact mappings" (or even SKOS exact|close|related matches onto at least one Biolink term), then broad and narrow would not be necessary. However, we don't have that situation at the moment (if we ever will).

Not sure what examples to use here but my sense here is that the direction of the edge (as defined by 'domain' and 'range' category) is totally independent of the question of whether a given 3rd party predicate is broader or narrower semantically relative to a given edge predicate semantics. 

Let me try with a facetious example:

```
 # MPO == My Parochial Location Ontology, term "live_at" defined as "Live at an given address", inverse "is_home_of"

Tom:IndividualOrganism - MPO:live_at -> Planet Earth:PlanetaryEntity
Planet Earth:PlanetaryEntity - MPO:is_home_of ->Tom:IndividualOrganism

 #Biolink - Option 3a(?)
located in:
   ...
   inverse: location of
   narrow_mappings:
       - MPO:live_at
   inverse_narrow_mappings:
       - MPO:is_home_of

location of:
   inverse: location of
   narrow_mappings:
       - MPO:is_home_of 
   inverse_narrow_mappings:
       - MPO:live_at
```

Obviously, if both 'biolink:located in' and 'biolink:location of' terms are maintained in the Biolink model, then we don't need the any inverse mappings let alone, 'inverse_narrow_mapping' but if we opt to prune the model down to single "preferred direction" predicates then simply map 3rd party predicates onto that, then the need to independently intersect both 'inverse' and 'narrow' (or broad) together likely becomes necessary.  

I can imagine other (perhaps more economical) lexical ways of expressing the above, e.g.

```
 # An embedded annotation version of the above  - Option 3b(?)

located in:
   ...
   inverse: 
      - location of
      - narrow_mappings:
          - MPO:is_home_of
   narrow_mappings:
       - MPO:live_at
```

@hsolbrig and @saramsey could comment on how this might complicate their (BiolinkML and RTX) parsing of the beast. Of course, if we retain 'location of' Biolink predicate above, we don't need inverse_mappings or inverse_narrow_mappings.

`close_mappings` and `related_mappings` are probably less of a problem with respect to inverse domain/range. As far as I can tell', `skos:relatedMatch` means "yeah, there's some kind of way that you can talk about the two concepts in one sentence but there they are not equivalent things".  The example at W3C (https://www.w3.org/TR/skos-primer/) is something like:

```
 ex1:platypus skos:broadMatch ex2:eggLayingAnimals.
 ex1:platypus skos:relatedMatch ex2:eggs.
 ex1:animal skos:exactMatch ex2:animals.
```

Of course, the concepts here are material entities not predicates. Maybe in the context of my contrived example (not sure how good it'll come across..), 

```
 MPO:live_at skos:broadMatch biolink:located_in.
 MPO:live_at skos:relatedMatch ENVO_01000739. # ENVO term is 'habitat' sensa ecology, within which an organism is "located_in" on planet earth
 MPO:live_at skos:exactMatch SIO:000172.  # SIO term is 'address is_a positional id'
```

So @cmungall, yes... Option 3 seems to be a reification of mappings, internal to the Biolink Model YAML, treated as a knowledge graph of ontology.  As I indicate above, we can brainstorm how to represent this succinctly and what the optimal computable format is for the anticipated use cases (and ease of processing by BiolinkML during model artifact generation and afterwards, through by ease of developer use of the generated Python modules and other code or (meta-)data artifacts).  It sounds like a YAML representation available for SSSOM is already adapted by BiolinkML (hence, Biolink Model)  as per https://github.com/biolink/biolinkml/issues/167?  This seems to suggest that the above  "_embedded annotation version_" example would be feasible.

Which gets me @cmungall, to your **Option 4** seems to be an alternate lexical representation to **Option 3**.  A parsed string using the '^' prefix is certainly compact. Would there be concerns, though, about the 'missing comma' phenomena, LOL: a single misplaced character changing the meaning of an assertion?  Using a YAML object spec seems safer, if only a bit more verbose. Remembering that the Biolink Model YAML, although human readable, is curated by human beings but meant to be (post)processed by code, suggests that 'in situ' readability (and avoiding the error of a missing or misplaced '^') not terseness is the main concern for accurate curation, but that BiolinkML can handle the parsing of a slightly more verbose YAML representation with ease.

Here's one final variation on my facetious example:

```
```
 # An embedded annotation version of the above  - Option 3c(?) / Option 4b-ish(?) with an additional concern relating to precision of definition of domain & range 

```
located in:  # 'preferred' predicate 
   ...
   domain: material entity        # note we don't have "material entity" defined as a concept but our definition talks about it
   range: material entity | site  # we don't really have such construct to constrain range to "material entity or site"
   inverse: 
      - location of  # would this Biolink predicate be removed if we prune down the model to on sided 'preferred' predicates
   mappings:
       inverse:
          narrow:
            - MPO:is_home_of
      narrow:
         - MPO:live_at
```

I close by posing the questions: what use cases and aspects of data representation are we optimising in the Biolink Model?  

I suspect that accurate semantic representation of core concept semantics and their mappings onto the global bazaar of bioinformatics ontology is the top level concern.   The 'translator_minimal' should truly be as minimal as feasible to capture all the useful relationships that meet core Translator knowledge wrangling objectives.  Facilitating human curation of and minimizing curator confusion are also primary concerns, since the quality assurance of the model drives its utility.  

Thoughtful curation of single third party predicate terms is "easy" for a curator to do but only if the number of bins they are curating things into are as minimal and distinct from one another as feasible, then very clearly defined. 

Once one is in the ball park of a given single Biolink term, deciding whether or not it is "inverse" ought to be relatively easy (just look at the category of the subject and object concepts involves, matched against the 'domain' and 'range' of the biolink predicate).  

The discernment of a term as 'close', 'related', 'broad' or 'narrow' are a bit more tricky but tractable (sometimes errors will be made) but knowledge of the SKOS definitions of these match terms should help.

Clarity and simplicity of representation of the bin mappings is important for the semantic binning task. Verbosity for BiolinkML is not an driving issue as long as it is deterministic by syntax parsing.

**Comment by cmungall** [comment]
> I might need to clarify what I initially meant by "asymmetrical".

These terms are all standardized, e.g
https://www.w3.org/TR/owl2-syntax/#Asymmetric_Object_Properties

https://en.wikipedia.org/wiki/Asymmetric_relation

**Comment by RichardBruskiewich** [comment]
Thanks @cmungall. I see!

That said, the Wikipedia article is actually open to mild confusion the way it is phrased given normal English usage. 

I do understand that when it says "A `related to` B" it means "A `has a given relationship to` B" (e.g. A `parentOf `B), the inverse which may not be true (i.e. B `parentOf `A is false).  However, two people can have the above kind of asymmetrical relationship to one another but still be "related to" one another i.e. a parent `related to` a child just as is a child `related to` a parent, _sensa_ normal English usage.

**Comment by RichardBruskiewich** [comment]
I just came across https://github.com/biolink/biolink-model/issues/57 which seems a related issue posted by Matt Brush in 2018 (sorry Matt for not noticing this earlier...)

**Comment by saramsey** [comment]
Responding to @RichardBruskiewich:

> In the RTX curations, @saramsey might have tagged some 3rd party predicates as the "inverse" of biolink:related_to, for example:
> 
> BTO:develops_from:
>   invert:
>   - related_to
> 
> but I'm not sure what that means... 

Thank you for bringing that to my attention. I think those are relations that had previously mapped (with inversion) to a directional (asymmetric) biolink relation type, but then at some point we threw up our hands and used the grab-bag relation type `biolink:related_to` (at which point, the "inversion" of the mapping, as you point out, no longer makes sense). We will fix that.

**Comment by nlharris** [comment]
Is there still work that needs to be done here?

**Comment by cmungall** [comment]
This is where I think we stand

 1. [ ] link existing predicates via `inverse_of` where appropriate
 2. [ ] define inference rules for inverse of #624 
 3. [ ] decide whether to name inverses for all predicates
 4. [ ] if so, create a report to ensure this is complete
 5. [ ] provide a programmatic way to look up an inverse predicate. DONE: use BMT

**Comment by cmungall** [comment]
decision on call:

 - agree on naming inverses

Return on future call to review behavior of edge properties on inversion

**Comment by nlharris** [comment]
"next step for that ticket is to create reports from biolink model to see whether inverses are defined properly
and then declaring the missing ones"

**Comment by sierra-moxon** [comment]
Per a biolink helpdesk call today, March 8, closing this ticket.
Unfinished "bug" level items are ported to this new issue: #664
