### ISSUE TITLE
Missing slot for slot_usage of genotype to genotype part association

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#441]
While tracking down a Travis build error, 

```
ValueError: File "/home/travis/build/biolink/biolink-model/biolink-model.yaml", line 3877, col 25:  Slot: "genotype to genotype part association_relation" - subproperty_of: "has variant part" does not reference a slot definition
```
The affected model entry:

```
  genotype to genotype part association:
    is_a: association
...etc.
    slot_usage:
      relation:
        subproperty_of: has variant part
...etc.
```
The error itself seemed to relate to the absence of a `biolink:has_variant_part` predicate which should be added, or the slot_usage removed.

**Comment by cmungall** [comment]
Let's do one thing at a time per ticket

in this case add the missing relation or remove the slot usage

Let's make a new ticket for changing R->EL which makes sense

**Comment by RichardBruskiewich** [comment]
Roger that @cmungall. 

Harold assures me that the (latest?) BiolinkML release used in the Biolink Model build likely processes the `subproperty_of` field properly so adding the missing relation(s) should fix the Travis build. I can do that today.

That said, I can split out this issue (#441) into two issues. I'll keep the original Travis bug here, then open another issue for the R->EL conversion.

**Comment by RichardBruskiewich** [comment]
Adding a proposed 'patch' to the biolink-model.yaml file in the new partitioned mappings file in https://github.com/biolink/biolink-model/pull/432
