### ISSUE TITLE
Change Association slot_usage: relation to predicate

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#442]
It is understood that the `slot_usage` here is meant to constrain the semantics of the slot; however, the `relation` slot is meant to hold the 3rd party relation predicate mapped onto the association, not a Biolink predicate, which is implied to be the range of value for the given `subproperty_of:` tag.

Should the `slot_usage `not therefore refer to the `edge_label `instead, namely:

```
  genotype to genotype part association:
    is_a: association
...etc.
    slot_usage:
      edge_label:
        subproperty_of: has variant part
...etc.
```

**Comment by RichardBruskiewich** [comment]
Since this issue was opened,  a decision was  made to deprecate the `biolink:Association` slot `edge label` in favor of the  `predicate` slot (name).  This issue was rechristened in this  manner.

**Comment by sierra-moxon** [comment]
@RichardBruskiewich - is this still an issue?  I know there is a decision to deprecate the 'relation' property.  Maybe this could be closed?

**Comment by sierra-moxon** [comment]
closing for now as relation is going to be deprecated, association does not have slot_usage and genotype to genotype part association has 'predicate' in the slot usage. :)
