### ISSUE TITLE
Review issue templates

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#444]
I think these could be improved. They don't seem to buy us much at the moment. Have a look at standard OBO templates, eg in mondo repo. @nlharris can help.

Templates should be aligned with labels. E.g. if I make a mapping request it should tag the issue with mappings

We should have specific team members associated with different templates, so people are auto-assigned

The template should have a structured form. E.g if I want to make a mapping request I should just have to fill out minimally a few fields:

 - source_id
 - target_id (optionally label)
 - any other provenance metadata

The title of the issue should also follow a standard form

**Comment by nlharris** [comment]
Will do. Wow, Mondo has a lot of issue types. https://github.com/monarch-initiative/mondo/issues/new/choose

**Comment by nlharris** [comment]
> We should have specific team members associated with different templates, so people are auto-assigned
Will need to discuss this with @deepakunni3

**Comment by nlharris** [comment]
Deepak and I discussed this; he is satisfied with the current state of the issue templates. We are also refining the labels.
