### ISSUE TITLE
Pathway predicate needed?

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#446]
```
The **DRUGBANK:pathway** predicate was mapped by RTX to `biolink:affects`, but one suspects that a new predicate might be helpful? Something like:

```
    in pathway:
       description: >-
           holds between a gene or gene products that are part of a biological pathway
       is_a: related to
      domain: gene or gene product
      range: pathway
      in_subset:
        - translator_minimal # should be?
      exact_mappings:
        - DRUGBANK:pathway
```

**Comment by cbizon** [comment]
My guess is `participates in` since pathway is a subclass of biological process.

**Comment by RichardBruskiewich** [comment]
Thanks for the feedback @cbizon!
