### ISSUE TITLE
Is biolink:coexists_with the best place for anatomical relationships?

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#447]
The Biolink (slot) predicate   `coexists with` seems to be a grab bag for many terms relating to the geometrical and functional relationships between anatomical components. 

Ongoing curation of mappings of 3rd party terms to the biolink predicates has me wondering whether a a more descriptive set of biolink predicates with more precise semantics for these relationships might be desirable (not sure exactly what though - opening this up for community discussion).

Maybe something like a new Biolink predicate slot `biolink:has_anatomical_positional_relationship_with` (I know... quite a mouthful!).

Alternately, do we move such terms as `narrow_mappings` to the  `biolink:colocalises_with` predicate slot? 

Or, would a `biolink:has_anatomical_positional_relationship_with` predicate also be defined in an `is_a` hierarchical subclass relationship with `biolink:colocalises_with`, to constrain anatomical mappings more precisely.  Some terms may also have some closer kin with `biolink:located_in`.

Of special interest to this issue report are all the identifiers in the **FMA (Functional Model of Anatomy)**, **UBERON** and **BSPO (Biological Spatial Ontology)** namespaces.  A great number of them are simply aggregated under generic tags - `biolink:coexists_with`, `biolink:part_of` and `biolink:related_to`.  It is possible that a broader and more fine-grained Biolink classification of these terms is desirable and feasible.

**Comment by sierra-moxon** [comment]
@RichardBruskiewich - do you have a particular bit of data/use case that you are trying to model?  I am going to close for now (in favor of the 'part_of' relation in an anatomical ontology perhaps?) but if you have something in mind, please feel free to reopen! :)
