### ISSUE TITLE
Deprecation of terms in the Biolink Model

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#448]
As we iterate on the Biolink Model, we may not "get it right" the first time, and may choose to modify the list of predicate and category terms we add into the model. 

Perhaps a formal mechanism for recording "deprecated" model terms would be helpful for computational mapping of knowledge tagged with older iterations of the model, especially of the records of deprecated terms point to the 'new' terms (and its mappings).

This relates to [issue 326 on model version management](https://github.com/biolink/biolink-model/issues/326).

We will also likely routine fix the 3rd party mappings in the model (although this might simply be managed on by correctly managing the model versions)

**Comment by sierra-moxon** [comment]
we have a deprecation process, we tag the deprecating item with the 'deprecated' attribute, then remove in the next release.  closing for now.
