### ISSUE TITLE
extension of 'gene expression' relations for 'expressed_in' class

### ISSUE THREAD

**Issue by realmarcin** [biolink/biolink-model#449]
After reviewing the Biolink Model entities and relations for gene expression data, I have some suggestions.

There is both gene (or protein) expression level data and relative differential expression levels. The former is a direct measurement of amount of a gene in condition X. The latter is a comparison of gene in condition X to a control condition Y, for example a time point in a time series where a sample has been subjected to a stressor and control has not.

Here is a list of terms to consider:

expressed_in

not_expressed_in
no_change_in

up_regulated_in
over_expressed_in

down_regulated_in
under_expressed_in

differentially_expressed_in

A few pairs of terms above are synonymous:
not_expressed_in
no_change_in

so picking a representative may be needed.

Also, these relations are most likely to apply between a gene or protein (or set) and a sample or experiment (or set). In this case the edge properties will be different between an expression level and differential expression.

Level properties:
- level value

Differential properties:
- relative level

In addition, in the differential expression case any additional properties would need to be distinguished between treatment vs control conditions. It could be assumed that any common properties are just listed as is, but any properties that are different between treatment and control (e.g. the concentration of an antibiotic) would have to be disintinguished, e.g. a case where the timepoint is shared and the concentrations are different:

timepoint
treatment_concentration
control_concentration

**Comment by nicholsn** [comment]
Nice to see this was raised, I am interested in modeling differential expression results (as well as other functional genomics analysis results like CRISPR screens). Previously, I've used the model from EBI (see below or [here](https://www.ebi.ac.uk/rdf/static/atlas/Microarray_Atlas_RDF_Schema.png
)), but like to see where biolink might go in this space.

![image](https://user-images.githubusercontent.com/463344/93387510-33346300-f81e-11ea-828d-98dfa3ecfc27.png)

**Comment by sierra-moxon** [comment]
we have expressed_in, we have postive and negative regulation.  we are in the middle of refactoring expression in general here, but I believe the use cases here are covered and will continue to be covered in the refactoring.  Closing for now as done.
