### ISSUE TITLE
Define standard serializations 

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#45]
todo: document this. Notes below

The biolink model is intended to be independent of any one serialization format or database technology. This adds an extra layer of abstraction when using for data exchange.

There are a few orthogonal choices here for exchanging links/associations

 1. Use the generic [Association](https://biolink.github.io/biolink-model/docs/Association.html) class or a subclass, e.g. [G2T](https://biolink.github.io/biolink-model/docs/GeneToExpressionSiteAssociation.html)
 2. JSON or RDF/graph format
 3. Which evidence model to mix in

For RDF exchange, a reality is that there is multiple reification standards. The reference one for us is OBAN, so we could define this as core and provide RDF shapes to check this.

But for many a JSON is most convenient, so the generic association class in the json-schema is best for general exchange.

**Comment by nlharris** [comment]
Is this still needed?

**Comment by sierra-moxon** [comment]
I believe KGX solves this use cases.  Please reopen if there is more nuance here.
