### ISSUE TITLE
Curies as node labels and edge types in neo4j

### ISSUE THREAD

**Issue by kshefchek** [biolink/biolink-model#451]
In the current spec neo4j labels and edge types are curies.  Colons are supported in neo4j but require backticks to escape them since they are part of the cypher syntax.  Proposing that for fully biolink compliant neo4j graphs remove the 'biolink:' prefix for ease of querying and reading.

**Comment by deepakunni3** [comment]
A strategy for achieving this is being worked on in KGX. Stay tuned 👍

**Comment by sierra-moxon** [comment]
sierra will document.

**Comment by sierra-moxon** [comment]
done in KGX I believe, please reopen if I got this wrong.
