### ISSUE TITLE
Fix Biolink Model CURIE prefixes and IRI's in generated biolink-model.owl file

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#452]
**Describe the bug**

OWL file CURIE prefixes for Biolink Model associations components showing up as '`meta:`' rather than '`biolink:`'.   In fact, the `biolink:` namespace (base URI https://w3id.org/biolink/vocab/) needs to be defined and applied throughout the file?

**To Reproduce**

Bug evident in currently generated file https://github.com/biolink/biolink-model/blob/master/biolink-model.owl (commit f1b05ea0dbc9f61f60c365bc2903892e028057a9)

**Expected behavior**
Generated file should have properly defined 

```
@prefix biolink: <https://w3id.org/biolink/vocab/> .
```
or

```
@prefix biolink: <https://w3id.org/biolink/biolink-model> .
```

(not really sure which - @cmungall to clarify?) 

such that the `biolink:` namespace prefix should then replace both `meta: ` prefix and (perhaps), the subject resource IRI's `<https://w3id.org/biolink/vocab/`_biolink-term_`>` in `meta:SlotDefinition`  in the RDF subject resources in Biolink Model OWL clauses

**What working group (or team) did this request originate from?**

Bug observed by @cmungall 

**Relevant members for discussion:**

@cmungall @hsolbrig

**Comment by nlharris** [comment]
@RichardBruskiewich do you still need clarification from @cmungall or @hsolbrig before you're able to work on this?

**Comment by sierra-moxon** [comment]
I think this is fixed, definitely reopen if I am wrong. :)
