### ISSUE TITLE
Would a predicate 'chemically interacts with' be a useful addition to the Biolink model?

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#456]
We have various subtypes of 'interacts with' predicates save 'chemical action at a distance' between two biological entities.  Would the addition of `biolink:chemically_interacts_with` _is_a_  `biolink:interacts_with` be a helpful Biolink predicate. 

Some 3rd party mappings (among others) which might sit well here could include the following _narrow_mappings_ to the term:

- RO:0002103
- RO:0002120
- RO:0002130

**Comment by deepakunni3** [comment]
There is a possibility of conflating `physically_interacts_with` to represent `chemically_interacts_with`. If that is too confusing then we can add `biolink:chemically_interacts_with`

**Comment by RichardBruskiewich** [comment]
I guess my sentiment on this is that the flow of chemical messages between two biological entities is distinct from the case where two biological entities directly make "physical" contact. 

I sense that the chemical flow interaction is so common in biology and has particular dynamics (e.g. diffusion gradients, etc.), that it should be separately highlighted as a relationship, keeping the physical interaction relationship for instances where two biological entities do directly "physically interact".

Of course, truth be known, *nothing* (no piece of not-so-solid quantum reality matter) in the world ever actual "touches" another *nothing*, except through electromagnetic fields, but I think we'd be splitting philosophical hairs here, LOL!

**Comment by sierra-moxon** [comment]
Hi @RichardBruskiewich  - I added a branch here with this addition: https://github.com/biolink/biolink-model/tree/456.  But it got me thinking about chemical-chemical interactions (antidotes, additive toxicity and synergism).  I'm wondering if we need to be a bit more broad in a chemical interaction predicate, or have a bit of a hierarchy here (or maybe there are already other ideas for these in the chemical working group?).

**Comment by sierra-moxon** [comment]
chemically interacts with has been added to the model.  
chemical WG is also refining chemical predicates.
