### ISSUE TITLE
Add prefix aliases

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#459]
Decided on chemistry translator call today

SRI will take on task of maintaining aliases for prefixes

**Comment by TomConlin** [comment]
From my understanding things like: 
 - CID:  PUBCHEM 

as well as preferred internal capitulations

- foo: FoO
- Foo: FoO
- fOO: FoO

**Comment by deepakunni3** [comment]
This is another feature that needs to be supported by Biolinkml.

Would be great to hear your thoughts @hsolbrig

**Comment by hsolbrig** [comment]
Will respond to this and issue #460 today or tomorrow...

**Comment by sierra-moxon** [comment]
The latest decisions here are that the source organization should be responsible for determining the casing of prefixes and registering these prefixes with idot, bioregstry, prefixcommons, etc (some of these sources slurp from the others).  We will continue adding prefixes to the biolink-model as needed: these already take precedence over the automatic prefix expansion built-in via idot, etc.  We will also try to add another context for bioregisty (a new prefix mapping service with a significant amount of traction, as well as ease of maintenance built-in).
