### ISSUE TITLE
Representing the spatial component of an exposure and an outcome

### ISSUE THREAD

**Issue by karafecho** [biolink/biolink-model#462]
**Is your feature request related to a problem? Please describe.**

We'd like to identify a way to capture the spatial component of an exposure and an outcome.

**What working group (or team) did this request originate from?**

The need for representing this type of data originated from the Translator 2020 breakout session on 9/23/2020.

**Note:**

This is relevant for members of NCATS Translator.

**Describe the solution you'd like**

We'd like to adapt Biolink such that we can represent the spatial component of an exposure and an outcome.

**Additional information to support this request** (optional)

![image](https://user-images.githubusercontent.com/26254388/94183695-d6195c80-fe70-11ea-8543-b3727fbc4ba4.png)

**Tag relevant members for discussion**

@karafecho @diatomsRcool @stevencox @xuhao

**Comment by nlharris** [comment]
see also #461

**Comment by sierra-moxon** [comment]
per clinical WG meeting: https://github.com/NCATSTranslator/Clinical-Data-Committee-Tracking-Voting/issues/14
closed in favor of the ticket in their repo, lower priority.
