### ISSUE TITLE
Intermediate predicate in between 'related_to' and 'expressed in' might be helpful?

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#464]
We currently (c.a. September 24, 2020) have the following:

```
  expressed in:
    is_a: related to
    description: >-
      holds between a gene or gene product and an anatomical entity in which it is expressed
    domain: gene or gene product
    range: anatomical entity
    in_subset:
      - translator_minimal
    inverse: expresses
```

There seem to be a possible role for a term narrower than `biolink:related_to` but broader than `biolink:expressed_in`, which might express the general relationship between a `biolink:BiologicalEntity` and an `biolink:AnatomicalEntity` as location.  A partial list (not exhaustive) of some 3rd party predicate mappings which might sit in that intermediate relationship type (not an exhaustive list) might include:

- RO:0004026 # disease has location
- RO:0004027 # disease has inflammation site
- RTXKG1:disease_has_location

The term `biolink:located_in` doesn't seem to have a completely appropriate scope for these mappings (i.e. a material entity distinct in existence from the material entity or site within which it is located):

```  located in:
    is_a: related to
    description: >-
      holds between a material entity and a material entity or site within which it is located (but of which it is not considered a part)
```

**Comment by deepakunni3** [comment]
It seems that `biolink:has_location` is appropriate here.

**Comment by RichardBruskiewich** [comment]
Hi @deepakunni3, I think you mean 

```
  location of:
     is_a: related to
     description: >-
        holds between material entity or site and a material entity that is located within it (but not considered a part of it)
 ...
```
However, looking closely at this definition, it is defined on a '_material entity_' which is not part of another '_material entity or site_' but is simply '_located within it_'.

Disease is not a 'material entity' but is tagged as a kind of  'biological entity' which can be conceptual as well as material (just having a "biological" conceptual essence).  In some cases, the location-like biological phenomenon (e.g. an 'inflammation site') is also again, a pretty vague conceptual localisation that is generally tied to anatomy. 

I suspect that we can do a bit better here!

**Comment by nlharris** [comment]
what's the action item here, and can someone other than chris do it?

**Comment by nlharris** [comment]
there was some discussion relevant to this in the predicates WG meeting on 23-apr-2021.

**Comment by sierra-moxon** [comment]
Proposal: 
Replace ‘located in’ with ‘has location’
‘Location of’ is the inverse of ‘has location’.
Domain: anything (process, entity, or quality) - ‘Named Thing’
There might need to be something (at some point) between named thing and something more restrictive.
Range: ‘physical entity’
Physical entity should have alias material entity
Change definition of located in (which will be changed to has location) to be more broad than material entity. 
Which is canonical?
Has location - canonical, location of is the inverse.
Could have a more general higher level conflation because its hard to say something is either located in or part of.
Contained, near, component (just brainstorming)

**Comment by nlharris** [comment]
Since this was moved to Done, I'm closing it.
