### ISSUE TITLE
Clarify Biolink Model specification with respect to symmetry and transitive relationships of predicates

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#466]
From a reasoning perspective, the semantics of edges in knowledge graphs can be unidirectional (asymmetric) or bidirectional (symmetric), based on the nature of the relationship specified by the semantics of the predicate. 

Many Biolink predicates are easily identified as unidirectional in that their stipulated **domain** (aka _subject concept_) and **range** (aka _object concept_) _category_ are not identical.

However, some predicates without explicit, or with identical **domain** and **range** _category_ constraints, may seem naturally _symmetric_, two examples being `biolink:related_to` and `biolink:interacts_with`.   At present, this quality of such predicates is not encoded in the Biolink Model.

That said, even if a predicate is deemed _symmetric_, it doesn't automatically follow that it implies _transitivity_, that is, if `A biolink:interacts_with B` and `B biolink:interacts_with A` are true, and `B biolink:interacts_with C` with `C biolink:interacts_with A`, it does not necessarily follow that `A biolink:interacts_with C` is true (think, for example, in terms of protein-protein interations).

Once again, the Biolink Model doesn't directly tag such semantic properties of predicates to this level of granularity.

**Comment by balhoff** [comment]
@RichardBruskiewich I think for bidirectional, you mean "symmetric" rather than "reflexive". Reflexive would be a self-relation.

**Comment by TomConlin** [comment]
a minimal intervention could be to assume symmetry with same types of nodes unless flagged as anti-symmetric.

**Comment by RichardBruskiewich** [comment]
> 
> 
> @RichardBruskiewich I think for bidirectional, you mean "symmetric" rather than "reflexive". Reflexive would be a self-relation. (at least according to OWL terminology)

Yes, you're correct. I think I've made this nomenclature error before! I'll fix my initial issue description accordingly.

**Comment by sierra-moxon** [comment]
Hi @RichardBruskiewich - both 'related to' and 'interacts with' both have the 'symetric:true' flag in the model, now.  We also just added some logical interpretation information to the model in this PR: https://github.com/biolink/biolink-model/pull/678/files.  Do we have more work to do here?  :)

**Comment by sierra-moxon** [comment]
@RichardBruskiewich  - closing for now, I think we've done the actionable tasks.  Definitely reopen if I've misinterpreted the issue! :)
