### ISSUE TITLE
Example usage for generated python classes

### ISSUE THREAD

**Issue by nicholsn** [biolink/biolink-model#468]
I'm interested in using the generated python classes to create an association instance and serialize it in turtle. 

I am able to create an example instance, but I haven't found an example for how to serialize a given instance or build up a collection of instances into a graph that can be serialized. 

For example:

```python
from biolink import model
association_id = model.GeneToDiseaseAssociationId(model.URIRef('http://example.com/iri/12345')
g2d_association = model.GeneToDiseaseAssociation(id=association_id,
    subject=model.ENSEMBL['ENSG00000201474'], 
    relation=model.RO['0002600'], 
    object=model.MONDO['0004975'])
```

Is there existing tooling to, for example, add this association to an `rdflib.Graph`? 

Are there other tools I should be looking at to use the biolink model in this way? I started looking at dipper, but my use case is to capture differentially expressed genes in bespoke analyses rather than entire repositories.

Very interesting project and appreciate all the work going into this!

**Comment by nlharris** [comment]
can anyone point @nicholsn to an example?

**Comment by nicholsn** [comment]
Came across a presentation with an example: https://bit.ly/linkml-yosemite

Looks like what was asking for will eventually be supported through something like this:

```
from examples.basic import Person
from linkml.dumpers import json_dumper, rdf_dumper

sam = Person("1172438", first_name=["Samual", "J"], last_name="Snooter")
ann = Person("17a3923", first_name="Jill", last_name="Jones", knows=[sam.id])

print(json_dumper.dumps(ann))
print(yaml_dumper.dumps(ann))
print(rdf_dumper.dumps(ann, contexts="../examples/jsonld/basic.context.jsonld"))
print(rdf_dumper.as_rdf_graph(ann, contexts="../examples/jsonld/basic.context.jsonld")) # See https://github.com/linkml/linkml/blob/main/linkml/dumpers/rdf_dumper.py#L16
```

**Comment by sierra-moxon** [comment]
closing for now, please reopen if there are additional bits we can highlight in our documentation :)
