### ISSUE TITLE
Addition of a food class to the model.

### ISSUE THREAD

**Issue by PhillipsOwen** [biolink/biolink-model#470]
Team: Ranking Agent

We propose an enhancement to the biolink model to include a class for food related ontologies and data.

Specifically, we seek the addition of the FoodOn (http://foodon.org) ontology and FooDB (https://fooddb.ca) curies to be incorporated into the biolink model. The addition of these will aid in the extension of data normalization and relationship efforts with other associated chemical compounds and their identifiers.

The FoodON ontology is a standardized food vocabulary that is supported by numerous ontology lookup services.

The FooDB dataset lists foods that contain chemical compounds and nutrients. Each compound record has sparsely curated relationships to other chemical compound curies already supported by the biolink model (CHEBI, PUBCHEM, etc.).

Thank you for your consideration.

**Comment by deepakunni3** [comment]
@PhillipsOwen Could you let us know how you'd like the food class be organized in the model?

**Comment by deepakunni3** [comment]
Based on discussion, perhaps we can have a `processed material` be the parent of `food` class.

**Comment by deepakunni3** [comment]
CC'ing @vdancik @RichardBruskiewich

**Comment by PhillipsOwen** [comment]
That sounds good to me. primarily i want to start using the foodb curie for node and edge normalization.

https://registry.identifiers.org/registry/foodb.compound

curie: foodb.compound:FDB002100 (FDB prefix and 0-padded 6 digit number)

**Comment by RichardBruskiewich** [comment]
Hi @PhillipsOwen,

How does FDB relate to FOBI (https://www.ebi.ac.uk/ols/ontologies/fobi), FIDEO (https://www.ebi.ac.uk/ols/ontologies/fideo) and FOODON (https://www.ebi.ac.uk/ols/ontologies/foodon)?

**Comment by PhillipsOwen** [comment]
foods are broken down into "contents", and those contents are comprised of "compounds" and "nutrients".

Compounds in a food are declared as "small molecular compounds". so in that respect i do not think you will find any that are not individual chemical substances. this of course allows us to normalize quite nicely in most cases. 

Nutrients (prefix FDBN, a small handful of broad classifications) that are not individual chemical substances, e.g. fat, proteins, carbohydrates, etc).
