### ISSUE TITLE
domain/range confusion in mapping for disease → gene and gene → disease 

### ISSUE THREAD

**Issue by colleenXu** [biolink/biolink-model#472]
**Is your feature request related to a problem? Please describe.**
In the biolink model yaml, _biolink: gene associated with condition_ gives domain as gene, range as disease / phenotypic feature (aka gene → disease). However, this relation/predicate maps to [NCIT:R176,](http://www.ontobee.org/ontology/NCIT?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_R176) which says that domain is disease/disorder/finding and range is gene (aka the inverse: disease → gene). Similarly, this relationship/predicate also maps to [hetio:associates_dag](https://elifesciences.org/articles/26726), which is also disease → gene. 

NCIT:R176 is also mentioned in the yaml as the "inverse" of the association _biolink: gene to disease association_. This is confusing since NCIT:R176 and _gene to disease association_ appear to be disease → gene. This object also has a mapping to [SIO:000983](https://www.ebi.ac.uk/ols/ontologies/sio/terms?iri=http%3A%2F%2Fsemanticscience.org%2Fresource%2FSIO_000983), which doesn’t seem to have a domain/range set. 

**Describe the solution you'd like**

- Richard's branch PR includes a _condition associated with gene_ relation/predicate to create an "inverse" of _gene associated with condition_. NCIT:R176 and hetio:associates_dag could fit there. **Or make some kind of symmetrical and general/high-level gene <-> disease relation/predicate (like [SIO:000983](https://www.ebi.ac.uk/ols/ontologies/sio/terms?iri=http%3A%2F%2Fsemanticscience.org%2Fresource%2FSIO_000983)).**
- Have a standard way of naming relations/predicates + associations [edit: currently this is only an issue for the _biolink: gene associated with condition_, so I won't make a separate issue right now]. Note that both the association object _biolink: gene to disease association_ and the relation/predicate _biolink: gene associated with condition_ start with the word "gene". But the association object has range = gene and the relation has domain = gene. 

**What working group (or team) did this request originate from?**
Exploring Agent

**Tag relevant members for discussion**
@deepakunni3 asked that I post this.

**Comment by RichardBruskiewich** [comment]
A proposed fix to this is in commit https://github.com/biolink/biolink-model/pull/432/commits/0805c4082149ef521b974e8338d6a5a36a7594f5 which will be merged with a larger PR https://github.com/biolink/biolink-model/pull/432

**Comment by RichardBruskiewich** [comment]
I'm going to reopen this issue for further community discussion given the following  comments from Jason Flannick (Genetics   Provider):

```
Well, technically a gene cannot be associated with a condition
Only variants are associated with conditions
The right model is probably, variant -> causes -> condition
This will exhibit itself, when tested in a population-based study (GWAS) as variant <- associated with -> condition, which is indeed symmetric
We then run a method that aggregates variants within a gene and comes up with a gene-level association
The proper relationships are probably gene -> has -> variant set <- associated with -> condition
Which could be condensed to a symmetric gene <- associated with -> condition
As long as it's okay in the model to gloss over things like genes vs. variants etc
```

Perhaps the Biolink Model expression for this use case needs to decompose the semantics into a two part statement:

`Biolink:DiseaseOrPhenotypicFeature - Biolink:variant_associated_with -> Biolink:SequenceVariant` 

and

`Biolink:SequenceVariant-  Biolink:is_sequence_variant_of -> Biolink:Gene`

?

**Comment by TomConlin** [comment]
Is there a plan for the unknown variant  of known gene case.

**Comment by colleenXu** [comment]
I'm not sure that gene-disease associations can always be decomposed into disease-variant-gene: 
- gene-disease associations may not include human variant info: examples include text mined associations, inferred associations from mode organism studies, inferred associations from altered expression or concentrations of something (found w/ histology/blood samples)
- not all gene-disease knowledgebases include information on variant-level that may underlie the assertion
- What is a variant/biolink: sequence variant? There are other types of genetic variation that can relate to disease: fusion gene/chromosome arrangement/CNV…
- **From my POV, it would help if a Provider gave both gene-disease associations and more granular variant-disease associations (if they were working with both). An ARA can then decide to do a Disease<->Gene lookup vs a Disease<->Variant<->Gene lookup.** An example of a Provider that gives both is [DisGeNET](https://www.disgenet.org/dbinfo#section11), which is ingested by Service Provider in MyDisease.info

**Comment by sierra-moxon** [comment]
action items here redundant with #504
