### ISSUE TITLE
Distinction between ontology class and other named things

### ISSUE THREAD

**Issue by wdduncan** [biolink/biolink-model#475]
The class `named thing` subsumes a number of classes (e.g, biological entity, material sample, etc.). But you have the class `ontology class` as subclass of `named thing`.  I find this confusing. Aren't all the classes ontology classes? Perhaps you could explain the intent of 'ontology class' better in the documentation? 

The definition for `ontology class` currently reads: a concept or class in an ontology, vocabulary or thesaurus.

**Comment by nlharris** [comment]
is chris the only person who can do this?

**Comment by mbrush** [comment]
I had the same question.  I always understood 'ontology class' as analogous to the [FHIR 'coding'](https://www.hl7.org/fhir/datatypes.html#Coding) data type - a data structure that lets you bundle an ontology class IRI, its label, and possibly other metadata - which can be used to populate fields that take enumerated/coded values.  In this sense, I think of 'ontology class' as more of a 'complex data type' than a Biolink Class.  

We have previously raised the idea of implementing some complex data types in Biolink, as these are useful modeling constructs in other paradigms. Not sure if this is still on the table - but might be worth thinking about.

**Comment by wdduncan** [comment]
Not sure I'm following ... But perhaps this just b/c I am not understanding the intent of biolink model. In one sense (I suppose) you can look at the entities in BM as data types. Then there is a data type call 'ontology class'. Is this what you mean?

**Comment by sierra-moxon** [comment]
In biolink-model 1.6.0, we moved OntologyClass to a mixin.  I think this should help reduce the duplicative meaning/confusion?  If not, please reopen of course! :)
