### ISSUE TITLE
should biological process  be a subtype of occurrent?

### ISSUE THREAD

**Issue by wdduncan** [biolink/biolink-model#476]
Should `biological process` (and similar classes)  be a subtype of occurrent? The definition of `occurrent` reads: A processual entity. 

Isn't a `biological process` a processual entity?

**Comment by deepakunni3** [comment]
Thanks for raising this concern.

This raises an issue of `occurrent` being a mixin in the model instead of a class by itself.

**Comment by wdduncan** [comment]
Thanks @deepakunni3   
I there guidance on the use mixins in the biolink-model? Mixins (AFIK) are a means to implement multiple inheritance using python classes. Is this what the "uses" link means in the diagram:

https://biolink.github.io/biolink-model/docs/BiologicalProcessOrActivity.html

**Comment by sierra-moxon** [comment]
@deepakunni3 @wdduncan - it looks like 'biological process' specifies the 'occurrent' mixin already?  Does this make this issue resolvable? :)

**Comment by wdduncan** [comment]
@sierra-moxon I think it depends on what the intent of using a mixin is. 
@deepakunni3 Is the intent of occurrent mixin to specify that biological process is a type of occurrent?

**Comment by deepakunni3** [comment]
@wdduncan Yes, that is correct. The mixin is to be used to add certain qualities to a class. In this case, the `occurrent` mixin is used to signify that `biological process` is also an `occurrent`.
