### ISSUE TITLE
Modeling of reaction participants

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#478]
Create a new association class `reaction to participant association`

The fields would be:

 - subject (https://w3id.org/biolink/vocab/MolecularActivity)
 - predicate: (todo: add has-participant to preds)
 - object (https://w3id.org/biolink/vocab/ChemicalSubstance)
 - usual provenance properties
 - stoichiometry: int
 - direction: One of l->r, r->l, bidirectional, neutral
 - side: One of l,r

TBD:

 - Consider generalizing subject to https://w3id.org/biolink/vocab/MolecularEntity, to allow proteins
 - use a different predicate and association type to link the catalyst (protein/complex)

**Comment by cbizon** [comment]
I wonder if it would be possible to bump this issue up a bit.   If we want to focus on errors of metabolism, having some shared way to handle reactions will be very helpful.

**Comment by nlharris** [comment]
Would what @cmungall described meet your needs, @cbizon?

**Comment by cbizon** [comment]
Possibly, but I would want to get opinions from @baranzini-lab who also has data of this type to model.  I think it would also be good to work through an example of reactions from the main sources, such as KEGG, reactome and rhea.

**Comment by baranzini-lab** [comment]
Happy to share what we have done (and doing). I can show how we have modeled reactions, and the successes and frustrations we had along the way. This may ultimately save some time for you, and your input will help us solve some ongoing challenges

**Comment by sierra-moxon** [comment]
From mini-hackathon 3/18/2021 (my notes, Dr. Baranzini will post a PR as well):

Dr. Baranzini presented his model for this. 
enzymatic activity (shortcut node that groups genes/proteins) --> reaction (node) -[consumes]-> chemicalCompound (node)
                                                                                                                                            -[produces]-> chemicalCompound (node)

Their group is getting close to removing 'enzymatic activity' as a node and replacing it with Gene.  
I did not catch which predicate you would use between enzymatic activity and reaction, @baranzini-lab (maybe 'catalyzes')?

Challenges: compounds are not well annotated (ie: which glucose to choose, a, b, both - other groups are working on this).

**Comment by colleenXu** [comment]
My view: what functionality is added by having a Reaction entity class? Perhaps the way the info is structured depends on how it would be used / how to query for it. 

1. Currently, aren't people doing direct ChemicalSubstance <-> Gene queries? Is a Reaction node intermediate needed? If the reaction is more of a way of describing how these two things are linked, then isn't reaction more like an edge property (rather than an intermediate node)? 

2. Having a Reaction entity class may mean dealing with reactions vs pathways. And that sounds potentially messy?
- is there any synonymization (so we know this reactome pathway/reaction is the same as this smpdb one)?
- some KPs may only ingest the pathway-level membership and not the reaction level
- KPs may not have all of the players related to a reaction (including every possible inducer / inhibitor and what they affect)
- what does the reaction's location in a pathway mean (downstream/upstream)? Is that even a concrete thing? Since there's feedback loops, complex behavior...it's hard to say that one chemical only does one thing in one step in one pathway ONLY.

**Comment by sierra-moxon** [comment]
more info: Molecular Entity has a synonym "reaction" in the model.

**Comment by baranzini-lab** [comment]
@colleenXu, metabolic pathways are a special case of pathways, and modeling them can be tricky. Some people use a metabolite-centric graph with the metabolites as nodes and reactions as edges. Others, use a reaction-centric graph where two reactions are connected by at least one arc representing a substrate or product metabolite. A third approach (https://www.pnas.org/content/105/36/13223), which we adopted, is  to describe metabolic networks is a bipartite graph with two types of nodes representing metabolites and reactions. We liked this approach as it naturally allows for modeling metabolic flux, and it naturally allows for reversibility, which many reactions show. 
This said, this is a decision each KP can make based on their own expertise and interests.

**Comment by karthiksoman** [comment]
Continuing from Sergio's comment on metabolic networks in SPOKE:
When it comes to modelling "Reaction" nodes in SPOKE, we use "KEGG" and "Metacyc" id's to define them. The closest mapping that we found in Biolink, corresponding to this is "[biolink:MolecularActivity](https://biolink.github.io/biolink-model/docs/MolecularActivity.html)". However, we see that this Biolink entity also maps to "EC" nodes, which is a different node type in SPOKE. I would be happy to discuss more about this and it would be great if @sierra-moxon could advise me regarding who will be the point of contact from the Biolink group to discuss about our SPOKE model and making it Biolink compatible with regard to the metabolic network.

**Comment by cbizon** [comment]
couple of quick notes: In @cmungall 's version at the top, how does one relate a gene/protein to the activity?

@colleenXu if we have reaction nodes (or use MolecularActivities to do roughly the same thing) then it doesn't preclude also making direct gene/chemical edges in a graph if those are useful.

**Comment by cmungall** [comment]
> how does one relate a gene/protein to the activity?

The catalyst gene/protein/ncRNA/complex would also be a reaction to participant association, `enabled by`

(of course, proteins can also participate as substrates too)

**Comment by cmungall** [comment]
@karthiksoman 

I would treat EC IDs as the same as MetaCyc and KEGG reactions, Rhea reactions, etc. This is how we are doing it in GO

You can make a linguistic argument that enzymes are proteins hence EC IDs denote biolink:Proteins, but I think this causes lots of problems. I'm interested in the decisions that led you to treat ECs differently.

Perhaps we should discuss this next call?

**Comment by cmungall** [comment]
@baranzini-lab good points

I think we can support all kinds of graphs with formal translations between each

**Comment by baranzini-lab** [comment]
> This is how we are doing it in GO

@cmungall I would be interested in discussing further your thoughts on how metabolic reactions ARE similar and how they are NOT similar to GO. 

In our case, we decided to introduce the concept of "enzymatic activity" (represented by the E.C. number) as a way to integrate several enzymes that can catalyze the same reaction from different species.

**Comment by karthiksoman** [comment]
@cmungall 
Currently, in SPOKE we have EC and reaction node types as separate entities for the reason that Sergio mentioned [here](https://github.com/biolink/biolink-model/issues/478#issuecomment-813701672). In that situation, if we map these two node types to the same biolink entity (biolink:MolecularActivity), wouldn't that introduce a many to one mapping. For example, if a TRAPI query has a node "biolink:MolecularActivity", to which SPOKE node type will we map this to, Reaction or EC?  
Sure, I would be happy to discuss this during the modelling call.
