### ISSUE TITLE
Help with Biolink modeling of clinical, spatiotemporal, and contextual data

### ISSUE THREAD

**Issue by karafecho** [biolink/biolink-model#479]
**Question:**

*A clear and concise description of what the request is.*

I would like to request a meeting with the Biolink HELP team, as I am unable to attend office hours. 

The purpose of the request is to review and resolve open issues related to the modeling of clinical, spatiotemporal, and contextual data.

*What working group (or team) did this request originate from?*

Clinical Data WG and at least five clinical/contextual KPs.

*Note:*

This is relevant for members of NCATS Translator.

*Describe the solution you'd like*

I'd like to identify solutions for open issues 
- [ ] #320
- [ ] #334
- [ ] #338
- [x] #341
- [ ] #354 
- [ ] #422 
- [ ] #461 
- [ ] #462

*Additional information to support this request*

None.

*Tag relevant members for discussion*

@karafecho @stevencox @Xuhao @deepakunni3 @diatomsRcool 

(The list above includes representatives from the Biolink team and the ICEES+ Exposures Provider team. Note, however, that the issues linked above apply to several KPs and thus any solutions that are developed will have broad applicability. Just thought it makes sense to restrict the meeting to a small group as a starting point and an initial test case for the new Biolink service.)

**Comment by nlharris** [comment]
@karafecho Thanks for including all this info so we can investigate this! We (Deepak, Matt, Chris M) are actually looking at it right now, and we will arrange a meeting with you if needed.

**Comment by karafecho** [comment]
Note that @patrickkwang may wish to join a meeting, should we decide to arrange one. 

Also, please see this relevant [TRAPI issue](https://github.com/NCATSTranslator/ReasonerAPI/issues/162).

**Comment by karafecho** [comment]
Here is a summary of what I think are the most pressing issues that are shared across clinical and contextual KPs:

1. KG edge semantics (e.g., representation of instance- vs class-based assertions, owlstar?)
2. Laboratory measures (e.g., LOINC codes, LOINC2HPO?)
3. Time and sequential events (e.g., exposures preceding an event [e.g., diagnosis] over specific time period, repeated measures [e.g., viral reinfection])
4. Outcomes that are not diseases or phenotypic features (e.g., ED visits, hospital readmission, death)
5. Exposures that are not chemicals (e.g., viral exposures, bacterial exposures, socio exposures)

There are others (e.g., space and exposure events), but I think the ones listed above are probably the more shared issues.

**Comment by stevencox** [comment]
[Notes](https://docs.google.com/document/d/1M5jT-JDGRxQnFvuFZjWnhbJGYWTBu8zo7lDP6AW9g0k/edit) from yesterday's Biolink office hours meeting.

**Comment by RichardBruskiewich** [comment]
Modelling requirements relative to item 3 above concerning **laboratory measurements** will need to be carefully pondered here, since such data may generally reside in the "Evidence/Provenance/Confidence" (EPC) part of the Translator ecosystem, the models for which are currently under discussion in the [EPC working group](https://github.com/NCATSTranslator/Evidence-Provenance-Confidence-Working-Group). The associated model changes may be developed in a [dedicated EPC fork of the main Biolink Model](https://github.com/NCATSTranslator/epcc-biolink-model-additions).

**Comment by sierra-moxon** [comment]
I think this is being handled by @mbrush  and @karafecho  in the clinical data modeling working group.  I think all the action items that need to be addressed are covered in the proposal Matt is working.  Closing for now - we can definitely reopen smaller tickets with action items that result from that working group's discussion! :)

**Comment by nlharris** [comment]
This still seems to be open--can we close it?

**Comment by stevencox** [comment]
Hi @nlharris - could we please add GitHub handle xu-hao here to continue this discussion?

**Comment by nlharris** [comment]
@stevencox did you mean can we assign this to @xu-hao? This repo is set up so that issues can only be assigned to core team members, but the @ I did should flag @xu-hao to see this issue.

**Comment by karafecho** [comment]
@sierra-moxon : This issue indeed is being addressed by the work that Matt and I are engaged with on behalf of the clinical data committee. The work is incomplete, however. We've completed requirements gathering, but we have not yet implemented any of the proposed changes.

**Comment by stevencox** [comment]
Hi @nlharris - Ok, thanks. I'd like @xu-hao to be aware of the issue and able to comment. Wasn't trying to assign it to him.

**Comment by nlharris** [comment]
@karafecho just wondering if any of the tickets linked to this can be closed yet!

**Comment by sierra-moxon** [comment]
per clinical WG meeting: closing as too broad, will reopen cases that are more specifically actionable
