### ISSUE TITLE
Add requirements.txt and pipenv.lock update to the github workflows

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolink-model#483]
When changes are made to the `Pipfile` file, it may be necessary to update `Pipfile.lock` and `requirements.txt`.  See https://github.com/biolink/biolinkml/blob/master/.github/workflows/main.yaml for an example of how requirements.txt might be updated.  We note, however, that we still have to update the lock file ...

**Comment by deepakunni3** [comment]
Okay, I'll make a PR to update the `Pipfile.lock` but we needn't have `requirements.txt`
Will remove that since it's redundant in addition to `Pipfile`

**Comment by hsolbrig** [comment]
I'll have to check, but my recollection is that there is still enough tooling out there that doesn't understand requirements.txt that it is recommended that you carry both forms for the near term

**Comment by deepakunni3** [comment]
This is now done, thanks to @hsolbrig's suggestions!
