### ISSUE TITLE
Clarify how to provide specific categorizations for nodes

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#486]
biolink provides a deliberately shallow hierarchy with which to categorize nodes. A node can have a [biolink:category](https://w3id.org/biolink/vocab/category) which must be a biolink class.

when a node is also an ontology class, then https://w3id.org/biolink/vocab/subclass_of (equivalent to rdfs:subClassOf) can be used as a categorization predicate. For example, in a CHEBI KG, for a node like serine (CHEBI:17822) we would have something like:

![image](https://user-images.githubusercontent.com/50745/96661810-d129ba80-1301-11eb-8810-17e3d762005d.png)

where each node has the same bl:category, and the edges have predicate subclass_of

the same thing would clearly hold for anatomical structures, pathways (GO processes), cells, etc; even for proteins (e.g. PRO)

subclass_of should connect two nodes of the same category, or in some cases the parent category can be more general than the child.

Other predicates may serve the same function as a subclass_of. For example, CHEBI models roles as a distinct hierarchy and use a has-role relation.

When a node is an instance, biolink:type (which is equivalent to rdf:type) can be used to connect the instance to the appropriate class node.

For example (using turtle syntax):

```turtle
pmid:1234 bl:category bl:Publication .
pmid:1234 rdf:type fabio:JournalArticle .
fabio:JournalArticle bl:category bl:OntologyClass .
```

note that we may want to have a more specific bl class for classifying information artefacts.

**Comment by RichardBruskiewich** [comment]
Thanks. This explanation was very helpful.

**Comment by nlharris** [comment]
Is there somewhere we should put this explanation so others can find it? @deepakunni3

**Comment by TomConlin** [comment]
https://github.com/monarch-initiative/dipper/issues/669

**Comment by cmungall** [comment]
To further expand, and answering @RichardBruskiewich comments on

https://github.com/biolink/biolink-model/pull/481/commits/dc6f61a67a54b09a76955ba48e9db2be2de1736b

When saying members of a class can be typed using bl:type, we can do this

 - by declaring `type` a class slot, optionally with slot_usage explaining the usage
 - as an associations, e.g. X-to-Y-classification

The latter should be done if we wish to annotate the edge with e.g. provenance, otherwise the former is more lightweight

**Comment by sierra-moxon** [comment]
- [ ] Move Chris's documentation into the main biolink-model documentation if its not there already, else link the documentation that exists already to this ticket.

**Comment by sierra-moxon** [comment]
Closing this for now - please reopen if I misjudged the status.
