### ISSUE TITLE
clarify documentation on best practices for edge annotation

### ISSUE THREAD

**Issue by andrewsu** [biolink/biolink-model#489]
Prompted a bit by this PR https://github.com/biolink/biolink-model/pull/485, I think it would be really useful to add some additional documentation on how `predicate`, `relation` and `association_type` (and any other related fields) should be used together or separately.  I'm thinking of a human-readable guide that is perhaps slightly higher level than annotations of each individual field.  For example, this is a similar type of document we use on Wikidata for how to specify evidence and provenance for various types of resources: https://www.wikidata.org/wiki/User:ProteinBoxBot/evidence.  Alternatively (or in addition), I could also see some of this added to the `description` or `seeAlso` sections...

**Comment by nlharris** [comment]
Flagging @mbrush to make sure he sees this

**Comment by sierra-moxon** [comment]
I think there is some documentation on this distinction - will link.

**Comment by sierra-moxon** [comment]
https://biolink.github.io/biolink-model/guidelines/working-with-the-model.html - happy to further document @andrewsu?  Or shall we close this?

**Comment by andrewsu** [comment]
Looks good to me!
