### ISSUE TITLE
Clarify predicate v relation distinction and change field name to 'edge label'

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#49]
In Translator we have the notion of minimal and maximal predicates. We had previously mapped minimal to 'predicate' and maximal to 'relation' but this is confusing.

Proposal is to keep `relation` as the true relationship type, at arbritrary specificity, using a CURIE if available.

For the 'min predicate' used `edge_label`. This is analogous to node labels in Neo4J. This is a human readable snake_case grouping for the relation

**Comment by nlharris** [comment]
@deepakunni3 is this now addressed?

**Comment by deepakunni3** [comment]
Closing this ticket since this was done in 2018. The changes discussed today on the Data Modeling call clarifies the changes made in 2018 to be more appropriate.
