### ISSUE TITLE
Possible duplicate entry for dbSNP?

### ISSUE THREAD

**Issue by zcqian** [biolink/biolink-model#495]
https://github.com/biolink/biolink-model/blob/92d794b58bd5c4ff9387755ac1eb94d54ce889e0/biolink-model.yaml#L3703-L3704

I am currently working on something that needs to parse all prefixes from biolink-model, and I encountered two entries for dbSNP. Is this a bug or is this intended?

**Comment by balhoff** [comment]
This has come up before in this issue: #460

It doesn't seem like it's resolved yet.

**Comment by nlharris** [comment]
What is the status of this? #460 is now closed.

**Comment by zcqian** [comment]
seems that everything was converted to uppercase (according to this [commit](https://github.com/biolink/biolink-model/commit/561fd2b7f0c891d1d46f9d1ce4ce7ae8b53f2b66))  but the duplication remains. So I don't think this issue in particular is fixed.
