### ISSUE TITLE
Align with semantic types and association types used by reasoner groups

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#5]
cc @dkoslicki

**Comment by cmungall** [comment]
See also https://docs.google.com/document/d/1bWuXQ3D-YzpqHOUe0V4Yqu1Nbm1FXrQ62IGN3uH5grY/edit

**Comment by nlharris** [comment]
is this still relevant?

**Comment by sierra-moxon** [comment]
closing as done; please reopen if I was incorrect in my assessment.
