### ISSUE TITLE
Missing prefixes from the model YAML

### ISSUE THREAD

**Issue by deepakunni3** [biolink/biolink-model#500]
Following prefixes are missing from the YAML:
```
  RTXKG1
  DGIdb
  oboFormat
  RXNORM
  LOINC
  PDQ
  CHEMBL.MECHANISM
  CPT
  PathWhiz
  NDDF
  VANDF
  HCPCS
  OBOREL
  REPODB
```

**Comment by saramsey** [comment]
My response to Richard B. about `RTXKG1`:

> Hi Richard, I think that CURIE prefix will be gone from RTX KG2 (i.e., it will not appear as the original-source relation for any of our KG edges), within a few months. We are in the process of deprecating it. But yes, for the time being, that is a reasonable prefix-to-baseurl mapping.

**Comment by RichardBruskiewich** [comment]
Issue resolved by PR https://github.com/biolink/biolink-model/pull/515
