### ISSUE TITLE
Review of the scope of application and interpretation of the 'subclass_of' tag to Biolink Model entities

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#501]
The `subclass of` tag is used in various Biolink model classes to constrain those classes to be bound to an external 3rd party ontology term hierarchies.  The rationale behind these bindings of ontology terms to  `subclass_of`  is to ensure that a given Biolink entity and all its descendants _qualify_ as child concepts of the given term.

Note that "Biolink entity" here means any named term in the Biolink model, not just a Biolink class.

There are some hidden challenges with the intent of this tag (outlined at the bottom of this issue).

Meanwhile, some typical examples `subclass_of` annotated classes are:

```
  attribute:
    subclass_of: PATO:0000001
```

Note that 'attribute' is not a category (not even "NamedThing"), a predicate nor an association, but just an "abstract entity'.

```
  biological sex:
    subclass_of: "PATO:0000047"
    is_a: attribute
```
```
  genotypic sex:
    subclass_of: "PATO:0020000"
```

Note that in the above `subclass_of` constraints appear self consistent with one another in that `PATO:0020000` is a descendent of  `PATO:0000047`, which is a descendent of `PATO:0000001`, all within the PATO ontology.

Additional notable examples of `subclass_of` usage are:

```
  individual organism:
    subclass_of: "NCBITaxon:1"
```

```
  anatomical entity:
    is_a: organismal entity
    mixins:
      - thing with taxon
    subclass_of: UBERON:0001062
```

```
  life stage:
    is_a: organismal entity
    mixins:
      - thing with taxon
    subclass_of: UBERON:0000105
```

```
  environmental process:
    is_a: planetary entity
    mixins:
      - occurrent
    subclass_of: ENVO:02500000
```

Most of these subclass_of tagged Biolink entity should present no great problems, since the attached 3rd party ontology may represent the global community standard for elaborating all the semantics of prospective inherited children of the entity (in most cases, a Biolink **category**). 

However, given the 'intent' of the the "Ontology Anchored Category" (or "OAN") as mentioned above - to ensure that the Biolink category and all its descendants qualify as child concepts of the given term - we need to ask: what is the practical consequence in three possible cases (both related concerns):

1. What if some descendant of the OAN is a Biolink entity which lacks a direct term mapping to the 'anchor ontology'

An example of this concern is that:

```
  named thing:
    subclass_of: BFO:0000001
```
anchors `NamedThing` to  the **Basic Formal Ontology** (BFO) term that defines the concept of "entity". However, many of the "is_a" descendants do not have any mapping onto BFO.

2. What if a descendant of the OAN is anchored by a `subclass_of` tag to a term from _another_ ontology.

Again, `NamedThing` is anchored to `BFO:0000001` whereas some descendants are anchored to 'root' terms in other ontology. 

3. The third situation combined the first and the third, if the semantics of the implied descendants of an OAN may not have any mapping onto the anchor ontology but have semantics mapped onto another ontology namespace. In fact, our first example above:

```
  attribute:
    subclass_of: PATO:0000001
```

is an example of this situation.  Whereas the namespace prefix acroynm PATO stands for "Phenotype and Trait Ontology" which is described as _"An ontology of phenotypic qualities"_,  the Biolink 'attribute' entity is used in practice to tag Biolink entities with other 'qualities' or 'concepts' which are not strictly covered within the scope of PATO, but rather, drawn from additional ontology such as EFO (Experimental Factor Ontology) and LOINC, which may only has some partial overlap with PATO.

Another possible example of this would be:

```
  phenotypic feature:
    aliases: ['sign', 'symptom', 'phenotype', 'trait', 'endophenotype']
...
    subclass_of: UPHENO:0001001
```

In fact, there are clinical data use cases which would annotate EFO and LOINC terms as 'phenotypic features'.  This issue is cited in Biolink Model issue https://github.com/biolink/biolink-model/issues/493. A subset of EFO and LOINC terms may overlap in semantics with UPHENO but not the complete set of terms which will be used in such clinical data set attributes.

The challenge of this ticketed issue is to clarify the exact intent, constraints, override rules and interpretation of the `subclass_of` tag in model schemata such as Biolink, relating to the above concerns.

**Comment by cmungall** [comment]
thanks for the detailed analysis, this is spot on. In fact these should all just be changed to the relevant skos mapping, many are exacts

**Comment by RichardBruskiewich** [comment]
Thanks @cmungall, 

I had another odd stray thought about the `subclass_of` property this morning: would it sometimes make sense to use it to signal that an entire subtree of an ontology hierarchy should somehow be treated as `narrow_mappings` of a given Biolink term? What this would signal to, say, SRI node or edge normalizers, is that processing input terms tagging a given node or edge, if found in the ontology subtree, could be tagged with the given Biolink term. That also may point at the fact that we don't really propagate the 'skos match' status of such terms into the resulting knowledge graph. For example, if an `Association.relation` from a knowledge source is associated with a given `Association.predicate` as, say, a narrow or related mapping, we don't remember that in the resulting knowledge graph. 

Does that represent a bit of lost useful information?

For a node `category`, the situation is even worse in that we don't really have any property 'original term mapping' for nodes, which would be analogous to the `Association.relation` property in edges.

**Comment by RichardBruskiewich** [comment]
OK.. following your recommendations @cmungall
