### ISSUE TITLE
Questions about provided_by and is_defined_by slots

### ISSUE THREAD

**Issue by mbrush** [biolink/biolink-model#51]
Creating ticket here to continue discussion in comments of the TKG Spec [here](https://docs.google.com/document/d/1TrvqJPe_HwmRJ5HCwZ7fsi9_mwGcwLOZ53Fnjo8Sh4E/edit#heading=h.88ipzwsvyy5s), concerning labels of the following  edge properties:
 
- **is_defined_by** [required]: A CURIE/URI for the translator group that made the KG
- **provided_by** [required]: A CURIE prefix, e.g. Pharos, MGI, Monarch. The group that curated/asserted the edge.
 
Comment in the gdoc was to consider names for these properties again - e.g. switching the labels so that is_defined_by describes the primary source that originally defined or asserted the claim, and provided_by describes the Translator group that provided the association to the uber graph.
 
A follow up comment asked if it made any sense to make these more fine-grained? We have an edge property "source" where we store the specific function in our code that produced the edge. But I could imagine putting a curie prefix on that so that is_defined_by becomes something like GAMMA:uberongraph.get_anatomy_by_cell_graph. Ditto for provided_by. Currently we have a property called URL where we put the url we retrieved the info from (for url-derived edges)
 
And a final comment offered: say you have a relation provided by drugbank, who in turn obtained it from a publication. who should be credited in the provided_by field?

**Comment by mbrush** [comment]
I agree that the labels 'is_defined_by' and 'provided_by' are not clear, and perhaps should be swapped as proposed above. But we may also consider new names for these altogether, and consider the question of creating more fine grained properties if needed.
 
It seems that _minimally_ we should have and edge property to link to any **resources** from which the information captured by an edge was retrieved, and an edge property that links to the **agent/group** that contributed the  edge to the KG.  A property like "**source**" or  would do for the former, and potentially capture any type of source (publication, database, web service url, etc). Then a property like could be used "**provided_by**" or "**contributed_by**" for the latter.
 
But as noted it can get more complex than this. The provenance of each edge in a KG can be traced back across potentially many different resources where it has been stored, and many services that have been used to retrieve/import it.  For example, the assertion captured in an edge may first appear in a **publication**, then get curated into a **database**, then be served by an **API/web service** at some URL,  which may be called by some **programmatic function**.  
 
If we wanted to support this level of granularity, the standard could provide series of "source _
_____" properties that could point to sources of an assertion/edge at different stages in its provenance. For  example:
- **source**
    - **source_publication** (an upstream publication that originally made the assertion or reported some data)
    - **source_database** (the DB/KB from which an assertion or data was originally retrieved)
    - **source_url** (the url of a specific API/web service that was used to retrieve the assertion/data)
    - **source_function** (a particular function used by the retrieving agent to query a data source and pull back the assertion or data)
    - **source_TKG**  - a source sub-property for Translator purposes that points to a TKG, e.g. "Xray KG"
 
This idea of a 'source' is distinct from the notion of the agent (here the Translator group/tool)  that contributed the edge to a particular KG. As noted, a property like provided_by  or contributed_by would point to, e.g.,  the "Xray" Translator group who made the KG providing the edge. This however might be duplicative of a property like source_TKG above.

**Comment by cmungall** [comment]
change source_TKG to source_aggregator?

**Comment by cmungall** [comment]
Discussion on thu call: if it's important for people to structure things in more detail at the provenance level then a multigraph is the best representation

**Comment by mbrush** [comment]
I missed the last call here, so wanted to clarify where things stand:
 
**To replace is_defined_by** (or can we keep is_defined_by for this?)
- **contributed_by**  (the Translator team who contributed the edge to the graph) . . .

**To replace provided_by, use one or more of:**
- **source_publications** (a list of publication(s) that made the assertion or reported some data - typically the most upstream point in the provenance of an assertion/edge)
- **source_database** (the _primary/original_ DB/KB from which an assertion or data was originally retrieved)
- **source_url** (the url of a specific API/web service that was used to retrieve the assertion/data)
- **source_function** (a particular function used by the retrieving agent to query a data source and pull back the assertion or data)
- **source_aggregator** - a database that aggregated data from an upstream/primary database 

**Questions:**
- Would **source publications** replace current **publications** edge property?
- Is the value of **source_publications** a list?  how about **source_database** and **source_aggregator**?
- To be clear about the idea about how multi-graphs will support "more detail at the provenance level"
    - multi-graphs allow multiple edges of same 'type' between same nodes, correct?
    - this means we can have multiple edges representing the assertion that "geneX"  expressed_in "anatomyY" - where each edge has separate provenance (i.e. is contributed by a different team, and/or has different provenance chain that traces back across the resources it was derived through)
    - for this multigraph, what would be the identity criteria for an edge?  
        - are values of all edge properties identifying criteria - such that if any is different a new edge is materialized? 
        - recall that in addition to the provenance properties above, we have **edge_label**, **relation**, **evidence_type**, **qualifiers**, and **negated**

**Comment by cmungall** [comment]
Your understanding of our discussion on MGs is correct. The identity criteria would be set of edge properties (including s/p/o). If groups wanted to collapse MG edges internally they could, but there may be a loss of structure of the provenance information.

**Comment by mbrush** [comment]
@cmungall - Following the 5-17 Arch Call, you said you still liked "is_defined_by" as the name of the edge property for recording the Translator group that contributed the edge to the TKG.  

I have no strong feelings here - my only concern would be that SciGraph uses is_defined_by to record the source_database, which will be captured in TKGs using the "source" properties below. So there is potential for confusion or inconsistency here.  

Let me know what you want us to call this . . .  we can keep is_defined_by, or try one of the other candidates -  e.g. 'provided_by', 'contributed_by', 'contributing_TKG', 'edge_contributor',  'source_TKG' . . . ?

As for the various"source" properties, the names above sounded good, except perhaps 'source_function'? And maybe 'source-url'?   Will implement once you/others give final feedback here.

**Comment by nlharris** [comment]
@mbrush are you still awaiting feedback on this?

**Comment by deepakunni3** [comment]
This is superseded by discussions happening within the EPC WG.
