### ISSUE TITLE
should chemical substance have a taxon?

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#511]
**Is your feature request related to a problem? Please describe.**
Looking up "slots" for chemical substance using the biolink toolkit returns  a bunch of slots.   One is "in taxon".  
Maybe that's ok?  Seems odd to me though, I don't think it should be there.  It's there because chemical substance's parent (molecular entity) has the has taxon mixin class.

**What working group (or team) did this request originate from?**
SRI, developing tests for the biolink lookup service

**Describe the solution you'd like**
I think that the taxon mixin should be pushed down to the children of molecular entity, but not to chemical substance

**Tag relevant members for discussion**
@deepakunni3 @cmungall

**Comment by sierra-moxon** [comment]
I think this was fixed by the chemical hierarchy refactor in biolink-model 2.0.0?  If not, please feel free to reopen. :)
