### ISSUE TITLE
Diagnosis concept category?

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#514]
**Is your feature request related to a problem? Please describe.**

- How can  we represent clinical diagnoses,  or statements about clusters of related possible diagnoses?

**Describe the solution you'd like**

Add a "Diagnosis"  category class  to Biolink.

**What working group (or team) did this request originate from?**

Inspired  by  Genetics Provider but probably of general relevance to clinical data.

Eg.  Their  GWAS(?) data has a 'trait' of **End-stage renal disease vs. macroalbuminuria**  which seems more of a concept of comparison between to possible  alternate diagnoses. A  'Diagnosis'  node  could  perhaps have  'either/or'  relationships to the two  disease alternatives(?).

**Comment by sierra-moxon** [comment]
we have 'diagnosis'  - closing for now, please reopen if I got it wrong.
