### ISSUE TITLE
conflicting usages of `PATO:` prefix

### ISSUE THREAD

**Issue by balhoff** [biolink/biolink-model#516]
There are various terms prefixed with `PATO:` in biolink-model.yaml, but they should not all be expanded the same way. This is separate from the issue that there is no PATO expansion found in the context (#450).

Terms like `PATO:0000001` are standard PATO terms and should be expanded as `http://purl.obolibrary.org/obo/PATO_0000001`. This is the namespace that should have the `PATO` prefix.

PATO local object properties like `decreased_in_magnitude_relative_to ` have IRIs like `http://purl.obolibrary.org/obo/pato#increased_in_magnitude_relative_to`:

https://github.com/biolink/biolink-model/blob/531f70da66dd190f7744a60e27af5bc97e0d811c/biolink-model.yaml#L246-L250

These can't be prefixed with `PATO`.

**Comment by RichardBruskiewich** [comment]
Thanks @balhoff, I've pushed the patch for this issue to the Monarch curi map. See https://github.com/monarch-initiative/dipper/pull/1002

**Comment by RichardBruskiewich** [comment]
Update: @TomConlin and I discussed this issue. Since the PATO Property namespace currently (for the moment) seem local to the Biolink model, I will curate this prefix mapping here under `prefixes:`.

**Comment by RichardBruskiewich** [comment]
@balhoff, resolved by PR https://github.com/biolink/biolink-model/pull/550 (once merged)

**Comment by balhoff** [comment]
Thanks!

**Comment by cmungall** [comment]
of course, PATO should just use resolvable OPs.
