### ISSUE TITLE
Predicates for gene-condition associations

### ISSUE THREAD

**Issue by mbrush** [biolink/biolink-model#52]
In recent Translator Knowledge Graph (tkg) standardization calls we reviewed different approaches for creating predicates linking genes directly to disease.  The proposal below would create a set of predicates for connecting  genes to diseases separate from those used to connect variants to conditions.    See column G in the spreadsheet [here](https://docs.google.com/spreadsheets/d/1zXitcR1QjHyh6WocukgshSR7IoAVg7MJQG-HNh96Jec/edit#gid=3366698), starting at row 14, to get a sense of the Reasoner-requested predicates that informed the predicates in this proposal.
 
## Approach 1
The proposed predicates below describe important ways genes are related to conditions, as informed by predicates used in one or more Reasoner/Translator KG.  In reality most are shortcuts for the fact that a variant or a product of the gene is related to the condition in the indicated way. These 'shortcuts' are needed because many KSs and KGs don’t represent gene variants or products, and wish only to associate genes directly to a condition to which their variants or products contribute.  
 
```
gene_associated_with_condition   
      gene_mutations*_contribute_to                        
            gene_mutations*_causal_for                
            gene_mutations*_affect_risk_for                
      gene_regulation_correlates_with                        
      gene_activity_contributes_to        
      gene_product_is_therapeutic_target_for             
  
*for labels, instead of 'gene_mutations' consider  'gene_alterations'?, 'gene_variants'?, 'gene_alleles'?
```            

Requirements for many of these predicates come from **Team IR** and their GNBR resource - again for specifics see column G in the spreadsheet [here](https://docs.google.com/spreadsheets/d/1zXitcR1QjHyh6WocukgshSR7IoAVg7MJQG-HNh96Jec/edit#gid=3366698), starting at row 14. **Team Xray** would likely use the generic top level predicate here to map to their 'gene_associated_with' predicate, but may also have a use case for the gene_mutation_contributes_to_condition predicate. **Monarch** would likely also use the gene_mutations_contribute_to predicate as their gene-disease associations are inferred across causal variants.

**In addition to the predicates above**, the following would be created to link things like **variants** or **exposures** to conditions. These would be used in KGs where the variant/allele is represented. Here we propose using relatively generic predicates such as  'causes' instead of 'causes_condition', which are not specific for variant as domain and condition as range. These predicates describe direct causal/correlation relationships - as it is the variant that is indeed doing the causing or correlating.
 
```
contributes_to
     causes
correlated_with
     biomarker_for
affects_risk_for
```
 
 
### Pros of this Approach
- semantically correct  and clear predicates with simple mappings to KG predicates in use by reasoners. 
- predicates provide precise semantics for traversal and reasoning.  
- the gene-condition relations above could all be derivable from the variant-condition associations through inference (e.g. property chains) - provided that the variants are connected to the genes they affect. The would allow interoperation of KGs that do and don’t capture this more normalized/granular pattern. 
 
### Cons of this Approach
- use of separate predicates for genes and variants results in larger number of predicates (but really only three are 'duplicated' in the proposal above).  
 
 ---------------------------
 
An orthogonal consideration for this approach concerns the granularity of the proposed gene-condition predicates - i.e. within this approach of using separate predicates for gene-condition vs variant-condition relationships, perhaps can we merge some predicates where the precision/distinction between them is not required at the level of the minimal spec.

**Comment by mbrush** [comment]
An alternative proposal  that captures the same level of predicate granularity, but allows use of the **same predicates** for 'causal' relationships between genes or variants and disease,  would be only slightly simpler (three fewer predicates).
 
We'd still need the following predicates that are specific to gene-condition associations:
```
gene_associated_with_condition
     gene_regulation_correlates_with                        
     gene_activity_contributes_to_condition        
     gene_product_is_therapeutic_target_for        
 ```
And then the following predicates could be used for causal and correlation relationships linking genes or variants to conditions:
```
causes_or_contributes_to
    causes
    contributes_to
correlates_with
    biomarker_for
affects_risk_for
```
  
One potential issue with this approach is that in gene-disease assertions using predicates that may be used to link genes to diseases in 'causal' associations ( e.g. 'causes', 'contributes_to'), the gene would not be inferred to a "gene_associated_with_condition" -  because these predicates are not descendants of the "genes_associated_with_condition" predicate (which is still needed for some reasoner sources where there is only a generic association asserted).  A slight disconnect that could result in missed inferences/connections. This is not an issue in the first proposal where predicates are created specifically for all  gene-disease associations.

**Comment by mbrush** [comment]
Note for either proposed approach above, the following predicates specific for variant-condition relationships repored by CIViC and other clinical interpretation knowledgebases  would also be required in the min set:
 
```
positive_diagnostic_predictor 
negative_diagnostic_predictor 
positive_prognostic_predictor 
negative_prognostic_predictor 
positive_therapeutic_predictor 
negative_therapeutic_predictor 
```

These are used primarily to describe relationships between somatic variants and conditions that they are specific diagnostic or prognostic markers for, or predict therapeutic response for.

**Comment by kshefchek** [comment]
Here are some of the relations from our gene to disease sources:

EBI developmental disorders
Doc: https://www.clinicalgenome.org/site/assets/files/2757/fitzpatrick_ddg2p.pdf
- both DD and IF
- confirmed
- probable
- possible

Orphanet
- Biomarker tested in
- Candidate gene tested in
- Disease-causing
- Major susceptibility factor in
- Role in the phenotype of
- Modifying germline mutation in

OMIM
- the disorder is placed on the map based on its association with a gene, but the underlying defect is not known.
- the disorder has been placed on the map by linkage; no mutation has been found.
- the molecular basis for the disorder is known; a mutation has been found in the gene.
- a contiguous gene deletion or duplication syndrome, multiple genes are deleted or duplicated causing the phenotype.

**Comment by cmungall** [comment]
@kshefchek - the Orphanet relations there appear different from the ones in ordo

```
62      Orphanet:317349 ! Role in the phenotype of
35      Orphanet:317346 ! Modifying germline mutation in
340     Orphanet:317345 ! Major susceptibility factor in
777     Orphanet:410295 ! Disease-causing germline mutation(s) (loss of function) in
3507    Orphanet:317343 ! Disease-causing germline mutation(s) in
43      Orphanet:465410 ! Biomarker tested in
227     Orphanet:317348 ! Part of a fusion gene in
221     Orphanet:327767 ! Candidate gene tested in
141     Orphanet:410296 ! Disease-causing germline mutation(s) (gain of function) in
156     Orphanet:317344 ! Disease-causing somatic mutation(s) in
```

OMIM - some of these don't seem like relations that would connect a d2g. Are these coming from the OMIM API?

**Comment by nlharris** [comment]
@kshefchek see question for you above!

**Comment by kshefchek** [comment]
the translation tables in dipper would be a good place to review, although OMIM is not represented there, 
https://github.com/monarch-initiative/dipper/blob/master/translationtable/orphanet.yaml
https://github.com/monarch-initiative/dipper/blob/master/translationtable/ebi_g2p.yaml

**Comment by sierra-moxon** [comment]
@kshefchek - I am closing - please feel to reopen if the predicates in the model don't fit for monarch? :)
