### ISSUE TITLE
The  'union_of' class property  seems  redundant

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#524]
The `is_a` class  hierarchy already provides a mechanism to specify set  union, as  the set  of all subclasses associated with a given  parent  class.  Should  this  property be  removed from the Biolink model?

If there is another use case which compels  retention of this property,  then it should be visibly documented in the Biolink Model  guidelines and/or in the BiolinkML SPECIFICATION.

**Comment by cmungall** [comment]
https://w3id.org/biolink/biolinkml/meta/union_of

is_a doesn't specify set union, it's open. given `C1 is_a P, C2 is_a P`, we leave open the possibility of a C3, C4, ...

**Comment by RichardBruskiewich** [comment]
@cmungall (cc:  @deepakunni3)

Although that is a truthful statement,  what one observes in the model in practice is that parent  P  classes with  'union_of` only have children of the listed union set,  thus the `is_a` subtree  reflects the  union set exactly.

Even for the one Biolink Model case that this  *doesn't* happen,  a curious discordance that the parent definition is defined  as a `union_of `some but not all `is_a` children of that class:


```
  gene product:
    is_a: gene or gene product
    description: >-
      The functional molecular product of a single gene. Gene products are either proteins or functional RNA molecules
    union_of:
      - protein
      - RNA product
```

where gene product is actually  the parent for `transcript` not included in the  union_of set (used to also  have the  '`gene product isoform`'  but  this was a `mixin` thus removed as an `is_a`  hierarchy of  `gene project` in the  `mixin`  PR).

Forgetting for the  moment that `transcript` here is operationally  vague, but is somehow synonymous  with `RNA product` but perhaps not quite, in that  `transcript`  may simply mean the RNA molecule, as initially directly transcribed from a gene locus,  or  any of the splice intermediates, but prior to its biological activity being expressed (as a protein coding  message or a bioactive RNA, e.g. with RNAi  activity, or a tRNA or  rRNA  or ???)... in other words, before it becomes a biologically functional 'product'  in the living system.

But, that  begs the question: is 'transcript' a 'gene product'  at all, in the  sense that we use the term 'product'  here?  Do we confound 'role' with 'essence' here?  The material  essence is the Central Dogma:  DNA -> RNA -> Protein (sometime),  whereas, the  'role'   of  product of either the RNA or Protein is  orthogonal.

At the end of the day, unless `union_of` is used in the Biolink Model to somehow  connect distinct siblings of subclasses of  a **parent** class,  my sense is that it it redundant to the practical nature of `is_a`  in  the Biolink Model.

What do I mean by this last statement? Let me partially rewire one of our key examples here:

```
  # Aggregate three distinct 'genomic entity' siblings into a  union set
  macromolecular machine:
    is_a: genomic entity
    union_of:
      - gene
      - gene product
      - macromolecular complex

  # Aggregate two distinct 'genomic entity' siblings into a union set
  gene or gene product:
    is_a: genomic entity
    union_of:
      - gene
      - gene product

  # don't need to specify the union set since all children are by default a part of it
  gene product:
    is_a: genomic entity

  gene:
    is_a: genomic entity

  protein:
    is_a: gene product

  RNA product:
    is_a: gene product

  transcript:
    is_a: genomic entity

  macromolecular complex:
    is_a: genomic entity
```

Note that most categories are children of the broader `genomic entity`  then aggregated into categories that present union sets, as  needed,  or  that some `is_a`  subtrees form the union  sets of interest (without the `union_of` slot being  used),.

I  note that `mixin`  tagging provides a very similar mechanism of tagging (possibly heterogeneous)  sets of Bioiink node class categories together.  In  fact,  in  curating  mixins, I had to decouple `gene product isoform` from   the  `gene product` hierarchy:

```
  gene product isoform:
    # biolink:GeneProductIsoform is most consistently used as a mixin thus it should
    # be declared as such and cannot inherit from the non-mixin biolink:GeneProduct
    #is_a: gene product
    description: >-
      This is an abstract class that can be mixed in with different kinds of gene products to indicate that the gene product is intended to
      represent a specific isoform rather than a canonical or reference or generic product. The designation of canonical or reference may be arbitrary,
      or it may represent the superclass of all isoforms.
    mixin: true
    abstract: true

  protein isoform:
    is_a: protein
    description: >-
      Represents a protein that is a specific isoform of the canonical or reference protein.
    mixins:
      - gene product isoform

  RNA product isoform:
    is_a: RNA product
    description: >-
      Represents a protein that is a specific isoform of the canonical or reference RNA
    mixins:
      - gene product isoform
```

In some sense, `gene product isoform` is a kind of union_of set as well.

Once again, additional  (perhaps confusing?) redundancy in  the  way we encoding the semantics of our model.

**Comment by cmungall** [comment]
go ahead and add union_of for gene product isoform and in cases where the is-a list is closed

good point about transcript vs RNA but that is covered in another ticket

I think we can close this ticket though

**Comment by nlharris** [comment]
closing as per chris's comment
