### ISSUE TITLE
Stricter mode for checking CURIEs and identifying prefixes that are not declared

### ISSUE THREAD

**Issue by deepakunni3** [biolink/biolink-model#527]
Stricter mode for checking CURIEs and identifying prefixes that are not declared.

> after this can we switch to a stricter checking mode such that it's
impossible to introduce new curies with undeclared prefixes rather than
relying on manual inspection?
> 
> would be good to have a prefix report tsv, or a github page per prefix...

**Comment by sierra-moxon** [comment]
this is currently implemented in linkml.
