### ISSUE TITLE
BioLink Classes documentation pages does not resolve anymore

### ISSUE THREAD

**Issue by vemonet** [biolink/biolink-model#528]
**Describe the bug**
The BioLink model documentation website fails to display Classes/Properties/Datatypes pages, e.g. https://biolink.github.io/biolink-model/docs/NamedThing.md 

Error shown on the page:

```
404

File not found
```

**To Reproduce**
Check here: https://biolink.github.io/biolink-model/docs/NamedThing.md

Or any other link at https://biolink.github.io/biolink-model/docs/

**Expected behavior**
The usual documentation page!

**What working group (or team) did this request originate from?**
This bug originated from the XYZ working group.

Note: This is relevant for members of NCATS Translator.

**Additional context**
The files types seems to have changed from `.html` to `.md`, but the old html link does not work neither: https://biolink.github.io/biolink-model/docs/NamedThing.html

**Tag relevant members for discussion**
@deepakunni3

**Comment by deepakunni3** [comment]
Hi @vemonet 

This has to do with a restructuring to the documentation site that happened recently.

The correct URL is https://biolink.github.io/biolink-model/docs/classes/entities/NamedThing.html

**Comment by nlharris** [comment]
if you go to https://biolink.github.io/biolink-model/docs/ (i don't know if that is linked anywhere) the links on that are wrong (or at least the one i tried, NamedThing, 404s)

**Comment by vemonet** [comment]
The restructuring brings a lot of relevant documentations, thanks for this @deepakunni3 (and all the people working on it)!

I don't mind getting an unstable documentation website for a few days then :)

**Comment by deepakunni3** [comment]
Thanks @nlharris for pointing that out.

I reverted the restructuring to ensure that the existing URLs are functional.

@vemonet That means that the old URLs should now be valid. i.e. https://biolink.github.io/biolink-model/docs/NamedThing.md will now resolve.

Apologies for the confusion.
