### ISSUE TITLE
Propagating original (exact|close|related|broad|narrow)_mapping of Association relation and node data types to Biolink Knowledge Graphs

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#544]
We do not propagate, into the resulting knowledge graph, the `skos:*Match` mapping status of original external 3rd party ontology terms mapped onto Biolink categories or predicates. 

For example, if an `Association.relation` from a given knowledge source is not under `exact_mappings` of the given `Association.predicate`  Biolink term, but rather, under `narrow_mappings`, `related_mappings`, etc., users of the annotate graph don't see the nature of that mapping marked in the resulting knowledge graph. 

Does that represent a bit of lost useful information?

**Comment by RichardBruskiewich** [comment]
@cmungall @deepakunni3,

It was suggested that if end users need to know the nature of the mapping, then they could parse the Biolink Model. 

If the `association.relation` term is explicitly mapped into the model, this is fine; however, what if edge normalization only indirectly infers the nature of the mapping. Perhaps a term is likely assumed to be a "narrow_mappings" if not explicitly mapped elsewhere in the Biolink Model.  

However, this involves an extra computational/lookup step on the Biolink Model.  Would embedding the information in the edge at the time of the edge normalization or (KP?) curation mapping, might make more expedient?

How such information is encoded is another question:

Option 1) Separate property, e.g.

```yaml
   Association.predicate:  biolink:interacts_with
   Association.relation: RO:0002103
   Association.mapping: narrow  # |exact|close|related|broad
```

Option 2) embedded 2-tuple


```yaml
   Association.predicate:  biolink:interacts_with
   Association.relation: narrow|RO:0002103 # could use a 'pipe' character to separate

```
or

```yaml
   Association.predicate:  biolink:interacts_with
   Association.mapping: narrow RO:0002103 # or space...
```
or

Option 3) more compressed yet

```yaml
   Association.predicate:  biolink:interacts_with | narrow | RO:0002103

```

**Comment by RichardBruskiewich** [comment]
Resolved by PR https://github.com/biolink/biolink-model/pull/541

**Comment by sierra-moxon** [comment]
In general, I believe 'relation' is being deprecated?  Do we still need this work?  :) I'm closing as it was assigned out to Deepak, but please feel free to reopen if this applies more broadly to properties other than relation?
