### ISSUE TITLE
New predicate proposals for Translator Min Predicate Set

### ISSUE THREAD

**Issue by mbrush** [biolink/biolink-model#55]
Alignment of additional knowledge sources (beyond the original 5 reasoner KGs that informed the initial iteration of the ~40 predicate set [here](https://docs.google.com/spreadsheets/d/1zXitcR1QjHyh6WocukgshSR7IoAVg7MJQG-HNh96Jec/edit#gid=3366698)) has suggested **~20 additional predicates** to add.  
 
We would add these to the biolink-model.yaml file, alongside the initial set of predicates that have already been added.  Here, predicates that are part of the minimal Translator set will be flagged using the 'subset' slot with the value "translator_minimal". This will allow consumers of the yaml to find the set of slots in this standard, and also enable derivation of a biolink-github.io web page that presents the hierarchy of only these predicates (like [this one](https://biolink.github.io/biolink-model/docs/) for blm types).
 
The hierarchy below presents the proposed new predicates (in **bold**) in the context of the hierarchy of predicates in the existing minimal set. Parentheticals explain the meaning and/or source requiring each new  term.

----------------------

- **interacts_with** (grouping term for interaction predicates)
    - directly_interacts_with
        - molecularly_interacts_with
    - **genetically_interacts_with** (gene - gene, for BioGrid via Monarch)
   
- coexists_with
    - **co-localizes_with** (gene/product -gene/product, for QuickGO via Gamma)
    - in_pathway_with
    - in_complex_with
    - in_cell_population_with

- **affects** 
    - regulates
        - positively_regulates
        - negatively_regulates
    - has_affected_sequence_feature 
    - **disrupts**
    - treats
  
- participates_in
    - **input_of**
    - **output_of** 
- has_participant
    - **has_input**
    - **has_output** 
- **overlaps** (new for Monarch - make parent of part of and has part)
    - part_of
    - **has_part**
  
- is_homologous_to
    - **is_parologous_to** (Monarch)
    - **is_orthologous_to** (Monarch)
    - **is_xenologous_to** (Monarch)
- affects risk for
      - prevents
- contributes_to                                
    - causes                        
- **is_correlated_with**
      - has_biomarker
      - **is_biomarker_for**

- expressed_in
- **expresses** (anatomy to gene, inverse of expressed_in, from HetNet via Gamma)

- **occurs_in** (GO/QuickGO)
- **is_located_in** (Wikidata)
- **is_location_of** (SemMedDB)
- **is_model_of** (for Monarch / MODs)   
- **derives_from** (for Monarch)
- **produces** (for WD - between producing entity/agent and the product or material produced)
- **enables** (for Monarch/GO, and WD/GO)
- **same_as** (for WD exact match, and owl same_as in Monarch, etc)
- in_taxon (Monarch, Wikidata)
- has_gene_product
- has_phenotype
- manifestation_of
- treated_by                      
- precedes
- derives_into
- subclass_of
 
---------------------

If there are questions about meaning/utility/name of any of the new proposed predicates, make comment here,  or create new ticket if you anticipate prolonged debate.

Also, note that predicates for gene-disease associations are not included here - and are addressed in the ticket #52.

**Comment by micheldumontier** [comment]
First, I'd suggest we remove the inverses. this will anyways be important for standardization.

here are 

has_affected_sequence_feature
-> why is this needed? why not just use affects?

disrupts
-> is disrupts simply an extreme form of negative regulation?

overlaps
-> what's the use case for overlaps?

causes_or_contributes_to
-> isnt' causes just a stronger form of contributes to?

correlated_with
-> isn't correlated with a parent for contributes to?

biomarker_of
-> what does this exactly mean? is this a kind of correlation, or is it proven causation?

expressed_in / occurs_in
-> seems like there is some kind of relationship between these...

enables
-> is this a kind of "affects"?

in_taxon
-> is this related to expressed_in / occurs_in?

prevents
-> a kind of negative regulation?

treats
-> a kind of negative regulation?
'

**Comment by mbrush** [comment]
Hi all. To keep things moving, I am going to implement several additional predicates proposed above in the BLM. For this pass I will 'resolve' issues raised by Michel's comments as described below - but happy to go back on these decisions if Michel or others reply and  make a case for different outcome. 
 
- **inverses**:  for now will only implement the 'canonical' direction in the min set in blm
- **affected sequence feature:** will drop this predicate  in the minimal set for now
- **disrupts, prevents, and treats:** will not change proposed placement in the hierarchy for these terms to move them under negatively regulates -  as these all have broader usage beyond context of biological regulation by a material/molecular entity
- **overlaps**:  will include as parent of part of and has part - to cover uses of this predicate in Monarch.  
- **causes or contributes to**: will re-org as proposed in my response, with causes a child of contributes to (as causation is just a stronger form of contribution)
- **correlated with:** will not make this a parent of contributes to 
- **expressed in vs occurs in**: no formal relationship between these, as detailed above
- **enables**: will not implement this yes - pending decision in #67
- **in taxon**: no formal relationship applies with the other predicates mentioned (expressed in , occurs in)

Holler if there are concerns with these 'decisions' - as I said, happy to go back and revise the BLM file.  
  
Once implemented, I will create an updated hierarchy that reflects these decisions and paste into this ticket.

**Comment by micheldumontier** [comment]
Hi Matthew,
 Good. let me comment inline:

inverses: for now will only implement the 'canonical' direction in the min set in blm
-> great.
affected sequence feature: will drop this predicate in the minimal set for now
-> excellent
disrupts, prevents, and treats: will not change proposed placement in the hierarchy for these terms to move them under negatively regulates - as these all have broader usage beyond context of biological regulation by a material/molecular entity
-> that's fine, but we should have good definitions for these then.  on first glance, disrupts and treats are effectively the same, unless they are restricted in their range (disrupts any process, treats any disorder/disease).

overlaps: will include as parent of part of and has part - to cover uses of this predicate in Monarch.
-> i'm not convinced of the merit of the inclusion of this predicate. i'd rather it not be included.

causes or contributes to: will re-org as proposed in my response, with causes a child of contributes to (as causation is just a stronger form of contribution)
-> great
correlated with: will not make this a parent of contributes to
-> ok
expressed in vs occurs in: no formal relationship between these, as detailed above
-> ok
enables: will not implement this yes - pending decision in #67
in taxon: no formal relationship applies with the other predicates mentioned (expressed in , occurs in
-> part of is an option, which we use in SIO.

**Comment by mbrush** [comment]
Thanks Michel.  I implemented most of the predicates in this ticket yesterday.  The only deviation from the decisions documented above is that inverses are currently included in the min set. I did not yet remove the non-canonical ones because: (a) it wasn't always clear which direction should be canonical, and (b) a final decision on this approach is pending #57.  Having them included in the min set for now will let folks look at them all together and make final decisions here.  But I anticipate removing many of these once we finalize issues in #57.  I will add list of inverses currently included in the min set there for discussion.
 
w.r.t. definitions for disrupts, prevents, and treat, and predicates in general - I added preliminary definitions/descriptions for all of them to the yaml file, but like other definitions there they are minimal and should be vetted/improved by others.  Crafting defs for the generic SemMedDB predicates, and relating them to more precise RO/SIO/WD predicates, is a particular challenge.

**Comment by nlharris** [comment]
Is there still work to do on this, or can it be closed?

**Comment by deepakunni3** [comment]
This ticket threads a lot of discussions that happened in the past and that are currently happening. I'll defer to @mbrush

**Comment by sierra-moxon** [comment]
@mbrush - I am going to close this issue?  I think much of this work is done already, and if there is outstanding work to do it is covered in a number of other issues linked here (and in both the clinical and predicates working groups).  Please reopen if I missed a critical point here? :)
