### ISSUE TITLE
Core Biolink Model architecture for representing Association Evidence - Provenance - Confidence - Context (EPCC)

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#554]
There seem to be two basic perspectives on how to "skin the cat" for representing knowledge statements and their supporting EPC (in our discussion here, contrasting interpretations and use of the [SEPIO](http://www.obofoundry.org/ontology/sepio.html) model serve as a focal point for presenting this dichotomy):

## Option 1

The first modelling perspective assumes that _every_ `biolink:Association` in a knowledge graph is `fully equivalent` to a single assertion (modelled as a `SEPIO:Assertion`) made by some authoritative source (i.e. every instance of  `biolink:Association` has a _one-to-one_ relationship to a single instance of `SEPIO:Assertion`). 

In the first case, the (possibly extensive) metadata for the assertion (i.e. all the `SEPIO:Assertion` properties) could (should?) be directly embedded into instances of `biolink:Association`, within explicitly enumerated slots and/or `biolink:has_attribute` annotation.  

TRAPI might represent such EPC metadata both directly as top level values in the Knowledge Graph `Edge` json model or within associated `Attribute` records tied to the given edge. The specific placement of this EPC metadata in TRAPI might depend on practical use case needs.  

More extended reporting of such EPC for individual instances of `biolink:Association` could also be represented as a single larger EPC knowledge subgraph hanging off some kind of reification(?) of the given instance of `biolink:Association`, however, such as subgraph would only come from a single authority, i.e. the one who compiled the contents of the single `SEPIO:Assertion` metadata "blob" associated (_one-to-one_) with the specific instance of `biolink:Association`.

Post-processing (essentially, merging) knowledge graphs from diverse sources requires that all equivalent `biolink:Association` a.k.a. `SEPIO:Assertion` entities be compared with one another to establish that associations in two knowledge graphs refer to an equivalent statement of knowledge (i.e. `A - related_to -> B`, with whatever _caveats_) even if the variations assertions of that knowledge may disagree about the truth value of the statement, with varying degrees of confidence.  There is also the question about how one would best represent such a consolidation of such distinct knowledge graphs into one merged graph.

## Option 2

In the second case, the (possibly extensive) metadata for the assertion (i.e. all the `SEPIO:Assertion` properties) would be reported in a distinct Biolink-like knowledge subgraph, but not embedded directly in the various `biolink:Association` edges of the knowledge graph being published.  

TRAPI might represent such EPC subgraphs from a query as `Attribute` records tied to the exported instances of Knowledge Graph `Edge` or as distinct EPC subgraphs exported alongside `Edge`, with appropriate TRAPI `EdgeBinding` mappings.  Perhaps one could consider extending the TRAPI EdgeBinding data schema (or introduce a parallel hybrid component, not sure what works best here) which can link a given edge binding with its specific EPCC assertion metadata.

If `biolink:Association` is a suitably qualified independent knowledge statement, it may be globally indexable across knowledge graphs, hence, the task global merging of knowledge graphs asserting comparable statements of knowledge, and the representation of the consolidated knowledge graph itself, may be simplified since the second perspective  _a priori_ assumes (and attempts to model) the use case of `many-to-many` relationships between knowledge statements as `biolink:Association` edges and (possibly multiple) EPC assertions as SEPIO:Assertions supporting such edges.

Another subtlety here might be that in the second modelling perspective, the `SEPIO:Assertion` model might not actually directly represent the specific subject-predicate-object plus qualifier contents of the `biolink:Association` since a given  `SEPIO:Assertion` may speak, with differing (or conditional) confidence, about the truth value of multiple instances of `biolink:Association`. 

An example of such a situation might be a result from mouse model organism experiments with a human gene ortholog, which might support two taxon-specific (one mouse, one human) instances of `biolink:Association`, with each supported by multiple alternate instances of SEPIO:Assertion generated by alternative experimental approaches (characterised and/or correlated by multiple underlying `SEPIO:LineOfEvidence`, `SEPIO:EvidenceItem` and `SEPIO:Method`, etc.).

**Comment by RichardBruskiewich** [comment]
After today's Biolink Model discussion with you, Deepak and Matt, we've decided that all `biolink:Association` entities are in fact, to be taken as instances of author-specific knowledge `SEPIO:Assertion` with a one-on-one relationship to a specific body of EPC annotation. The Biolink Model will be designed accordingly.

Corresponding  `biolink:Association` instances taken as instances of `SEPIO:Proposition` can be created with one or more `SEPIO:Assertion` level entities as their EPC support.  Such a propositional association will have some additional confidence/probabality semantic that relates to the truth value of the Proposition based on the aggregation of the confidence/probability scores of the underlying SEPIO:Assertion associations. 

How we specifically represent this duality within the Biolink Model remains to be further clarified.

**Comment by mbrush** [comment]
@RichardBruskiewich, my understanding of our decision on the call today is that we would not introduce the Proposition level artifact at all into the Biolink model or data.  In cases where we want to aggregate to Assertions of the same underlying fact/proposition in order to capture a combined confidence score that considers the respective confidences of both assertions, we would create another Association representing a third assertion, and indicate that is based on the two existing Associations as its evidence. We could then attach the combined confidence score to this new association/assertion.  

This woudl mean that the notion of a 'propositional association' is not something we would represent explicitly in the model or data.  All associations would be assertional.  tagging @cmungall in case he wants to confirm or reject my interpretation.

**Comment by RichardBruskiewich** [comment]
Hi @mbrush, actually, a careful read of my comments would indicate that we are saying essentially the same thing: that the statement _roles_ of `SEPIO:Assertion` and `SEPIO:Proposition` are _both_ going to be modelled within `biolink:Association` class objects. A `biolink:Association` entity serving as a `SEPIO:Proposition` will simply be, as you say, a new `biolink:Association` 'edge' created with one or more  `biolink:Association` 'edges', which are instances of `SEPIO:Assertion`, serving as the EPC support for the new association.  

My modelling comments simply hint that this 'duality' will somehow be reflected somewhere in the `biolink:Association` class design, perhaps mainly in 'confidence score' association slot usage (although there may be other slots to point to as well, not sure).

BTW, I'm having trouble deciding whether or not `SEPIO:Proposition` is in `exact_mappings`, `broad_mappings` or 'narrow_mappings` conceptually, relative to `SEPIO:Assertion`.
