### ISSUE TITLE
We have both FB and FlyBase

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#557]

**Comment by nlharris** [comment]
"bug" seems like the right label here🦟
(i can't believe there's not a fly emoji--even just a regular housefly, not a fruitfly)

**Comment by RichardBruskiewich** [comment]
Flybase namespaces are a bit odd. Prerogative of the pioneering esoteric fly community,  I  guess?

As best as I can figure,  there are different opinions about prefixes. Although  the  prefix 'FB' is somehow  'canonical' to FlyBase, it also seems that Flybase partitions its namespace (with  multiple prefixesa cross multiple related URIs),   i.e.

```
   'FBcv' :  ''
   'FBgg':  ''
   'FBpp':  ''

etc.
```

In some cases, the various partitions are rather reflected  in the object identifiers specific to each namespace, thus blurring the  boundary between the  URI and local identifier.

I'll explore the options here and issue PR for what I sense will  work best in the Biolink Model  context.

**Comment by RichardBruskiewich** [comment]
Resolved  by  PR  https://github.com/biolink/biolink-model/pull/593.
