### ISSUE TITLE
Proposed label changes for a few Translator min predicates

### ISSUE THREAD

**Issue by mbrush** [biolink/biolink-model#56]
Proposing a few minor changes to labels used for min predicates - mainly to maintain internal consistency of naming principles and assure clear distinction between terms as new predicates get added.  And in some cases simply shorten/simplify labels where feasible.

1. directly_interacts_with -> physically_interacts_with (to better distinguish from its new sibling ‘genetically_interacts_with')
2. has_affected_sequence_feature -> affects_sequence_feature (a bit cleaner with shorter label) . . . or just eliminate this and use the more generic 'affects' predicate for these edges)

**Comment by nlharris** [comment]
Did this get resolved?

**Comment by sierra-moxon** [comment]
I see both @mbrush's suggestions in the model, so I am closing as done. :)
