### ISSUE TITLE
Subclass of biolink:treats for "approved to treat"

### ISSUE THREAD

**Issue by saramsey** [biolink/biolink-model#561]
**Is your feature request related to a problem? Please describe.**

Yes, we have edges in RTX KG2 that derive from drug/disease REPODB assertions that have 
the source relation `REPODB:clinically_tested_approved_unknown_phase`.
We also have edges in RTX KG2 that derive from drug/disease REPODB assertions like
`clinically_tested_withdrawn_phase_1` (and similar), which are useful and interesting, but 
not as strong from a prediction standpoint as knowing that the a drug/disease pair has
`REPODB:clinically_tested_approved_unknown_phase`. Currently, these are all mapped to `biolink:treats`. 

**Describe the solution you'd like**
Our team is really desiring a subclass that specifically indicates that the
drug is *approved* to treat the disease, like `biolink:approved_to_treat` or whatever.

**What working group (or team) did this request originate from?**
The need for this change originated from Team Expander Agent.

Note: This is relevant for members of NCATS Translator.

**Additional context**

**Tag relevant members for discussion**

CC: @RichardBruskiewich

**Comment by webyrd** [comment]
@saramsey This would be useful to the Unsecret Agent reasoner.  We currently use a notion of a "safe" drug, based partly on predicates in REPODB via RTX KG2.  `biolink:approved_to_treat` would be convenient in these cases.

**Comment by RichardBruskiewich** [comment]
@webyrd @saramsey:  see PR  https://github.com/biolink/biolink-model/pull/591 for an effort to resolve this issue.
