### ISSUE TITLE
Where do we officially document, with indexing, Biolink modelling for specific scientific use cases?

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#568]
Our primary Biolink Model documentation is extremely helpful, but we (yet) seem to have a systematic repository of examples of using the Biolink Model for specific scientific use cases.

This came to mind while I was thinking about PR https://github.com/biolink/biolink-model/pull/565 about synthetic lethality and realising that the model templates of another PR https://github.com/biolink/biolink-model/pull/494 might in fact be a suitable framework within which to model synthetic lethality. 

The challenge here is that it is not obvious to me where we might best document such possible "best practices" exemplars to scientific knowledge representation use cases. Simply embedding such documentation in the biolink-model.yaml file itself is not likely to be optimal unless we have some kind of automatic way of harvesting such examples and adding a suitable rendering of those examples on the Biolink Model (web) documentation (a bit like OpenAPI has examples which can be used to self-document an API).

There are probably several diverse PR's that were merged that represent interesting scientific "best practices" usecases to document (e.g. gene expression PR https://github.com/biolink/biolink-model/pull/349) plus perhaps other relevant documentation issues (e.g. https://github.com/biolink/biolink-model/issues/566). Simply leaving these in Github to eventually fade into the cemetery of "closed issues" doesn't seem like a good idea.

A structured web site ("Git" README.md, "ReadTheDocs", "Wiki" or equivalent) might be a good start, as would the Biolink paper we're trying to get out, but I suspect, something a bit more formal might best support the model in the longer term.

**Comment by sierra-moxon** [comment]
- perhaps a separate page in the repo that describes "lessons learned" or "best practices."
- better capture how curation of this model happens and what decisions are made at which points (ie: when to use a mixin vs. a predicate).

**Comment by sierra-moxon** [comment]
I took a stab at this in guidelines/association-examples-with-qualifiers.yaml
even better would be to have some tests that ran against these examples, but this is our first pass.
