### ISSUE TITLE
Inverse predicates (and their use in Translator KGs)

### ISSUE THREAD

**Issue by mbrush** [biolink/biolink-model#57]
Different knowledge sources often assert associations in different directions.  For example, the gene _expressed_in_ anatomy, vs anatomy _expresses_ gene. 

On the 4-30 KG Standardization call, it was proposed that rather than enforcing such associations to always be made in one direction in KGs, such that only a single predicate is needed, we would allow assertion in either direction, and create the inverse predicates.  A _has_inverse_ slot  in the biolink model will be used to indicate inverse predicates, and allow normalization to one direction when required.  

The convention here will be to add the _inverse_of_ statement in the blm only on the predicate representing the 'canonical' direction (which will need to be decided for each such pair of predicates. In this way we mark the canonical direction that is preferred for normalization.

Looking for feedback in this proposal before it gets implemented in the biolink-model.yaml file.

**Comment by cbizon** [comment]
If this way of handling inverses is standard or common in the ontology world, then I'm fine with it.  That said, I don't like the implicitness of whether the predicate with the inverse_of is the canonical one or the noncanonical one.  I'd rather that it was somehow more explicit than that.  FWIW, if I saw inverse_of X, I would think that the model is trying to tell me that the concept with the inverse_of property is defined as the inverse_of the other property, and therefore the other property is the canonical one.

**Comment by cmungall** [comment]
How about this, we already need a way of marking the minimal list. Let's just call this the `translator_minimal` set of elements, and tag all of these. This will include only canonical directions in the case of inverse pairs

**Comment by cbizon** [comment]
I like that.

**Comment by mbrush** [comment]
@cbizon I agree about the implicit nature of the initial proposal.

@cmungall In some cases there are Reasoner KGs or Translator sources that natively assert the same thing in opposite directions.  For example the Xray and Monarch make gene expression assertions as [gene] - expressed_in - [anatomy], while knowledge sources such as HETNET that Gamma is ingesting assert [anatomy] - expresses - [gene].  There are other examples like this for things like biomarker assertions (biomarker_for vs has_biomarker).

If we choose to only include one of these pairs of inverses in the minimal set, then a simple transform would need to be performed on KGs/sources asserting in the opposite direction to comply, correct?  

This is likely to come up in many other cases in the future - so want to be sure we realize this and are ok with enforcing canonical directionality to be compliant.

**Comment by mbrush** [comment]
Documenting the pairs of inverse predicates currently in the TKG minimal set. The proposal above is to include in the minimal set only the one considered 'canonical' for each pair.  If we do this, we should decide which one that is for each of the pairs below - and generally, what are criteria for selecting the canonical direction.
 
- treats, treated by
- is biomarker for, has biomarker
- expresses, expressed in
- is location of, is located in
- part of, has part
- participates in, has participant
- derives from, derives into
 
Note that each of these inverses is included because there is at least one source/KG that asserts these relationships in each direction. Eliminating one of these from a given pair would require the KG using it to refine their model to reverse the direction of the assertion.

**Comment by cbizon** [comment]
One annoyance that I've run into with direction: we get a relation from a service, and we want to put it on our edge, as well as the relation from biolink model that best maps to the relation we got from the service.  So our edge should have the standard relation on it, and then also the (often more specific) relation from the service.  If only one of the two directions is in the minimal set, and it is in the opposite direction from whatever comes from the service, then this gets challenging.

**Comment by cmungall** [comment]
I'm closing this, subsumed by #440
