### ISSUE TITLE
Deprecate the 'iri' slot, add a 'url' slot?

### ISSUE THREAD

**Issue by mbrush** [biolink/biolink-model#572]
Discussed this with Deepak and Richard today, and it seems that the *iri* slot (currently owned by Entity) is a legacy slot that is meant to capture the expansion of the curie in the *id* slot.   We agreed that this *iri* slot is not particularly useful, as the expanded iri is easily derivable form the curie + prefix mappings in the context.  And the slot doesn’t seem to be used anywhere.   Proposing we deprecate it.
 
What may be more useful on the Entity is a *url* slot that holds urls of website/resources that represent or provide information about the Entity.  TRAPI folks have a use case for this in their Attribute object. Proposing we add a *url* slot to the Entity class for this purpose. 

Thoughts @RichardBruskiewich @deepakunni3 @cmungall

**Comment by cmungall** [comment]
> Discussed this with Deepak and Richard today, and it seems that the iri slot (currently owned by Entity) is a legacy slot that is meant to capture the expansion of the curie in the id slot. We agreed that this iri slot is not particularly useful, as the expanded iri is easily derivable form the curie + prefix mappings in the context. And the slot doesn’t seem to be used anywhere. Proposing we deprecate it.

OK. It would necessarily be bad to keep this around provided the relationship is clear. But probably simplest to deprecate.

> What may be more useful on the Entity is a url slot that holds urls of website/resources that represent or provide information about the Entity. TRAPI folks have a use case for this in their Attribute object. Proposing we add a url slot to the Entity class for this purpose.Thoughts @RichardBruskiewich @deepakunni3 @cmungall

No strong opinions. On the one hand this could be done externally using a resolver system. This could be a separate json-ld context for resolution purposes. cc @kshefchek we were discussing this in the context of the monarch curie mappings

But I can see how it's convenient to treat as a property of the node, so am OK with adding it

 - I might prefer a more explicit property name, e.g. primary_web_url
 - Document how this is a derived field, and provide some guidance for how it would be derived. Would there be a priority order of providers? How would we rank say id.org vs obo?
 - check if there are any use cases for >1 provider. E.g. what do we do for INSDC IDs?
 - maybe this is better done as a reified annotation, we can have multiple URLs, we can annotate each one with priority or context for its usage, provenance. May seem OTT but worth doing right.

**Comment by RichardBruskiewich** [comment]
Resolving this by https://github.com/biolink/biolink-model/pull/573. 

Initial commit there only took @mbrush proposal into account, but clearly, a further iteration may be needed based on @cmungall feedback above.

BTW, Chris, this change of slot name is largely motivated by the ongoing efforts oo align Biolink Model Attribute class and TRAPI Attribute schema `url` property, with one another. 

I suspect that we won't really consider the field derived (like the IRI definition says) rather, this would be curated data on the KP end of things.

**Comment by mbrush** [comment]
> I suspect that we won't really consider the field derived (like the IRI definition says) rather, this would be curated data on the KP end of things.

@cmungall @RichardBruskiewich This was my understanding/intention as well.  The _url_ field would NOT merely represent the expansion of the curie for the entity.  It would be able to hold 0..m addresses of web sites/resources that represent or describe the entity.  The data creator could include any url they felt useful provided consumers with relevant information.

**Comment by saramsey** [comment]
I favor making the `url` (or `iri` or whatever it is called) slot *optional*, as it can in principle be obtained from the CURIE provided that a suitable CURIE prefix to base URI mapping is available. On the other hand, I think it is good to standardize the name of the slot for providers that *want* to provide the URI. There could well be use cases where we want the server-side to expand to get the URI and realize it as a node property, so that front-end (i.e., in-browser) code does not have to.

**Comment by RichardBruskiewich** [comment]
> I favor making the `url` (or `iri` or whatever it is called) slot _optional_, 

Hi @saramsey ..that's actually the  default for all  slots unless  they a re  marked `required:  true`

**Comment by RichardBruskiewich** [comment]
Colleagues -  @cmungall, @mbrush,  @saramsey (and  @deepakunni3) -  I  wish to point out that although `iri`  was injected as a slot of `biolink:Entity`, in fact, I  sense that the original  use case which inspired @mbrush to  post this issue  may have been alignment  of Biolink Model with the TRAPI  Attribute  schema, which currently has a JSON property `url` to hold  a web reference to the `attribute.value`.

We're  really talking less here about the expansion of a node or  edge `id` CURIE of a  node  than  the notion of adding (one or more) web references as web documentation for a concept (node) or relationship (edge).

For this use  case,  I  do wonder whether or not it is really necessary to embed `primary  web url` as a dedicated slot within the  abstract `entity` parent of `biolink:NamedThing`  and   `biolink:Association`.  

Would  it rather suffice to  use  keep  the  "url"  slot/property in  the  Attribute  (TRAPI) schema /  (Biolink) class, thus automatically  providing  the  facility for (@saramsey) optional  use of a (@cmungall ) one-to-many  'reified'  annotation documented  with  other  value  metadata  such as provenance ("source")?

**Comment by RichardBruskiewich** [comment]
See PR  https://github.com/biolink/biolink-model/pull/573 for an attempted resolution of this issue.

**Comment by saramsey** [comment]
So `iri` is being changed to `url`, is that correct?

**Comment by saramsey** [comment]
If this change is indeed happening, in what version of Biolink will it be rolled out? It is (obviously) a breaking change since we are using `iri` in the RTX-KG2 code-base. The change is not *too* hard from a coding standpoint, but it will require a new KG2 build (which takes a week, plus or minus) and careful coordination within the Expander Agent team to make sure that nothing breaks downstream since there are now various channels through which RTX-KG2 is used (TRAPI KP API, PloverDB, export to MediKanren, etc.).

**Comment by saramsey** [comment]
And will the new `url` slot have the same semantics as the old `iri` slot?  I mean, I know it will be a URI (that's obvious), but is it still supposed to contain URI that results from expanding the CURIE from the entity's `id` slot?

**Comment by saramsey** [comment]
Tagging @sierra-moxon and @RichardBruskiewich

**Comment by sierra-moxon** [comment]
Thanks for the details here @saramsey.  No, I would not suggest us taking this change into the model.  I was triaging PRs and this ticket was closed _before_ the PR went in.  I am leaving the ticket open (so if we need to do this later its still something to think about), but I've closed the PR as 'won't do' so we don't get confused here (clearly still confusing - I'm sorry about that :( ).

**Comment by saramsey** [comment]
Ah, OK, thanks.

**Comment by sierra-moxon** [comment]
from my comment on the PR: @RichardBruskiewich - I think I should close this PR? The original concerns from Matt (probably) are addressed by the infores and EPC work in the mix (and cover a slightly different use case than a simple IRI). Please, of course, reopen if I summarized incorrectly.

**Comment by noelmcloughlin** [comment]
I was wondering if `url` should be alias for `iri` based on goals of this WG: https://url.spec.whatwg.org/#goals 

> Standardize on the term URL. URI and IRI are just confusing. In practice a single algorithm is used for both so keeping them distinct is not helping anyone. URL also easily wins the search result popularity contest. 

An alias is non-breaking model change.
