### ISSUE TITLE
Some biological processes are 'pathological'

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#575]
A biological process like "metastasis" is classified as a descendant of `biological process` in NCIT (NCIT:C19151) and EFO (EFO:0009708). The NCIT ontology path to metastasis is deeper than that in EFO, but both have a similar intermediate node `pathological process` just under `biological process`. Perhaps the creation of a new subclass to `biological process` is merited here?

**Comment by saramsey** [comment]
My layperson's $0.02:  some kind of class like `pathological process` would be quite useful. We would definitely use it in KG2.

**Comment by RichardBruskiewich** [comment]
Fixed by  PR  https://github.com/biolink/biolink-model/pull/576
