### ISSUE TITLE
Concrete class like `activity`

### ISSUE THREAD

**Issue by saramsey** [biolink/biolink-model#578]
**Is your feature request related to a problem? Please describe.**
In the current Biolink model, what Biolink `category` should we assign (in our algorithm for assigning Biolink categories) to a UMLS concept with UMLS semantic type `T058` (health care activity), `T062` (research activity), `T057` (occupational activity), or `T052` (activity)? As it stands right now, we only seem to be able to choose `named thing` which represents a loss in precision compared to the UMLS semantic type. We can't choose `activity and behavior` because (I am told) it is an abstract (mixin) class and thus not legal to use as the category for a node in a Biolink knowledge graph.  Somehow `activity` seems more intentional than what would be implied by `phenomenon`, so I am not sure that `phenomenon` is an ideal choice either. 

**What working group (or team) did this request originate from?**
Team Expander Agent. We discussed the matter with Richard B. and he suggested that we log an issue here.

**Note:** This is relevant for members of NCATS Translator.

**Describe the solution you'd like**
A concrete class with a name like `activity` that is legal to use as a node `category`, so that we don't have to use `named thing` to represent UMLS concepts that are activities in our KG. 

**Additional information to support this request** (optional)

**Tag relevant members for discussion**
@RichardBruskiewich @cmungall @deepakunni3 @hsolbrig

**Comment by RichardBruskiewich** [comment]
'Activity' `category` added and mapped in  PR https://github.com/biolink/biolink-model/pull/590

**Comment by saramsey** [comment]
Thank you @RichardBruskiewich
