### ISSUE TITLE
literature co-occurence slot

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#58]
We'd like store edges in a knowledge graph indicating that two entities are both mentioned in a particular article (or articles).     Appearing together in the same abstract is interesting, but I don't think it's really appropriate to say that the two entities are "associated" or "interacting", so I'd like a slot that is used specifically for literature co_occurence.

**Comment by mbrush** [comment]
@cmungall I would consider a new relation specific for correlated mentions, which could potentially live under 'correlates_with'.  If we use the parent 'correlated_with' for literature-co-occurrence, we may end up with assertions in our KGs about correlations between entities like chemicals and diseases  where some describe correlation of the actually entities in biological setting, and others that describe correlated occurrence in the literature.  e.g.  HER2 and breast cancer may be correlated biologically, and their mentions in the literature may also be correlated.  We need to be able to distinguish between these cases.

I might propose a correlated_with sub-property to handle the literature co-occurrence - perhaps something like  'mentions_correlated_with'.  Or maybe it doesn't even make to have this be a correlated_with subproperty - as the entities represented by the subject and object of this predicate in a KG (e.g. a variant and disease) don't themselves correlate with each other in the way that the correlated_with predicate is defined (from RO: "A relationship that holds between two entities, where the entities exhibit a statistical dependence relationship. The entities may be statistical variables, or they may be other kinds of entities such as diseases, chemical entities or processes.")

Curious what peoples thoughts are here.

**Comment by nlharris** [comment]
Is this still relevant?

**Comment by sierra-moxon** [comment]
I'm going to assign this to the predicates WG - thanks @nlharris! :)

**Comment by sierra-moxon** [comment]
Right now in the model, @cbizon - we have 'correlated with' (as per @cmungall's proposal above), which specifies namedthing and namedthing as domain/range specifically.  There are also several children of correlated with in the model that might address some of @mbrush's concerns.  I am going to close this case (please definitely reopen if I missed a use case).
