### ISSUE TITLE
biological process and molecular activity

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#59]
BLM contains concepts for "biological process" and "molecular activity".  It also contains entries that are unions of other entries.   Can we add an entry that is "biological process and molecular activity"?  We have found that grouping those two concepts together is useful in building COPs.  The biolink function returning "function" returns both of these types, so it would also be useful in annotating that service.

**Comment by cmungall** [comment]
shall we go with `biological process or activity`?

another option is to make `biological process` the grouping (this is actually in line with BFO terminology) and have a new name for a chain of activities. But this is fenkled a bit by GO which already asserts BP and MF as disjoint, with BPs being multiple MF steps. So I think the explicit disjointness name for the grouping is best

**Comment by cbizon** [comment]
I'm pretty neutral on the name as long as the type is there.  But I guess my default would be to change "molecular activity" to "molecular function" a la GO, mostly since that terminology is already pretty common.  the the union would be "biological process or molecular function".  But again, not a strong preference on my part.
