### ISSUE TITLE
Document how to represent KP specific variables and their metadata using LinkML

### ISSUE THREAD

**Issue by deepakunni3** [biolink/biolink-model#606]
Document how to represent KP specific variables and their metadata using LinkML and related toolchains.

For example: https://github.com/microbiomedata/metadata_converter is used for managing different variables for the NMDC project.

We could use a similar approach for representing ICEES and COHD variables and then import these into Biolink Model.

CC'ing @mbrush @cmungall @RichardBruskiewich @sierra-moxon

**Comment by sierra-moxon** [comment]
- this is a good place for discussion, when more finalized, make a ticket in biolinkml repo as a "feature."

**Comment by sierra-moxon** [comment]
If I understand correctly, this strategy would make adding long lists of variables to the biolink-model easier (automatable)  ie: https://docs.google.com/spreadsheets/d/1ckc37my-L_y7rhX0S4j1aotz1dWRs_bJhhDiUGYnZW4/edit#gid=0

**Comment by sierra-moxon** [comment]
Hi @deepakunni3  - thank you!  I am closing this one in favor of #853 with a couple of links to code that we could tweak to add a specific spreadsheet of supporting data properties to the model.  Please do reopen if I interpreted this incorrectly. :)
