### ISSUE TITLE
Catalog sources of Drug-Gene Product Interaction knowledge

### ISSUE THREAD

**Issue by mbrush** [biolink/biolink-model#607]
This is a thread to discuss documenting knowledge sources and other relevant resources for the chemical-gene product interaction predicate harmonization work.  This may include all sources that provide knowledge about chemical/drug interactions with genes/gene products, which may include a specific mechanism/mode of interaction (e.g. agonist, allosteric inhibitor, blocker, etc.) Note that this is different from, but often related to, knowledge about the mechanism of action by which a Drug - treats - Disease.  

Issue #570 is a **related ticket** that lays out options for modeling a Biolink Association class that will be used to represent this type of knowledge.  The Chemical WG, in collaboration with Biolink/SRA team, will work to define a harmonized set of terms to use in this Association model (likely in the `predicate` slot, but possible in the `relation` slot or a `qualifier` slot if option 2 or 3 in the ticket linked above is chosen) 

I think a first step here is to catalog the external sources of this type of knowledge, including links to relevant documentation of interaction mechanism terms, and what KPs/ARAs do or will provide this data in Translator.  I started a **[Google Doc here](https://docs.google.com/document/d/1BA4D2v2ROvWb68AoBRfBKm1_aTdocxQK7A1WsNega2A/edit#heading=h.4eijx6hq8ghh)** with a possible template and examples here - t.b.d. if/where we want our final catalog to live (in this ticket, in a gdoc or spreadsheet).  Valdo also assembled a list of interaction mechanism terms form MolePro sources in the [spreadsheet here](https://docs.google.com/spreadsheets/d/1VI2s5YVDwOHiQv7hBWkl12d86yWvm-z_pDJFnDwsoiY/edit#gid=0).

**Comment by nlharris** [comment]
Tagging @vdancik to make sure he saw this.

**Comment by mbrush** [comment]
Closing ticket, as I believe Vlado and the Chemical WG have completed this task in the spreadsheet [here](https://docs.google.com/spreadsheets/d/1VI2s5YVDwOHiQv7hBWkl12d86yWvm-z_pDJFnDwsoiY/edit#gid=0).
