### ISSUE TITLE
add mappings to google data commons vocab

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#608]
Google has a wikidata-like KG called 'data commons': https://datacommons.org/ (despite the name it's more a KG than a data commons).

it seems to have it's own schema, where you can browse instances, e.g
https://datacommons.org/browser/Person

you can see mappings to foaf etc. I think this is schema.org?

They also have some bio nodes and edges

For example, their gene class:

https://datacommons.org/browser/Gene

this would have an obvious mapping to biolink

some of the modeling is a bit odd; e.g. the variant class has a single-valued property for mondo ID:
https://datacommons.org/browser/bio/701505

they also have classes that would map to the association hierarchy, e.g

https://datacommons.org/browser/DiseaseGeneAssociation

**Comment by sierra-moxon** [comment]
- explore data commons 
- understand if the mappings are valid/only map relevant cases.
- not high priority, but easy-ish "starter case"

**Comment by sierra-moxon** [comment]
round about way to find the class list: https://datacommons.org/browser/Class
