### ISSUE TITLE
Continued evolution of the exposure/outcome/cohort models

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#610]
This issue iterates further on clinical model development discussions concerning exposure/outcome/cohort models started in PR https://github.com/biolink/biolink-model/pull/494, following discussions in issue https://github.com/biolink/biolink-model/issues/479.

Resolution of this 'issue' is underway in PR https://github.com/biolink/biolink-model/pull/614.

Some fresh clinical model revisions relate to decisions concerning when to use node properties versus predicated (association) edges (discussed in PR https://github.com/biolink/biolink-model/pull/587 and elsewhere).  

In particular, we have the following 'clinical' node predicates:

- `has drug`
- `has device`
- `has procedure`
- `has receptor`
- `has route`
- `has stressor`

The general rule of thumb now is that node properties should have literal values, but if a node 'property' is another Biolink category class concept, then it should rather be modelled as a full association edge. For this reason, we will start this new clinical iteration by converting the above node properties into predicate slot definitions, then propagate this new design pattern as needed elsewhere in the Biolink Model (e.g. see if any new associations are helpfully defined).

## Ontology for Interventions

In the latest iteration of the model, the nomenclature 'treatment' has been renamed to 'medical intervention' to render the semantics a bit less ambiguous.  There is perhaps a helpful set of [ontology terms for medical interventions](https://www.ebi.ac.uk/ols/ontologies/ero/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FERO_0000347&viewMode=All&siblings=false) we can tap into.

**Comment by sierra-moxon** [comment]
might consider more broadly how we name and define association qualifiers that capture a 'context' in which the core S-P-O triple holds. We have come across use cases for other types of context as well (population context for clinical feature variable associations, experimental context for statistical associations computed from high-throughput biological data). We should consider these and other use cases together to define a consistent and coherent approach.  -- From @mbrush

**Comment by sierra-moxon** [comment]
replaced by : https://github.com/NCATSTranslator/Clinical-Data-Committee-Tracking-Voting/issues/10
