### ISSUE TITLE
Remove 'is ' prefix to slot names

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#615]
Low value prefix word in slots which have pattern "is something of". Remove to leave "something of" slot names.

**Comment by cbizon** [comment]
This would cause a lot of rework in existing databases.  So unless there is a very strong reason, I would leave these alone.

**Comment by RichardBruskiewich** [comment]
Hi @cbizon (cc: @vdancik @mbrush @cmungall),

I completely understand this valid concern. 

This issue arose yesterday during chemistry working group discussions, relating on how to spell various predicates derived from CHEMBL etc 'roles'. Mainly an aesthetic of simplifying nomenclature. We would deprecate the old names for now (but not remove them right away).

That said, I checked the Biolink Model just now and there appear to be two disjoint sets of such existing terms, one new and one old.

- The very new set (merged 6 days ago!) are the chemistry set from Vlado in PR https://github.com/biolink/biolink-model/pull/582:  `biolink:is_metabolite_of`, `biolink:is_active_ingredient_of`, `biolink:is_excipient_of`, ...

- The older set are all the sequence variant slots: `biolink:is_sequence_variant_of` and its descendants. Those predicates may perhaps already be in wider use already.

Thus, there may be a reasonable case for deprecating the very new 'chemistry' terms, to be consistent with the full set of chemistry predicates not yet finalized, but perhaps, leaving the older 'sequence variant' set alone. What do you think?

**Comment by sierra-moxon** [comment]
Assigned as part of triaging cases here, please let us know if this needs broader discussion than chemical working group. :)

**Comment by cbizon** [comment]
IMO, if we're changing predicate names (or e.g. curie prefixes) then those changes need to be given wide (e.g. DM Call) discussion or at least warning.   If we think that's wrong, e.g. that these changes should be localizable, then it may be worth a discussion of why the system is brittle to these changes and see if there are tools that could help.

**Comment by sierra-moxon** [comment]
@RichardBruskiewich - with Chris' comments, I am going to close for now.  We can do our best to exclude 'is' from predicates going forward.  I know there are other tickets for refactoring the variant model a bit, we could address those then (and publicize/request feedback on any remodeling we do there with a wider audience).
