### ISSUE TITLE
Change range of Association.category slot?

### ISSUE THREAD

**Issue by mbrush** [biolink/biolink-model#619]
At present the range of Association.category is 'association'. See 
https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L7223 

I understand this to mean that an Association instance should populate this slot.  But I think the intent is to capture a Biolink class representing the type of Association it is. If this is the case, shouldn't the range of Association.category be ['category type](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L184)'?

**Comment by nlharris** [comment]
(This is a general issue with the biolink model, not EPC-related.)

**Comment by sierra-moxon** [comment]
Closing - ticket done! :)
