### ISSUE TITLE
Look at predicates in example: drug associated with decreased risk of atrial fib

### ISSUE THREAD

**Issue by nlharris** [biolink/biolink-model#625]
Action item from "Fix It" session in Translator Winter Relay:
DM should look at the predicates in this example

### Query from Ryan Roper drug associated with decreased risk of atrial fib (in #fix-it Slack channel)

> Query results:  https://ars.transltr.io/ars/api/messages/36ad42a4-41ec-4182-acbc-7758dd0167c9 
Methodology: divide into two different time periods: medications and diagnosis and second period predicting the outcome using features. 

Ryan Roper (Multiomics Provider) Today at 7:32 AM
A couple queries we'd like to try:
```
{
  "message": {
    "query_graph": {
      "edges": {
        "e00": {
          "subject": "n00",
          "object": "n01",
          "predicate": "biolink:associated_with_decreased_risk_for"
        }
      },
      "nodes": {
        "n00": {
          "category": "biolink:Disease"
        },
        "n01": {
          "category": "biolink:Disease",
          "id": "MONDO:0004981"
        }
      }
    }
  }
}
And:
{
  "message": {
    "query_graph": {
      "edges": {
        "e00": {
          "subject": "n00",
          "object": "n01",
          "predicate": "biolink:associated_with_decreased_risk_for"
        }
      },
      "nodes": {
        "n00": {
          "category": "biolink:Drug"
        },
        "n01": {
          "category": "biolink:Disease",
          "id": "MONDO:0004981"
        }
      }
    }
  }
}
```
8 replies

Ryan Roper (Multiomics Provider)  2 hours ago
Note, based on communications with some ARAs, our clinical risk KP (https://api.bte.ncats.io/v1/smartapi/1bef5ecbb0b9aee90023ce9faa2c8974/query) still needs to be integrated with some ARAs. But, the Disease to Disease query should at least hit improving agent and BTE. Also, at least one group doesn't yet support Disease to Disease queries.
As for the second, I think there are at least one or two groups that don't yet support use of biolink:Drug. We chose that class because it lists RXCUI as a valid curie prefix. But, it seems RXCUI should be a valid curie prefix for ChemicalSubstance as well.

Matt Brush (SRI)  2 hours ago
I don't see a associated_with_decreased_risk_for predicate in Biolink.  I see 'affects_risk_for', and its children 'prevents' and 'predisposes' - which seem close.
:+1:

Ryan Roper (Multiomics Provider)  2 hours ago
A note: I need to fix something in the spec for the Drug-Disease query. So, we can hold off on that query for now.
[Update: Fixed, see comment below. This query should get results now, at least from BTE.] (edited) 

Ryan Roper (Multiomics Provider)  2 hours ago
Yeah, unfortunately that's something we want added to the biolink model. Or something similar. Right now, there's no suitable predicate for our clinical risk KP.

Ryan Roper (Multiomics Provider)  1 hour ago
Okay, I've fixed the spec. The Drug to Disease query now works directly on the clinical risk KP endpoint. Through the ARS, both queries should now return results at least from BTE.

Chris Bizon (SRI, Ranking Agent)  33 minutes ago
Is there not already a predicate about decreasing risk?

Brett Smith imProving Agent  30 minutes ago
This should return results from imProving, but we haven't dealt with biolink:Drug vs biolink:ChemicalSubstance yet

Mark Williams (Link Broker)  24 minutes ago
For increased risk https://ars.transltr.io/ars/api/messages/36ad42a4-41ec-4182-acbc-7758dd0167c9

**Comment by RichardBruskiewich** [comment]
See also the clinical modelling for "exposures" and "outcomes" continuing in issue https://github.com/biolink/biolink-model/issues/610

**Comment by nlharris** [comment]
See also Prediction and risk factors #335

**Comment by jh111** [comment]
Earlier discussion in 335
https://github.com/biolink/biolink-model/issues/335

**Comment by sierra-moxon** [comment]
prevents and predisposes are also options but don't match exactly the intent her.
