### ISSUE TITLE
Add "Mechanism of Action" Biolink Category Class

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#626]
**Problem**

No category that adequately captures the spirit of [NCIT:C54680, Mechanism of Action: The mechanism by which a pharmacologically active substance produces an effect on a living organism or in a biochemical system](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C54680).

**Describe the solution you'd like**

Add a "Mechanism of Action" category plus some supporting biolink:Association types and possibly, predicates, allowing 1) placeholder of Drug -...-> Mechanism of Action -...-> subgraph of descriptive edges (e.g. anatomical site of action, process, molecular targets, etc.)

**Working group (or team) this request originate from:**

Requested by Trung of LinkBrokers during February 2021 Relay.

**Additional context**

- https://bioportal.bioontology.org/ontologies/ATC/ -  "...classification of active ingredients of drugs according to the organ or system on which they act and their therapeutic, pharmacological and chemical properties...."

- people would recognize “antineoplastic” as the MoA (not very specific but it’s a general category (note: **Antineoplastic:** Acting to prevent, inhibit or halt the development of a neoplasm (a tumor). An agent with antineoplastic properties.)

- several  CHEMBL.MECHANISM mapped terms in the Biolink Model but mostly under specific molecular-level categories, i.e. a predicate like biolink:physically_interacts_with

-  "mechanism of action" is a general concept node type, from which one would hang off several qualifying Association edges (e.g. anatomic site of action, process target, chemical reaction, etc.)
    - e.g. apixiban is_a Direct factor Xa (i.e. molecular target) is_a "antithrombotic agent" (general process targeted) is_a Blood and Blood Forming Organ drug (general organ or systemic  or process target)
-  specific to a cell type or cellular process or cell surface receptor, e.g.
     - **Herceptin:** targets HER2 receptors; mechanism? blocks access of the receptor to its ligand, thereby blocking signal transduction promoting cell division?
     - **Paclitaxel:** blocks mitotic spindle formation in cells(?) hence cell division

**Tagged members for discussion**

@vdancik @cbizon @mbrush @cmungall

**Comment by cmungall** [comment]
Great start, but we need to flesh this out more. More example edges.

In particular, I want to know where these MOA nodes are coming from?

The hierarchy here is limited, this seems more like something modeled as a qualifier on an edge or node:
https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C54680

![image](https://user-images.githubusercontent.com/50745/106679432-7e52d680-6571-11eb-84e5-6b29f8b6c661.png)

Would you consider the CHEBI 'role' hierarchy in scope here?

E.g here is your Paclitaxel example in CHEBI

![image](https://user-images.githubusercontent.com/50745/106679749-2a94bd00-6572-11eb-8789-d93e7960b221.png)

We have a project with @choyt called CHIRO that axiomatizes the roles, essentially providing outward links to other nodes, allowing you to shortcut

E..g

 * chebi:Paclitaxel _has-role_ chebi:microtubule-stabilizing agent
 * chebi:microtubule-stabilizing agent _inhibits_ go:mitotic spindle formation

then using a property chain we can eliminate the role middleperson

* chebi:Paclitaxel _inhibits_ go:mitotic spindle formation

I would opt for this direct form of modeling, where we connect directly from the drug to the node of interest, and no role/MOA middleperson

**Comment by choyt** [comment]
I am flattered by the mention, but I am not the choyt you are looking for.

**Comment by choyt** [comment]
Also, I recommend using a strongly-typed hierarchy rather than a class-based polymorphic approach. Composition is more generally extensible than inheritance, and mixins often end up multiplying layers of abstraction without a concomitant increase in clarity.

**Comment by RichardBruskiewich** [comment]
Thanks @cmungall for your feedback about  about removing MOA as a middle node.  In my latest commit https://github.com/biolink/biolink-model/pull/627/commits/d24f79046bad0950b85dc3191d8f4c9730cb0b18 to PR #627,  I've converted "`MechanismOfAction`" into the predicate `mechanism_of_action` which would be used in a simpler `DrugToBiologicalEntityAssociation` which captures the semantics of the situation more directly.

**Comment by cmungall** [comment]
Yes indeed I meant to tag Charles hoyt.. but that is awesome advice anyway!
We are trying to find the right balance between overloading subclass yet
retaing its benefits. In fact we were just discussing the need for
composition pattern for modeling drugs and treatments in our hackathon
today!!

**Comment by vdancik** [comment]
Is DrugToBiologicalEntityAssociation appropriate association? Mechanism of action is also applicable to chemical substances (biochemical probes that are not drugs) and possibly proteins that may act as natural ligands. Maybe MolecularEntityToBiologicalEntityAssociation?

**Comment by caodac** [comment]
Here's an example of a very specific MoA https://www.accessdata.fda.gov/drugsatfda_docs/label/2003/021588lbl.pdf (top of page 2). How would you model something like this?

**Comment by southalln** [comment]
I think there is some reason to distinguish this from the previous discussion of Mechanism of Action https://github.com/biolink/biolink-model/issues/570.  While I think the intent in that issue was to model pharmacology as predicates within Biolink descending from `affects`, here the drug to (typically) protein target relationship connotes additionally that this target engagement is principally responsible for the therapeutic effect of the drug. So while imatinib inhibits many protein kinases, its inhibition of BCR-ABL is why it is a useful AML therapeutic. As a further case to consider, both loperamide (Imodium) and morphine act as opioid-receptor agonists acting on the μ-opioid receptors, and while both induce constipation, only the latter affords pain relief --- so I am not sure if further modeling of mechanism of action including context like tissue of action is required to properly annotate these two MoAs.

**Comment by nlharris** [comment]
What is the status of this?

**Comment by vdancik** [comment]
We have discussed this issue at the chem-info WG call and have agreed that **mechanism of action** should be modelled as a path in a knowledge graph or even as a subgraph in more complex MoA cases. Rather then to have a single node to represent MoA, we propose to have a dedicated attribute, `biolink:mechanism_of_action`, that would indicate which nodes and edges represent given mechanism of action.

**Comment by cmungall** [comment]
node attribute or edge attribute? I assume the latter since the MOA will be
contextual?

**Comment by choyt** [comment]
Amateur here.
@suihuang-ISB made the point that MoAs are often controversial, which could be modeled by a Range of theories. However, I would propose that any piece of knowledge considered controversial by reasonable, knowledgeable people should simply be left out of the graph, rather than being reflected in its schema. How is this currently handled?
