### ISSUE TITLE
Addressing the Concept of Drug Targets

### ISSUE THREAD

**Issue by MarkDWilliams** [biolink/biolink-model#628]
During the Fix It group in the February Relay, the topic of finding drug targets was raised.  There is not currently a biolink association for 'has_target' or 'is_target_of', though there are many more specific relationships (e.g. negatively_regulates, directily_interacts_with, etc).  I am wondering what the best way to represent this type of query is.  I believe the idea of curating related predicates and using a mix-in were raised in response to this question.  Apologies for the brevity of this issue.  I'm happy to answer questions or add clarification, but wanted to get an issue in as at least a placeholder while it's still fresh in my mind from the session. @southalln can likely give more examples/clarity on how "targets" is used in Pharos and elsewhere.

**Comment by nlharris** [comment]
I think this might relate to #626

**Comment by sierra-moxon** [comment]
- if #626 does not handle 'is_target'/'has_target', we could just just add a direct edge and map it directly to NCTS. 
- 626 gives more information, and we might also want a direct predicate/edge.  
- [] create is_target predicate
- [] survey the additional specific relationships (perhaps using chemical WG predicates list).

**Comment by sierra-moxon** [comment]
@MarkDWilliams - did we eventually handle this with the regulates and interacts_with hierarchies of predicates?  I think this can be closed (even without a 'targets' predicate)?  Or, do we still need a "targets" predicate?  We also have mechanism of action association slot.

**Comment by ehinderer** [comment]
This will be relevant to my "drug target landscape" proposal:
 https://github.com/NCATSTranslator/Clinical-Data-Committee-Tracking-Voting/issues/9

**Comment by sierra-moxon** [comment]
we now have has_target predicate.
