### ISSUE TITLE
Should UMLSSC:T046 be mapped to "pathological process"

### ISSUE THREAD

**Issue by saramsey** [biolink/biolink-model#629]
**Question:**
Hi Richard, our team is wondering about the Biolink category that best maps to UMLS semantic type T046 (pathologic function). Currently, T046 is mapped to Biolink category `disease`. We are wondering whether biolink category `pathological process` would be a better fit?

**Comment by saramsey** [comment]
Same goes for UMLS semantic type T037 (injury or poisoning). We are wondering if the Biolink category `pathological process` would be a better fit for that.

**Comment by sierra-moxon** [comment]
@saramsey - thank you for the question, will check into this.  @RichardBruskiewich - do you have the access to the UMLS Thesaurus?

**Comment by saramsey** [comment]
Hello Biolink team, just checking back on this?
