### ISSUE TITLE
Biolink monthly releases following SemVer versioning (major.minor or major.minor.patch)

### ISSUE THREAD

**Issue by nlharris** [biolink/biolink-model#630]
We decided to follow a regular release cycle, we will aim for monthly, but if required we can push out releases more quickly (e.g. if needed for urgent bug fixes). We will sync releases with DM calls: once every 4 weeks we will dedicate a portion of the call to discussing release, summarizing changes, see if objections to going ahead.
We will follow semantic versioning, and improve documentation/SOP for what constitutes major/minor/patch.

Related issues:
versioning #313 
versioning for the KG standard for the Translator project #87
- [x] document release methodology
- [x] latest branch creation 
- [x] add latest branch to release methodology

**Comment by nlharris** [comment]
Each release has change notes: https://github.com/biolink/biolink-model/releases

**Comment by nlharris** [comment]
We will announce releases in advance to all of Translator, and will particularly note if there are any breaking changes.

**Comment by sierra-moxon** [comment]
documentation todos:
- our version of the semantic release methodology
- release process guide, "how to do a release" including who should do what when and when/how we notify folks of a release (and who are the folks to notify).

**Comment by nlharris** [comment]
@deepakunni3 will be doing a release today (1.6.0) and then will pass the baton to @sierra-moxon!

**Comment by nlharris** [comment]
See #686 for plan to make "latest" branch persistent.

Also, we are revisiting our process of broadcasting upcoming release changes to the consortium. More details soon.
