### ISSUE TITLE
Document strategy for selective conflation (e.g. gene vs protein) 

### ISSUE THREAD

**Issue by nlharris** [biolink/biolink-model#633]
(with Arch)

Fix-it sessions revealed cases where we may want more selective control over conflation of categories - e.g the ability to treat a disease and a phenotypic feature as equivalent for certain purposes, or a gene and a protein, or even a virus and a disease (e.g. SARS-CoV-2). We would like to maintain distinctions in the model but allow for conflation, both at the time of knowledge provision (e.g. NLP provider may wish to conflate on species or gene-vs-protein), at query time, and also at ‘join time’. Some of this can be encoded in the model, e.g. that reference proteins can be proxies for genes. This is also tied to the idea of selective conflation at the level of individual nodes - e.g. two nodes representing chemicals that are in some isomery relationship, e.g. stereoisomers, may be conflatable for certain purposes. The DM group will also coordinate with the TrAPI group on implementing ‘controls’ for selective conflation.

See @cmungall's thoughts on flexible conflation [here](https://docs.google.com/presentation/d/1Gro8TeK84zoTP3FiP-23LKL19YrTW9yg9kN9G2zl1_0/edit) and @mikebada's extension classes here: Biolink representation for class conflation #638

**Comment by sierra-moxon** [comment]
- different groups annotated different.  
- query in ways that support either/or instead of half of it.
- documentation of the strategy would be helpful.
- grouping classes in the model should be a deliverable (we do this for disease in the model - phenotype as a disease, 'disease or phenotypic feature' allows for the querying of both children, disease and phenotype).
- not enough to have it in the model - need documents to help explain it (ie: asked for search at the gene level, need to know to use the ancestor etc.).

**Comment by sierra-moxon** [comment]
documentation todos:
- our version of the semantic release methodology
- release process guide, "how to do a release" including who should do what when and when/how we notify folks of a release (and who are the folks to notify).

**Comment by sierra-moxon** [comment]
There will be a fixit session at the May relay to cover this topic.

**Comment by sierra-moxon** [comment]
Decision in 5/20/2021 DM call: establish a list of conflated entities via the property chains that they participate in.  This list would live in a TSV in the biolink-model repository.

**Comment by sierra-moxon** [comment]
From DM 7/8/2021 - reference proteins and genes will be aggressively conflated via the node normalizer.  
https://docs.google.com/presentation/d/1Gro8TeK84zoTP3FiP-23LKL19YrTW9yg9kN9G2zl1_0/edit

**Comment by sierra-moxon** [comment]
closing for now with the strategy in place for implementation in the node normalizer
