### ISSUE TITLE
Document deductive inference rules

### ISSUE THREAD

**Issue by nlharris** [biolink/biolink-model#634]
The Arch group is concerned with the question of where in the stack inferences happen. The DM group is concerned with specifying the semantics of classes and predicates in the model. This includes ensuring that declarations are complete (for example, that ‘interacts with’ is declared symmetric, and that ‘part of’ is transitive) and also for specifying the semantics of these characteristics. As an example, there was previously a question in which some groups were assuming that the symmetry property was inherited over the predicate hierarchy, when in fact this is not the case. The DM group will coordinate with the Arch group on the testing framework (e.g. if a query for A-interacts-with-B should return same results as B-interacts-with-A)

Linked discussion: Deductions in Translator #25

**Comment by sierra-moxon** [comment]
- Architecture team (@cbizon) has started a discussion on this topic here: https://github.com/NCATSTranslator/TranslatorArchitecture/discussions/25

**Comment by sierra-moxon** [comment]
https://github.com/NCATSTranslator/TranslatorArchitecture/pull/35 - PR submitted to document inverse reasoning.
https://github.com/NCATSTranslator/TranslatorArchitecture/pull/28 - PR accepted to document reasoning in general.
fixit session from Chris B in the Spring Relay will go further to help identify tooling needs to help KPs do reasoning.
