### ISSUE TITLE
Integrate work from EPC

### ISSUE THREAD

**Issue by nlharris** [biolink/biolink-model#635]
Issues include:
- [x] Include sufficient provenance info for tests (knowing which KPs are hit)
- [x] Align Biolink edge properties and TrAPI attribute model #583

**Comment by sierra-moxon** [comment]
- @mbrush and DM team met to discuss a simple key:value approach to EPC meta data, will present on March 11 to the TrAPI call.

**Comment by nlharris** [comment]
is this still in progress?
