### ISSUE TITLE
Include sufficient provenance info for tests

### ISSUE THREAD

**Issue by nlharris** [biolink/biolink-model#637]
One request that came out of the Winter Relay was to be able to track the provenance on which KPs are hit (for certain queries/questions) to better understand how and from where the answer was provided.

While some of this falls within the purview of EPC discussions, the requirement for tracking such provenance needs to be made front and center.

This information can be represented in one of two ways:
- A node/edge property defined in the model that is capable of representing KPs/sources from which a particular assertion is provided. We could always conflate `provided_by` or have something that is dedicated for this purpose
- Incorporate this requirement in the EPC discussions and ensure that such provenance is tracked via the EPC model

The benefit of the latter approach is a more expressive style of representation for provenance.

**Comment by mbrush** [comment]
Several working groups  (Reasoner API, Data Modeling, EPC) have discussed requirements and modeling proposals for tracking the “sources” of knowledge expressed in Associations/Edges.  The initial goal will be to support implementation of a common, simple model across different Translator formats (e.g. TRAPI Attributes, KGX, property graphs like neo4j).  

I created the [Google doc here](https://docs.google.com/document/d/1hO8SU14v0-6LCBjTn_MalLuCQgQ3YhNkMOJ_bXbX7rY) to summarize some ideas to come out of these discussions. I think at this stage a gdoc will provide easiest way to capture comments/contributions.

**Comment by sierra-moxon** [comment]
This has been done and implemented by participating members.
