### ISSUE TITLE
Biolink representation for class conflation

### ISSUE THREAD

**Issue by mikebada** [biolink/biolink-model#638]
We recently discussed the idea of implementing some sort of facility for Biolink for flexibly creating classes or other kinds of representations for conflations of similar/related concepts. This reminded me of something we've already put a lot of work into for our extensive efforts in creating manual, gold-standard semantic markup of biomedical text.

More specifically, we've created a large number of what we call extension classes in that we've created them as extensions of the Open Biomedical Ontologies (OBOs) whose classes we use to annotate our corpus. These extension classes were created for various reasons: Some were created to unify classes from different ontologies that are semantically equivalent (or essentially so, even if they have different natural-language definitions) so that there wouldn't be multiple concept annotations for the same text spans (which are somewhat difficult to work with) if disparate annotation sets for disparate ontologies were aggregated.  (This also adds to the semantic integration of the ontologies.)  Others were created to unify multiple classes for cases in which they were difficult to consistently use for text annotation; that is, we found it difficult to reliably differentiate among the concepts for observed textual mentions. Others were created to represent classes different from but directly corresponding to proper OBO classes so as to use classes that are more straightforward for textual annotation.  (For example, we programmatically created a whole parallel hierarchy of extension classes directly corresponding to the GO Molecular Function subontology that instead represent the material bearers of molecular functions, e.g., kinase, based on the proper GO Molecular Function classes, e.g., kinase activity, as we've observed many more textual mentions of the former than the latter.)

A more thorough overview of our extension classes has been written up: 
[Facilitating Concept Annotation of Biomedical Text with Ontology Extension Classes.pdf](https://github.com/biolink/biolink-model/files/5967408/Facilitating.Concept.Annotation.of.Biomedical.Text.with.Ontology.Extension.Classes.pdf)

(This was accepted into a conference workshop whose papers ended up not being published, so we're planning on resubmitting it elsewhere.)

The complete set of extension classes that are currently used can be examined in the following OWL ontology:
[CRAFT_aggregate_OWL_ontology.owl.zip](https://github.com/biolink/biolink-model/files/5967434/CRAFT_aggregate_OWL_ontology.owl.zip)

The manually created extension classes are currently just direct subclasses of grouping classes for each of the OBOs we're using, e.g., CHEBI extension classes, CL extension classes.  (An extension class can and often is an extension of more than ontology, in which it would be a subclass of each of the corresponding grouping classes.)  The programmatically generated parallel hierarchy of GO Molecular Function classes has GO_EXT:0003674 (GO_EXT:'bearer of molecular_function') as its root. The logical definitions of the manually created extension classes can be seen in the form of Manchester OWL syntax in their definition fields (and the text for which the classes are used in their comment fields).  (However, we haven't yet formally implemented these definitions, as until recently we were using the .obo versions of these ontologies, and some of the semantic constructs we've used aren't representable in OBO syntax.)  I think the ones that are simply unions of named classes (e.g, X or Y, X or Y or Z) are the most relevant to consider for this discussion.  

Upon more reflection, though these extension classes have been extremely useful for our text annotation work, I don't think it's necessary to create corresponding Biolink class conflations for most/all of them.  For one thing, I wouldn't think that the concepts mentioned in assertions that we mine have to exactly correspond to their textual mentions for Translator users, e.g., kinase vs. kinase activity, post-translational processes vs. the resulting post-translational modifications.  On the other hand, for the many occurrences of the same or similar concepts among multiple ontologies, though we don't need class conflations, it'd still be useful to aggregate this overlapping semantic content.  However, this could be done in other ways, e.g., query expansion, along the lines of what Melissa Haendel has suggested.

**Comment by cbizon** [comment]
Agree that Query Expansion and Property Chains are important here.

I also wanted to mention an approach that I think Chris M suggested on one of the relay calls: Right now node normalization handles equivalences for identifiers.  Maybe it could be parameterized by various conflations.  So if you do nothing it keeps genes and proteins separate, but if you pass it the "genes=proteins" argument, it merges those two concepts.

**Comment by sierra-moxon** [comment]
Hi @cbizon :) -
Which software component would pass the conflation parameter?  Maybe via a TrAPI query parameter? 

@mikebada @cmungall @deepakunni3 - would an action item here be that we establish the conflation groups that would be most helpful for translator?  

@nlharris - this seems like a good topic for a data modeling call?

**Comment by nlharris** [comment]
> @nlharris - this seems like a good topic for a data modeling call?

Sure--let me know when you think would be a good time to add it to the DM agenda (or feel free to add it to the agenda yourself!).

**Comment by sierra-moxon** [comment]
- will put this on the DM agenda (as time permits)
updated in March 8 biolink-model helpdesk call.

**Comment by nlharris** [comment]
@cbizon is this blocking anything for you?

**Comment by cbizon** [comment]
Hmm, not immediately.   For working on errors of metabolism rare diseases, I think that reactions would be a higher priority.  That said, there are two issues where this might be helpful.  One is in terms of generally making queries more flexible (https://github.com/NCATSTranslator/minihackathons/issues/7).   

The other would be in providing some more principled way of handling gene and protein.  Right now, for instance, the nodenormalizer merges uniprot ids with gene ids, which is practical but messy.  Having a more formal way to describe/handle this would be nice.

**Comment by mikebada** [comment]
I think that formulation of class conflation groups can largely be use/query-driven; for example, if there's a question template that's desired to be answerable by Translator (e.g., which drugs could be used to counter some side effect of some given drug) for which the requisite queries are hampered due to an ontological distinction between two or more types of things but that's irrelevant to the question, then that's an argument for creating a mechanism for conflating those classes somehow. An obvious example is gene/gene-product conflation; another might be drugs as molecular entities versus drugs as macroscopic things.

However, I'm unsure as to how this conflation should happen, e.g., through a formal Biolink representation or through configurable query expansion. For the Text Mining KP, I would like to advocate for a mechanism for at least a limited amount of the former. For one, the difficulty in distinguishing text mentions of genes vs. gene products is a well-known issue in biomedical named entity recognition, and it's one that we want to avoid by simply (almost) always using Protein Ontology classes for them whether they're referring to genes, transcripts, or proteins. We also would like to overwhelmingly use taxon-independent PRO classes, at least for the initial direct annotation of the text. (This is a bit of a different case, as the conflated taxon-independent PRO classes already exist, but this kind of conflation should be similarly taken into account for configurable querying.) We may come across some others as we produce more types of assertions in the future.

**Comment by nlharris** [comment]
@sierra-moxon do you know if this is in progress?

**Comment by sierra-moxon** [comment]
I believe gene/protein conflation will happen in the node-normalizer.

**Comment by cbizon** [comment]
Yes, I have a branch of the normalizer doing gene/protein conflation.  I guess the question is whether there is benefit to defining in the model specific allowed conflations or not.  And any information about the behavior of that conflation.  So for instance, when we conflate a gene and a protein, do we care about the prefix ordering? i.e. is NCBIGene preferred or UniProtKB?

**Comment by sierra-moxon** [comment]
closing for now as we have mixins for the above decision.  Please reopen as necessary.
