### ISSUE TITLE
Add a grouping for directional affects

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#639]
Currently the MRCA of increases-abundance-of and increases-expression-of is `affects`

We might want to have a grouping under affects to capture the positive nature of each

Not clear that grouping pos/neg blindly is a good idea, e.g doesn't make sense to group decrease degradiation and increase abundance

**Comment by sierra-moxon** [comment]
MRCA - most common recent ancestor.  
- added working-group/predicates to this issue.

**Comment by sierra-moxon** [comment]
closely related to #752

**Comment by sierra-moxon** [comment]
closing for now as we have mixin "increase|decrease amount or abundance of" mixins to group together "up and down" predicates.  please reopen if I missed the point :)
