### ISSUE TITLE
Add node properties for chemicals, e.g. inchikey

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#64]
From @stuppie in gdoc "What about string or numerical properties (such as the molecular weight or INCHIKEY for a compound)?"

is there a standard rdf pred for this?

**Comment by stuppie** [comment]
I don't know if there is a "standard"..

Looking at the docs from Pubchem RDF, they are listed as descriptors: http://pubchemdocs.ncbi.nlm.nih.gov/rdf$_4-3
Example: https://pubchem.ncbi.nlm.nih.gov/rest/rdf/compound/CID60823.html, which `sio:has-attribute`: https://pubchem.ncbi.nlm.nih.gov/rest/rdf/descriptor/CID60823_Molecular_Weight.html

and that descriptor has a `sio:has-value`, `rdf:type`, and `sio:has-unit`.

Case 3 has an example sparql query: http://pubchemdocs.ncbi.nlm.nih.gov/rdf$_8-3

It looks like CHEMBL also structures this the same way: https://www.ebi.ac.uk/rdf/static/chembl/chembl_18_rdf_full_schema.png

**Comment by cmungall** [comment]
I think creating a new object representing the property is nice and rigorous and works well in an RDF database, but I was thinking that here we would have simple shortcut literal-triples/node properties, as it's done in wikidata, e.g. https://www.wikidata.org/wiki/Property:P235
