### ISSUE TITLE
CTD:therapeutic maps to exacerbates?

### ISSUE THREAD

**Issue by PhillipsOwen** [biolink/biolink-model#642]
**Describe the bug**
The CTD:therapeutic predicate maps to exacerbates. This appears to be an antonym. this particular predicate should map to ameliorates.

exacerbates:
    is_a: affects
    description: >-
      A relationship between an entity (e.g. a chemical,
      environmental exposure, or some form of genetic variation)
      and a condition (a phenotype or disease), where the presence
      of the entity worsens some or all aspects of the condition.
    # 'biological entity' currently includes 'exposure event' which covers alot of related ground
    domain: biological entity
    range: disease or phenotypic feature
    exact_mappings:
      - RO:0003309
      - CTD:therapeutic

**Expected behavior**
This value should have a better analogue like ameliorates.

**What working group (or team) did this request originate from?**
SRI

Tagging:
@RichardBruskiewich

**Comment by deepakunni3** [comment]
Thanks for raising this concern @PhillipsOwen

**Comment by deepakunni3** [comment]
And thanks for the PR.

**Comment by PhillipsOwen** [comment]
My pleasure!
