### ISSUE TITLE
show mandated prefixes for translator

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#65]
From Eric D in gdoc
> id [required]: MUST be a CURIE, MUST use translator-mandated prefix <- where is the list of these

currently in yaml, need to better expose

**Comment by edeutsch** [comment]
I just learned that the YAML is here:
https://github.com/monarch-initiative/dipper/blob/master/dipper/curie_map.yaml

**Comment by edeutsch** [comment]
I note that there is no entry in the YAML for ChEMBL. Should that be added?

**Comment by cmungall** [comment]
I added a link to the JSON-LD context in the README, also here:

https://github.com/biolink/biolink-model/blob/master/context.jsonld

This has *both*

 1. prefixes and their recommended expansion
 2. mappings between biolink class and predicate names and their URIs
