### ISSUE TITLE
validate, add and document inverse predicates

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#664]
Chris's checklist (as a summary of work left to do from #440)

 1. [x] link existing predicates via `inverse_of` where appropriate
 2. [x] define inference rules for inverse of #624 
 3. [x] decide whether to name inverses for all predicates
 5. [x] provide a programmatic way to look up an inverse predicate. DONE: use BMT
 7. [x]  create reports from biolink model to see whether inverses are defined properly
 8. [ ] declaring the missing ones

**Comment by colleenXu** [comment]
Missing inverse predicates:
- inverse of 'has gene product'. See #671 
- inverse of 'has phenotype'. Have to use 'related_to' for PhenotypicFeature -> Disease.

(From Biolink help desk discussion today)
