### ISSUE TITLE
"associated environmental context" not showing up in the documentation

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#665]
missing in the "own" section: https://biolink.github.io/biolink-model/docs/OrganismTaxonToOrganismTaxonInteraction

**Comment by mbrush** [comment]
Just noted this in my stream and wondered if we might consider more broadly how we name and define association qualifiers that capture a 'context' in which the core S-P-O triple holds.  We have come across use cases for other types of context as well (population context for clinical feature variable associations, experimental context for statistical associations computed from high-throughput biological data). We should consider these and other use cases together to define a consistent and coherent approach.   

I realize this is not the primary concern of this ticket - so happy to move it into its own issue.

**Comment by sierra-moxon** [comment]
closing this case as resolved, opening issue for Matt's comment here:
