### ISSUE TITLE
biolink model web page documentation hyperlink problems

### ISSUE THREAD

**Issue by edeutsch** [biolink/biolink-model#668]
**Describe the bug**
When looking at a BioLink documentation page, many of the hyperlinks aren't working

**To Reproduce**
Go to: https://biolink.github.io/biolink-model/docs/types/IriType.html
The virtual path hyperlinks at the top don't go back up the hierarchy as they probably should
![image](https://user-images.githubusercontent.com/12707718/110980856-28fda800-831b-11eb-9dc0-bb38ee166742.png)

The hyperlinks lower on the page are all 404s
![image](https://user-images.githubusercontent.com/12707718/110980905-374bc400-831b-11eb-84cf-e2ea4bf47227.png)

**Expected behavior**

**What working group (or team) did this request originate from?**
This bug originated from the XYZ working group.

Note: This is relevant for members of NCATS Translator.

**Additional context**

**Tag relevant members for discussion**
Tag all relevant members to this ticket to start a discussion.

**Comment by nlharris** [comment]
Thanks for reporting this, @edeutsch! @sierra-moxon, maybe you could take a look?
