### ISSUE TITLE
Request for 'capable of' predicate for anatomy - GO MF/BP associations

### ISSUE THREAD

**Issue by mbrush** [biolink/biolink-model#67]
Documenting a predicate request from Steve Ramsey (Gamma): 

> Can we please get a “capable_of” predicate added to the Minimum Predicate Hierarchy?  This is for connecting UBERON terms to GO terms (see this page for details:
https://github.com/obophenotype/uberon/wiki/inter-anatomy-ontology-bridge-ontologies

**Comment by mbrush** [comment]
The developing min predicate set  proposed in #55 includes  an ‘enables’ predicate,  which was created to support GO annotations of **genes** that link them to **molecular functions** they are capable of.  A ‘capable of’ predicate was considered here, but  for reasons I won’t go into GO chose to use the RO:’enables’ relation in their data instead of its more general parent  RO:‘capable of’  relation (the curator note [here](http://www.ontobee.org/ontology/RO?iri=http://purl.obolibrary.org/obo/RO_0002327)  explains rationale for this).

For Translator purposes, I propose a ‘capable of’ predicate for the Translator minimal set, instead of the more constrained ‘enables’ predicate. KGs can use this ‘capable of’ predicate for connecting things like genes or anatomical entities to GO molecular functions or biological processes.   

Thoughts? (in particular from @cmungall)

**Comment by saramsey** [comment]
enables is fine.  I'll go with that!

thank you Matt!

**Comment by saramsey** [comment]
Would be great if "capable_of" was at least in the maximal predicate set (it may already be, I confess I haven't checked)

**Comment by cmungall** [comment]
Do we want an even more general relation that subsumes 
enables/capable_of (the structure carries out all of the activity) and 
involved_in (the structure carries out a step in the overall process)?

We have has_participant, but presumably you want to restrict to 
participants that are active or have some "agency"

**Comment by mbrush** [comment]
To keep things moving ahead, I am going ahead and implementing as proposed above, specifically:

```
'participates in'           (any type of participation in a process or function)
      'involved in'         (has agency for at least part of the process or function)     
            'capable of'    (has agency on its own to drive entire process or function)
```

Happy to revisit and revise if this ends up being problematic - but want to get certain predicates in the spec that teams need now for their KGs.

**Comment by cmungall** [comment]
One important factor to consider: a gene product M that has an activity that acts upstream of a process P (either regulating P or playing some role that causally affecting P) is not considered a participant in that process in RO. The RO property [acts upstream of or within](http://purl.obolibrary.org/obo/RO_0002264) covers the more general case

**Comment by mbrush** [comment]
Good point Chris.  There are many nuances to consider here, as evidenced by the number and fine-grained distinctions made between the many RO relations in this area. 

If we keep them, should be clear that the relations above should be used when the entity does indeed participate in the indicated process or function.  If there are cases where we cannot or don't want to distinguish whether the entity facilitates a process or function through upstream action or through direct participation/execution, we can add an 'acts upstream of or within' predicate.  But I would do so only if/when there is a real need/use case for it in our work.

**Comment by saramsey** [comment]
copy that. we are implementing is_capable_of predicates to relate proteins to "molecular function" ontology terms.

**Comment by nlharris** [comment]
Can this be closed?

**Comment by deepakunni3** [comment]
Yes. The request has been implemented in the model.
