### ISSUE TITLE
Predicates for gene-to-GO-term associations

### ISSUE THREAD

**Issue by colleenXu** [biolink/biolink-model#670]
**Is your feature request related to a problem? Please describe.**
It's not clear what predicates to use in relating genes to their annotated GO terms, OR there's something problematic with the current predicates. 

Using the current model:

- Gene -> MolecularActivity (MF sub-ontology) and its inverse:
  - using biolink 'enables' but this has the domain 'physical entity'. Seems like Gene isn't a 'physical entity'; instead, stuff like [material sample](https://github.com/biolink/biolink-model/blob/3985c060240cf838e485299c1e380ae4ba35a925/biolink-model.yaml#L5561) is. Inverse predicate 'enabled_by' has this issue too. 
  - This predicate is a bit confusing. Is this meant to be used like "has activity" or "has function"?
  - There is RO:0000085 (has_function) and its inverse RO:0000079 (function_of), but they're not mapped to the biolink model

- Gene -> BiologicalProcess and its inverse:
  - using biolink 'participates in'/'has participant'. It feels odd that this set of predicates is also used for something closer to group membership (Gene -> Pathway, Pathway -> Gene). But it could be okay. 
  - Should this be contributes to/contributed to by instead? 

- Gene -> CellularComponent and its inverse:
  - using biolink 'expressed in'/'expresses'. It feels odd, since it's a gene whose activity takes place in the cellular component (complex or organelle). The activity happening there doesn't necessarily mean that organelle or complex "expressed" the gene though. 
  - located_in/location of feels weird too, since genes are in the nucleus....it's the gene product and/or gene activity that was found in the complex or organelle

**What working group (or team) did this request originate from?**
MetaKG-related (Service Provider, Exploring Agent)

**Describe the solution you'd like**
Review and decide what predicates should be used to be compliant with biolink model. Share with the greater Translator group.

(From Biolink help desk discussion earlier today)

**Comment by cmungall** [comment]
Perfect timing as go2term relationships are being added to go gafs very soon! Great qs we will clarify shortly
