### ISSUE TITLE
Modeling Drug-Drug Interactions With the Biolink Model

### ISSUE THREAD

**Issue by ericawood** [biolink/biolink-model#679]
This question came up during the Mini Hackathon on 3/18/21. What is the best predicate for modeling drug-drug interactions? Currently, Expander Agent's KG2 maps DrugBank drug-drug interactions to "physically interacts with". However, the meaning of this predicate is unclear because it applies to several situations, (for example, DrugBank's drug-target interactions are also mapped to "physically interacts with").

**Comment by nlharris** [comment]
This was discussed during the Help Desk on 22-Mar-2021.

**Comment by sierra-moxon** [comment]
@ericawood - I am going to close this ticket in favor of https://github.com/biolink/biolink-model/issues/662 as that ticket has the link to the harmonization efforts in the chemical WG around drugbank drug-drug interactions.  I will tag you on that ticket (662) as well.
