### ISSUE TITLE
Make 'latest' branch and keep up to date with the latest tag

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#686]
See discussion: https://github.com/biolink/biolink-model/discussions/675
We'd like to support stable URLs to biolink-model artifacts.  One suggestion is to create a 'latest' branch and keep that up to date with our latest tag. 

- [x] create latest branch 
- [x] update release instructions to include an update to the latest branch and keep this branch up to date.
- [x] investigate w3id alternatives and document how that would work instead (by default, we think this would involve changing the default branch to the release branch/tag each time we released but we should confirm).

**Comment by nlharris** [comment]
@sierra-moxon do you think we can close this issue?

**Comment by sierra-moxon** [comment]
Yep!  thanks for finding.
