### ISSUE TITLE
Map to UMLS semantic types

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#7]
See also https://github.com/NCATS-Tangerine/beacon-aggregator/issues/15 and https://github.com/NCATS-Tangerine/translator-knowledge-beacon/issues/15

**Comment by cmungall** [comment]
@RichardBruskiewich has already done a lot of this, e.g. https://github.com/biolink/biolink-model/commit/9951bee8c602c28b1a3e779c2be2981a5332e044

**Comment by cmungall** [comment]
the goal isn't to include all of these. We're calling this done when existing entity types in BLM have a mapping

**Comment by cmungall** [comment]
Is this completed?

**Comment by RichardBruskiewich** [comment]
Ancient issue, long neglected... I note that the "semantic types" were note added. They are more fine grained than the UMLS semantic groups. I vaguely seem to recall that MediKanren may have been using them, but don't know if that is still the case. 

I can strive to add them into Biolink today.

**Comment by RichardBruskiewich** [comment]
@cmungall are biolink category mappings supposed to be one-to-one? The reason I ask is that we have two UMLSSG:GENE mappings: one to the Biolink category "genomic entity" and the other (obviously) to "gene".

I wonder if this presents any practical difficulties with software using the Biolink model? I suspect perhaps...

The UMLS semantic types under the Semantic Group "GENE" are:

```
T028	gngm	Gene or Genome	GENE	Genes & Molecular Sequences
T085	mosq	Molecular Sequence	GENE	Genes & Molecular Sequences
T086	nusq	Nucleotide Sequence	GENE	Genes & Molecular Sequences
T087	amas	Amino Acid Sequence	GENE	Genes & Molecular Sequences
T088	crbs	Carbohydrate Sequence	GENE	Genes & Molecular Sequences

T028 | gngm | Gene or Genome | GENE | Genes & Molecular Sequences
-- | -- | -- | -- | --
T085 | mosq | Molecular Sequence | GENE | Genes & Molecular Sequences
T086 | nusq | Nucleotide Sequence | GENE | Genes & Molecular Sequences
T087 | amas | Amino Acid Sequence | GENE | Genes & Molecular Sequences
T088 | crbs | Carbohydrate Sequence | GENE | Genes & Molecular Sequences


T028 | gngm | Gene or Genome | GENE | Genes & Molecular Sequences
-- | -- | -- | -- | --
T085 | mosq | Molecular Sequence | GENE | Genes & Molecular Sequences
T086 | nusq | Nucleotide Sequence | GENE | Genes & Molecular Sequences
T087 | amas | Amino Acid Sequence | GENE | Genes & Molecular Sequences
T088 | crbs | Carbohydrate Sequence | GENE | Genes & Molecular Sequences
```

Which are (carelessly) broad in Biolink scope.

**Comment by RichardBruskiewich** [comment]
Completed the above task (I think...) and issued a pull request: https://github.com/biolink/biolink-model/pull/209
