### ISSUE TITLE
missing subClassOf link between ChemicalSubstance and ChemicalOrDrugOrTreatment

### ISSUE THREAD

**Issue by bill-baumgartner** [biolink/biolink-model#701]
**Is your feature request related to a problem? Please describe.**
The `biolink:ChemicalSubstance` class does not appear to be subClassOf `biolink:ChemicalOrDrugOrTreatment`. 

**What working group (or team) did this request originate from?**
Text Mining Provider

**Describe the solution you'd like**
The `biolink:ChemicalOrDrugOrTreatment` mixin should be added to the `biolink:ChemicalSubstance` class, similar to how it is already linked to the `biolink:Drug` and `biolink:Treatment` classes.

**Comment by sierra-moxon** [comment]
Hi @bill-baumgartner - thanks a bunch!  I think there are some changes coming to the chemical hierarchy in the model - we'll make sure this is fixed as well.

**Comment by sierra-moxon** [comment]
@bill-baumgartner - I believe this is addressed in the biolink-model 2.0.0 release?  Closing for now, but can definitely reopen if the new model doesn't fit the bill. :)
