### ISSUE TITLE
Reduce the curie exceptions in biolink-model to non-overlapping sets with the imported curie frameworks.

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#704]
- identified in the monarch data commons call.

**Comment by nlharris** [comment]
Is this related to #697?

**Comment by sierra-moxon** [comment]
yep!  you got it.  Lets close this in favor of #697 with more details.  We need to maintain prefixcommons/biocontext as well to help this become easier downstream for biolink-model, etc.
