### ISSUE TITLE
How should DrugCentral:diagnosis be mapped?

### ISSUE THREAD

**Issue by ericawood** [biolink/biolink-model#705]
Which biolink predicate do you think best fits DrugCentral:diagnosis, which roughly means "a drug that helps diagnose a condition". Here is an example: https://drugcentral.org/drugcard/5271.

**Comment by mikebada** [comment]
I don't see one in Biolink, but it seems it should be parallel to `treats`, whose domain is `chemical or drug or treatment` and whose range is `disease or phenotypic feature`, so perhaps add a `diagnoses` predicate, with the same domain and range?

**Comment by sierra-moxon** [comment]
Yep, lets add a diagnosis predicate.
