### ISSUE TITLE
what is the appropriate Biolink category for Sequence Ontology concepts?

### ISSUE THREAD

**Issue by bill-baumgartner** [biolink/biolink-model#706]
**Question:**
We have a text-mining pipeline that extracts mentions of Sequence Ontology concepts from text. The KGX format to which we serialize requires that a Biolink category accompany each SO id. What Biolink concept do you recommend be used as the category for SO concepts? 

Is the [biolink:GenomicEntity](https://biolink.github.io/biolink-model/docs/GenomicEntity.html) class appropriate for this use-case? Or should a more abstract `SequenceFeature` class be used? Or maybe something else?

Thanks!

**Comment by sierra-moxon** [comment]
I think we should add the SO concepts needed for your KP - yep, biolink:GenomicEntity is meant to encompass "SequenceFeature."   Do you need more granular objects?

**Comment by bill-baumgartner** [comment]
Thanks Sierra. I was looking for a catch-all for any Sequence Ontology concept because any concept in the ontology could be recognized in text potentially. It looks like there are four roots to the Sequence Ontology. If we can map each of the roots to an appropriate Biolink concept then I think that should work.

* [sequence_attribute (SO:0000400)](http://www.sequenceontology.org/browser/current_svn/term/SO:0000400)
* [sequence_collection (SO:0001260)](http://www.sequenceontology.org/browser/current_svn/term/SO:0001260)
* [sequence_feature (SO:0000110)](http://www.sequenceontology.org/browser/current_svn/term/SO:0000110)
* [sequence_variant (SO:0001060)](http://www.sequenceontology.org/browser/current_svn/term/SO:0001060)

It seems like `biolink:GenomicEntity` covers `SO:sequence_collection` (e.g. genome), `SO:sequence_feature`, and `SO:sequence_variant`.

Do you agree with that statement, and do you think it's appropriate to also bin `SO:sequence_attribute` under `biolink:GenomicEntity` or should that map do a different biolink class?

**Comment by mikebada** [comment]
I'd say that `biolink:GenomicEntity` covers most but not all of `SO:sequence_collection`, `SO:sequence_feature`, and `SO:sequence_variant`. Things that I don't think quite fit include sequence assembly concepts, junctions, and sequence constructs such as vectors and primers. I don't think `SO:sequence_attribute` fits at all into `biolink:GenomicEntity`. However, I think what we're going to export in associations for Translator are probably limited to genomic entities, but let's talk about it.

**Comment by bill-baumgartner** [comment]
Thanks all for the answers. I think I'm good to go for now. Will followup with @mikebada for things that shouldn't be considered as `biolink:GenomicEntity`. Closing this question for now. Thanks!
