### ISSUE TITLE
Consider going more granular with the minimal predicate set

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#71]
In our [neo4j mapping](https://biolink.github.io/biolink-model/about/mapping-neo4j.html) we use a human-readable minimal predicate (snake-case) as the neo4j relationship type ([edge label](https://biolink.github.io/biolink-model/docs/edge_label.html)). The more granular [relation](https://biolink.github.io/biolink-model/docs/relation.html) is an edge property.

The original thinking was that grouping at a high level was good, and people could add edge properties in the cypher query where granularity is required. However, @dosumis points out that while it is easy to specify a disjunction of relationship types in a cypher query, incorporating edge properties is more difficult. The implication is that it would be better to have the relationship types be more granular.

**Comment by cbizon** [comment]
Agreed.  In general, I don't see that predicates defined purely by the types in the relations are very useful.  If the standard relation between gene and disease is just "gene_associated_with_condition" and that is the relation for every gene/condition edge then the edge label contains no extra information beyond the types of the nodes connected.

**Comment by nlharris** [comment]
Did this get addressed?

**Comment by deepakunni3** [comment]
CC'ing @cmungall

**Comment by nlharris** [comment]
is this still relevant?

**Comment by mbrush** [comment]
I think its is still very relevant.  Recent Translator Data Modeling conversations have led to the same conclusion that we should allow more granular predicates into the Biolink model so the full semantics of an association don't rely on a `relation` edge property.  

One specific context where this was discussed was in representation of chemical-gene product interaction mechanisms, where the emerging consensus is that we should allow for predicates describing specific interaction mechanisms (e.g. 'is allosteric modulator of', 'is antagonist of') into Biolink so they can be used in the `Association.predicate` slot.   See [issue #570](https://github.com/biolink/biolink-model/issues/570#issuecomment-748315684).

A related topic that arose was the need for strategies for managing the complexity that will inevitably result when we start defining many, very specific predicates in Biolink.   e.g. ways to compartmentalize domain-specific granular predicates in separate files that could be imported as needed into the core Biolink model (where predicates remain relatively high level).

**Comment by sierra-moxon** [comment]
thanks, @mbrush! - my understanding is that we have committed to making more granular predicates and have begun this process by querying for predicates in use that are not in the model.  So hopefully well on our way to accomplishing the first task here. 

The second task I was hoping for some more clarification on?  Why do we need to break up the predicates in to domains and in separate files?   My understanding is that the predicates can be more granular in the core model now (this might've been a recent decision :))?  

Maybe we can close this ticket?

**Comment by mbrush** [comment]
I don't know that we do need to compartmentalize using separate files.  That was just one example of a way we might manage some of the complexity that a decision to support very granular predicates may lead to.  I think for now we can just get them into the core model. Fine IMO to close this ticket, and if the number / diversity starts to be problematic, we can open a new one to debate strategies for managing this.

**Comment by sierra-moxon** [comment]
Thanks @matt! :)
