### ISSUE TITLE
generate simple prefix map

### ISSUE THREAD

**Issue by balhoff** [biolink/biolink-model#710]
It looks like the latest biolink-model build is using the more complicated JSON-LD context needed for correct prefix expansion in JSON-LD 1.1 (great!). But now this file is a lot harder to use for consumers just wanting a basic mapping from prefixes to namespaces. We added a new command to linkml for this purpose. Could biolink-model add this file to its products? I think the command is `prefixmapgen`.

**Comment by cmungall** [comment]
Yes, the command is `gen-prefix-map`

This should just be a matter of adding `gen-prefix-map` to the Makefile
