### ISSUE TITLE
change in URI for some slots, in the biolink-model.owl.ttl file

### ISSUE THREAD

**Issue by saramsey** [biolink/biolink-model#712]
**Describe the bug**
Hi Biolink team:  In commit 5cc92f52c09beda936fce6c718bb4a1be159b8ee (on April 5), there was a bunch of URIs for slots that changed in `biolink-model.owl.ttl`. Now slots like `chemical_to_chemical_derivation_association_catalyst_qualifier` have a CURIE that is like `linkml:chemical_to_chemical_derivation_association_catalyst_qualifier`. It previously used to be `meta:chemical_to_chemical_derivation_association_catalyst_qualifier` in the `biolink-model.owl.ttl` file. This change (and the many others other like it, in that same commit) was breaking for the KG2 build system which depends on `biolink-model.owl.ttl`. It was a one-line fix for us, but I thought I would bring it to your attention in case this change was not intended. Part of why I am wondering if maybe that change was not intended is because I do not see that commit having a similar change in `biolink-model.ttl`; *that* file still has the same URI `https://w3id.org/biolink/vocab/chemical_to_chemical_derivation_association_catalyst_qualifier` it has already had.

**To Reproduce**
see https://github.com/biolink/biolink-model/blob/bd3607404bae3677bc8fa6de16067c8abfab56b6/biolink-model.owl.ttl#L1604

**Expected behavior**
did not expect to see this slot with a `linkml:` prefix; that threw off our biolink ingestion and validation code

**What working group (or team) did this request originate from?**
Team Expander Agent

Note: This is relevant for members of NCATS Translator.

**Additional context**

**Tag relevant members for discussion**
Tag all relevant members to this ticket to start a discussion.

**Comment by sierra-moxon** [comment]
Thanks for the heads up @saramsey - I'll track it down.

**Comment by sierra-moxon** [comment]
related ticket in linkml repo: https://github.com/linkml/linkml/issues/164

**Comment by nlharris** [comment]
Possibly also related: #788

**Comment by sierra-moxon** [comment]
Hi @saramsey - there have been a lot of improvements made to this file since you submitted this ticket.  I hope they fit your needs better or otherwise fix this issue?  

(for example, no more meta or linkml tagged objects).

Shall I close this ticket?
