### ISSUE TITLE
add CHEBI mapping for 'chemical substance'

### ISSUE THREAD

**Issue by balhoff** [biolink/biolink-model#718]
Would it be possible to map 'chemical substance' to a CHEBI term? This is currently missing and causing query misses in the ontology KP.

**Comment by cbizon** [comment]
Can this make it into the next release?

**Comment by cmungall** [comment]
We could do this right away, but chem substance will be deprecated in favor
of chemical entity with the chem refactor

**Comment by cbizon** [comment]
Granted, but it would be helpful to have in the  interim.

**Comment by cmungall** [comment]
let's do it!
