### ISSUE TITLE
Add UMLS prefixes for gene, gene product

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#722]
**Is your feature request related to a problem? Please describe.**
Some sources like semmedb use UMLS terms to represent genes and proteins.

**What working group (or team) did this request originate from?**
Unsecret agent

**Describe the solution you'd like**
Addition of UMLS as an identifier prefix for gene and gene product, and the addition of appropriate UMLS semantic types to the mappings of these categories.

**Tag relevant members for discussion**
@webyrd

This is a high priority item, as the node normalizer uses the model to determine legal prefixes for identifiers.

**Comment by sierra-moxon** [comment]
@cbizon - we took a look at this in the helpdesk this morning, and there doesn't seem to be a clear UMLS->'gene or gene product' mapping.  Instead, would the following changes work?

- [ ] add 'UMLS' to the list of possible prefixes for 'gene', and 'protein' 
- [ ] add 'UMLSSC:T087' as an exact mapping for 'protein' 

('genomic entity' already has a narrow mapping to UMLSC:T028 - 'Gene or Genome')
https://metamap.nlm.nih.gov/Docs/SemGroups_2018.txt

**Comment by cbizon** [comment]
That seems reasonable to me.  I was under the impression from @webyrd that there was a UMLS->'gene' mapping, but maybe I misunderstood (I don't know UMLS all that well).
