### ISSUE TITLE
NCBIGENE prefix

### ISSUE THREAD

**Issue by balhoff** [biolink/biolink-model#725]
I thought that a decision had been made to use `NCBIGene` instead of all caps (I can't find an issue though). But the latest file has all caps: https://github.com/biolink/biolink-model/blob/8b5ca35ad171f5837ae3b61d3df31e5c3a04b344/context.jsonld#L264

**Comment by cbizon** [comment]
in the id_prefixes for gene, it's listed as "NCBIGene". Seems like maybe a good place for a test - all id_prefixes should have an entry in context.jsonld?

**Comment by sierra-moxon** [comment]
@cbizon @balhoff - I think I've tracked this down to an issue in the idot_context file here: https://github.com/prefixcommons/biocontext/pull/35

I'll try to see if I can get that merged in, or if it is even further upstream in MIRIAM (or if I change the order of prefix imports in biolink-model, if I can get it to pickup one of the fixed contexts like this one: https://github.com/prefixcommons/biocontext/blob/master/registry/monarch_context.jsonld

**Comment by balhoff** [comment]
FYI, @kshefchek recently said something about considering deprecating Monarch context.

**Comment by balhoff** [comment]
FYI, this issue is causing a lot of problems in answering Translator test queries.

**Comment by sierra-moxon** [comment]
biolink-model 2.0.1 has been released with this change
