### ISSUE TITLE
WormBase and Flybase Prefixes

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#727]
Under gene.id_mappings, we have:
```
      - WB
      - WormBase
      - FB  # FlyBase FBgn*
      - FB
```
For some reason FB is there twice.

Also, I think that WB and WormBase are meant to be the same thing?  But one resolves to a wormbase URI and one to identifiers.org/wb.   Do we need both?

**Comment by sierra-moxon** [comment]
@cbizon - I removed the redundant FB.  Unfortunately, I think we should keep both WB and WormBase.  wormbase.org supports WormBase: prefix and identifiers.org and alliancegenome.org support WB:.

**Comment by cbizon** [comment]
Does that mean that we need both?  Do they have different expansions?

**Comment by sierra-moxon** [comment]
removed duplicative prefixes
