### ISSUE TITLE
capture 'regressor of' statistical predicate

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#731]
Use case: 
Looking for the most suitable predicate for statistical prediction.

'biolink:related_to' for the predicate and the relation could be  RO:0002616 (related via evidence or inference to, that's the explanation on Ontobee) maybe?

The Wellness KP uses correlated_with, but that too is a statistical correlation.  Most children of correlated_with probably don't apply, because the correlation coefficient is a column, which of course is a signed number.

Might we need a 'regressor of' predicate as a child of 'predicts'? (from Arpita Joshi, Postdoc, ISB, (Multiomics Provider).

**Comment by aj95b** [comment]
RO:0002472 seems better http://www.ontobee.org/ontology/RO?iri=http://purl.obolibrary.org/obo/RO_0002472 , the previous one has a curator note.

**Comment by sierra-moxon** [comment]
Arpita is using 'has real world evidence of association with' at the moment.

**Comment by sierra-moxon** [comment]
subject                      LOINC:47828-9
predicate          biolink:correlated_with
object                    UniProtKB:P05231
relation                        RO:0002610
N                                     1970
rho                               -0.16958
Bonferroni_pval                3.53915e-14
subject_name            ADIPONECTIN, SERUM
object_name                    CVD2_P05231
category               biolink:Association

Only information that example is missing would come from the nodes TSV and it is the biolink concepts of the two nodes-- ClinicalFinding and Protein (respectively for the Loinc and Uniprot)

**Comment by sierra-moxon** [comment]
The complication here is that this seems like a predicate, while we already have has_evidence (the inverse of is_evidence_for) as an association slot (edge property).  

This use case wants to make an association between two variables using the inverse of has_evidence, whereas we currently model has_evidence as a property to hold evidence for an existing association.

**Comment by sierra-moxon** [comment]
@aj95b - is there someone in your old group that is taking over for you now that you have moved on from Translator? :)
I think the solution here might be to use a supporting data property to represent regression.  And, we have captured your microbiome use case for predicates in our Association Use Case document. (please let me know if you can't find it).

**Comment by aj95b** [comment]
@sierra-moxon - that’s great! The last version of Wellness KP I forwarded, to be served via BTE was yet to be deployed and that’s the one that had edges with microbiome data and also the ones that represented statistical predictions. I unfortunately don’t know who took over and if that same last version was deployed or not. I am tagging the Multiomics PIs who would likely know more or may have handed it over to someone new. @jh111 @gglusman

PS: In case this knowledge is still to be a part of the Wellness KP, the ‘data property’ solution sounds good.

**Comment by sierra-moxon** [comment]
@jh111 - is this still necessary?

**Comment by jh111** [comment]
@gglusman - do you need this?

**Comment by sierra-moxon** [comment]
closing for now; @gglusman, happy to reopen if you want to capture this going forward.
