### ISSUE TITLE
Add xenbase prefix

### ISSUE THREAD

**Issue by kevinschaper** [biolink/biolink-model#732]
I need a Xenbase prefix to be added to the curie prefix map, identifiers.org shows it as 'xenbase'

**Comment by cmungall** [comment]
Hi @kevinschaper - try annotating relevant classes like 'Gene' with `Xenbase` in `id_prefixes`. Probably the same places you see `ZFIN`. Then when the json-ld-context is built it will contain Xenbase (the actual prefix is defined upstream in both go and idorg). Note `Xenbase` is canonical capitalization (idorg lowercases everything, but the GO registry uses the MOD's preference)

**Comment by kevinschaper** [comment]
Thanks @cmungall! 

I made that change here: https://github.com/biolink/biolink-model/pull/733

As far as I know right now, Gene looks like the only relevant class.

**Comment by kevinschaper** [comment]
@cmungall @sierra-moxon 

I added XPO to the biolink curie map, but is there somewhere more general that it should be added?

**Comment by kevinschaper** [comment]
@sierra-moxon 

Could there be a problem with bringing in the monarch context? I'm not sure if Xenbase should actually specifically need to be added, because it looks like it's defined here: https://github.com/prefixcommons/biocontext/blob/master/registry/monarch_context.jsonld

(I'm guessing that's where it pulls from?)

I also think we could toss my PR entirely by adding XPO here? https://github.com/prefixcommons/biocontext/blob/master/registry/obo_context.jsonld

I assume the process is more like re-generating that file from an OBO source or something?

**Comment by kevinschaper** [comment]
Fixed, thanks!
