### ISSUE TITLE
add edge properties to capture EPC of an inference

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#735]
See issue3 here: https://docs.google.com/document/d/1teKsqTWUxk5Yi6lPrgK7aTANtLLLs10_Wz0pGuQTaxc/edit#

An example: if we conflate genes and proteins and decide to return UniProtKB identifier when a user queried via a NCBIGene identifier, we need to return the method (maybe the equivalence axiom used, or a summary key:value attribute pair that denotes ‘conflation’ in general? -- needs discussion) used to do this conflation.

“EPC” key:value pair attributes might include:
“Infores:inferred_property_chain”:”name_of_property_chain”
“Infores:entity_or_predicate_conflation”:”gene_has_product_protein” 
(these need discussion)

@mbrush

**Comment by nlharris** [comment]
Closing as done. Can be reopened if I closed it prematurely.
