### ISSUE TITLE
Disease Susceptibility

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#736]
**Is your feature request related to a problem? Please describe.**
Are Disease Susceptibility terms (MONDO_0042489 and descendants) part of biolink:Disease or not?  If not, what are they? 

**What working group (or team) did this request originate from?**
SRI Node Normalizer

**Describe the solution you'd like**
Either adding MONDO_0042489 to the mapping for Disease, or the creation of a new category for entities of this type.

**Additional information to support this request** (optional)
Logically, disease and disease susceptibility are separate things, hence MONDO separating them.  In terms of querying translator, I think this distinction is too fine grained to worry about.  So my inclination would be to merge these.  If we do keep them separate, then we at least need to join them up somewhere like DiseaseorPhenotpyicFeature.

**Tag relevant members for discussion**
@sierra-moxon @cmungall @RichardBruskiewich

**Comment by sierra-moxon** [comment]
From 5/20/2021 DM call: add MONDO_0042489 as a narrow_mappings right now, but leave open the option to make 'Medical State' class as a parent of 'Disease' and 'Disease Susceptibility'  (genetic susceptibility is what we are mostly talking about here).

**Comment by sierra-moxon** [comment]
@cbizon - I think at the DM call, we decided that all MONDO terms would be considered biolink:Disease.  Is that your recollection?

**Comment by cbizon** [comment]
Yes, at least as a stop-gap

**Comment by nlharris** [comment]
but that doesn't totally address this request?

**Comment by sierra-moxon** [comment]
from helpdesk: susceptibility in this use case would be a qualifier/modifier of a subject or object, or incorporated into a predicate (depends on the outcome of the predicate work).
