### ISSUE TITLE
model longitudinal data (modeling recovery) and time related dependencies

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#739]
From Sandrine Muller (Molecular Data Provider): "How does longitudinal data (time related dependencies) modeled in the biolink model?  Longitudinal data in at least clinics is indeed very common (modeling recovery). I am aware of some efforts from companies and European consortiums  and can have a closer look"

**Comment by sandrine-m** [comment]
Examples of time dependencies in biomedical data:
(1) measure a phenotype in time in clinics
(2) longitudinal gene expression data (e.g. Allen brain developmental atlas)
(3) single cell velocity and other methods for pseudo-time
(4) evolution of protein functions in species
(5) physiological recordings of cells
(6) human tracking data though devices (sleep/gait...etc)
...
Here are a few ressources for modeling time in KG:
https://dl.acm.org/doi/10.1145/3308560.3316521
https://openreview.net/forum?id=pGIHq1m7PU
https://www.sciencedirect.com/science/article/abs/pii/S1570826815001456

**Comment by sierra-moxon** [comment]
@sandrine-m - we do have "context qualifiers" that can hold stage/age/timing information: https://github.com/biolink/biolink-model/blob/b8c46fb1097ac2e33d0cf0cde844314459284b05/biolink-model.yaml#L1085

Does this answer your question?

**Comment by sandrine-m** [comment]
Very nice! Thank you!!!!

**Comment by nlharris** [comment]
So can this be closed?

**Comment by sandrine-m** [comment]
Yes! Thank you!
