### ISSUE TITLE
add association between gene and publication

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#740]

**Comment by sierra-moxon** [comment]
We should provide an association between gene and publication with an appropriately high level predicate.  
We should think about if this association can be a parent of any other more specific association.

**Comment by sierra-moxon** [comment]
@ehinderer - it could be either of those use cases yes.  This request came specifically from Monarch (and model organism databases).  Sometimes the knowledge provider doesn't capture the specifics about assertion that the publication is making about the gene, just that it does mention the gene.  Would you mind reviewing my PR #741 for me?  I'd love your feedback on this approach. :)

**Comment by sierra-moxon** [comment]
@mbrush  - would you mind reviewing this PR #741, https://github.com/biolink/biolink-model/pull/741/files with EPC in mind as well?
this might mean we have two ways of recording a gene-publication assertion? (both as an edge property when the association is specific, ie: gene to disease association) and another when the association is less specified (gene 'mentioned in' publication assertion). gene->disease (with edge property) and gene->publication (using 'mentions' predicate).

**Comment by ehinderer** [comment]
@sierra-moxon I reviewed that PR. Looks good to me in terms of what it claims to capture. The issue still remains, however, if there should be a distinction between provenance sources that merely _refer_ to established assertions, and provenance sources that lay claim to novel assertions, if that makes sense.

**Comment by sierra-moxon** [comment]
in biolink-model 2.0.0
