### ISSUE TITLE
remove/replace generic id mappings to UMLS?

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#749]
Throughout the model, we have mappings like: "UMLSST:phsf" that use broad UMLS categories(?) as a sort of identifier.  I'd like to propose removing them as they don't resolve.  

Are they critical for the node normalizer, or other downstream components that would be harmed if we removed them? @cbizon @RichardBruskiewich @mbrush

**Comment by cmungall** [comment]
We should use the T codes

e.g T039 not phsf

Bioportal uses STY, we could ask for this in bioregistry.io http://bioregistry.io/registry/sty -- can you make a ticket? https://github.com/bioregistry/bioregistry/issues

we can make URLs

http://purl.bioontology.org/ontology/STY/T039

but given there is a hierarchy I don't see the value of curating broad/narrows that can be inferred?

**Comment by cmungall** [comment]
mappings for codes like phsf -> T codes here: https://metamap.nlm.nih.gov/Docs/SemanticTypes_2018AB.txt

**Comment by cmungall** [comment]
Request to add STY:
https://github.com/bioregistry/bioregistry/issues/83

We should just go ahead and add STY in the biolink yaml header for now

**Comment by cthoyt** [comment]
I've added STY to the Bioregistry and made a new deployment. Here's the new entry: https://bioregistry.io/registry/sty. Please let me know if there's anything else I can add

**Comment by cmungall** [comment]
Thanks @cthoyt!

OK, my PR fixes things such that we use STY for semantic types. I also got rid of UMLSST as it was redundant

We still have this:

UMLSSG: 'https://metamap.nlm.nih.gov/Docs/SemGroups_2018.txt/group#'

but this 404s
