### ISSUE TITLE
predicate mixins for up -thing and down-thing

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#752]
**Is your feature request related to a problem? Please describe.**

We have found that there are lot of queries like "make this gene do more" or "make this gene do less".  There are many predicates that might capture this idea such as
'increases activity of'
'increases expression of'
'decreases degradation of'
...

Currently teams maintain lists of like-minded predicates for use in queries, but to share these we could/should make them into biolink mixins.

@webbyrd please provide UnsecretAgent's predicate lists.

**What working group (or team) did this request originate from?**

September Demo / minihackathon / Unsecret Agent.

**Note:** This is relevant for members of NCATS Translator.

**Describe the solution you'd like**

Mixins that bridge from a fuzzy mechanism-free query that user might come up with to a specific set of predicates that might have such an effect.

Tag all relevant members to this ticket to start a discussion.
@sierra-moxon @cmungall

**Comment by mikebada** [comment]
We've been discussing this in the Predicates group call; how about increases_amount_or_activity_of as a slot mixin?
