### ISSUE TITLE
Mapping "Protein Domain" and "Protein Family" nodes to Biolink entity

### ISSUE THREAD

**Issue by karthiksoman** [biolink/biolink-model#755]
**Question:**
Our knowledge network (SPOKE) has node types such as "Protein Domain" and "Protein Family". To make our knowledge network Biolink compatible, we map our nodes to Biolink entities. However, we do not see mappings for these node types in Biolink model. It would be great if you could direct us here to find the correct Biolink mapping for these.

In addition, it would be great if you can also suggest Biolink mappings for node types such as "Side effect" and "Pharmacologic class".

**Comment by sierra-moxon** [comment]
@karthiksoman - in the biolink-model we have 'gene family' with an alias of 'protein family' (following our conflation discussions.  Protein domain might be a good addition here.  Does using 'gene family' in this way raise any red flags for you?  

I am going to put your second part of this ticket in a new ticket.

**Comment by karthiksoman** [comment]
Thanks Sierra for the reply and for assigning a separate ticket. We had an improving agent team internal discussion on this. So the consensus we reached was that, it would be nice to include Protein domain as a separate class/entity in Biolink rather than an addition under gene family. Reason is because we consider gene and protein as two separate entities.

**Comment by nlharris** [comment]
Since the request was broken out into a separate ticket, can we close this ticket?

**Comment by karthiksoman** [comment]
Hi Nomi, I think, we still need to figure out where does protein domain/protein family maps to? Currently, it is getting mapped to gene family. However, improving agent ARA team has got a suggestion if it is possible to take this out from "gene family" in Biolink? Maybe if we get some suggestion on this from Biolink help desk, I think, we can close this out. Thanks.
