### ISSUE TITLE
in_subset field should be multivalued

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#76]
e.g.

change
```
   in_subset: translator_minimal
 ```

to
```
   in_subset:
      - translator_minimal
 
```

@mbrush - I can easily fix this super-fast, I just want to make sure you are not in the midst of changes here

**Comment by mbrush** [comment]
Hi Chris. good catch  not making edits - you can go ahead and change.

**Comment by nlharris** [comment]
Did this get changed?

**Comment by deepakunni3** [comment]
Yes.
