### ISSUE TITLE
deprecate relation, add "original_" subject, predicate, object edge properties 

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#761]
As discussed in the DM call on 06-03-2021, we should deprecate 'relation' (this will be a change to KGX edges file specification as well).

We will retain the 'original relation' in the form of edge properties using 'original_' keyword in front of subject, predicate, object.

**Comment by aj95b** [comment]
Some predicates (for example, correlated_with) have exact and narrow mappings. The use of relation still helps identify the closer relationship between two nodes. The Wellness KP uses correlated_with as a predicate and then the RO:0002610 to convey it is a statistical correlation. 

Github issues: [731](https://github.com/biolink/biolink-model/issues/731), [335](https://github.com/biolink/biolink-model/issues/335#issuecomment-722084961) and related issue [625](https://github.com/biolink/biolink-model/issues/625). probably need resolution before this change goes through @jh111

**Comment by mbrush** [comment]
@aj95b this is a good point we should consider. In the example you give, the RO term is something that the KP added, correct?  (as opposed to a term provided by the original source).  

This raises a question about how we define and use 'original_predicate': (1) narrowly, such that it can only hold a term that was actually used/provided by the original source; or (2) more broadly, such that it can hold our interpretation of what the original source was saying (e.g. the specific RO term in your example, which represents what the KP thought the original source was saying, even though the original source never actually used it).

With the broader interpretation, I think it would be fine to use the new 'original_predicate' to capture the more precise RO relationship.   But I suspect the narrow interpretation was intended - in which case we may need to keep 'relation' (or some similar association slot) to address the need you describe above.
