### ISSUE TITLE
Alleles and implicated genes in x to phenotype/disease

### ISSUE THREAD

**Issue by kshefchek** [biolink/biolink-model#773]
I noticed Biolink model does not have an association for Allele to phenotype or allele to disease (or allele model of disease). These will likely be necessary when modelling model organism data.

Something also missing is an association slot for implicated genes in any x to phenotype/disease where x is a {variant, allele, genotype}. Since it's often not as simple as joining x -> gene and x -> phenotype to correctly make this inference.

**Comment by nlharris** [comment]
Maybe this should be a topic of discussion at a Data Modeling meeting. @cmungall @sierra-moxon

**Comment by sierra-moxon** [comment]
from koza call - we want implicated in in the predicates hierarchy for monarch.

**Comment by mikebada** [comment]
Two options I can think of: (1) Since alleles are types/variants of genes, broaden the subjects of the GeneToXAssociation classes to include alleles and (2) otherwise, if the subjects of these classes not broadened as such, represent the allele information in allele/variant qualifiers for the subjects.

**Comment by nlharris** [comment]
@kshefchek does that answer your question? If so, please close this issue. Thanks!

**Comment by sierra-moxon** [comment]
@kshefchek - do you think its reasonable to add these to the model even though translator is conflating gene/allele (eventually?).  It makes sense to me to add them.

**Comment by sierra-moxon** [comment]
closing @kevinschaper - if Monarch starts allele->pheno allele->disease ingests, I'm happy to reopen, etc, just let me know :)
