### ISSUE TITLE
UMLS Semantic Type URI Doesn't Resolve

### ISSUE THREAD

**Issue by ericawood** [biolink/biolink-model#776]
The base URI for the UMLS semantic types doesn't resolve:
https://github.com/biolink/biolink-model/blob/763c53f5e656bb5c47d99fe893a2bc60bae70b8c/biolink-model.yaml#L117

Example: https://metamap.nlm.nih.gov/Docs/SemanticTypes_2018AB.txt/code#T121 gives there error

![image](https://user-images.githubusercontent.com/36611732/122305884-647cb500-cebc-11eb-85ac-e6a1082eeba1.png)

Expander Agent has had more success with this base URI: `http://purl.bioontology.org/ontology/STY/`. An example is: http://purl.bioontology.org/ontology/STY/T121.

**Comment by cmungall** [comment]
See also: #749. - yes I also suggested bioportal there

hiwever i think the correct thing to do is first to register on bioregistry.io it may eventually propagate to id.org

**Comment by sierra-moxon** [comment]
original bug is fixed by Chris' PR.  Still need to register UMLSSC with bioregistry.

**Comment by sierra-moxon** [comment]
This was handled in #749
