### ISSUE TITLE
Move Gene out of ChemicalEntity

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#780]
**Is your feature request related to a problem? Please describe.**
Move gene out from under nucleic acid entity, and out of ChemicalEntity entirely.  Maybe put it under BiologicalEntity?

**What working group (or team) did this request originate from?**
Just me :)

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Do you have some recommendations on how this should be modeled?

**Additional information to support this request** (optional)
There are 2 reasons for this request.  One practical (query related) and one theoretical.

Practical:
Suppose I want to find chemical entities that have something to do with asthma.  Sometimes those will be small molecules, but they might also be mixtures like smoke.   The simplest way to write this query would be to write something like:
(ChemicalEntity)-[related to]-(asthma).  
However this will now also return every gene related to asthma, which (I would argue) is not intended, and would be unexpected.

Theoretical:
A gene is not a chemical entity.  An RNA transcript is a chemical entity.  A gene is a conceptual entity that is perhaps best modeled as a somewhat arbitrary collection of transcripts.  (See https://genome.cshlp.org/content/17/6/669.short)

**Tag relevant members for discussion**
@cmungall @sierra-moxon @vdancik

**Comment by nlharris** [comment]
Was this addressed by the latest Biolink release?

**Comment by nlharris** [comment]
Is this done now?

**Comment by sierra-moxon** [comment]
done, closing
