### ISSUE TITLE
Exposures Shouldn't Be Subclasses Their Exposure Type

### ISSUE THREAD

**Issue by ericawood** [biolink/biolink-model#786]
Currently, several exposure classes are subclasses of their exposure type:
 - "chemical exposure" is a subclass of "chemical entity"
 - "biotic exposure" is a subclass of "organism taxon"
 - "genomic background exposure" is a subclass of "biological entity"
 - "disease or phenotypic feature exposure" is a subclass of "disease or phenotypic feature"
 - "environmental exposure" is a subclass of "environmental process"
 - "geographic exposure" is a subclass of "geographic location"
 - "drug exposure" is a subclass of "drug"
 - "behavioral exposure" is a subclass of "behavior"
 - "socioeconomic exposure" is a subclass of "behavior"
 - "pathological process exposure" is a subclass of "pathological process"
 - "pathological anatomical exposure" is a subclass of "pathological anatomical structure"
 With the new semantic operations requirement, this doesn't make sense. The meaning of a subclass relation is that the subclass retains all of the properties of its superclass, it's role being as a more specific version of the superclass. 

I first brought this up to Steve Ramsey, who thought that this seemed problematic. He directed me to Vlado. Vlado directed me to Richard, who committed the `drug exposure` is a subclass of `drug` relationship into the biolink model. His response was:

> that's a bit of ancient Biolink history. Ask Kara Fecho and Steven Cox about where things ended up there.  The design pattern at the time was to model "Exposures" and "Outcomes" as "mixins" in Biolink, then subclass the various exposure agents or outcomes accordingly. Thus a "Drug Exposure" was a child class of "Drug" which has the added (exposure mixin) of being an "Exposure" to that drug
> I haven't myself revisited these models since last year, but the clinical group (perhaps, with some leadership from Matt Brush) may have push the modelling in a different direction now.
> There are other ways of modelling this: 1) as "composition" that is, have an "Exposure" class and give it a node attribute pointing the exposure agent (e.g. a drug)
> 2) model exposure as a node, and the agents of exposures as relationships to that exposure, e.g. "Exposure" has_cause "Drug" (not sure of the predicate here,... just illustrative)
> We should probably post an issue to clean this up. I'm not sure if the conversation is up-to-date, but it is summarized on https://docs.google.com/document/d/1EMRmaPMPruyqDKDvPShMqML4GXRQ5U95skNIA0z9jlA/edit#heading=h.cm7qqn8k0ni3
...
> Bottom line, though, is that the Drug Exposure model you mentioned above might be (or rather, ought to be) deprecated now

I consulted Kara about the `drug exposure` is a subclass of `drug` relationship and this was her response: 

> I apologize for the slow reply. I circulated your question to some of the folks at RENCI and the unanimous response was that it now longer makes sense to treat drug exposureas a subclass of drug in Biolink, the reasoning being that a drug exposure is an event, not a drug.

**Comment by cmungall** [comment]
The addition of these classes passed me by. I agree these are problematic

 - the composition pattern rather than is-a should be used to connect X-exposure to X
 - it's not clear we even need this level of granularity

cc @diatomsRcool
