### ISSUE TITLE
Need prefixes for Protein

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#795]
**Is your feature request related to a problem? Please describe.**
The protein category no  longer has any id_prefixes, causing normalization problems.
I don't quite understand how id_prefixes are or are not inherited, but BMT doesn't seem to be returning any prefixes either.

**Describe the solution you'd like**
Either add back the prefixes from biolink 1.8 to protein, or maybe this is a BMT implementation issue?

**What working group (or team) did this request originate from?**
SRI

**Comment by sierra-moxon** [comment]
right now upstream in linkml, id prefixes are not designated as being inherited, but we fixed this last Friday in linkml.  For now while we wait for the next release of linkml, I think we have to add the prefixes back to Protein.

**Comment by sierra-moxon** [comment]
was released in 2.2.0
