### ISSUE TITLE
`biolink-model.owl.ttl`'s does not have a 'version' property that reflects biolink-model version

### ISSUE THREAD

**Issue by ericawood** [biolink/biolink-model#809]
**Describe the bug**
The `biolink-model.owl.ttl` file's listed version number has remained `1.7.0`, despite new releases coming out. This is from Version 2.1.0:
https://github.com/biolink/biolink-model/blob/615629a4e3ad198b68c3ef08c4e8935816c7deb3/biolink-model.owl.ttl#L1-L18

**Expected behavior**
It would be great if the version number could match the one in the YAML file. (Expander Agent's RTX-KG2 build process depends on the version number in that file for downstream reasoning).

Thank you!

**Comment by sierra-moxon** [comment]
Hi @ericawood, that line in the file is actually describing the 'meta model' (the version of linkml that biolink-model is using).   The meta model is the language model that is used to define the attributes like 'enums', 'symmetric', 'exact_mappings' etc.  In the biolink-model.ttl file (line 16) shows the actual version of the biolink-model, while line 299 shows the same metamodel_version you see in the owl.ttl file.  However, I don't see the 'version' property in the owl.ttl file which seems like a bug (will look into it).  I would avoid using the metamodel_version however, as it is not tied to the biolink-model itself.

**Comment by sierra-moxon** [comment]
@ericawood - the model version number is now appearing in the owl.ttl file
