### ISSUE TITLE
Dead link to technical documentation for BMT

### ISSUE THREAD

**Issue by nlharris** [biolink/biolink-model#810]
The readthedocs link on https://github.com/biolink/biolink-model-toolkit doesn't work:
> Documentation
> The technical documentation for BMT can be found at bmt.readthedocs.io [links to https://github.com/biolink/biolink-model-toolkit/blob/master/bmt.readthedocs.io]

@sierra-moxon do you know whether there should be a different link, or whether something needs to be done to fix that link?

**Comment by nlharris** [comment]
(Note: this was reported by Noel in Slack)

**Comment by nlharris** [comment]
I just noticed that this is a duplicate of https://github.com/biolink/biolink-model-toolkit/issues/47
but I'll leave this issue open for now because it's easier to find here.

**Comment by nlharris** [comment]
@RichardBruskiewich do you by any chance know how to fix this?

**Comment by sierra-moxon** [comment]
I'm adding sphinx, tox etc to bmt in the course of testing cookie-cutter and cruft management.  Should be a PR open this week with these changes. :)

**Comment by sierra-moxon** [comment]
https://biolink.github.io/biolink-model-toolkit/ is up and I am happy for any feedback.
