### ISSUE TITLE
map pharmacological class and side effect in biolink model

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#823]
In addition, it would be great if you can also suggest Biolink mappings for node types such as "Side effect" and "Pharmacologic class".

@karthiksoman

related to #755

**Comment by brettasmi** [comment]
@sierra-moxon , is this ticket still relevant or perhaps has been superseded elsewhere?

I was looking through our mappings today and saw that we still don't have these.

FYI, our pharmacological class comes from [DrugCentral](https://drugcentral.org/) and the side effect comes from [SIDER](http://sideeffects.embl.de/)

The uses would be 
- drug - part of / subclass of / is a - pharmacological class, e.g. naproxen is an anti-inflammatory
- drug - causes / exhibits? - side effect, e.g. naproxen causes dyspepsia

**Comment by brettasmi** [comment]
As I was thinking about this more, I remembered that side effects are usually covered elsewhere in Translator as "drug causes disease or phenotypic feature."

I'm not savvy enough to know if that is the best implementation or if keeping the semantics of "side effect" is important to the user. Perhaps there is a qualifier or mix-in for "causes"?

**Comment by sierra-moxon** [comment]
@brettasmi 
we did just recently add 'has chemical role' to the ChemicalEntity class.  Does that collection the use case of anti-inflammtory? (note 'has chemical role' is a slot that is a collection of 'chemical role' objects that inherit from the attribute class.  So you could in theory specify more details about the role if you needed to). 

For side effects: 
do we need to worry about side effects occurring differently in the context of the treatment/disease or is this kind of "side effect" something that we'd want to record as always "a possible side effect" of this particular drug?
Also, what kind of other data from SIDER do you want to record (the link above talks about frequency of side effects, etc. as possible data they also store).

**Comment by brettasmi** [comment]
Thanks for the response @sierra-moxon 
> We did just recently add 'has chemical role' to the ChemicalEntity class. Does that collection the use case of anti-inflammtory?
For our use case, this would probably cover it, but I'll take it back to the group and ask around as well.

> Dd we need to worry about side effects occurring differently in the context of the treatment/disease or is this kind of "side effect" something that we'd want to record as always "a possible side effect" of this particular drug?
This is where I am not savvy enough to answer this myself. I think I'd have to speak with a clinical expert to see if they'd want that context available.

> Also, what kind of other data from SIDER do you want to record (the link above talks about frequency of side effects, etc. as possible data they also store).
As far as I can tell, the SPOKE developers are currently only storing the association between a drug and a side effect as well as the [side effects themselves](http://sideeffects.embl.de/se/)

I will take your questions back to the imProving team and follow up when I have some responses. Let me know if my responses bring anything else to mind from you.

**Comment by sierra-moxon** [comment]
One suggestion from the QotM session this morning, was to add "causes side effect" to the "causes adverse event" predicate.  Jennifer noted that there can be "positive" side effects as well, but Sui said that the colloquial understanding of the words "side effect" were "negative side effect."

@brettasmi - it might be a Arcitecture/UI question as to how we'd use they synonym 'causes side effect' in queries and results.  @cbizon - do you know if ARAs treat model component synonyms as equivalent to the actual model component?  (e.g.: if I write a TRAPI query that uses "causes side effect" as the predicate, will ARAs return triples with the "causes adverse event" predicate?)

**Comment by sierra-moxon** [comment]
@cbizon - I think I am of the opinion that aliases in a user-facing interface should return their biolink-model identifiers, but probably not in TRAPI directly. 

how about the 'mappings' constructs in biolink-model.  I can add 'NCIT:C2861 # side effect' as a narrow_mapping to causes_adverse_event.  Would that be picked up by any tooling already (maybe node-norm uses mappings constructs?)

**Comment by karafecho** [comment]
Also see: https://github.com/NCATSTranslator/Feedback/issues/76.
