### ISSUE TITLE
PANTHER sub families are not handled

### ISSUE THREAD

**Issue by PhillipsOwen** [biolink/biolink-model#824]
**Describe the bug**
the biolink model does not seem to support the PANTHER.FAMILY sub-families. 

**To Reproduce**
biolink does not seem to support this representative example: PANTHER.FAMILY:PTHR10104:SF18

**Expected behavior**
I would have expected that the biolink model would support the PANTHER.FAMILY sub-families CURIEs natively.

**What working group (or team) did this request originate from?**
This was discovered by the RENCI SRI team while using KGX (https://github.com/NCATS-Tangerine/kgx.git) when loading KGX jsonl files into a graph.

**Additional context**
RENCI data parsers create KGX files from raw data sets. in this case, the KGX files created from raw PANTHER data did not load via KGX into the graph properly. KGX throws the following error: Warning: node id PANTHER.FAMILY:PTHR10104:SF18 has no CURIE prefix. this is presumably due to insufficient support of PANTHER sub-families in the biolink model.

**Tag relevant members for discussion**
@RichardBruskiewich 

Relevant data for this issue can be found at https://stars.renci.org/var/plater/ filename: PANTHER_curie_issue.zip

**Comment by RichardBruskiewich** [comment]
The joy of it all: if I plug the URI - **http://identifiers.org/panther.family/** - associated with the prefix of the CURIE you've provided -  **PANTHER.FAMILY:PTHR10104:SF18** - one gets the URI **http://identifiers.org/panther.family/PTHR10104:SF18** which resolves as a URL just fine, into http://www.pantherdb.org/panther/family.do?clsAccession=PTHR10104:SF18

Not sure if LinkML or Biolink itself is the point of intervention to deal with this, so I've assigned this issue to both Harold and Sierra.

**Comment by sierra-moxon** [comment]
yep, upstream in prefix commons, the URL string used relies on a lowercase prefix ('panther.family').  
We can support this as a stop gap in biolink-model itself and revisit how to support casing upstream in linkml (potentially).

**Comment by RichardBruskiewich** [comment]
Hi @sierra-moxon, there's an additional complexity here: the **object identifier** of panther.family curies also contain a **colon**! Aargh!
