### ISSUE TITLE
MolePro wants to introduce two new id prefixes based on the BiGG Model knowledge source

### ISSUE THREAD

**Issue by nlharris** [biolink/biolink-model#825]
BIGG.METABOLITES - small molecule
BIGG.REACTION - molecular activity
(Requested by Larry Chung)

**Comment by nlharris** [comment]
Addressed in Biolink Help Desk on 26-July-2021 (see linked PR)

**Comment by codewarrior2000** [comment]
@nlharris  @sierra-moxon 
I am sorry, it was my fault for making a typo in one of the id prefixes. Please correct it to "BIGG.METABOLITE - small molecule" for me.  Many thanks!
