### ISSUE TITLE
markdown issue: subsets are showing up as classes

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#828]
this is pretty confusing:

https://biolink.github.io/biolink-model/docs/Samples.html

I thought - why have we a class named in the plural?

until you realize the 'samples' is actually the name of a subset. Arguably not the best name for a subset. However, the docs should not label subsets as classes

**Comment by sierra-moxon** [comment]
https://biolink.github.io/biolink-model/#subsets are no longer listed as classes
