### ISSUE TITLE
Class for adverse events?

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#83]
Aeolus returns adverse events for a drug as MedDRA codes.   Some of these MedDRA codes seem to be equivalent to MONDOs, and some to HP, but many (most?) don't seem to be either.  A lot of them are more event-like (drug reactions or miscarraige, etc).    Is there a class in biolink-model for these things?  Or do we want to consider them phenotypes?  That doesn't seem quite right...

**Comment by cmungall** [comment]
We have things like miscarriage in HPO. I think it gets a bit arbitrary trying to split the classes into AEs vs pheno vs disease. Instead can we treat this more as a role? E.g. if it's at the end of a suitable edge label or comes from a drug node, we can think of as an adverse effect. We could have an Association template for this.

cc @pnrobinson @mbrush

**Comment by pnrobinson** [comment]
I would vote to model AEs as phenotypes (usually) or rarely diseases (e.g., adverse event to a transfusion that is contaminated with hepatitis C). We did a mapping from the SIDR database (which itself just uses UMLS) to HPO a long time ago and could map about 95% of side effects to HPO terms with no problem. Most of the remaining 5% were mistaken (in SIDR).

**Comment by cbizon** [comment]
So is the missing piece here mappings between MedDRA (or the subset of it in Aeolus) and HPO?

**Comment by nlharris** [comment]
Did this get resolved?

**Comment by sierra-moxon** [comment]
I believe we have both MedDRA and Aeolius mappings in the model at the moment.  Please feel free to reopen if what we have isn't sufficient. :)
