### ISSUE TITLE
non-inverted predicates exist

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#831]
The following predicates do not have inverses in the model. 
active in
mentions
contributor
provider
publisher
editor
author
affects activity of
predisposes
ameliorates
exacerbates
occurs in
capable of
affects expression in
disease has basis in
in taxon

**Comment by ehinderer** [comment]
1) Are there other predicates that could serve as inverses, to some of these or would they all need to be created?
2) Do all need inverse predicates? e.g. in_taxon vs. taxon_of
3) Are the provenance examples even invertible? What would be the inverse of contributor, provider, publisher, editor, or author?
