### ISSUE TITLE
Report on recent updates to TKG min predicate set

### ISSUE THREAD

**Issue by mbrush** [biolink/biolink-model#84]
Summarizing recent updates/developments to the TKG min predicate set. Apologies again for any changes that require updates to your KGs - input from new sources/KGs has required additional predicates and updates to labels of a few existing ones for the sake of clarity and consistency. 

The good news is that the biolink-model.yaml file is now the single source of truth for TKG min predicates, and we are able to generate [this handy github.io webpage](https://biolink.github.io/biolink-model/docs/) that will show the current hierarchy at all times.  Specifically, the 'Predicates and Properties' tagged as in the **translator_minimal** subset are those that should be used.  As for category labels on **nodes** in TKGs, ANY of the 'Classes' in the BLM are acceptable.  

Hope this helps developers standardize their KGs in run up to the hackathon.  Changes to the min predicates over the past week or two are summarized below.  Feedback/suggestions welcome.

----------------

### Updated labels
- directly interacts with -> physically interacts with
- affects risk for condition -> affects risk for
- enables -> capable of
- associated with condition -> gene associated with condition
- treats condition -> treats

------

### Deprecated predicates
- deprecated 'has affected sequence feature' (just use 'affects')
- deprecated 'causes or contributes to' (use 'contributes to', which is now the parent of 'causes')

-------

### New predicates
- contributes to
- correlated with
- biomarker for
- interacts with
- genetically interacts with
- co-localizes with
- participates in                        
- actively involved in          
- capable of          
- overlaps
- has part
- paralogous to
- orthologous to 
- xenologous to 
- affects
 - disrupts
- expresses
- occurs in
- located in
- location of
- model of
- derives from
- produces
- predisposes
- has input
- same as

**Comment by nlharris** [comment]
Is there an action item here or can this be closed?

**Comment by deepakunni3** [comment]
Yes, this has been superseded by many subsequent discussions.
