### ISSUE TITLE
Utility of mixin slots for 'stimulates' and 'inhibits?

### ISSUE THREAD

**Issue by mbrush** [biolink/biolink-model#85]
Thoughts on mixin predicates for the notions of 'stimulates' and 'inhibits' - which are broader than the existing notions of positively and negatively regulates.  These could live under blm:affeccts, and be mixin parents of blm:positively regulates and blm:negatively regulates, respectively.

One use case here is that SemMedDB uses STIMULATES and INHIBITS predicates largely to describe regulation between entities (e.g. gene/protein regulating gene/protein), but also in other ways that wouldn't qualify as entity-entity regulation (e.g. statements that a procedure STIMULATES physiologic functions, and statements that a chemical INHIBITS cellular functions).

Beyond this specific use case (which may not be long lived if we abandon semmeddb as a reliable data KS for the translator) would it  generally be useful to have predicates  for describing cases where thing 1 stimulates/increases or impairs/decreases thing 2 (which may or may not cases of  biological regulation)?

**Comment by mbrush** [comment]
once resolved, add mappings of these predicates to BLM (to pos/neg regulates e to e if we don't add the new predicates proposed above)

**Comment by nlharris** [comment]
Is this done?
