### ISSUE TITLE
Incorrect SNOMED prefix

### ISSUE THREAD

**Issue by balhoff** [biolink/biolink-model#855]
I noticed this in the context file:

https://github.com/biolink/biolink-model/blob/4ce314c2d73b6c7ed3def1ecbed01cec35f3f3c5/context.jsonld#L390-L393

SNOMED shouldn't expand to the OBO prefix.

**Comment by nlharris** [comment]
@balhoff so what should the bit you quoted say instead?

**Comment by balhoff** [comment]
I'm not that familiar with SNOMED, but I know it's not in OBO. :-) The Biolink context also has `"SNOMEDCT": "http://identifiers.org/snomedct/"`, which is better. I would expect that SNOMED has their own preferred namespace used in their OWL file.

**Comment by sierra-moxon** [comment]
SNOMED should probably be removed from the copy of monarch context upstream in prefixcommons.  Likely, prefixcommons is out of date with the monarch context.  Fixing in biolink-model for now.
