### ISSUE TITLE
Conventions for use of has_phenotype predicate in BLM and TKGs

### ISSUE THREAD

**Issue by mbrush** [biolink/biolink-model#90]
**Preface:** In the text below, 'condition' subsumes the notions of 'phenotypic features' and 'disease'
 
**Issue:** 
The has_phenotype relation has historically been used to describe three different types of relationships:

1. linking **diseases** to **phenotypic features** that are part of or characterize them
2. linking **organisms** or **anatomical entities** to **conditions** (phenotypes or diseases) they exhibit
3. linking **genes** or **genetic variants/genotypes** to **conditions** (phenotypes  or diseases) they cause or contribute to.
 
The third use of has_phenotype is problematic because there are other relations (e.g. contributes_to or causes) that can be used for describing causal relationships between genes/variants and conditions.  This means that some KGs may choose to link gene or variant to a condition using has_phenotype, and others may choose to use contributes_to or causes.
 
Complicating this further is the fact that genes as a class do not 'cause' conditions in the same way that their variants do,  and it is commonplace to see causes, contributes_to, or has_phenotype used to link genes to conditions.  For this reason we created the 'gene associated with condition' predicate in the BLM specifically for linking genes to conditions (where abnormalities in the sequence or regulation of the gene contributes to the condition). 
 
Given this state of affairs, the following proposal prescribes conventions for predicate use in linking entities (genes, variants, genotypes) to using for the BLM and TKG spec.
 
1. Linking a '**disease**' to a **'phenotypic feature**' that characterizes it --> use _has_phenotype_
2. Linking an affected '**organism**' or '**anatomical entity'** to a '**phenotypic feature or disease'** it exhibits  --> use _has_phenotype_ 
3. Linking a '**gene**' to a '**phenotypic feature or disease**' --> use _gene_associated_with_condition_
4. Linking a '**sequence variant**'/'**allele**'/'**genotype**' to a '**phenotypic feature or disease**' it causes or contributes to  --> use  _contributes_to_ (if there may be additional causal factors), and use  _causes_ (if the variant alone is causal)

Note for case 2 above, we should consider a more appropriately named predicate that considers use for linking organisms to diseases they exhibit as well as phenotypes (e.g. _has_condition_, or _exhibits_condition_, or _manifests_condition_).

Hoping this will clarify when to use has_phenotype vs other predicates, and promote consistent use  of these predicates across efforts. Feedback welcome, in particular from @cjmungall @mellybelly.

Once  we make  final decisions here, we can formalize in the BLM spec using the 'predicate' slot of association classes for each of these types of associations.

**Comment by mbrush** [comment]
@kshedckek For Monarch, I think the only area we are not compliant with the proposal is our edges linking variants/genotypes to 'phenotypic features', where we currently use _has_phenotype_ instead of _causes_.  And perhaps also linking genes to conditions, where we may also use _has_phenotype_ instead of _gene_associated_with_condition_. 

Of course, the predicates we use for Monarch may or may not be the same ones we use in Monarch-Lite to achieve TKG spec compliance.

**Comment by sierra-moxon** [comment]
closing for now, I believe all these concepts are adequately represented in the model - please reopen if necessary as always :)
