### ISSUE TITLE
Field on slots to define conventions of use in context of specific projects

### ISSUE THREAD

**Issue by mbrush** [biolink/biolink-model#91]
In defining predicates for the Translator minimal set, it is becoming clear that we need also to prescribe when and how each should be used. Important as many predicates are fairly generic and has no strict domain and range constraints.  Some specific examples provided in comment below.

One proposal is to extend the utility of the in_subset field to capture this type of info.  Will flesh out ideas here shortly.

**Comment by mbrush** [comment]
Examples of associations where conventions of use would be helpful:

**1. Gene-Process/Activity (what level of participation to assign to different associations):**
- Gene/Product - Pathway  --> participates_in
- Gene/Product - Biological Process --> actively_involved_in
- Gene/Product - Molecular Activity--> capable_of
  
**2. Disease-Anatomy:**
-  occurs_in? located_in? affects?
 
**3. Gene-Phenotype:** 
- has_phenotype?  causes?  gene_associated_with_condition?

**Comment by sierra-moxon** [comment]
per discussion at the predicates wg meeting, this is being closed for now - we can revisit/reopen at a later time.
