### ISSUE TITLE
is there a predicate that would correspond to `rdf:type`?

### ISSUE THREAD

**Issue by saramsey** [biolink/biolink-model#912]
In `go-plus.owl` (converted to OBOgraph-JSON using `owltools` and then loaded using `ontobio`), there are some triples that come to us like
```
(IAO:0000428, rdf:type, IAO:0000078)
```
(here, `IAO:0000428` is the subject, and `IAO:0000078` is the object). I gather from looking at RDF documentation that we should probably use such triples as a guide to determine the `category` of the subject. But is it correct to also realize that triple as an "association" in the Biolink representation of the ontology?  i.e., as an "edge" in the KGX-TSV version of that ontology?  If so, what Biolink predicate should we use?  For now, we are opting to use `related_to` since something about `subclass_of` doesn't feel right, to approximate the meaning of `rdf:type`. Thanks for any advice.

**Comment by saramsey** [comment]
Tagging @acevedol who brought this issue to my attention as we were working on making RTX-KG2 compliant with Biolink 2.2.6.

**Comment by balhoff** [comment]
`rdf:type` corresponds to the Biolink slot `type`. In OWL, `rdf:type` relates individuals (instances) to a class they're a member of. `IAO:0000428` is an instance of the class `IAO:0000078`. Does that clarify anything?

**Comment by saramsey** [comment]
Thanks @balhoff! So it is sounding like we should not realize the aforementioned triple as an "edge" in the Biolink/KGX knowledge graph, but should instead put this information in a `type` slot on the node for `IAO:0000428` ?

**Comment by saramsey** [comment]
Thanks @balhoff. So, I guess ideally, in a Biolink object model, the entity `IAO:0000428` should have a slot `type` that refers to `IAO:0000078`?

**Comment by sierra-moxon** [comment]
@saramsey - I think that is correct.

Do you need anything else from this ticket?  :)

**Comment by saramsey** [comment]
Thanks @sierra-moxon. I think we can close out the ticket.
