### ISSUE TITLE
Remove commas (and any other symbols) from names

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#92]
The "name" entity in the biolink model classes are meant to be used as "types" and "labels" in neo4j.  (when snake cased).

neo4j doesn't allow symbols in the names of types and labels: https://neo4j.com/docs/developer-manual/current/cypher/syntax/naming/

So these should be removed from the names somehow.  In particular something like "regulates, entity to entity".   It might even make sense to put specific labels on the classes/relations, at least for the translator_minimal subset such that there is no room for error in devolving the names provided into neo4j strings.

**Comment by deepakunni3** [comment]
@cmungall This is still a problem. We cannot have relations with commas. 
How is this being handled when translating the YAML to different products?

**Comment by nlharris** [comment]
Is this still a problem?

**Comment by deepakunni3** [comment]
Yup, still a problem :(
