### ISSUE TITLE
Review and update Translator Ontology Primer

### ISSUE THREAD

**Issue by nlharris** [biolink/biolink-model#924]
A few years ago, @cmungall put together this useful document: [An Ontology Primer for the NCATS Data Translator Reasoner Teams](https://docs.google.com/document/d/1faKOTMOrH4vn8NHx9s8WzdDujOkKu0RwaYZPrdtmnoI/edit).

We should look at this and make any needed updates or additions.

(I wasn't sure where to put this ticket -- it doesn't really belong here, but I didn't find another good place for it.)

**Comment by nlharris** [comment]
That doc was written in 2018, so it's probably mostly obsolete. Should we give up on this and close this ticket as won't do?

**Comment by sierra-moxon** [comment]
@nlharris - I read through this doc today, and it still seems good and relevant to me?  Is there a more specific Translator issue/question/problem that we want to answer with this doc?

**Comment by sierra-moxon** [comment]
I think this is still a good doc, closing for now, please reopen if my read-over the doc missed some key changes that obsolete it.
