### ISSUE TITLE
decreases activity of <-> activity is increased by 

### ISSUE THREAD

**Issue by kennethmorton** [biolink/biolink-model#925]
I believe that one of these two inverse predicates should be annotated as biolink:canonical_predicate.

I have no preference for which is the canonical predicate, however ranking agent has observed "decreases activity of" as the only one of these two in use by some data sources. We have also observed both predicates in use in TRAPI queries. Some knowledge sources such as SemMed DB appear to contain both predicates.

**Comment by nlharris** [comment]
See also #657
