### ISSUE TITLE
BFO:0000066 mapped twice

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#93]
Both occurs_in and located_in have a mapping to BFO:0000066.

Does it make sense for both terms to map to the same identifier?  Does this mean that occurs_in=located_in?

Also, maybe I'm missing something, but I can't find any reference to this CURIE existing anywhere?

**Comment by cmungall** [comment]
This is just a mistake, it should only be for occurs_in. Now we have changed the format of the YAML we can go in and make the fix

**Comment by mbrush** [comment]
fixed with PR #113
- removed mapping of blm:located in to BFO:0000066 - and replaced with mapping to RO:0001025 (located in)
- also moved mapping to WD:276 (location) from blm:located in to blm:location of

**Comment by nlharris** [comment]
sounds like this was fixed; closing
