### ISSUE TITLE
Missing / different mappings for semmeddb node categories

### ISSUE THREAD

**Issue by colleenXu** [biolink/biolink-model#935]
**Is your feature request related to a problem? Please describe.**
Biolink-model is missing mappings for some SEMMEDDB terms (node categories). Additionally, Service Provider / BTE will use different mappings from what is in the biolink model for some SEMMEDDB terms...

<br>

Missing mappings, Service Provider maps these to SmallMolecule:
* STY:T123 (bacs, full name: Biologically Active Substance) 
* STY:T131 (hops, full name: Hazardous or Poisonous Substance) 
* STY:T125 (horm, full name: Hormone) 
* STY:T197 (inch, full name: Inorganic Chemical) 
* STY:T109 (orch, full name: Organic Chemical) 
* STY:T118 (carb, full name: Carbohydrate) - note that this term is missing from newer SRDEF files (depreciated?), but is still used by the SEMMEDDB data files)
* STY:T111 (eico, full name: Eicosanoid) - same note as above
* STY:T119 (lipd, full name: Lipid) - same note as above
* STY:T124 (nsba, full name: Neuroreactive Substance or Biogenic Amine) - same note as above
* STY:T115 (opco, full name: Organophosphorus Compound) - same note as above
* STY:T110 (strd, full name: Steroid) - same note as above

<br>

Missing mappings, Service Provider maps these to other biolink terms:
* STY:T129 (imft, full name: Immunologic Factor) -> ChemicalEntity

<br>

Service Provider / BTE uses different mappings from biolink-model, so the data integrates with other sources better (multi-hop queries):
* STY:T195 (antb, full name: Antibiotic) -> We map it to SmallMolecule (rather than Drug)
* STY:T121 (phsu, full name: Pharmacologic Substance) -> We map it to SmallMolecule (rather than Drug)
* STY:T028 (gngm, full name: Gene or Genome) -> We map it to Gene (rather than GenomicEntity)
* STY:T114 (nnon, full name: Nucleic Acid, Nucleoside, or Nucleotide) -> We map it to SmallMolecule (rather than NucleicAcidEntity)
* STY:T127 (vita, full name: Vitamin) -> We map it to SmallMolecule (rather than Vitamin)

**Describe the solution you'd like**
Action to add the missing terms would be nice. The different mappings are more of an FYI / food-for-thought. 

**What working group (or team) did this request originate from?**
Service Provider / Exploring Agent

Note: This is relevant for members of NCATS Translator.

**Additional context**
This is not a complete list of the SEMMED terms (node categories) that don't have mappings. The full list is under the heading `3.5  review mappings and deciding what to change, remove` of this [notebook](https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/semmeddb/AutoGen_SEMMEDDB.ipynb)

**Tag relevant members for discussion**
Tag all relevant members to this ticket to start a discussion.

**Comment by colleenXu** [comment]
Note that the following were mapped to PathologicalProcess...which is a mixin. Is that alright or should those be mapped to a non-mixin?

T037 | Injury or Poisoning | inpo 
T046 | Pathologic Function | patf

**Comment by sierra-moxon** [comment]
it doesn't look like in the current BM "PathologicalProcess" is a mixin.   I'll leave these as they are now. 
T037 | Injury or Poisoning | inpo
T046 | Pathologic Function | patf

I can take care of most of the rest, we might wish to talk about the conflation use cases above with the larger group.

**Comment by colleenXu** [comment]
I checked again, looks like I misread the pathological process entry. Even in version 2.2.13, [it's a biological_process child](https://github.com/biolink/biolink-model/blob/e911ce3109a7b95c210faa16713a89e1f96c6379/biolink-model.yaml#L8743), not a mixin.
