### ISSUE TITLE
deprecate approved_to_treat in favor of FDA approval and regulatory status worldwide edge and node properties

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#937]
'approved to treat' predicate is redundant with the new FDA and worldwide approval status edge and node properties.
we should probably deprecate 'approved to treat' and move its metadata to regulatory status worldwide (and make it a parent of FDA approval status?)

**Comment by ehinderer** [comment]
This will also be relevant to my "Drug Target Landscape" use case proposal:
https://github.com/NCATSTranslator/Clinical-Data-Committee-Tracking-Voting/issues/9
