### ISSUE TITLE
Is there a class for "material entity"?

### ISSUE THREAD

**Issue by nlharris** [biolink/biolink-model#939]
@bill-baumgartner wrote (in Slack):
Hi DM folks, I have a Biolink question. The phrase material entity is used in the description for a number of Biolink predicates and classes, e.g., the description for the located in predicate is:
> holds between a material entity and a material entity or site within which it is located (but of which it is not considered a part)

I don’t see a class in Biolink for material entity however. Apologies in advance if I have simply failed to find it, but should there be one, or should this description reference a different class?
The context for this question stems from the recent standup queries that have been targeting  disease-to-anatomical_part  relations. One of the predicates that has been used is located_in. I am wondering if that is a valid predicate for this relationship, i.e., does Biolink consider disease to be a material entity?

**Comment by sierra-moxon** [comment]
- [ ] add a domain and range for located_in predicate

@bill-baumgartner - would an example of disease located in the anatomical part be 'gout location in the big toe'?  And this would be to be able to connect anatomical terms to the disease that affect them.  Perhaps 'affects' would be good here?

**Comment by bill-baumgartner** [comment]
Hi @sierra-moxon , yes, I think that's a reasonable example. The target for the standup query was `myocarditis located_in heart`. I see that there is a [disease has location](https://github.com/biolink/biolink-model/blob/312bb00f93985a9473258248966a807126724f71/biolink-model.yaml#L4667) predicate, so perhaps that is the one to use instead?

The use of `occurs in` also came up in this context. In the case of `myocarditis occurs_in heart` the disease would have to be modeled as a process which seems plausible, but does Biolink allow for that? Looks like `occurs in` could also use a domain and range.
