### ISSUE TITLE
Are antibody therapeutics ChemicalEntities or Proteins? 

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#940]
What is the most appropriate category to assign to the active ingredient in a monoclonal antibody therapeutic like bevacizumab (Avastin)?  Seems to me it is not a biolink:SmallMolecule because it is not small; and it is not a biolink:MolecularEntity because it has subunits that are not covalently bonded together; should we use biolink:ChemicalEntity or biolink:Protein?
(Expander Agent)

**Comment by sierra-moxon** [comment]
@vdancik 
I suggested that Expander Agent use ChemicalEntity for now as the 'treats' predicate asks for a ChemicalEntity in its domain.  Antibodies in general are not currently modeled in biolink - we might want to think about where they belong?

**Comment by vdancik** [comment]
Actually, we can also consider to use biolink:ChemicalMixture.
