### ISSUE TITLE
Mapping from Trait Ontology to Biolink Model Classes

### ISSUE THREAD

**Issue by Shalsh23** [biolink/biolink-model#946]
**Is your feature request related to a problem? Please describe.**

I am interested in importing Arabidopsis gene-phenotype relations into our knowledge graph. The GWAS associations btwen Arabidopsis genes and phenotypes are available on [AraGWAS catalog](https://aragwas.1001genomes.org/#/), and they references the phenotypes from [AraPheno](https://arapheno.1001genomes.org/). The phenotypes on AraPheno use the Trait Ontology. For example, here is the link to a GWAS [study](https://aragwas.1001genomes.org/#/study/144) which references AraPheno [phenotype](https://arapheno.1001genomes.org/phenotype/144/), which in turn is referencing a Trait Ontology term.    

- I want to add mappings from Trait Ontology to Biolink Model classes

@cbizon

**Comment by sierra-moxon** [comment]
@Shalsh23 - check out the [phenotypic feature class.](https://biolink.github.io/biolink-model/docs/PhenotypicFeature.html)?  I think we'd need to add TO to the id prefixes section of that class, but the 'plant trait' sub-hierarchy of TO seems to fit our definition of PhenotypicFeature.

**Comment by sierra-moxon** [comment]
@Shalsh23 - closing for now, please do reopen if I haven't adequately answered your question.  :)

**Comment by cbizon** [comment]
Hi @sierra-moxon has TO actually made it into the id prefixes?
