### ISSUE TITLE
Representing combination of multiple terms using biolink

### ISSUE THREAD

**Issue by Shalsh23** [biolink/biolink-model#947]
**Is your feature request related to a problem? Please describe.**

We are exploring the ingestion of [RARGE](http://rarge-v2.psc.riken.jp/) database ([ref paper](https://academic.oup.com/pcp/article/55/1/e4/1840279)), which has data about Arabidopsis gene phenotype relations. 
 However, they are defining phenotypic concepts for Arabidopsis using a combination of terms from multiple ontologies. For example, one of the phenotypic terms is `whole plant::decreased height` which is represented using `po:0000003 pato:0000569` as seen [here](http://rarge-v2.psc.riken.jp/trait/search?q=po:0000003+pato:0000569).

Will it be possible to use the biolink model to represent these kinds of combinatorial terms?

**Tag relevant members for discussion**
@cbizon

**Comment by sierra-moxon** [comment]
Good questions!

Some folks in our group are dedicated to making single phenotype ontology terms out of these multi-ontology term statements via the upheno effort: https://github.com/obophenotype/upheno/wiki/Phenotype-Ontologies-Reconciliation-But for plants is probably a bit farther away (eg: the mappings and patterns haven't been formalized yet for plants so we can't get this conversion for free here yet).   

The biolink model metamodeling framework has a number of modeling components that we used to divide the semantics of a knowledge statement into (the "onion" diagram here might help define these divisions a bit more): 

<img width="643" alt="Screen Shot 2022-02-15 at 10 33 14 AM" src="https://user-images.githubusercontent.com/4561292/154126526-c268e04c-7b57-41f6-928f-300de607bf91.png">

What about for this use case, we try something like:
subject: geneX
predicate: has_phenotype
object: biolink:PhenotypicFeature (Maybe with a hash key generated from the logical definition of the phenotype. Something like 'whole_plant_decreased_height' ?).

where subject and object are nodes in a graph and the predicate is the edge between those nodes.

then your PhenotypicFeature node would have the multivalued property:
has_attribute: ['PO:000003', 'PATO:0000569']

@cmungall

**Comment by matentzn** [comment]
@Shalsh23 in our experience, it is often better to "coordinate" such post-coordinated annotations for consumptions into knowledge graphs. For example at ZFIN, g2ps are similarly curated using combinations of PATO and anatomy terms, and occasionally GO biological process terms. To classify this kind of precoordinated phenotype data, it is often best to:

1. Select appropriate uPheno computational patterns
2. Manifest the pre-coordinated descriptions into OWL using DOSDP tools
3. Run the reasoner to classify the phenotype entirely
4. classify the data against uPheno to compare it with other species.

Having an ID for each phenotype makes it much easier to:
1. Provide landing pages for a KG based application
2. Classify phenotypes data correctly
3. Link phenotypes with related data

It is probably worth corrdinating this kind of work with @marieALaporte and @cooperl09.

This is an example ontology that is entirely generated from post coordinated data such as the one you are talking about:

https://github.com/obophenotype/zebrafish-phenotype-ontology

**Comment by sierra-moxon** [comment]
Hi @Shalsh23 - does this biolink model solution work for you (without a single ontology, yet)?

**Comment by sierra-moxon** [comment]
@Shalsh23 - closing for now, please do reopen if I haven't adequately answered your question or we need to discuss it on a data modeling or biolink helpdesk call?  In particular, if you are interested in generating a pre composed ontology from the post coordinated plant phenotype data, we can organize a meeting with the plant oncologists and the phenotype ontologies folks. :)

**Comment by cbizon** [comment]
It seems like having a unified ontology via upheno would be the best thing here for sure.

In the absence of that, though, I'm not 100% sure how this works.  We can certainly generate a hashed id of some kind.  And we can stick it in the id-field of our database.   And this might be a minor concern, but it won't be biolink compliant because the id prefix will be something we made up?

**Comment by mbrush** [comment]
Agree that if we can relatively quickly coordinate with the plant and uPheno folks to generate a proper OBO ontology for these phenotypes we should.  As I understand it the machinery to do this as all there - just a matter of mapping the post-composed phenotype combinations to uPheno design patterns, and running DOSDP tools to generate an ontology.  I know a couple Phenotype curators who could knock this out pretty quick (if there are a reasonable number of them).  But there are likely also sociotechnical coordination issues to consider. 

Barring that, another approach to generating unique ids for these phenotypes is to just concatenate their PO/PATO ids together into a single IRI/CURIE.  I think the GO folks did these to quickly generate terms for abnormal CC/MF/BP phenotypes based on GO annotations with a IMP evidence code.   If its just temporary (until we get proper uPheno IRIs) - this might be worth considering,.

**Comment by sierra-moxon** [comment]
@cbizon - is this closeable?  I will make the bold step of closing and you can tell me to reopen if further discussion is needed?  From our helpdesk call a month ago, I believe the action forward was the path documented on Feb. 14:
```
an edge is made like this:
subject: geneX (biolink:Gene)
predicate: has_phenotype (biolink:has_phenotype)
object: hashid_for_phenotype (biolink:PhenotypicFeature) (the hashid could be generated from the logical definition of the phenotype? in plain text, something like 'whole_plant_decreased_height' ?).

The association here would be: biolink:GeneToPhenotypicFeatureAssociation

then your PhenotypicFeature node (in graph language) would have the multivalued property:
has_attribute: ['PO:000003', 'PATO:0000569']
```
