### ISSUE TITLE
add regex validation to curie or URI

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#948]
In the switchover from Koza pydantic to LinkML pydantic models, Kevin pointed out that we might want more regex validation in biolink model (in particular some rules for validating that something is a curie).  

FYPCO (pombase) is the example here. Column 14 from the pombase gene to phenotype file ingest.

From the Monarch data ingest call Feb 14, 2022

**Comment by sierra-moxon** [comment]
We discussed this in LinkML and decided to add the regex matching to the URIorCurie data type, I believe.

**Comment by cmungall** [comment]
See also #127 -- metamodelcore already does regex checking on these types, though I think having the regexes in the actual metamodel schema is better than hardcoding
