### ISSUE TITLE
relation for "consumes"

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#95]
One of the current MVP queries of interest is something to the effect: "Find proteins that consume/sequester chemical X".    There is also a similar question for "produces", but there's already a produces edge.   

Of note, CTD also has relationships "increases abundance", "decreases abundance", and "affects abundance".   I kind of like these better than the produces/consumes language because the abundance statement is not as direct.  Produces sounds very hands-on.

**Comment by nlharris** [comment]
@cbizon can you clarify what your question or request is?

**Comment by cbizon** [comment]
How would I make the statement that 
"Protein P metabolizes the reaction that consumes chemical C?" (i.e. C is the substrate of P)
How would I make the statement that
"Protein P somehow (possibly indirectly) reduces the amount of C?"

**Comment by sierra-moxon** [comment]
in chemical working group - the inverse predicate consumed by needs an is_a: relationship.
