### ISSUE TITLE
Biolink documentation: move useful links to top of the left sidebar

### ISSUE THREAD

**Issue by nlharris** [biolink/biolink-model#951]
@vdancik had a suggestion re https://biolink.github.io/biolink-model/docs/: move useful links that are currently at the bottom of the left sidebar to the top.
![Screen Shot 2022-02-28 at 10 03 33 AM](https://user-images.githubusercontent.com/348704/156035302-65f15544-0b61-43dd-b2e3-be3bb7a2f00d.png)

Sierra said they are discussing making the Biolink documentation use the same theme/template as other documentation (e.g. LinkML)

**Comment by sierra-moxon** [comment]
https://biolink.github.io/biolink-model/ new nav hierarchy is deployed -feedback welcome

**Comment by sierra-moxon** [comment]
https://github.com/biolink/biolink-model/pull/1418
