### ISSUE TITLE
Represent Lipid, macromolecule from ChEMBL

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#960]
ChEMBL identifies identifies [25 target types](https://docs.google.com/spreadsheets/d/1r8rI6hiiti5jMdQZPSI9aguk49TucoogxiSciWR8_k4/edit#gid=292122141)
in their latest release. 

These don't have an equivalent in the Biolink Model:
LIPID
MACROMOLECULE
SELECTIVITY GROUP
UNCHECKED
UNKNOWN

Thanks @codewarrior2000 for bringing up this issue.

**Comment by sierra-moxon** [comment]
@codewarrior2000 - just to clarify,`chemical entity` is the closest we have in biolink at the moment for macromolecule and lipid.  Is this good?

**Comment by codewarrior2000** [comment]
@sierra-moxo Thank you very much for researching into the current Biolink for me. I am sure chemical entity is good for now, till the consortium wants to add something more specific in the future. I really appreciate the answer.
