### ISSUE TITLE
condition "sensitive to" chemical

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model#97]
One of the current  MVP questions is:

"What toxicants (chemical agent / toxic protein) does [condition] have specific sensitivity to?"

Any thoughts on what would be a good relation from biolink model for this question?

**Comment by nlharris** [comment]
can anyone answer cbizon's question?

**Comment by sierra-moxon** [comment]
Thanks for the bump @nlharris! :) I put this in the predicates working group.  I think it could be somewhere in the hierarchy of the set of predicates we talked about briefly on Friday (ie: sensitivity to and risk for might be part of the same hierarchy - I will touch base with the WG this week about it).

gene_has_variant_that_contributes_to_disease_association
gene_has_variant_that_contributes_to_drug_response_association
associated_with_risk_for
associated_with_increased_risk_for
associated_with_decreased_risk_for
gene expression affects drug efficacy
mutant gene affects drug efficacy

**Comment by sierra-moxon** [comment]
I think in our most recent predicates group iteration, sensitivity and resistance were proposed as predicates to add.

**Comment by sierra-moxon** [comment]
resolving in favor of currently worked on #765
