### ISSUE TITLE
Align with knet-miner ontology

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#99]
See:
https://github.com/Rothamsted/bioknet-onto

Core definitions:
https://github.com/Rothamsted/bioknet-onto/blob/master/bioknet.owl

Browse:
https://cdn.rawgit.com/Rothamsted/bioknet-onto/ed070a8e/utils/to_lode/lode_bioknet.html

Relations (e.g acetylates)
https://github.com/Rothamsted/bioknet-onto/blob/master/bk_ondex.owl

browse:
https://cdn.rawgit.com/Rothamsted/bioknet-onto/ed070a8e/utils/to_lode/lode_bk_ondex.html

cc @marco-brandizi

**Comment by deepakunni3** [comment]
@cmungall This might be interesting with our recent COV-IRT involvement and knet-miner collaboration

**Comment by marco-brandizi** [comment]
Hi @cmungall and others. Yes, some mapping between biolink and knetminer entities would be really interesting to us. We're already maintaining a number of [mappings][10].

This is also related to some ongoing work about an [agriculture schema][20], which I'm developing. It is related for several reasons: 

- obviously, many plant biology entities occur in biology in general
- I'm trying to extend and reuse bioschemas (and schema.org), which is yet another thing interesting to map to biolink
- I'm developing a little [reusable ETL pipeline framework][30] to build agrischemas datasets from heterogeneous data sources, which is conceptually similar to KGX.

[10]: https://github.com/Rothamsted/bioknet-onto/blob/master/bk_mappings.ttl
[20]: https://github.com/Rothamsted/agri-schemas/tree/master/drafts/201904-dfw-hackathon
[30]: https://github.com/Rothamsted/agri-schemas/tree/master/dfw-dataset

**Comment by nlharris** [comment]
Not a Translator priority

**Comment by sierra-moxon** [comment]
closing for now; please reopen if it becomes a priority.
