### ISSUE TITLE
Qualifier-based approach for modeling Gene->Chemical associations

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#991]
[Prerequisite reading material](https://docs.google.com/document/d/1LTzwoRoHQOWtpr23q_CzWzJZHgBhEoTS2iCy5Mn5t8Q/edit#heading=h.cxntx0nr2fjg)

We have more complex use cases that aren’t supportable in the current SPO triple model, without complex predicates. (because we want to keep subject and objects core biological concepts that have data in many sources and can be linked to other data robustly).

CTD is a good example, we have > 60 predicates to support the direction, aspect, and mechanisms of a gene->chemical statement. 
Lots of predicates mean users that want to comply with the model have to navigate through them which is difficult and also it could lead to inconsistency.  Users writing queries might have trouble navigating as well.
We suggest we move towards accepting the qualifier paradigm instead.

Questions:
- Can we ignore qualifiers?  

Only when reading the core triple, and ‘negation’ is an exception.  Never ignore negation.  Never ignore qualifiers when reading the full statement. 

- Does aspect qualifier change the category?  Yes it does, we can derive this/infer this.

- What does roll out look like?

We will spin up a test instance of some portion of CTD data and expose a TRAPI endpoint (via plater) that models the data using the qualifier paradigm.  Once the data is in place, we will solicit feedback on querability with TRAPI, ease of use, and report back any pain points.

We will create mapping tables and store them in the biolink model repo that map the deprecating predicates to their equivalent qualifier representations.

We will add more specific associations and hierarchical enumerations to constrain them, to the model to help elucidate the values possible for the five types of qualifiers that we currently have presented:
specializing
aspect
direction
mechanism
qualified predicate

- How does querying work with qualifiers?
TBD

- How do you navigate between qualifier hierarchy and predicate hierarchy.
TBD

Comments from our discussion in the DM call:
Proposal seems practical, but will take time to implement.
We like that more data will be given to the user, making the system more nuanced. 

Please cast your vote for one of the following so we know officially to proceed:
🎉  move forward: the proposal of moving the semantics of predicates into qualifiers.
👎 while the proposal makes sense, it is not feasible to make the changes that this would take and we should not go forward.
👍 move forward, but support (technical) is needed to do the migration, and it will take a very long time.  
🤖 more information is required to make an informed decision.

**Comment by sierra-moxon** [comment]
<img width="758" alt="Screen Shot 2022-04-13 at 12 47 13 PM" src="https://user-images.githubusercontent.com/4561292/163258411-abda1265-1df7-486d-ac18-46c6b45c6a61.png">

@micheldumontier (snippet taken from the doc above). :)

**Comment by micheldumontier** [comment]
i can see the benefit of having a more expressive description language (although this is still significantly weaker compared to the OWL description logic).  For comparison: https://dl.acm.org/doi/10.1145/3460210.3493561 , and examples: https://content.iospress.com/articles/data-science/ds210048
